Repository NVIDIA/spark-rapids, pull requests merged in 2020-10, with the labels that each got.

#893 Fix rounding error when casting timestamp to string for timestamps before 1970
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#908 Dataproc removed ANACONDA as an optional component in preview2
  docs/get-started/getting-started-gcp.md
Labels: documentation

#907 remove configs from databricks that shouldn't be used by default
  docs/get-started/getting-started-databricks.md
Labels: documentation

#900 Turn off CollectLimitExec replacement by default
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitExecSuite.scala
Labels: performance

#903 update getting-started-gcp.md with new component list
  docs/get-started/getting-started-gcp.md
Labels: documentation

#909 GCP preview version image name update
  docs/get-started/getting-started-gcp.md
Labels: documentation

#912 GCP preview version name update (#909)
  docs/get-started/getting-started-gcp.md
Labels: documentation

#904 Add command-line argument for benchmark result filename
  integration_tests/pom.xml
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
Labels: benchmark

#843 [REVIEW] Cache plugin to handle reading CachedBatch to an InternalRow
  docs/configs.md
  integration_tests/src/main/python/cache_test.py
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/ParquetMaterializer.scala
Labels: feature request

#850 Add in basic support for lead/lag
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: feature request

#919 Add label benchmark to performance subsection in changelog
  CHANGELOG.md
  scripts/generate-changelog
Labels: build, documentation

#917 create new SparkContext in GPU notebook explicitly.
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
Labels: documentation

#916 create new sparkContext explicitly in CPU notebook
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
Labels: documentation

#923 Gh pages gcp notebook fix
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
Labels: documentation

#820 Benchmarking guide
  README.md
  docs/benchmarks.md
Labels: benchmark, documentation

#928 Fix RapidsBufferStore NPE when no spillable buffers are available
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
Labels: bug, shuffle

#929 Pick a default tableId to use that is non 0 so that flatbuffers allow…
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CopyCompressionCodec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvcompLZ4CompressionCodec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
Labels: bug, shuffle

#926 Move pandas_udf functions into the tests functions
  integration_tests/src/main/python/udf_cudf_test.py
Labels: build

#942 fix github action env setup [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#940 Fix closeOnExcept suppressed exception handling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ArmSuite.scala
Labels: bug

#935 Add in support/tests for a window count on a column
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: feature request

#915 Add option to control number of partitions when converting from CSV to Parquet
  docs/benchmarks.md
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeSpark.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
Labels: benchmark

#918 Benchmark runner script
  docs/benchmarks.md
  integration_tests/src/main/python/benchmark.py
Labels: benchmark

#970 Add legacy config to clear active Spark 3.1.0 session in tests
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: test

#968 XFail pos_explode tests until final fix can be put in
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/generate_expr_test.py
Labels: test

#973 Stop reporting totalTime metric for GpuShuffleExchangeExec
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala
Labels: bug

#949 Fix GpuWindowExec to work with a CPU SortExec
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuCustomShuffleReaderExec.scala
Labels: bug

#964 Refactor TPC benchmarks to reduce duplicate code
  docs/benchmarks.md
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
Labels: benchmark

#983 clean jenkins file for premerge on NGCC
  jenkins/Dockerfile.ubuntu16
  jenkins/Jenkinsfile.premerge
Labels: build

#988 Change in Spark caused the 3.1.0 CI to fail
  shims/spark310/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/ParquetMaterializer.scala
Labels: build

#992 Skip post-clean if aborted before the image build stage in pre-merge [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#934 Iterator to make it easier to work with a window of blocks in the RAPIDS shuffle
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/WindowedBlockIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/WindowedBlockIteratorSuite.scala
Labels: performance, shuffle

#914 Write InternalRow to CachedBatch
  integration_tests/src/main/python/cache_test.py
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
Labels: performance

#986 Fix missing dataSize metric when using RAPIDS shuffle
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: shuffle

#981 Change databricks build to dynamically create a cluster
  jenkins/Jenkinsfile.databricksnightly
  jenkins/databricks/build.sh
  jenkins/databricks/clusterutils.py
  jenkins/databricks/create.py
  jenkins/databricks/run-tests.py
  jenkins/databricks/shutdown.py
Labels: build

#1000 Always use RAPIDS shuffle when running TPCH and Mortgage tests
  pom.xml
Labels: test

#998 Update benchmark automation script
  integration_tests/src/main/python/benchmark.py
Labels: benchmark

#1016 [REVIEW] Change Hash Aggregate to allow pass-through on MapType
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: P1, feature request

#886 Spark BinaryType and cast to BinaryType
  docs/configs.md
  integration_tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: feature request

#991 Updated GCP Dataproc Mortgage-ETL-GPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
Labels: documentation

#1014 Add --append-dat flag for TPC-DS benchmark
  integration_tests/src/main/python/benchmark.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
Labels: benchmark

#990 Parquet coalesce file reader for local filesystems
  docs/configs.md
  integration_tests/src/main/python/parquet_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuParquetScan.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/Spark300dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuParquetScan.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: performance

#1001 ColumnarBatch to CachedBatch and back
  integration_tests/src/main/python/cache_test.py
  jenkins/spark-tests.sh
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
Labels: performance

#1028 Update to cudf-0.16
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Jenkinsfile.databricksnightly
  jenkins/databricks/run-tests.py
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#854 Arbitrary function call in UDF
  docs/compatibility.md
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/LambdaReflection.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/State.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: feature request

#1034 [BUG] To honor spark.rapids.memory.gpu.pool=NONE
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug

#1036 Increase number of retries when waiting for databricks cluster
  jenkins/databricks/clusterutils.py
Labels: build

#1037 Add in support for the SQL functions Least and Greatest
  docs/configs.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: SQL

#1017 Log whether PTDS is enabled
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: feature request

#1046 Fix broken links
  docs/_config.yml
  docs/dev/README.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/tuning-guide.md
  docs/version/stable-release.md
Labels: documentation
