Repository NVIDIA/spark-rapids, pull requests merged in 2020-12, with the labels that each got.

#1219 Upgrade to jucx 1.9.0
  docs/get-started/getting-started-on-prem.md
  shuffle-plugin/pom.xml
Labels: shuffle

#1220 Support replacing ORC format when Hive is configured
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: SQL

#1173 Support relational operators for decimal type
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DecimalBinaryOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuExpressionTestSuite.scala
Labels: feature request

#1180 Remove batches if they are received after the iterator detects that t…
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
Labels: bug, shuffle

#1193 Verify shuffle of decimal columns
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: test

#1068 Write int96 to parquet
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: feature request

#1232 Move SortOrder creation to shims
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: build

#1237 In transport, limit pending transfer requests to fit within a bounce
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
Labels: shuffle

#1133 Refactor batch coalesce to be based solely on batch data size
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: feature request

#1204 Avoid empty batches on columnar to row conversion
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
Labels: bug

#1169 Use CUDF's "UNBOUNDED" window boundaries for time-range queries.
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: bug

#1248 At BatchedTableCompressor.finish synchronize to allow for "right-size…
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TableCompressionCodec.scala
Labels: shuffle

#1194 Drop redundant total time metric from scan
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#1170 Add nested type support to MetaUtils
  sql-plugin/src/main/format/ShuffleMetadataResponse.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/ColumnMeta.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/SubBufferMeta.java
  sql-plugin/src/main/scala/ai/rapids/cudf/ColumnViewUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: shuffle

#1242 Remove compatibility documentation about unsupported INT96
  docs/compatibility.md
Labels: documentation

#1240 Fix loading from ORC file with no column names
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: SQL

#1247 Ensure column names are valid when writing benchmark query results to file
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark

#1260 Update UCX license info in NOTIFY-binary for 1.9 and RAPIDS plugin copyright dates
  NOTICE
  NOTICE-binary
Labels: shuffle

#1264 Fix race condition in batch creation
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: bug

#1275 Temporarily disable more CAST tests for Spark 3.1.0
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: build

#1291 Increase pre-merge resource requests [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#1266 Updating Databricks getting started for 0.3 release
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
  docs/img/sparkconfig.png
Labels: documentation

#1235 Trigger reading and handling control data.
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: bug

#1268 Adds in support docs for 0.3 release
  docs/supported_ops.md
Labels: documentation

#1272 Add Alias to shims
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: build

#1278 Add a config to disable decimal types by default
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: P1, SQL

#1265 Chunking input before writing a ParquetCachedBatch
  pom.xml
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: Spark 3.1+

#1302 Add GpuSubstring handling to SortOrder canonicalization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: SQL

#1299 Benchmark runner improved error handling
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark, bug

#1310 Fix canonicalization of GpuFileSourceScanExec, GpuShuffleCoalesceExec
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: SQL

#1303 Add explicit outputOrdering for BHJ and SHJ in spark310 shim
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
Labels: Spark 3.1+, bug

#1307 Fallback to cpu when reading Delta log files for stats
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: P1, bug

#1337 Use UTC instead of GMT
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: build, documentation

#1318 Fix copying GpuFileSourceScanExec node
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: SQL

#1336 Fix missing post-shuffle coalesce with AQE
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: SQL

#1311 ParquetCachedBatchSerializer code cleanup
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: Spark 3.1+

#1281 Documentation added for testing
  CONTRIBUTING.md
  README.md
  docs/testing.md
  integration_tests/README.md
  tests/README.md
  tests/pom.xml
Labels: documentation

#1350 fix GpuRangePartitioning canonicalization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioning.scala
Labels: SQL

#1342 Fix and edit docs for standalone mode
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#1273 Update docs and scripts to 0.4.0-SNAPSHOT
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Jenkinsfile.databricks301nightly
  jenkins/databricks/create.py
  jenkins/version-def.sh
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/README.md
Labels: build

#1343 Do not run UDFs when the partition is empty.
  integration_tests/src/main/python/udf_cudf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: bug, test

#1359 Use SortOrder from shims.
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapCoGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
Labels: Spark 3.1+

#1361 Use the correct precision when reading spark columnar data.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: P1, bug

#1358 auto-merge: instant merge after creation [skip ci]
  .github/workflows/auto-merge/automerge
Labels: build

#1368 Move to cudf 0.18-SNAPSHOT
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#1349 Add canonicalization tests
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#1367 Reuse gpu expression conversion rules when checking sort order
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#1376 MetaUtils.getBatchFromMeta should return batches with GpuColumnVectorFromBuffer
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorFromBuffer.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
Labels: bug, performance, shuffle

#1370 [REVIEW] init changelog 0.3 [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#1380 Adds in basic support for decimal sort, sum, and some shuffle
  docs/configs.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: SQL

#1390 Accelerated columnar to row/row to columnar for decimal
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/org/apache/spark/sql/catalyst/CudfUnsafeRow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
Labels: performance

#1387 Update cudf version to 0.17
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#1395 Fix branch-0.3 -> branch-0.4 automerge
  integration_tests/README.md
Labels: build

#1391 Remove extra null join filtering because cudf is fast for this now.
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance

#1323 More advanced type checking and documentation
  dist/pom.xml
  docs/configs.md
  docs/supported_ops.md
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuSortMergeJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuSortMergeJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuSortMergeJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapCoGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: documentation

#1389 Update project version to 0.3.0
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/README.md
Labels: build

#1404 Fix branch 0.4 merge conflict
  integration_tests/README.md
Labels: build

#1392 Turn on hash partitioning for decimal support
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: SQL

#1393 Support RAPIDS-accelerated HiveSimpleUDF
  dist/pom.xml
  docs/configs.md
  docs/supported_ops.md
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/rapids_udf_test.py
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/java/com/nvidia/spark/RapidsUDF.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveSimpleUDF.scala
  udf-examples/pom.xml
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/URLDecode.java
Labels: SQL, feature request

#1407 Update docs and tests for null CSV support
  docs/compatibility.md
  integration_tests/src/main/python/csv_test.py
Labels: documentation, test

#1408 Support RAPIDS-accelerated HiveGenericUDF
  dist/pom.xml
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/rapids_udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/hiveUDFs.scala
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/URLEncode.java
Labels: SQL, feature request

#1410 Add Decimal support for In, InSet, AtLeastNNonNulls, GetArrayItem, GetStructField, and GenerateExec
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: SQL

#1409 Add option to use decimals in tpc-ds csv to parquet conversion
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
Labels: benchmark

#1414 Build merged code of HEAD and BASE branch for pre-merge [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#1412 Fix a lot of tests marked with xfail for Spark 3.1.0 that no longer fail
  docs/compatibility.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/qa_nightly_sql.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/tpch_test.py
Labels: Spark 3.1+, documentation, test

#1411 Add udf-examples jar to databricks build
  jenkins/databricks/build.sh
Labels: build

#1313 Support spilling to disk directly via cuFile/GDS
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
Labels: feature request, performance, shuffle

#1401 Accelerate the coalescing parquet reader when reading files from multiple partitioned folders
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarPartitionReaderWithPartitionValues.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: feature request

#1422 Log the number of concurrent gpu tasks allowed on Executor startup
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: P2, feature request

#1420 Add udf jar to nightly integration tests
  integration_tests/README.md
  integration_tests/src/main/python/rapids_udf_test.py
  jenkins/spark-tests.sh
Labels: build

#1424 Make the multi-threaded parquet reader the default since coalescing doesn't handle partitioned files well
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: SQL

#1427 Revert "Make the multi-threaded parquet reader the default"
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: SQL, feature request

#1425 Add in Decimal support for abs, floor, ceil, unary - and unary +
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: SQL

#1433 fix pandas 1.2 compatible issue
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/Dockerfile-blossom.ubuntu16
  jenkins/Dockerfile.integration.ubuntu16
  jenkins/Dockerfile.ubuntu16
Labels: build
