Repository NVIDIA/spark-rapids, pull requests merged in 2020-09, with the labels that each got.

#563 cudf and spark version info in artifacts
  build/dependency-info.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  shims/spark300/pom.xml
  shims/spark300db/pom.xml
  shims/spark301/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
Labels: build

#599 [FEA] changelog generator
  scripts/generate-changelog
Labels: build

#623 Fix issues with canonicalization
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: bug, performance

#644 Small fix for race in catalog where a buffer could get spilled while …
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
Labels: bug, shuffle

#646 Stop reporting zero metrics for GpuCustomShuffleReader
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuCustomShuffleReaderExec.scala
Labels: bug

#647 Improve warnings about AQE nodes not supported on GPU
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: feature request

#653 Move to the cudf-0.15 release
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Jenkinsfile.databricksnightly
  jenkins/databricks/run-tests.py
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  udf-compiler/README.md
Labels: build

#652 Mark UVM config as internal until supported
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug, documentation

#639 BooleanType test shouldn't xfail
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/qa_nightly_sql.py
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/tpch_test.py
Labels: test

#660 Add in neverReplaceExec and several rules for it
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: feature request

#657 Fix verify build after integration tests are run
  .gitignore
  integration_tests/run_pyspark_from_build.sh
Labels: bug, test

#614 Fix for aggregation with multiple distinct and non distinct functions
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: bug

#655 Implement AQE unit test for InsertAdaptiveSparkPlan
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: test

#666 [window] Disable GPU for COUNT(exp) queries
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  tests/src/test/resources/window-function-test.orc
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: bug

#593 Add support for isNaN and datetime related instructions in UDF compiler
  docs/compatibility.md
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: feature request, test

#648 add signoff-check use github actions
  .github/workflows/signoff-check.yml
  .github/workflows/signoff-check/Dockerfile
  .github/workflows/signoff-check/action.yml
  .github/workflows/signoff-check/signoff-check
Labels: build, feature request

#673 Increase build timeouts on nightly and premerge builds
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.nightly
  jenkins/Jenkinsfile.premerge
  jenkins/Jenkinsfile.release
Labels: build

#682 Fix path to start-slave.sh script in docs
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#683 Fix issues with cannonicalization of WrappedAggFunction
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: bug

#676 fixUpJoinConsistency rule now works when AQE is enabled
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: bug, test

#645 [window] Add GpuWindowExec requiredChildOrdering
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: P2, bug

#675 Added TimeAdd
  docs/configs.md
  integration_tests/src/main/python/date_time_test.py
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#686 Remove sorts when replacing sort aggregate if possible
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuSortMergeJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: performance

#684 Enable test for literal string values in a select
  integration_tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
Labels: test

#638 Add Parquet-based cache serializer
  integration_tests/src/main/python/cache_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/rapids/shims/spark310/GpuColumnarToRowTransitionExec.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/rapids/shims/spark310/GpuInMemoryTableScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: feature request

#677 Use multi-threaded parquet read with small files
  docs/configs.md
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/Spark300dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInputFileBlock.scala
Labels: performance

#690 Update the version to 0.3.0-SNAPSHOT
  api_validation/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300db/pom.xml
  shims/spark301/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#687 Include the UDF compiler in the dist jar
  dist/pom.xml
  udf-compiler/README.md
Labels: build

#692 Merge shims dependency to spark-3.0.1 into branch-0.3
  api_validation/README.md
  integration_tests/pom.xml
  jenkins/Jenkinsfile.301.integration
  pom.xml
  tests/pom.xml
Labels: build

#693 Update jenkins files for 0.3
  jenkins/Jenkinsfile.301.integration
  jenkins/Jenkinsfile.302.integration
  jenkins/Jenkinsfile.310.integration
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#668 refactor automerge to support merge for protected branch
  .github/workflows/auto-merge.yml
  .github/workflows/auto-merge/automerge
Labels: build

#695 Fix spark-3.0.1 shim to be released
  docs/configs.md
  shims/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug, build

#701 fix checkout-ref for automerge
  .github/workflows/auto-merge.yml
Labels: bug, build

#702 Update slack channel for Jenkins builds
  jenkins/Jenkinsfile.301.integration
  jenkins/Jenkinsfile.302.integration
  jenkins/Jenkinsfile.310.integration
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
Labels: build

#705 Enable configuration check for cast string to timestamp
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: bug

#642 Init workflow for blossom-ci
  .github/workflows/blossom-ci.yml
  jenkins/Dockerfile-blossom.ubuntu16
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#709 [BUG] fix unexpected indentation issue in blossom yml
  .github/workflows/blossom-ci.yml
Labels: bug, build

#711 fix blossom checkout repo
  .github/workflows/blossom-ci.yml
Labels: bug, build

#721 Add some more checks to databricks build scripts
  jenkins/databricks/build.sh
Labels: build

#722 Initial code changes to support spilling outside of shuffle
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillPriorities.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/TempSpillBufferId.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: SQL, feature request

#729 Fix collect time metric in CoalesceBatches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: bug

#720 Stop removing GpuCoalesceBatches from non-AQE queries when AQE is enabled
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: bug

#733 Remove GPU Types from github
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#741 Fix issue with parquet partitioned reads
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#745 Revert Null Join Filter
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/tpcds_test.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuHashJoin.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuBroadcastHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: bug

#637 Documentation changes for 0.2 release
  docs/FAQ.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/testing.md
  docs/version/stable-release.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#732 Add a timeout for RapidsShuffleIterator to prevent jobs to hang infin…
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/shuffle/RapidsShuffleExceptions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: shuffle

#754 Filter nulls from joins where possible to improve performance
  integration_tests/src/main/python/tpcds_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuHashJoin.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuBroadcastHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: bug, performance

#751 Correct the channel for cudf installation
  jenkins/Dockerfile.integration.centos7
Labels: build

#752 Fix snapshot plugin jar version in docs
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#758 Skip the udf test fails periodically.
  integration_tests/src/main/python/udf_test.py
Labels: build

#759 Add CHANGELOG for release 0.2
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#765 Add config to override shims provider class
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: SQL, feature request

#723 Update code coverage to find source files in new places
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile.premerge
Labels: bug, build

#674 Unit test for GPU exchange re-use with AQE
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: test

#726 parquet writer support for TIMESTAMP_MILLIS
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: feature request

#727 Update cudf dependency to 0.16-SNAPSHOT
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  docs/testing.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Jenkinsfile.databricksnightly
  jenkins/databricks/run-tests.py
  jenkins/spark-tests.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/pom.xml
Labels: build

#763 [REVIEW] Allow CoalesceBatch to spill data that is not in active use
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillPriorities.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: SQL, feature request

#771 Various improvements to benchmarks
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
Labels: test

#785 Make shuffle run on CPU if we do a join where we read from bucketed table
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: bug

#783 Improved GpuArrowEvalPythonExec
  docs/configs.md
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillPriorities.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: performance

#798 Fix shims provider override config not being seen by executors
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
Labels: P1, SQL, bug

#790 CI: Update cudf python to 0.16 nightly
  jenkins/Dockerfile.integration.centos7
  jenkins/Jenkinsfile.integration
  python/rapids/worker.py
Labels: SQL, build

#793 Update Jenkins scripts for release
  jenkins/Jenkinsfile.databricksrelease
  jenkins/Jenkinsfile.release
  jenkins/databricks/build.sh
  jenkins/deploy.sh
Labels: build

#777 Enable tests in udf_cudf_test.py
  integration_tests/src/main/python/udf_cudf_test.py
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: build, test

#802 Update 0.2 CHANGELOG
  CHANGELOG.md
Labels: documentation

#800 Merge fixes on branch-0.2 to main
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
Labels: bug

#807 Deploy integration-tests javadoc and sources
  jenkins/deploy.sh
Labels: build

#797 Allow host spill store to fit a buffer larger than configured max size
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: SQL, feature request, shuffle

#805 [FEA] nightly build trigger both IT on spark 300 and 301
  jenkins/Jenkinsfile.nightly
Labels: build

#788 [FEA] Persist workspace data on PVC for premerge
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#813 Revert "Enable tests in udf_cudf_test.py"
  integration_tests/src/main/python/udf_cudf_test.py
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: test

#782 Benchmark utility to perform diff of output from benchmark runs, allowing for precision differences
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: test

#815 Update documentation for Scala UDFs in 0.2 since you need two things
  docs/compatibility.md
Labels: documentation

#816 [BUG] fix nightly is timing out
  jenkins/Jenkinsfile.nightly
Labels: bug, build

#826 Fix link to cudf-0.15-cuda11.jar
  docs/version/stable-release.md
Labels: documentation

#827 Add Spark 3.0 EMR Shim layer
  integration_tests/README.md
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/spark_session.py
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300emr/pom.xml
  shims/spark300emr/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark300emr/src/main/scala/com/nvidia/spark/rapids/shims/spark300emr/Spark300EMRShims.scala
  shims/spark300emr/src/main/scala/com/nvidia/spark/rapids/shims/spark300emr/SparkShimServiceProvider.scala
  shims/spark300emr/src/main/scala/com/nvidia/spark/rapids/spark300emr/RapidsShuffleManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: feature request

#839 First/Last reduction and cleanup of agg APIs
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: feature request

#824 Skip cudf_udf test by default
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/udf_cudf_test.py
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  pom.xml
Labels: test

#781 Add AQE unit tests
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: test

#796 Record spark plan SQL metrics to JSON when running benchmarks
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
Labels: test

#853 Remove nodeAffinity from premerge pipeline
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#857 fix pvc scheduling issue
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#851 Use contiguous table when deserializing columnar batch
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: performance

#848 Update task memory and disk spill metrics when buffer store spills
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: feature request

#840 [REVIEW] Fixed failing cache tests
  integration_tests/src/main/python/cache_test.py
Labels: bug

#841 Fix a hanging issue when processing empty data.
  integration_tests/src/main/python/udf_cudf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: bug

#832 Skip pandas tests if pandas cannot be found
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
Labels: test

#756 Add stream-time metric
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuHashJoin.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuBroadcastHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
Labels: feature request

#856 Move GpuWindowInPandasExec in shims layers
  integration_tests/src/main/python/udf_cudf_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300/src/main/scala/org/apache/spark/sql/rapids/shims/spark300/GpuWindowInPandasExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/rapids/shims/spark310/GpuWindowInPandasExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: build

#833 Add nvcomp LZ4 codec support
  sql-plugin/src/main/format/ShuffleCommon.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/CodecType.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CopyCompressionCodec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvcompLZ4CompressionCodec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TableCompressionCodec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
Labels: feature request, shuffle

#872 Ensure that receive-side batches use GpuColumnVectorFromBuffer to avoid
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorFromBuffer.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
Labels: performance, shuffle

#875 fix the non-consistency for `spark.rapids.sql.format.parquet.multiThreadedRead` in RapidsConf.scala
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#883 [BUG] fix IT dockerfile args ordering [skip ci]
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/Dockerfile.integration.centos7
Labels: bug, build

#885 [BUG] fix IT dockerfile arguments [skip ci]
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/Dockerfile.integration.centos7
Labels: bug, build

#888 Shrink detect scope to compile only [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#879 Update SpillableColumnarBatch to remove buffer from catalog on close
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/TempSpillBufferId.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: bug

#889 Fix crash on scalar only orderby
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
Labels: bug

#871 Add support for using the arena allocator
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Labels: performance

#892 Only manifest the current batch in cached block shuffle read iterator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
Labels: bug, performance, shuffle

#890 Clean up CoalesceBatch to use withResource
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: feature request

#887 Update gh-pages for 0.2
  docs/FAQ.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/README.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-menu.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started.md
  docs/testing.md
  docs/version/stable-release.md
  index.md
Labels: documentation

#891 Add config to dump heap on GPU OOM
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request
