Repository NVIDIA/spark-rapids, pull requests merged in 2020-11, with the labels that each got.

#1051 Add simple retry for URM dependencies [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
Labels: build

#1050 Fix broken links (#1046)
  _config.yml
  docs/dev/README.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/tuning-guide.md
Labels: documentation

#1056 Add query number to Spark app name when running benchmarks
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
Labels: benchmark

#1044 Accelerated row to columnar and columnar to row transitions
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/java/org/apache/spark/sql/catalyst/CudfUnsafeRow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: performance

#1047 Sanity checks for cudf jar mismatch
  build/build-info
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#1057 Fix empty table broadcast requiring a GPU on driver node
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: SQL

#1055 Fix build warnings
  integration_tests/pom.xml
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/CompareResults.scala
  pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300db/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#1029 BenchmarkRunner should produce JSON summary file even when queries fail
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
Labels: benchmark

#1066 More fixes for conversion to ColumnarBatch
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuShuffledHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorFromBuffer.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: feature request

#1078 Another round of fixes for mapping of DataType to DType
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorFromBuffer.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarPartitionReaderWithPartitionValues.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMonotonicallyIncreasingID.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRoundRobinPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSparkPartitionID.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/namedExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInputFileBlock.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleDependency.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/NormalizeFloatingNumbers.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuRandomExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuUnitTests.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ImplicitsTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DateTimeUnitTest.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: feature request

#1062 Get cudf/spark dependency from the correct .m2 dir
  build/build-info
  build/dependency-info.sh
  jenkins/databricks/build.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  pom.xml
  shims/spark300/pom.xml
  shims/spark300db/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
Labels: build

#1083 Revert "Get cudf/spark dependency from the correct .m2 dir"
  build/build-info
  build/dependency-info.sh
  jenkins/databricks/build.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  pom.xml
  shims/spark300/pom.xml
  shims/spark300db/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
Labels: build

#1084 Avoid issues where more scalars that expected show up in an expression
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#1086 Speed up test performance using pytest-xdist
  docs/testing.md
  integration_tests/README.md
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/spark_init_internal.py
  jenkins/Dockerfile-blossom.ubuntu16
  pom.xml
Labels: test

#1090 Fix the integration build
  jenkins/spark-tests.sh
Labels: build

#1097 Cleanup some instances of excess closure serialization
  shims/spark300/src/main/scala/org/apache/spark/sql/rapids/shims/spark300/GpuWindowInPandasExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: SQL

#1077 Improve AQE transitions for shuffle and coalesce batches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: bug, performance

#1069 Accelerate the data transfer between JVM and Python for the plan 'GpuWindowInPandasExec'
  docs/configs.md
  integration_tests/src/main/python/udf_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300/src/main/scala/org/apache/spark/sql/rapids/shims/spark300/GpuWindowInPandasExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/rapids/shims/spark310/GpuWindowInPandasExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExec.scala
Labels: performance

#1106 Improve mechanism for expected exceptions in tests
  tests/src/test/scala/com/nvidia/spark/rapids/CsvScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#1107 closeOnExcept -> withResources in MetaUtils
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
Labels: bug

#1112 Remove bad config from pytest setup
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, test

#994 Packs bounce buffers for highly partitioned shuffles
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/ai/rapids/cudf/CudaUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BounceBufferManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: performance, shuffle

#1080 Support for CalendarIntervalType and NullType
  integration_tests/src/main/python/cache_test.py
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
Labels: Spark 3.1+

#1108 Remove integration test pipelines on NGCC
  jenkins/Dockerfile.integration.centos7
  jenkins/Jenkinsfile.301.integration
  jenkins/Jenkinsfile.302.integration
  jenkins/Jenkinsfile.310.integration
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
Labels: build

#1102 Auto-register UDF extention when main plugin is set
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  udf-compiler/README.md
Labels: feature request

#1116 Optimize normal shuffle by coalescing smaller batches on host
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: performance

#1129 Fix resource leaks with new shuffle optimization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleCoalesceExec.scala
Labels: bug

#1124 Add shim layers for GpuWindowInPandasExec.
  integration_tests/src/main/python/udf_test.py
  python/rapids/daemon_databricks.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuWindowInPandasExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuWindowInPandasExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/Spark300dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonHelper.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: feature request

#1134 Support saveAsTable for writing orc and parquet
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark300/src/main/scala/org/apache/spark/sql/rapids/shims/spark300/GpuSchemaUtils.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  shims/spark310/src/main/scala/org/apache/spark/sql/rapids/shims/spark310/GpuSchemaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
Labels: SQL

#1121 Shuffle/better error handling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/org/apache/spark/shuffle/RapidsShuffleExceptions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
Labels: feature request

#1095 Dependency info
  build/build-info
  build/dependency-info.sh
  jenkins/databricks/build.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark310/pom.xml
Labels: build

#1156 Fix warning introduced in iterator suite
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
Labels: build, shuffle

#1113 Support unix_timestamp on GPU for subset of formats
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/TimeOperatorsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: feature request

#1154 Mark test as xfail until we can get a fix in
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#1105 [REVIEW] Change ColumnViewAccess usage to work with ColumnView
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: P1

#1160 Fix some performance problems with columnar to columnar conversion
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: performance

#1161 Fix nightly build pipeline failure.
  jenkins/spark-nightly-build.sh
Labels: build

#1159 fix bug where 'now' had same value as 'today' for timestamps
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: SQL

#1166 Fix the cast tests for 3.1.0+
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#1163 Add in support for GetStructField
  docs/configs.md
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: SQL

#1165 Fix race condition in SerializeConcatHostBuffersDeserializeBatch
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: bug

#1167 Nulls out the dataframe if --gc-between-runs is set
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark, shuffle

#1152 Add spark301db shim layer for WindowInPandas.
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuWindowInPandasExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: feature request

#1060 Show partition metrics for custom shuffler reader
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuCustomShuffleReaderExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala
Labels: SQL

#1172 Revert "Fix race condition (#1165)"
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: bug

#1162 Set job descriptions in benchmark runner
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark

#1138 [REVIEW] Support decimal type for GpuProjectExec
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBatchUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: SQL

#1175 Fix leaks seen in shuffle tests
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: build, shuffle

#1174 Fix race condition in SerializeConcatHostBuffersDeserializeBatch
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: bug

#1176 Add in support for null type
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/row_conversion_test.py
  integration_tests/src/main/python/sort_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuSortMergeJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuSortMergeJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuBroadcastHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffledHashJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuSortMergeJoinExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/java/org/apache/spark/sql/catalyst/CudfUnsafeRow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuUnitTests.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: SQL

#1182 Close buffer catalog on device manager shutdown
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug

#1187 Updated documentation for distinct count compatibility
  docs/compatibility.md
Labels: documentation

#1186 Fix compilation and scaladoc warnings
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: build

#1181 Fix resource leaks in unit tests
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: test

#1189 Enable NullType for First and Last in 3.0.1+
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
Labels: bug

#1188 Add in tests for parquet nested pruning support
  integration_tests/src/main/python/parquet_test.py
Labels: test

#1150 udf spec
  docs/compatibility.md
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/LambdaReflection.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/State.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: feature request

#1183 Support for CalendarIntervalType and NullType
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/CacheTestSuite.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: feature request

#1206 Update Spark 3.1 shim for ShuffleOrigin shuffle parameter
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuShuffleExchangeExec.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: Spark 3.1+

#1205 Fix missing input bytes read metric for Parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataSourceRDD.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: SQL

#1208 [BUG] Fix GHSL2020-239 [skip ci]
  .github/workflows/blossom-ci.yml
Labels: bug, build

#1201 Replace only window expressions on databricks.
  integration_tests/src/main/python/udf_test.py
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuWindowInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: test

#1213 Skip casting StringType to TimestampType for Spark 310
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: test

#1202 Fix a bug with the support for java.lang.StringBuilder.append.
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: bug

#1210 Support auto-merge for branch-0.4 [skip ci]
  .github/workflows/auto-merge.yml
  scripts/generate-changelog
Labels: build

#1214 changelog update 2020-11-30. Trigger automerge check [skip ci]
  CHANGELOG.md
Labels: documentation

#1218 Remove obsolete HiveStringType usage
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/ParquetCachedBatchSerializer.scala
Labels: build

#1217 Aggregate reductions in Complete mode should use updateExpressions
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: P1

#1081 Add option to upload benchmark summary JSON file
  integration_tests/src/main/python/benchmark.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark
