Repository NVIDIA/spark-rapids, pull requests merged in 2020-07, with the labels that each got.

#312 Trigger branch-0.2 integration test
  jenkins/Jenkinsfile.nightly
Labels: build

#309 Update databricks patch to latest changes
  jenkins/databricks/dbimports.patch
Labels: SQL, build

#318 Build docker image with Dockerfile
  jenkins/Dockerfile.integration.centos7
  jenkins/Dockerfile.ubuntu16
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
  jenkins/Jenkinsfile.premerge
  jenkins/Jenkinsfile.release
  jenkins/settings.xml
Labels: build

#258 Enable running TPCH tests with AQE enabled
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeAdaptiveSparkSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSparkSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: feature request, test

#320 Don't mount passwd/group to the container
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.databricksrelease
  jenkins/Jenkinsfile.nightly
  jenkins/Jenkinsfile.release
Labels: build

#322 Add oss.sonatype.org to download the cudf jar
  pom.xml
Labels: build

#324 Add in basic support for GpuCartesianProductExec
  docs/configs.md
  integration_tests/src/main/python/join_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: SQL

#330 Hide private info in Jenkins scripts
  jenkins/Dockerfile.integration.centos7
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.databricksrelease
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
  jenkins/Jenkinsfile.premerge
  jenkins/Jenkinsfile.release
  jenkins/databricks/deploy.sh
  jenkins/settings.xml
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/version-def.sh
  pom.xml
Labels: build

#310 Update release Jenkinsfile for Databricks
  jenkins/Jenkinsfile.databricksrelease
Labels: build

#339 Fix databricks build
  integration_tests/src/main/python/join_test.py
  jenkins/Jenkinsfile.databricksnightly
  jenkins/databricks/build.sh
  jenkins/databricks/dbimports.patch
  jenkins/databricks/shutdown.py
Labels: build

#332 Match GPU overwritten functions with SQL functions from FunctionRegistry
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#337 Fix Scala compile phase to allow Java classes referencing Scala classes
  pom.xml
Labels: build

#298 Point to maven repository folder for current release
  docs/getting-started.md
  favicon.ico
Labels: documentation

#331 Adds iterator and client unit tests, and prepares for more fetch failure handling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleReceivedBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/shuffle/RapidsShuffleFetchFailedException.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: shuffle

#344 Fix small typo in readme
  README.md
Labels: documentation

#346 Update the Title Header for Fine Tuning
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#335 Integration tests on spark 3.0.1-SNAPSHOT & 3.1.0-SNAPSHOT
  jenkins/Jenkinsfile.301.integration
  jenkins/Jenkinsfile.310.integration
  jenkins/version-def.sh
Labels: build

#349 Updated join code to treat null equality properly
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/qa_nightly_sql.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashJoin.scala
Labels: SQL

#342 Implement build-side rules for shuffle hash join
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinExec.scala
Labels: bug

#313 Additional tests for broadcast hash join
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastHashJoinSuite.scala
Labels: test

#353 Fix broadcast nested loop join for the no column case
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: bug

#359 Karthik changes
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.zpln
  docs/demo/gpu-mortgage_accelerated.ipynb
  docs/examples.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-menu.md
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/get-started/getting-started.md
  docs/get-started/yarn-gpu.md
  docs/img/dataproc-cluster.png
  docs/img/dataproc-service.png
  docs/img/ease-of-use.png
  docs/img/initscript.png
  docs/img/perf-cost.png
  docs/img/spark3cluster.png
  docs/img/sparkconfig.png
  docs/index.md
  docs/version/stable-release.md
  docs/version/version.md
Labels: documentation

#369 Documentation changes for Karthik to gh-pages
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.zpln
  docs/demo/gpu-mortgage_accelerated.ipynb
  docs/examples.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-menu.md
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/get-started/getting-started.md
  docs/get-started/yarn-gpu.md
  docs/img/dataproc-cluster.png
  docs/img/dataproc-service.png
  docs/img/ease-of-use.png
  docs/img/initscript.png
  docs/img/perf-cost.png
  docs/img/spark3cluster.png
  docs/img/sparkconfig.png
  docs/version/stable-release.md
  docs/version/version.md
  index.md
Labels: documentation

#370 Fix index.md to point to perf-cost.png
  index.md
Labels: documentation

#372 Applying changes for getting started for GCP
  docs/get-started/getting-started-gcp.md
Labels: documentation

#374 Fix rat issue for notebooks
  pom.xml
Labels: bug, build

#376 Add our session extension correctly if there are other extensions configured
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: SQL, bug

#373 Modifying branch name to conform with rapidsai branch name change
  CONTRIBUTING.md
Labels: documentation

#377 Update heading in configs.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#378 Added in FAQ and fixed spelling
  docs/FAQ.md
  docs/index.md
Labels: documentation

#380 Fix databricks notebook link
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
Labels: documentation

#381 Fix link to databricks init script link in getting started guide
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
Labels: documentation

#383 Test utility to compare SQL query results between CPU and GPU
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#387 Remove the term whitelist
  api_validation/src/main/scala/com/nvidia/spark/rapids/api/ApiValidation.scala
  integration_tests/README.md
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: feature request

#391 Hide slack channel in Jenkins scripts
  jenkins/Jenkinsfile.301.integration
  jenkins/Jenkinsfile.310.integration
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.integration
  jenkins/Jenkinsfile.nightly
Labels: build

#390 Ucx getting started
  docs/get-started/getting-started.md
Labels: documentation, shuffle

#389 Added in support for RangeExec
  docs/configs.md
  integration_tests/src/main/python/range_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: SQL

#393 Contributor license agreement
  CONTRIBUTING.md
Labels: documentation

#286 [REVIEW] Updated join tests for cache
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#397 Fix small bug in ShuffleBufferCatalog.hasActiveShuffle
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ShuffleBufferCatalogSuite.scala
Labels: shuffle

#352 Change spark tgz package name
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: build

#398 Add tests for GpuPartition
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#401 Extended the FAQ
  docs/FAQ.md
Labels: documentation

#395 Databricks doc updates
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/img/sparkconfig.png
Labels: documentation

#405 Change slave->worker
  docs/dev/nvtx_profiling.md
Labels: P2, documentation

#404 Updating databricks getting-started
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/img/sparkconfig.png
Labels: P2, documentation

#406 Update cast handling to deal with new libcudf casting limitations
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: SQL

#413 Fix download link
  docs/get-started/getting-started.md
Labels: documentation

#419 Fix download link
  docs/get-started/getting-started.md
Labels: documentation

#420 Change slave->worker on gh-pages branch
  docs/dev/nvtx_profiling.md
Labels: documentation

#421 Make it easier to run TPCxBB benchmarks from spark shell
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
Labels: test

#435 Add in checks for Parquet LEGACY date/time rebase
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: SQL, bug

#437 Fix bug with InSet and Strings
  integration_tests/src/main/python/cmp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: bug

#422 Documentation updates
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-menu.md
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/get-started/getting-started.md
  docs/index.md
Labels: documentation

#445 Added in StringRPad and StringLPad
  docs/configs.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: SQL

#440 Run mortgage test both with AQE on and off
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageAdaptiveSparkSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
Labels: test

#426 Update BufferMeta to support multiple codec buffers per table
  sql-plugin/src/main/format/ShuffleCommon.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/BufferMeta.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/CodecBufferDescriptor.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/CodecType.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
Labels: feature request

#447 Add scalastyle plugin to shim module
  shims/pom.xml
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/Spark310Shims.scala
Labels: build

#442 Shim layer support for Spark 3.0.0 Databricks
  integration_tests/pom.xml
  integration_tests/src/main/python/join_test.py
  jenkins/Jenkinsfile.databricksnightly
  jenkins/Jenkinsfile.databricksrelease
  jenkins/databricks/build.sh
  jenkins/databricks/deploy.sh
  jenkins/databricks/run-tests.py
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300db/pom.xml
  shims/spark300db/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuBroadcastHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuBroadcastNestedLoopJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuHashJoin.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuShuffledHashJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/GpuSortMergeJoinExec.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/Spark300dbShims.scala
  shims/spark300db/src/main/scala/com/nvidia/spark/rapids/shims/spark300db/SparkShimServiceProvider.scala
  shims/spark300db/src/main/scala/org/apache/spark/sql/rapids/shims/spark300db/GpuFileSourceScanExec.scala
  sql-plugin/pom.xml
  tests/pom.xml
Labels: build

#450 Enable scalastyle for shuffle plugin
  shuffle-plugin/pom.xml
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
Labels: build

#449 Enforce NoScalaDoc rule in scalastyle checks
  scalastyle-config.xml
  sql-plugin/src/main/scala/ai/rapids/cudf/CudaUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarPartitionReaderWithPartitionValues.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostMemoryStreams.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvtxWithMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SamplingUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BounceBufferManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/OrcFilters.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/storage/RapidsStorageUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CsvScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: build

#464 Turn off noscaladoc rule until codebase is fixed
  scalastyle-config.xml
Labels: build

#456 Add closeOnExcept to clean up code that closes resources only on exceptions
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ArmSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: SQL

#468 fix broken link
  docs/get-started/getting-started.md
Labels: documentation

#474 Re-enable noscaladoc check
  scalastyle-config.xml
Labels: build

#469 Update HashAggregateSuite to work with AQE
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: test

#477 Fix special case joins in broadcast nested loop join
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: bug

#448 Preliminary support for keeping broadcast exchanges on GPU when AQE is enabled
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: performance

#480 Fix link from README to getting-started.md
  README.md
Labels: documentation

#467 Apply branch-0.2 documentation updates to gh-pages
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-menu.md
  docs/get-started/getting-started-with-rapids-accelerator-on-databricks.md
  docs/get-started/getting-started.md
  index.md
Labels: documentation

#485 Show plan in assertion message if test fails
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: test

#482 Prevent bad practice in python tests
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#490 Fix Spark 3.1.0 build for HashJoin changes
  shims/spark310/src/main/scala/com/nvidia/spark/rapids/shims/spark310/GpuHashJoin.scala
Labels: build

#491 Temporarily ignore AQE integration tests
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageAdaptiveSparkSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeAdaptiveSparkSuite.scala
Labels: test
