Repository NVIDIA/spark-rapids, pull requests merged in 2021-11, with the labels that each got.

#3965 Add how-to resolve auto-merge conflict [skip ci]
  .github/workflows/auto-merge/automerge
Labels: build

#3978 Update aggregator jar name in databricks deploy script [databricks]
  jenkins/databricks/build.sh
  jenkins/databricks/deploy.sh
Labels: bug, build

#3972 Revert udf-examples dependency change to restore test build phase
  udf-examples/pom.xml
Labels: build

#3976 Replace long artifact lists with an ant loop
  dist/maven-antrun/build-parallel-worlds.xml
  dist/pom.xml
Labels: build, task

#3981 Replace tasks w/ target of maven-antrun-plugin in udf-example
  udf-examples/pom.xml
Labels: bug, build

#3947 Enable rlike tests on databricks [databricks]
  integration_tests/src/main/python/string_test.py
Labels: test

#3967 Bring back AST support for BNLJ inner joins
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: performance

#3973 Add shims for Apache Spark 3.2.1-SNAPSHOT builds
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  pom.xml
  shims/pom.xml
  shims/spark321/pom.xml
  shims/spark321/src/main/scala/com/nvidia/spark/rapids/shims/spark321/Spark321Shims.scala
  shims/spark321/src/main/scala/com/nvidia/spark/rapids/shims/spark321/SparkShimServiceProvider.scala
  shims/spark321/src/main/scala/com/nvidia/spark/rapids/spark321/RapidsShuffleManager.scala
  shims/spark321/src/main/scala/org/apache/spark/sql/rapids/shims/spark321/RapidsShuffleInternalManager.scala
  shims/spark321/src/test/scala/com/nvidia/spark/rapids/shims/spark321/Spark321ShimsSuite.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/HashUtils.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/OffsetWindowFunctionMeta.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/ShimAQEShuffleReadExec.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/ShimDataSourceRDD.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/TreeNode.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/YearParseUtil.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/gpuWindows.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/v2/GpuShuffleBlockResolver.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/v2/storage/ShimDiskBlockManager.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/execution/ShimTrampolineUtil.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/v2/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/rapids/shims/v2/Spark32XShimsUtils.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/rapids/shims/v2/datetimeExpressions.scala
Labels: Spark 3.2+

#3991 Fix aggegator jar copy logic [databricks]
  dist/maven-antrun/build-parallel-worlds.xml
  dist/pom.xml
Labels: bug, build

#3821 Support ORC write Map column
  docs/supported_ops.md
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3968 Allow null character in regexp_replace pattern
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3871 Add integration test for RLike with embedded null in input
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: documentation, test

#3862 Prevent approx_percentile aggregate from being split between CPU and GPU
  docs/supported_ops.md
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/ShimAQEShuffleReadExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: bug

#3767 Add shim for Databricks 9.1 [databricks]
  CONTRIBUTING.md
  docs/additional-functionality/rapids-shuffle.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/spark_session.py
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
  pom.xml
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkShimServiceProvider.scala
  shims/spark312db/pom.xml
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/shims/spark312db/Spark312dbShims.scala
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/shims/spark312db/SparkShimServiceProvider.scala
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/spark312db/RapidsShuffleManager.scala
  shims/spark312db/src/main/scala/org/apache/spark/sql/rapids/shims/spark312db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/312db/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuRunningWindowExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuWindowInPandasExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/ShimBroadcastExchangeLike.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/python/shims/v2/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/python/shims/v2/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/v2/GpuFileScanRDD.scala
  sql-plugin/src/main/post320-treenode/scala/com/nvidia/spark/rapids/shims/v2/TreeNode.scala
  sql-plugin/src/main/pre320-treenode/scala/com/nvidia/spark/rapids/shims/v2/TreeNode.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/VersionUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFallbackSuite.scala
Labels: feature request

#3960 Use a fixed RMM pool size
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Labels: documentation, ease of use, improve

#3869 Add Std dev samp for windowing [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#4020 Fix CPU columnar to GPU columnar conversion for decimal128
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: bug

#4021 Explicitly use the public version of ParquetCachedBatchSerializer
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
Labels: bug, P1

#4024 Allow using a custom Spark Resource Name for a GPU
  docs/configs.md
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Labels: feature request

#4014 fix can't open notebook 'docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb'[skip ci]
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
Labels: documentation

#4029 Update buildall script and the build doc [skip ci]
  CONTRIBUTING.md
  build/buildall
Labels: documentation, task

#3993 Qualification tool: Remove "unsupported" word for nested complex types
  docs/spark-qualification-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/db_sim_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/decimal_part_expectation.csv
  tools/src/test/resources/QualificationExpectations/directory_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_type_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv1_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/spark2_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
Labels: tools

#4019 initialize RMM with a single pool size
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: improve

#3984 Check for data write command before inserting hash sort optimization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FunSuiteWithTempDir.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
Labels: task

#3998 Check for CPU cores and free memory in IT script
  integration_tests/run_pyspark_from_build.sh
Labels: test

#4035 Hash aggregate fix empty resultExpressions [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: task

#4038 Change the `catalystConverter` to be a Scala `val`.
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
Labels: performance

#3770 Enable approx percentile tests
  integration_tests/src/main/python/hash_aggregate_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
Labels: bug

#4046 lower GPU memory reserve to 256MB
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug, documentation, ease of use

#4008 [Doc] Update the getting started guide for databricks: Change from 8.2 to 9.1 runtime [skip ci]
  docs/FAQ.md
  docs/additional-functionality/rapids-shuffle.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#4054 Use install for the base version build thread [skip ci]
  CONTRIBUTING.md
  build/buildall
Labels: bug, build

#3982 Fix the issue of parquet reading with case insensitive schema
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
Labels: bug

#3925 verify AQE and DPP both on
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: test

#3937 Qualification tool: Detect JDBCRelation in eventlog
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/resources/QualificationExpectations/jdbc_expectation.csv
  tools/src/test/resources/spark-events-qualification/jdbc_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#4057 Restore original ASL 2.0 license text
  LICENSE
Labels: documentation

#4044 RLike: Fall back to CPU for regex that would produce incorrect results
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#4066 Temply disable cudf_udf test [databricks]
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test

#4067 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#4072 Fix overflow checking on optimized decimal sum
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
Labels: bug

#4077 Update docs for decimal overflow
  docs/compatibility.md
Labels: documentation

#4070 Support building from sub directory
  integration_tests/pom.xml
  pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark312db/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shims/spark321/pom.xml
  shims/spark330/pom.xml
Labels: build

#4051 Upgrade ORC version from 1.5.8 to 1.5.10
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  tests/src/test/resources/hybrid-Julian-calendar.orc
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
Labels: build

#4049 Change Databricks image from 8.2 to 9.1 [skip ci]
  dist/pom.xml
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/databricks/build.sh
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
Labels: build

#4090 Update pre-merge expression for 2022+ CI [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-tests.sh
Labels: build

#4087 Regex parser improvements and bug fixes
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
Labels: bug

#4043 Promote cudf as dist direct dependency, mark aggregator provided
  README.md
  aggregator/pom.xml
  dist/pom.xml
  dist/scripts/binary-dedupe.sh
Labels: build

#4071 Treat scalac warnings as errors
  pom.xml
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/hiveUDFs.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4094 Remove spark311db shim layer [databricks]
  jenkins/databricks/build.sh
  jenkins/databricks/params.py
  pom.xml
  shims/spark311db/pom.xml
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkShimServiceProvider.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/spark311db/RapidsShuffleManager.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
Labels: build

#4097 Enable auto-merge from branch-21.12 to branch-22.02 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#4109 Stop using redundant partitionSchemaOption dropped in 3.3.0
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: audit_3.3.0

#4113 Fix pre-merge CI 2 conditions [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4099 [REVIEW] Init version 22.02.0 [databricks]
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shims/README.md
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark312/pom.xml
  shims/spark312db/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shims/spark321/pom.xml
  shims/spark330/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation, build

#4114 Refactoring cudf_udf test setup [databricks]
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test

#4101 update emr 6.4 getting started doc and pic to gh-pages[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#4107 Set the task context in background reader threads
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: task

#4095 Support Read/Write ORC on Decimal128
  docs/supported_ops.md
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request

#4111 Added external doc links for JRE and Spark
  pom.xml
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ExplainPlan.scala
Labels: bug

#4116 Add in tests to check for overflow in unbounded window [databricks]
  integration_tests/src/main/python/window_function_test.py
Labels: test

#4052 Support null safe host column vector
  sql-plugin/src/main/301until310-all/scala/com/nvidia/spark/rapids/shims/v2/GpuRowBasedScalaUDF.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/GpuRowBasedScalaUDF.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsNullSafeHostColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsNullSafeHostColumnVectorCore.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowBasedUDFSuite.scala
Labels: task

#4125 Remove unused imports
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
Labels: build

#4128 Fix build errors in udf-examples native build
  udf-examples/Dockerfile
  udf-examples/src/main/cpp/CMakeLists.txt
  udf-examples/src/main/cpp/src/cosine_similarity.cu
Labels: build

#4132 Fix auto merge conflict 4131 [skip ci]
  udf-examples/Dockerfile
  udf-examples/src/main/cpp/CMakeLists.txt
  udf-examples/src/main/cpp/src/cosine_similarity.cu
Labels: build

#4129 Check executor timezone is same as driver timezone when running on GPU
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#4154 Use num_slices to guarantee partition shape in the pandas udf tests
  integration_tests/src/main/python/udf_test.py
Labels: test

#4163 Enable config to check for casting decimals to strings
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: bug

#4165 Fix type checks for get array item in 3.2.0
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
Labels: bug

#4177 Decimal128: added missing decimal128 signature on Spark 32X
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
Labels: bug

#4100 Add PCA example to ml-integration page [skip ci]
  docs/additional-functionality/ml-integration.md
Labels: documentation

#4106 Add docs for MIG on YARN [skip ci]
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#4181 Fix element_at for 3.2.0 and array/struct cast
  docs/supported_ops.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#4174 Document Bloop, Metals and VS code as an IDE option [skip ci]
  CONTRIBUTING.md
  build/buildall
Labels: documentation, build

#4173 Update approx percentile docs to link to issue 4060 [skip ci]
  docs/compatibility.md
Labels: documentation

#4187 Added a getting started guide for Synapse[skip ci]
  docs/FAQ.md
  docs/download.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-azure-synapse-analytics.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-workload-qualification.md
Labels: documentation

#4197 Ignore failing string to timestamp tests temporarily
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: test

#4200 Disable approx percentile tests that intermittently fail
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#4193 Rename 311until320-apache to 311until320-noncdh
  pom.xml
  sql-plugin/src/main/311until320-noncdh/scala/org/apache/spark/rapids/shims/v2/sql/execution/datasources/parquet/rapids/ShimVectorizedColumnReader.scala
Labels: build

#4199 modify some words for synapse getting started guide[skip ci]
  docs/get-started/getting-started-azure-synapse-analytics.md
Labels: documentation

#4202 Parameter for the Databricks zone-id [skip ci]
  jenkins/databricks/clusterutils.py
  jenkins/databricks/create.py
Labels: build

#4211 Update test_floor_ceil_overflow to be more lenient on exception type
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#4212 Remove an unused method with its outdated comment
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: task

#4214 Fix pre_merge ci_2 [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: bug, build

#4217 Enable event log for qualification & profiling tools testing from IT [databricks]
  jenkins/databricks/test.sh
Labels: build

#4215 Rebalance testing load [databricks]
  integration_tests/src/main/python/qa_nightly_select_test.py
  integration_tests/src/main/python/udf_test.py
  jenkins/databricks/test.sh
Labels: build

#4230 Change to build tools module with all the versions by default
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  pom.xml
  tools/pom.xml
Labels: build

#4233 Add databricks init script for UCX
  docs/additional-functionality/rapids-shuffle.md
  docs/img/Databricks/initscript_ucx.png
  docs/img/Databricks/sparkconfig_ucx.png
Labels: documentation, shuffle

#4153 Regexp: Only transpile once per expression rather than once per batch
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
Labels: performance
