Repository NVIDIA/spark-rapids, pull requests merged in 2021-06, with the labels that each got.

#2536 Don't do an extra shuffle in some TopN cases
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: performance

#2525 support interval.microseconds for range window TimeStampType
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: feature request

#2520 Add event logs for integration tests
  integration_tests/README.md
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#2423 Add cloudera shim layer
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311cdh/pom.xml
  shims/spark311cdh/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/ParquetCachedBatchSerializer.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkShimServiceProvider.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/spark311cdh/RapidsShuffleManager.scala
  shims/spark311cdh/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/spark311cdh/ParquetMaterializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFallbackSuite.scala
Labels: feature request

#2558 Fix cdh shim version in 21.08 [skip ci]
  shims/spark311cdh/pom.xml
Labels: build

#2559 Release profiling tool jar to maven central
  jenkins/deploy.sh
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/pom.xml
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
Labels: build

#2538 Fixed code indentation in ParquetCachedBatchSerializer
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
Labels: task

#2523 Not compile RapidsUDF when udf compiler is enabled
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Plugin.scala
Labels: task

#2563 Document: git commit twice when copyright year updated by hook
  CONTRIBUTING.md
Labels: documentation

#2565 Merge branch-21.06 into branch-21.08
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
Labels: build

#2515 Remove fetchTime and standardize on collectTime
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
Labels: task

#2460 align GDS reads/writes to 4 KiB
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
Labels: cudf_dependency, performance

#2566 expose unspill config option
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, performance

#2553 Cancel requests that are queued for a client/handler on error
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
Labels: performance, shuffle

#2458 Split batch by key for window operations
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorBase.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKeyBatchingIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: feature request

#2429 Change RMM_ALLOC_FRACTION to represent percentage of available memory, rather than total memory, for initial allocation
  docs/configs.md
  docs/tuning-guide.md
  integration_tests/run_pyspark_from_build.sh
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Labels: ease of use

#2569 Remove -SNAPSHOT in documentation in preparation for release
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#2581 Fix merge conflict 2580 [skip ci]
  docs/demo/Databricks/generate-init-script.ipynb
Labels: documentation

#2571 Change test_single_sort_in_part to print source data frame on failure
  integration_tests/src/main/python/sort_test.py
Labels: test

#2587 Handle UCX connection timeouts from heartbeats more gracefully
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#2570 Added nested structs to UnionExec
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2590 Profiling tool support for collection and analysis
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetrics2_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetrics_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetricsmulti_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetrics_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsagg2_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsagg_expectation.csv
  rapids-4-spark-tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsaggmulti_expectation.csv
  rapids-4-spark-tools/src/test/resources/spark-events-profiling/eventlog_minimal_events
  rapids-4-spark-tools/src/test/resources/spark-events-profiling/rapids_join_eventlog
  rapids-4-spark-tools/src/test/resources/spark-events-profiling/rapids_join_eventlog2
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: feature request

#2591 Implement test for qualification tool sql metric aggregates
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: test

#2594 Change the README of the qualification and profiling tool to match the current version.
  rapids-4-spark-tools/README.md
Labels: documentation

#2603 Add the doc for -g option of the profiling tool.
  rapids-4-spark-tools/README.md
Labels: documentation

#2576 Add filter support for qualification and profiling tool.
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ToolUtils.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: feature request

#2604 Profile/qualification tool error handling improvements and support spark < 3.1.1
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/resources/spark-events-profiling/malformed_json_eventlog
  tools/src/test/resources/spark-events-profiling/rp_nosql_eventlog
  tools/src/test/resources/spark-events-profiling/rp_sql_eventlog
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: task

#2611 Revert "disable cudf_udf tests for #2521"
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test

#2614 change rapids-4-spark-tools directory to tools in deploy script [skip ci]
  jenkins/deploy.sh
Labels: build

#2612 Profiling tool, add in job to stage, duration, executor cpu time, fix writing to HDFS
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ToolTextFileWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/ProfilingExpectations/rapids_duration_and_cpu_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: task

#2618 Correct an issue for README for tools and also correct s3 solution in Args.scala
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
Labels: documentation

#2620 Change aggregation of executor CPU and run time for Qualification tool to speed up query
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: task

#2636 Profiling tool - Fix file writer for generating dot graphs, supporting writing sql plans to a file, change output to subdirectory
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ToolTextFileWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
Labels: task

#2577 Update download.md and FAQ.md for 21.06.0
  docs/FAQ.md
  docs/download.md
Labels: documentation

#2637 Fix databricks for 3.1.1
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastExchangeExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffleExchangeExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastExchangeExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffleExchangeExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffleExchangeExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuBroadcastExchangeExec.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: P1, SQL, bug

#2582 support parquet write arrays
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2616 support GpuSortArray
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: feature request

#2643 Profiling tool: Health check follow on
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheck.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/ProfilingExpectations/executors_removed_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/tasks_failure_eventlog_expectation.csv
Labels: task

#2638 Add an init script for databricks 7.3ML with CUDA11.0 installed
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
Labels: task

#2631 Update docs for Databricks 8.2 ML
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
Labels: documentation

#2623 Fixed minor mistakes in documentation
  tools/README.md
Labels: documentation

#2651 Profiling tool - fix reporting contains dataset when sql time 0
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
Labels: bug

#2600 Accelerate `RunningWindow` queries on GPU
  integration_tests/src/main/python/window_function_test.py
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuRunningWindowExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuRunningWindowExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: bug

#2663 Qualification tool - add in estimating the App end time when the event log missing application end event
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: bug

#2677 Add pre-merge independent stage timeout [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#2672 Update cudfjni dependency version to 21.06.0
  jenkins/version-def.sh
  pom.xml
Labels: build

#2673 Profiling tool: Enable tests and update compressed event log
  tools/src/test/resources/ProfilingExpectations/executors_removed_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/jobs_failure_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/removed_blockManagers_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/stages_failure_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/tasks_failure_eventlog_expectation.csv
  tools/src/test/resources/spark-events-profiling/tasks_executors_fail_compressed_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheckSuite.scala
Labels: bug, test

#2671 Clean profiling&qualification tool README
  tools/README.md
Labels: documentation

#2665 Update docs to move RAPIDS Shuffle out of beta [skip ci]
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
Labels: documentation

#2666 [DOC]Update custom image guide in GCP dataproc to reduce cluster startup time
  docs/get-started/getting-started-gcp.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#2676 Profiling tool: Print Job Information in compare mode
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
Labels: task

#2668 Remove CUDA 10.x from getting started guide [skip ci]
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#2669 Fix multiple problems reported and improve error handling
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheck.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/spark-events-profiling/rapids_join_eventlog2
  tools/src/test/resources/spark-events-qualification/empty_eventlog
  tools/src/test/resources/spark-events-qualification/join_missing_sql_end
  tools/src/test/resources/spark-events-qualification/rdd_only_eventlog
  tools/src/test/resources/spark-events-qualification/udf_func_eventlog
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: bug

#2681 Avoid NPE when casting empty strings to ints
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: P1, bug

#2661 Make tools inherit common dependency versions from parent pom
  tools/pom.xml
Labels: build

#2686 Profiling tool: Print Job Information in compare mode
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
Labels: task

#2687 Remove CUDA 10.x from getting started guide (#2668)
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#2691 Update properties to check if table there
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
Labels: bug

#2697 fix GDS spill bug when copying from the batch write buffer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
Labels: P1, bug

#2664 Update changelog for 21.06 release [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#2548 support collect_set in rolling window
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#2706 Change rapids version to 21.06.0
  api_validation/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#2700 Set numSlices and use parallelize to build dataframe for partition-se…
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/sort_test.py
Labels: test

#2699 Add a pre-commit hook to reject large files
  .pre-commit-config.yaml
Labels: build

#2702 Add in support for arrays in BroadcastNestedLoopJoinExec and CartesianProductExec
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: SQL, task

#2596 Initial running window memory optimization
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: SQL, performance

#2554 Upload build failure log to Github for external contributors access
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build

#2716 Add file size check to pre-merge CI
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-premerge-build.sh
Labels: build

#2586 Update metrics use in GpuUnionExec and GpuCoalesceExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: task

#2722 Support aggregation on NullType in RunningWindowExec
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: P1, bug

#2726 Fix local mode starting RAPIDS shuffle heartbeats
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: shuffle

#2729 fix 301db-shim typecheck typo
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
Labels: bug, test

#2747 Fix num_slices for test_single_nested_sort_in_part
  integration_tests/src/main/python/sort_test.py
Labels: test

#2707 Support `KnownNotNull` running on GPU
  docs/configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/constraintExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/KnownNotNullSuite.scala
Labels: feature request

#2751 remove invalid blossom-ci users [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2740 Update cudf Java bindings to 21.06.1
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2753 Merge branch-21.06 to branch-21.08 [skip ci]
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/printJarVersion.sh
Labels: documentation

#2181 abstract the parquet coalescing reading
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: performance

#2749 Revert "Add in support for lists in some joins (#2702)"
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#2743 Disable dynamicAllocation and set maxFailures to 1 in integration tests
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: test

#2745 Add link to Mellanox RoCE documentation and mention --without-ucx installation option
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation, shuffle

#2532 date_format should not suggest enabling incompatibleDateFormats for formats we cannot support
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: bug

#2770 [Doc] add more for Alluxio page [skip ci]
  docs/get-started/getting-started-alluxio.md
Labels: documentation

#2774 Update changelog for 21.06 release [skip ci]
  CHANGELOG.md
Labels: documentation

#2769 Add developer documentation for Adaptive Query Execution
  docs/dev/README.md
  docs/dev/adaptive-query.md
Labels: documentation

#2768 Make window function test results deterministic.
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: test

#2735 Use UCX Active Messages for all shuffle transfers
  docs/configs.md
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXTransaction.scala
  sql-plugin/src/main/format/ShuffleTransferRequest.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/BufferTransferRequest.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/TransferRequest.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: shuffle

#2760 Add in application timeline to profiling tool
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimeline.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimelineSuite.scala
Labels: task

#2791 Correct jar download link in Databricks generate-init-script.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
Labels: documentation

#2761 Update dot graph to include stages and remove some duplication
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
Labels: task

#2762 Profiling tool: Update comparison mode output format and add error handling
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheck.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/resources/ProfilingExpectations/jobs_failure_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/stages_failure_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/tasks_failure_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/unsupported_sql_eventlog_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: feature request

#2744 Cost-based optimizer: Implement simple cost model that demonstrates benefits with NDS queries
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: performance

#2794 Prevent integer overflow when estimating data sizes in cost-based optimizer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: performance

#2801 Update pre-merge to use reserved_pool [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#2796 show disk bytes spilled when GDS spill is enabled
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
Labels: ease of use

#2797 Update documentation for InitCap incompatibility
  docs/configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: documentation

#2805 Revert "Use UCX Active Messages for all shuffle transfers (#2735)"
  docs/configs.md
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXTransaction.scala
  sql-plugin/src/main/format/ShuffleTransferRequest.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/BufferTransferRequest.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/TransferRequest.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: bug, shuffle

#2806 Noted testing for A10, noted that min driver ver is HW specific
  docs/FAQ.md
  docs/download.md
Labels: documentation

#2792 Automatically set spark.task.maxFailures and local[*, maxFailures]
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: test

#2788 Update the type signatures for some expressions
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: P2, task

#2798 Mirror apache repos to urm
  jenkins/settings.xml
Labels: build

#2810 Use SecureRandom for UCPListener TCP port choice
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
Labels: shuffle, task

#2817 Update changelog for v21.06.0 release [skip ci]|
  CHANGELOG.md
Labels: documentation

#2819 Merge branch-21.06 to main [skip ci]
  CHANGELOG.md
  docs/FAQ.md
  docs/configs.md
  docs/download.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: documentation

#2793 Report equivilant stages/sql ids as a part of compare
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimeline.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
Labels: task

#2827 Update cmake to build udf native [skip ci]
  udf-examples/Dockerfile
  udf-examples/pom.xml
Labels: build

#2821 Truncate long plan labels and refer to "print-plans"
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
Labels: bug, tools

#2816 Improve some existing collectTime handling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: task

#2720 Add metrics documentation to the tuning guide
  docs/tuning-guide.md
Labels: documentation

#2829 Fix filtering directories on compression extension match
  tools/src/main/scala/com/nvidia/spark/rapids/tool/EventLogPathProcessor.scala
Labels: bug

#2823 Add semaphoreWaitTime and gpuOpTime for GpuRowToColumnarExec
  docs/tuning-guide.md
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvtxWithMetrics.scala
Labels: bug

#2822 Rewrite Qualification tool for better performance
  tools/README.md
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/tool/EventLogPathProcessor.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ToolTextFileWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualEventProcessor.scala
  tools/src/test/resources/QualificationExpectations/db_sim_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/directory_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheckSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: performance, task

#2837 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2833 Stop running so many versions of Spark unit tests for premerge
  jenkins/spark-premerge-build.sh
Labels: build

#2836 Update gh-pages for 21.06 release
  docs/FAQ.md
  docs/additional-functionality/cache-serializer.md
  docs/additional-functionality/gds-spilling.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_3.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#2841 Add a threadpool to Qualification tool to process logs in parallel
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualAppInfo.scala
Labels: tools

#2787 Add metrics definition link to tool README.md[skip ci]
  tools/README.md
Labels: documentation

#2844 Document Qualification tool Spark requirements
  tools/README.md
Labels: documentation, tools

#2840 Fix Gpu -> GPU
  docs/additional-functionality/cache-serializer.md
Labels: documentation

#2848 Update release notes to include qualification and profiling tools
  docs/download.md
Labels: documentation

#2785 Profiling tool: Print UCX and GDS parameters
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/spark-events-profiling/gds_ucx_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: feature request

#2851 Fix build failure - update ucx profiling test to fix parameter type to getEventLogInfo
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: test

#2845 Split window exec into multiple stages if needed
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: task

#2852 Fix hash aggregate tests leaking configs into other tests
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: test
