Repository NVIDIA/spark-rapids, pull requests merged in 2021-05, with the labels that each got.

#2318 Fix ColumnarToRowIterator handling of empty batches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuColumnarToRowSuite.scala
Labels: bug

#2319 Disable hash partitioning on arrays
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: bug

#2316 Update doc to note that single quoted json strings are not ok
  docs/compatibility.md
Labels: documentation

#2324 Upmerge from branch-0.5 and resolve merge conflicts
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuColumnarToRowSuite.scala
Labels: build

#2173 Support GpuHashJoin on Structs
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: feature request

#2321 Restore output of unsupported column types
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#2326 Update changelog for 0.5.0 release
  CHANGELOG.md
Labels: documentation

#2310 Allow batching the output of a join
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/join_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBoundAttribute.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: cudf_dependency, feature request

#2335 Merge branch-0.5 to main for 0.5.0 release
  CHANGELOG.md
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuColumnarToRowSuite.scala
Labels: build

#2243 Remove ShuffleExchangeExec from the automatic allow list in tests
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastNestedLoopJoinSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CsvScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#2337 Update the databricks shim for struct joins.
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuSortMergeJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuSortMergeJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuSortMergeJoinExec.scala
Labels: bug

#2166 Script for auto prioritizing audit
  scripts/audit-spark-3.2.sh
  scripts/prioritize-commits.sh
Labels: audit

#2341 Fix deprecated aggregation and GpuFlatMapGroupsInPandasExec scaladoc
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
Labels: build

#2340 Allow partial materialization of broadcast nested loop join and cartesian exec
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastNestedLoopJoinSuite.scala
Labels: SQL, feature request

#2271 Parquet support for Structs
  docs/additional-functionality/cache-serializer.md
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/parquet_write_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#2357 Have broadcast exchange exec produce a contiguous table
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: performance

#2358 Allow noop filter and joins to keep contig tables untouched.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: performance

#2263 Support columnar pipeline for Grouped Agg UDF
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/python/rapids/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: feature request

#2361 Fix Alias to properly call the shim version
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: P1, bug

#2270 Deal with rolling API Changes in CUDF
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: task

#2366 Fix noop filter check to handle nulls
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: bug

#2373 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2376 Disable the cudf window test on Databricks
  integration_tests/src/main/python/udf_cudf_test.py
Labels: test

#2377 Remove team member not working on the project [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#2323 Update CBO to use fixed cost model and to respect estimated row counts
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: performance

#2383 Remove unneeded join key "optimization"
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance

#2386 Add Decimal types to caching tests
  integration_tests/src/main/python/cache_test.py
Labels: test

#2393 change location of audit log
  scripts/prioritize-commits.sh
Labels: task

#2388 `CaseWhen` supports `ArrayType`
  docs/supported_ops.md
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request

#2394 Document tuning of spark.task.resource.gpu.amount
  docs/get-started/getting-started.md
  docs/tuning-guide.md
Labels: documentation

#2311 Update Spark Operator getting started guide.
  docs/get-started/getting-started-kubernetes.md
Labels: documentation

#2396 Keep GpuCoalesceExec if a shuffle or custom reader is the parent exec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: shuffle

#2384 Refactor to avoid code duplication between GpuBroadcastToCpu and GpuBroadcastExchange
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala
Labels: task

#2399 Github pages 0.5 update
  CONTRIBUTING.md
  docs/FAQ.md
  docs/additional-functionality/cache-serializer.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/yarn-gpu.md
  docs/img/concurrentPythonWorker.PNG
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#2274 Enable struct columns for GpuHashAggregateExec
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: feature request

#2405 Activate databricks 8.2 runtime jar being included in nightly and use property instead of profile
  jenkins/spark-nightly-build.sh
  shims/aggregator/pom.xml
Labels: build

#2413 Ignore group order in test_struct_groupby_count
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug, test

#2403 Provide optional pre-commit hook config
  .pre-commit-config.yaml
  CONTRIBUTING.md
  scripts/auto-copyrighter.sh
Labels: build, documentation, task

#2418 Change Databricks zone [skip ci]
  jenkins/databricks/clusterutils.py
Labels: build

#2020 Support integral type range window
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ArmSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: feature request

#2395 Unify legacy and 3.1.x struct cast implementations
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: P1, bug

#2363 Refactor the handling of scalar columnarEval results
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalarSubquery.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/GpuScalarUnitTest.scala
Labels: task

#2260 Support ElementAt
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: feature request

#2419 Fix rolling window API differences
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: task

#2434 Update cudfjni to 21.06-SNAPSHOT
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2350 AnsiMode support for GetArrayItem GetMapValue and ElementAt for Spark 3.1.1
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/map_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: task

#2432 Switch to single-level structs in hash aggregate tests and work around value-dedupe bug
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#2444 Update auto-merge to branch-21.06 [skip ci] [bot]
  .github/workflows/auto-merge.yml
Labels: build

#2433 Split up stream side for exploding joins
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: task

#2313 Supports `GpuLiteral` of array type
  docs/supported_ops.md
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: feature request, task

#2402 Add profiling tool
  pom.xml
  rapids-4-spark-tools/.gitignore
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/pom.xml
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ToolUtils.scala
  rapids-4-spark-tools/src/test/resources/eventlog_minimal_events
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  workload_profiling/.gitignore
Labels: feature request

#2448 support creating list ColumnVector for Literal(ArrayType(NullType))
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
Labels: bug

#2435 support lead/lag on arrays
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2451 Update tuning docs to add batch size recommendations.
  docs/tuning-guide.md
Labels: documentation

#2299 support creating array of array
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: feature request

#2426 Implement cast of nested arrays
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request

#2447 Filter out the nulls after slicing the batches.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
Labels: bug

#2456 Fall back to the CPU for literal array values on case/when
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: P1, SQL, bug

#2379 support GpuConcat on ArrayType
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: feature request

#2442 fix GpuCreateNamedStruct not serializable issue
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: bug

#2397 Include memory access costs in cost models (cost-based optimizer)
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: feature request

#2409 Change shuffle metadata messages to use UCX Active Messages
  docs/configs.md
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXTransaction.scala
  sql-plugin/src/main/format/ShuffleMetadataRequest.fbs
  sql-plugin/src/main/format/ShuffleMetadataResponse.fbs
  sql-plugin/src/main/format/ShuffleTransferRequest.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/MetadataRequest.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/MetadataResponse.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/TransferRequest.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/UCXConnectionSuite.scala
Labels: shuffle

#2446 Update plugin version to 21.06.0
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark310db/pom.xml
  shims/spark311/pom.xml
  shims/spark312/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsExecutorPluginSuite.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2471 skip test_window_aggs_for_rows_lead_lag_on_arrays
  integration_tests/src/main/python/window_function_test.py
Labels: test

#2476 Fix for UCP Listener created spark.port.maxRetries times
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
Labels: bug, shuffle

#2472 Fix hash_aggregate_test
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#2484 Fix the failing test `test_window` on Databricks
  integration_tests/src/main/python/udf_cudf_test.py
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuWindowInPandasExec.scala
  shims/spark310db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark310db/GpuWindowInPandasExec.scala
Labels: bug

#2469 Adding additional functionalities to profiling tool
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Qualification.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ToolUtils.scala
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: feature request

#2482 Window tests with smaller batches
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/window_function_test.py
Labels: bug, test

#2491 Fix regression in cost-based optimizer when calculating cost for Window operations
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: bug

#2498 Add in basic support for scalar maps and allow nesting in named_struct
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: feature request

#2499 Fix regression in TOTAL_TIME metrics for Databricks
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark310db/src/main/scala/com/nvidia/spark/rapids/shims/spark310db/GpuBroadcastHashJoinExec.scala
Labels: P1, bug

#2502 Remove work around for nulls in semi-anti joins
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance

#2500 Update Dockerfile for native UDF
  udf-examples/Dockerfile
Labels: build

#2475 Update shuffle documentation for branch-21.06 and UCX 1.10.1
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation, shuffle

#2509 Added in basic support for scalar structs to named_struct
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: SQL

#2505 Qualification tool updates for datasets, udf, and misc fixes
  rapids-4-spark-tools/README.md
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  rapids-4-spark-tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Qualification.scala
  rapids-4-spark-tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  rapids-4-spark-tools/src/test/resources/dataset_eventlog
  rapids-4-spark-tools/src/test/resources/udf_dataset_eventlog
  rapids-4-spark-tools/src/test/resources/udf_func_eventlog
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  rapids-4-spark-tools/src/test/scala/orga/apache/spark/rapids/TestUtils.scala
  workload_profiling/.gitignore
Labels: feature request

#2516 Avoid listener race collecting wrong plan in assert_gpu_fallback_collect
  integration_tests/src/main/python/asserts.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: test

#2463 Add EMR 6.3 documentation
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_3.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#2526 Improve debug print to include addresses and null counts
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
Labels: test

#2507 Improve test coverage for sorting structs
  integration_tests/src/main/python/sort_test.py
Labels: test

#2479 Support concat with separator on GPU
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: feature request

#2528 Make GenerateDot test more robust
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
Labels: test

#2533 Fix concat_ws test specifying only a separator for databricks
  integration_tests/src/main/python/string_test.py
Labels: test

#2513 Report opTime not totalTime for expand, range, and generate execs
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
Labels: task

#2537 Add CentOS documentation and improve dockerfiles for UCX
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
Labels: documentation, shuffle

#2534 Remove scaladoc on an internal method to avoid warning during build
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: build

#2514 Add Struct support for ParquetWriter
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: documentation

#2539 disable cudf_udf tests for #2521
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test

#2543 Init branch-21.08
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  rapids-4-spark-tools/pom.xml
  rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2542 enable auto-merge from 21.06 to 21.08 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build
