Repository NVIDIA/spark-rapids, pull requests merged in 2021-08, with the labels that each got.

#3107 Add setting to enable/disable RAPIDS Shuffle Manager dynamically
  docs/additional-functionality/rapids-shuffle.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleDependency.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: shuffle

#2971 Support GpuCollectList and GpuCollectSet as TypedImperativeAggregate
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
Labels: task

#3119 Branch 21.06 databricks update [skip ci]
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3118 Fix databricks 3.0.1 for ParquetFilters api change
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: bug

#3124 Fix merge conflict 3122 [skip ci]
  scripts/generate-changelog
Labels: documentation

#3123 Update rapids plugin version to 21.06.1 [skip ci]
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/README.md
  tools/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation, test

#3127 Update CHANGELOG for the release v21.06.1 [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#3128 Fix merge conflict 3126 from branch-21.06 [skip ci]
  CHANGELOG.md
Labels: build, documentation

#3129 Update rapids version for the v21.06.1 release [skip ci]
  CHANGELOG.md
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  scripts/generate-changelog
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/pom.xml
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  shims/spark320/pom.xml
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/README.md
  tools/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build

#3109 Cudf agg type changes
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: task

#3117 First pass at enabling structs, arrays, and maps for more parts of the plan
  docs/supported_ops.md
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitExecSuite.scala
Labels: task

#3112 Qualification tool: Add conjunction and disjunction filters
  docs/additional-functionality/qualification-profiling-tools.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/EventLogPathProcessor.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#3136 Update tool docs to explain default filesystem [skip ci]
  docs/additional-functionality/qualification-profiling-tools.md
Labels: documentation

#3137 Branch 21.06 databricks update [skip ci] (#3119)
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3148 Updated RunningWindow to support extended types too
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: bug

#2728 Support string `repeat` SQL
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/StringRepeatUnitTest.scala
Labels: feature request, SQL

#3099 Decimal_128 type checks
  docs/supported_ops.md
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: documentation

#3080 Update docs for 21.08 release
  docs/FAQ.md
  docs/additional-functionality/qualification-profiling-tools.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/adaptive-query.md
  docs/dev/nvtx_profiling.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/supported_ops.md
  integration_tests/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation

#3146 update cudf Java binding version to 21.08.2
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation, build

#3168 Update 21.08 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#3169 Fix auto-merge conflict 3167 [skip ci]
  CHANGELOG.md
  docs/FAQ.md
  docs/additional-functionality/qualification-profiling-tools.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/adaptive-query.md
  docs/dev/nvtx_profiling.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation

#3170 Update version to v21.08.0 [skip ci]
  CHANGELOG.md
  api_validation/pom.xml
  dist/pom.xml
  docs/FAQ.md
  docs/additional-functionality/qualification-profiling-tools.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/adaptive-query.md
  docs/dev/nvtx_profiling.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/supported_ops.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build

#3161 Rework Profile tool to not require Spark to run and process files faster
  docs/additional-functionality/qualification-profiling-tools.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimeline.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheck.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/resources/ProfilingExpectations/rapids_duration_and_cpu_expectation.csv
  tools/src/test/resources/ProfilingExpectations/unsupported_sql_eventlog_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/CompareSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimelineSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheckSuite.scala
Labels: tools

#3113 Fix order of operations when using mkString in typeConversionInfo
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: task

#3173 Profile tool: Fix reporting app contains Dataset
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
Labels: bug, tools

#3171 Refine upload log stage naming in workflow file [skip ci]
  .github/workflows/blossom-ci.yml
  CONTRIBUTING.md
Labels: documentation, build

#3193 Append res-life to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#3190 Update GpuInSet for SPARK-35422 changes
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
Labels: audit

#3178 Fix hash_aggregate test failures due to TypedImperativeAggregate
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: bug

#3189 Disable snapshot shims by default
  CONTRIBUTING.md
  shims/aggregator/pom.xml
  shims/pom.xml
Labels: build

#3197 Databricks parquetFilters api change in db 8.2 runtime
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: bug

#3198 Databricks parquetFilters api change in db 8.2 runtime
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: bug, P1

#3205 Branch 21.06 databricks update [skip ci]
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3208 Update rapids plugin version to 21.06.2 [skip ci]
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/README.md
  tools/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation

#3209 Update 21.06.2 changelog [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#3210 Update 21.08.0 changelog to latest [skip ci]
  CHANGELOG.md
  integration_tests/README.md
  scripts/generate-changelog
Labels: documentation

#3212 Fix merge conflict 3211 [skip ci]
  CHANGELOG.md
  integration_tests/README.md
  scripts/generate-changelog
Labels: documentation

#3214 Update download and databricks doc for 21.06.2 [skip ci]
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3216 Update changelog to include download doc update [skip ci]
  CHANGELOG.md
Labels: documentation

#3204 Decrease parallelism for pre-merge integration tests
  jenkins/spark-premerge-build.sh
Labels: build

#3213 Merge branch 'origin/branch-21.08' into main [skip ci]
  CHANGELOG.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  integration_tests/README.md
  scripts/generate-changelog
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: build

#3218 Add UCX 1.11.0 to the pre-merge Docker image
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#3203 Fix Parquet test_round_trip to avoid CPU write exception
  integration_tests/src/main/python/parquet_test.py
Labels: test

#3219 Release 21.06.2 doc update [skip ci]
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3200 Enable a smoke test for UCX in pre-merge
  integration_tests/pytest.ini
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/marks.py
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: test, shuffle

#3228 Fix unreachable code warnings in GpuCast
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: build

#3179 Support GpuFirst/GpuLast on more data types
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: feature request

#3231 Fix some resource leaks in GpuCast and RapidsShuffleServerSuite
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
Labels: bug

#2846 default rmm alloc fraction to the max to avoid unnecessary fragmentation
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: shuffle, ease of use

#3236 Fix Scaladoc warnings in GpuScalaUDF and BufferSendState
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
Labels: documentation

#3184 Support broadcast nested loop join for LeftSemi and LeftAnti
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: SQL

#3233 update 21.08 gh-pages doc
  docs/FAQ.md
  docs/additional-functionality/cache-serializer.md
  docs/additional-functionality/qualification-profiling-tools.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/README.md
  docs/dev/adaptive-query.md
  docs/dev/nvtx_profiling.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#3241 Split pytest by 'slow_test' tag and run from different k8s pods to reduce premerge job duration
  integration_tests/pytest.ini
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/udf_test.py
  jenkins/spark-premerge-build.sh
Labels: test

#3246 Disable test_broadcast_nested_loop_join_condition_missing_count on Databricks
  integration_tests/src/main/python/join_test.py
Labels: test

#3183 Add TypeSig checks for join keys and other special cases
  docs/supported_ops.md
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuSortMergeJoinMeta.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuSortMergeJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffledHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuSortMergeJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuBroadcastHashJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuShuffledHashJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuSortMergeJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: documentation

#3249 Fix typo in Spark311dbShims
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: build

#3252 Update to new cudf AST API
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBoundAttribute.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/namedExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
Labels: build, cudf_dependency

#3254 gh-pages fix links in rapids-udfs.md
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#3230 Initial support for CreateMap on GPU
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: feature request

#3239 Support decimal type in orc reader
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: feature request

#3242 Support for LeftOuter/BuildRight and RightOuter/BuildLeft nested loop joins
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: feature request

#3261 Fix some typos[skip ci]
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/compatibility.md
Labels: documentation

#3164 Support Union on Map types
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3259 Generate docs for AST from checks
  docs/configs.md
  docs/supported_ops.md
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuSortMergeJoinMeta.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuSortMergeJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffledHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuSortMergeJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuBroadcastHashJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuShuffledHashJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuSortMergeJoinExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: documentation, feature request

#3270 Remove reference to old maven-scala-plugin
  tools/pom.xml
Labels: build

#3272 Fix Databricks shim build
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: build

#3264 Add parallel support to nightly spark standalone tests
  integration_tests/run_pyspark_from_build.sh
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/spark-tests.sh
Labels: test

#3281 Decrease parallelism for pre-merge pod to avoid potential OOM kill
  jenkins/spark-premerge-build.sh
Labels: test

#3285 Qualification tool: Check for metadata being null
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
Labels: tools

#3280 Update project URL to the public doc website
  pom.xml
Labels: build

#3234 Parquet support for MapType
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: feature request

#3251 CreateMap support for multiple key-value pairs
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: feature request

#3274 Add m2 cache to fast premerge build
  jenkins/spark-premerge-build.sh
Labels: test, build

#3295 Rename pytest 'slow_test' tag as 'premerge_ci_1' to avoid confusion
  integration_tests/pytest.ini
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/udf_test.py
  jenkins/spark-premerge-build.sh
Labels: test, build

#3282 Test for `current_date`, `current_timestamp` and `now`
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: test

#3294 Update Qualification and Profiling tool documentation for gh-pages
  docs/additional-functionality/qualification-profiling-tools.md
Labels: documentation

#3299 Insert buffer converters for TypedImperativeAggregate
  integration_tests/src/main/python/hash_aggregate_test.py
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuColumnarToRowTransitionExec.scala
  shims/spark311cdh/src/main/scala/org/apache/spark/sql/rapids/shims/spark311cdh/GpuColumnarToRowTransitionExec.scala
  shims/spark312/src/main/scala/org/apache/spark/sql/rapids/shims/spark312/GpuColumnarToRowTransitionExec.scala
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/GpuColumnarToRowTransitionExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuCustomShuffleReaderExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: task

#3317 Adds in support for the transform_values SQL function
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
Labels: task

#3343 Qualification tool backport: Check for metadata being null (#3285)
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
Labels: tools

#3351 Update changelog for tools v21.08.1 release [skip CI]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#3353 Fix automerge conflict 3349 [skip ci]
  CHANGELOG.md
  docs/additional-functionality/qualification-profiling-tools.md
  scripts/generate-changelog
Labels: documentation

#3352 Merge remote-tracking branch 'origin/branch-21.08' into main [skip ci]
  CHANGELOG.md
  docs/additional-functionality/qualification-profiling-tools.md
  scripts/generate-changelog
  tools/pom.xml
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
Labels: build

#3346 Mark more tests as premerge_ci_1
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/qa_nightly_select_test.py
  jenkins/spark-premerge-build.sh
Labels: test

#3276 Use child type in some places to make it more clear
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation, task

#3340 xfail AST nested loop join tests until cudf empty left table bug is fixed
  integration_tests/src/main/python/join_test.py
Labels: test

#3355 Add new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#3357 Avoid RAT checks on any CSV file
  pom.xml
Labels: build

#3345 Add job commit time to task tracker stats
  sql-plugin/src/main/scala/com/nvidia/spark/TimingUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/BasicColumnarWriteStatsTracker.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ColumnarWriteStatsTracker.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuWriteStatsTracker.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: audit_3.2.0

#3344 Move classes out of Apache Spark packages
  sql-plugin/src/main/java/com/nvidia/spark/rapids/CudfUnsafeRow.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/org/apache/spark/shuffle/rapids/RapidsShuffleExceptions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
Labels: task

#3356 Support Databricks 3.0.1 with new build profiles
  integration_tests/pom.xml
  jenkins/databricks/build.sh
  pom.xml
  shims/spark301db/pom.xml
  shims/spark311db/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build
