Repository NVIDIA/spark-rapids, pull requests merged in 2021-07, with the labels that each got.

#2849 Update release notes to include qualification and profiling tool
  docs/download.md
Labels: documentation

#2675 Support for Decimals with negative scale for Parquet Cached Batch Serializer
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/parquet_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnCastUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DecimalUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: task

#2721 Check-list for corner cases in testing.
  integration_tests/README.md
Labels: documentation, test

#2828 add cloud reading for orc
  docs/configs.md
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: feature request

#2843 Qualification/Profiling tool add tests for Spark2 event logs
  tools/README.md
  tools/src/test/resources/QualificationExpectations/spark2_expectation.csv
  tools/src/test/resources/spark-events-profiling/spark2-eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: test, tools

#2874 Update audit script to clone branch-3.2 instead of master
  scripts/audit-spark-3.2.sh
Labels: task

#2882 Refactor window operations to do them in the exec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: task

#2870 Avoid readers acquiring GPU on next batch query if not first batch
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: performance

#2838 Replace `toTitle` with `capitalize` for GpuInitCap
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug, cudf_dependency

#2873 Fix infinite loop in MultiFileCloudPartitionReaderBase
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: bug

#2854 Qualification Tool to output only the 'k' highest-ranked or 'k' lowest-ranked applications
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: feature request

#2894 Fixes a JVM leak for UCX TransactionRequests
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
Labels: shuffle

#2875 Add support for timeParserPolicy=LEGACY
  docs/compatibility.md
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CudfTestHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: feature request

#2886 Use UCP Listener for UCX connections and enable peer error handling
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: shuffle

#2908 Fixes bad string contains in run_pyspark_from_build
  integration_tests/run_pyspark_from_build.sh
Labels: bug

#2890 Fix cast to date bug
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: P1, bug

#2906 Fix compiler warning
  tests/src/test/scala/com/nvidia/spark/rapids/CudfTestHelper.scala
Labels: task

#2914 Profiling tool: add app index to tables that don't have it
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheck.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/ProfilingExpectations/executors_removed_eventlog_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetrics_expectation.csv
  tools/src/test/resources/ProfilingExpectations/removed_blockManagers_eventlog_expectation.csv
Labels: tools

#2911 Add in ID as sort for Job + Stage level aggregated task metrics
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
Labels: tools

#2880 Added ParquetCachedBatchSerializer support for Databricks
  jenkins/databricks/run-tests.py
  jenkins/databricks/test.sh
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: feature request

#2842 Support STRUCT/STRING for LEAD()/LAG()
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#2898 Add fuzz tests for cast from string to other types
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: test

#2895 Add in running window optimization using scan
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: performance

#2903 Fix cast string to bool
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: P1, bug

#2888 Type check with the information from RapidsMeta
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: task

#2926 GPU Active Messages for all buffer types
  docs/configs.md
  shuffle-plugin/pom.xml
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXTransaction.scala
  sql-plugin/src/main/format/ShuffleTransferRequest.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/BufferTransferRequest.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/TransferRequest.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: shuffle

#2932 Profiling tool: Fix comparing spark2 and spark3 event logs
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#2934 Qualification tool: Add filter based on appName
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/EventLogPathProcessor.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/FilterAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#2940 qualification tool: add filtering by app start time
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#2938 Qualification tool: Add negation filter
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#2909 Support orc coalescing reading
  docs/configs.md
  integration_tests/src/main/python/orc_test.py
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuOrcScan.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuOrcScan.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: P1, feature request

#2917 Refine GpuHashAggregateExec.setupReference
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: task

#2944 Fix childExprs list for GpuWindowExpression, for Spark 3.1.x.
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/OffsetWindowFunctionMeta.scala
Labels: P1, bug

#2919 Fix bugs in CAST string to integer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#2941 Make test event log compression codec configurable
  integration_tests/README.md
  integration_tests/src/main/python/spark_init_internal.py
Labels: task, test

#2951 Qualification tool: Allow app start and app name filtering and test with filesystem filters
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#2961 Fix ParquetFilters issue
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: Spark 3.1+, bug

#2922 Improve UCX assertion to show the failed assertion
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
Labels: ease of use

#2950 Fix shutdown bugs in the RAPIDS Shuffle Manager
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#2924 Fix bug when collecting directly from a GPU shuffle query stage with AQE on
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: P1, bug

#2956 Profile Tool: make order consistent between runs
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
Labels: tools

#2963 Add override getParquetFilters for shim 304
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/Spark304Shims.scala
Labels: bug, build

#2933 Improve CAST string to float implementation to handle more edge cases
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#2969 Make the dir for spark301 shuffle shim match package name
  shims/spark301/src/main/scala/org/apache/spark/sql/rapids/shims/spark301/GpuSchemaUtils.scala
  shims/spark301/src/main/scala/org/apache/spark/sql/rapids/shims/spark301/ShuffleManagerShim.scala
Labels: task

#2968 Fix AQE CustomShuffleReaderExec not seeing ShuffleQueryStageExec
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: bug

#2948 Remove unnecessary copies of ParquetCachedBatchSerializer
  docs/additional-functionality/cache-serializer.md
  jenkins/spark-tests.sh
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/ParquetCachedBatchSerializer.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/ParquetCachedBatchSerializer.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/ParquetCachedBatchSerializer.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/ParquetCachedBatchSerializer.scala
Labels: task

#2974 Qualification tool: fix performance regression
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
Labels: tools

#2973 Assert that CPU and GPU row fields match when present
  integration_tests/src/main/python/asserts.py
Labels: test

#2947 Qualification tool: Filter based on timestamp in event logs
  tools/README.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/EventLogPathProcessor.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#2946 ORC reader supports list
  docs/supported_ops.md
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
Labels: feature request

#2978 enable auto-merge from branch 21.08 to 21.10 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#2826 CaseWhen supports scalar of list and struct
  docs/supported_ops.md
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: cudf_dependency, feature request

#2935 Read the complete batch before returning when selectedAttributes is empty
  integration_tests/src/main/python/cache_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: bug

#2986 Avoid struct aliasing in test_round_robin_sort_fallback
  integration_tests/src/main/python/repart_test.py
Labels: test

#2970 Put the GPU data back on host before processing cache on CPU
  integration_tests/src/main/python/cache_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
Labels: bug

#2984 Avoid comparing window range canonicalized plans on Spark 3.0.x
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: test

#2994 Tweak RAPIDS Shuffle Manager configs for 21.08
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation, shuffle

#2992 Remove commented/redundant window-function tests.
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: P2, test

#2985 Move tools README to docs/additional-functionality/qualification-profiling-tools.md with some modification
  docs/additional-functionality/qualification-profiling-tools.md
  tools/README.md
Labels: documentation, tools

#2977 Expire executors from the RAPIDS shuffle heartbeat manager on timeout
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleHeartbeatManagerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleHeartbeatManagerTest.scala
Labels: bug, shuffle

#3000 Merge branch-21.08 to branch-21.10
  docs/additional-functionality/qualification-profiling-tools.md
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
  tools/README.md
Labels: build

#2987 Update documentation for unsupported edge cases when casting from string to timestamp
  docs/compatibility.md
Labels: documentation

#2839 GpuIf and GpuCoalesce support array and struct types
  docs/supported_ops.md
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: cudf_dependency, feature request

#2982 Add FAQ entry for timezone error
  docs/FAQ.md
Labels: documentation

#2967 Resolve hidden source incompatibility between Spark30x and Spark31x Shims
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala
Labels: bug

#2999 Remove unused configuration setting spark.rapids.sql.castStringToInteger.enabled
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: documentation

#2989 Re-enable Array support in Cartesian Joins, Broadcast Nested Loop Joins
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: P1, feature request

#3009 Propagate child output ordering in GpuCoalesceBatches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: bug

#2980 Init version 21.10.0
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2953 Add in support for rank and dense_rank
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: cudf_dependency, feature request

#3018 [BUG] fix db script hides error issue
  jenkins/databricks/run-tests.py
Labels: bug, test

#3022 Add in docs to describe window performance
  docs/tuning-guide.md
Labels: documentation

#3025 Qualification tool: Add regex and username filters.
  docs/additional-functionality/qualification-profiling-tools.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/FilterAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#3028 Enable parallel build for pre-merge job to reduce overall duration [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build, test

#2887 ORC reader supports struct
  docs/supported_ops.md
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
Labels: cudf_dependency, feature request

#3053 cherry-pick #3028 [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build, test

#3015 Fix ORC read error when read schema reorders file schema columns
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#3050 Updates for google analytics [skip ci]
  docs/_config.yml
  docs/_includes/analytics.html
Labels: documentation

#3048 Apply unique committer job ID fix from SPARK-33230
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: audit_3.1.0, audit_3.2.0

#3031 add doc for PR status checks [skip ci]
  CONTRIBUTING.md
Labels: documentation

#3068 Profiling tool generate dot file fails on unescaped html characters
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDotSuite.scala
Labels: tools

#3069 Fall back to the CPU on window partition by struct or array
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: bug

#3024 Check validity of any() or all() results that could be null
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RebaseHelperSuite.scala
Labels: task

#3011 Support MapType in joins
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/join_test.py
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
Labels: feature request

#3067 Update to UCX 1.11.0
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  shuffle-plugin/pom.xml
Labels: shuffle

#3049 Handle mmap exception more gracefully in RapidsShuffleServer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/org/apache/spark/shuffle/RapidsShuffleExceptions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
Labels: shuffle

#3064 Tweak scaladoc to callout the GDS+unspill case in copyBuffer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
Labels: documentation

#3034 Support Sort on nested struct
  docs/supported_ops.md
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3077 Updates for google analytics [skip ci] (#3050)
  _config.yml
  docs/_includes/analytics.html
Labels: documentation

#3062 Fix ORC read corruption when specified schema does not match file order
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  tests/src/test/resources/disorder-read-schema.parquet
  tests/src/test/resources/schema-can-prune.orc
  tests/src/test/resources/schema-cant-prune.orc
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: bug

#3079 Remove the struct support in ORC reader
  docs/supported_ops.md
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
Labels: bug, test

#3074 Partial support for time windows
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/time_window_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/TimeWindow.scala
Labels: feature request

#3083 Initial CHANGELOG.md update for 21.08
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#3086 Fix Support of MapType in joins on Databricks
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
Labels: bug

#3096 add spark311db GpuSortMergeJoinExec conditional joins filter
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuSortMergeJoinExec.scala
Labels: bug

#3100 Update databricks 3.0.1 shim to new ParquetFilter api
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
Labels: P1, bug
