Repository NVIDIA/spark-rapids, pull requests merged in 2021-12, with the labels that each got.

#4222 Add arguments support to 'databricks/run-tests.py' [databricks]
  jenkins/databricks/params.py
  jenkins/databricks/run-tests.py
Labels: build

#4247 Disable failing CastOpSuite test
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: build

#4251 Skip test_regexp_replace_null_pattern_fallback on Databricks [databricks]
  integration_tests/src/main/python/string_test.py
Labels: build

#4007 Implement duplicate key handling for GpuCreateMap
  docs/configs.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMapUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: task

#4221 GpuCast from ArrayType to StringType [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request

#4241 fix bug in parsing regex character classes that start with `^` and contain an unescaped `]`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
Labels: bug

#4250 Update the release script [skip ci]
  jenkins/deploy.sh
Labels: build

#4259 fix regression in cast from string to float that caused signed NaN to be considered valid
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#4268 Fix merge conflict with branch-21.12 [databricks]
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/301+-nondb/scala/com/nvidia/spark/rapids/shims/v2/AQEUtils.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/AQEUtils.scala
  sql-plugin/src/main/301db/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/301until310-nondb/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/311+-nondb/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/v2/AQEUtils.scala
  sql-plugin/src/main/312db/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: build

#4270 Document exponent differences when casting floating point to string [skip ci]
  docs/compatibility.md
Labels: documentation

#4278 Use mamba for cudf conda install [skip ci]
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: bug, build

#4263 Add missing ORC write tests on Map of Decimal
  integration_tests/src/main/python/orc_write_test.py
Labels: test

#4271 Skip test_regexp_replace_null_pattern_fallback on Spark 3.1.1 and later
  integration_tests/src/main/python/string_test.py
Labels: test

#4274 Add tests for timestamps that overflowed before.
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: test

#4235 Commonize v2 shim [databricks]
  pom.xml
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/Spark302Shims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/Spark303Shims.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/Spark304Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/Spark312Shims.scala
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/shims/spark312db/Spark312dbShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShimsBase.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301util320Shims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/AQEUtils.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShimsBase.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/rapids/shims/v2/GpuShuffleExchangeExec.scala
Labels: build

#4159 Optimize sample perf
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GatherUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuPoissonSampler.scala
Labels: cudf_dependency

#4242 Fix indentation issue in getting-started-k8s guide [skip ci]
  docs/get-started/getting-started-kubernetes.md
Labels: documentation

#4287 Update 21.12 compatibility guide for known regexp issue [skip ci]
  docs/compatibility.md
Labels: documentation

#4030 Support code coverage report with single version jar [skip ci]
  build/coverage-report
  docs/dev/README.md
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build

#4265 Remove aggregator dependency before deploying dist artifact
  dist/maven-antrun/build-parallel-worlds.xml
  dist/pom.xml
  jenkins/deploy.sh
  jenkins/version-def.sh
Labels: build

#4261 Update cudfjni version to released 21.12.0 [databricks]
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, build

#4306 Revert commonizing the int96ParquetRebase* functions
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301util320Shims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
Labels: bug, P1

#4255 Make regexp pattern `[^a]` consistent with Spark for multiline strings
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#4272 Full support for SUM overflow detection on decimal [databricks]
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/301until310-all/scala/org/apache/spark/sql/rapids/aggregate/GpuSum.scala
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/aggregate/GpuSum.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: feature request

#4307 Update Download page for 21.12 [skip ci]
  docs/download.md
Labels: documentation

#4308 Bump up GPU reserve memory to 640MB
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, ease of use, improve

#4258 Sanitize column names in ParquetCachedBatchSerializer before writing to Parquet [databricks]
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
Labels: bug

#4245 Update changelog 21.12 to latest [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: build

#4317 [BUG] Update nightly test script to dynamically set mem_fraction [skip ci]
  jenkins/spark-tests.sh
Labels: test

#3144 Optimize AQE with Spark 3.2+ to avoid redundant transitions [databricks]
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/AvoidAdaptiveTransitionToRow.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: task

#4282 Use data type to create an inspector for a foldable GPU expression.
  integration_tests/src/main/python/row-based_udf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/rowBasedHiveUDFs.scala
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/EmptyHiveSimpleUDF.java
Labels: bug

#4326 Fix 4315 decrease concurrentGpuTasks to avoid sum test OOM
  integration_tests/pytest.ini
  jenkins/spark-tests.sh
Labels: test

#4310 Fix typo in shim class name
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301until320Shims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
Labels: task

#4331 Fix parquet options builder calls
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
Labels: bug, build

#4256 Allow returning an EmptyHashedRelation when a broadcast result is empty [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHelper.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: performance

#4338 Use scala Int.box instead of Integer constructors
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: bug, test

#4328 Change the explanation of why the operator will not work on GPU
  docs/get-started/getting-started-workload-qualification.md
  integration_tests/src/main/python/explain_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: task

#4336 Split expensive pytest files in cases level [skip ci]
  jenkins/spark-tests.sh
Labels: test, improve

#4335 Fix the issue of exporting Column RDD [databricks]
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRDDConverterSuite.scala
Labels: bug

#4269 The option for the nightly script not deploying jars [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#4349 Fix PYTHONPATH in pre-merge
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: test

#4285 Add support for regexp_extract on the GPU
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
Labels: feature request

#4343 Fix issue with binding to hash agg columns with computation [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: bug

#4354 Fix regression in AQE optimizations
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: bug

#4327 Print meaningful message when calling scripts in maven
  dist/maven-antrun/build-parallel-worlds.xml
  dist/scripts/binary-dedupe.sh
  pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark312/pom.xml
  shims/spark312db/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shims/spark321/pom.xml
  shims/spark330/pom.xml
Labels: task

#4303 Update gh-page docs v21.12[skip ci]
  docs/FAQ.md
  docs/additional-functionality/cache-serializer.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/dev/README.md
  docs/dev/compute_sanitizer.md
  docs/dev/microk8s.md
  docs/dev/nvtx_profiling.md
  docs/download.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-azure-synapse-analytics.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/img/Databricks/initscript_ucx.png
  docs/img/Databricks/sparkconfig_ucx.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#4359 Audit - SPARK-37268 - Remove unused variable in GpuFileScanRDD [Databricks]
  sql-plugin/src/main/301db/scala/org/apache/spark/sql/rapids/shims/v2/GpuFileScanRDD.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/v2/GpuFileScanRDD.scala
Labels: audit_3.3.0

#4367 update 21.12 branch for doc [skip ci]
  docs/additional-functionality/ml-integration.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#4366 Fix some 21.12 branch related doc issues on gh-pages branch.[skip ci]
  docs/additional-functionality/ml-integration.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#4369 Update documentation for recent fixes in 21.12 [skip ci]
  docs/additional-functionality/ml-integration.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#4355 Dedicated deploy-file with reduced pom in nightly build [skip ci]
  .gitignore
  jenkins/spark-nightly-build.sh
  jenkins/version-def.sh
Labels: bug, build

#4371 Fix typo in skipTestsFor330 calculation [skip ci]
  jenkins/spark-nightly-build.sh
  jenkins/version-def.sh
Labels: bug

#4372 Move casting to string tests from array_test.py and struct_test.py to cast_test.py
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/struct_test.py
Labels: test

#4150 Support GpuSubqueryBroadcast for DPP [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
Labels: performance

#4373 Add pytest tags for nightly test parallel run [skip ci]
  integration_tests/pytest.ini
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  jenkins/spark-tests.sh
Labels: test

#4364 Replace Scala document with Scala comment for inner functions
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: build

#4382 Remove unused scallop dependency from integration_tests
  integration_tests/pom.xml
Labels: build

#4365 Not publishing integration_tests jar to Maven Central [skip ci]
  jenkins/deploy.sh
Labels: build

#4374 Fix the IT module depends on the tests module
  integration_tests/pom.xml
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/ArmSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TimeOperatorsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/CacheTestSuite.scala
Labels: build

#4379 update hot fix cudf link v21.12.2
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#4394 Use correct column name in GpuIf test [databricks]
  integration_tests/src/main/python/conditionals_test.py
Labels: bug

#4391 update gcp custom dataproc image version to avoid log4j issue[skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#4361 Accommodate altered semantics of `cudf::lists::contains()`
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: bug

#4396 GpuShuffleCoalesceIterator acquire semaphore after host concat
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
Labels: performance

#4407 Fix GpuSubqueryBroadcast on multi-fields relation [databricks]
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
Labels: bug

#4399 Update docs for Profiling and Qualification tool to change wording
  docs/download.md
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimeline.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
Labels: documentation

#4388 Add support for ReplicateRows
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#4397 Ignore cufile.log
  .gitignore
  pom.xml
Labels: task

#4427 Update getFileScanRDD shim for recent changes in Spark 3.3.0 [databricks]
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  shims/spark321/src/main/scala/com/nvidia/spark/rapids/shims/spark321/Spark321Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301until320Shims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: build

#4419 Import the right pandas from conda
  jenkins/spark-tests.sh
Labels: build

#4429 Update hotfix ghpages[skip ci]
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#4433 Import the right pandas from conda [skip ci]
  jenkins/spark-tests.sh
Labels: build

#4431 Add DateType support for AST expressions
  docs/supported_ops.md
  integration_tests/src/main/python/ast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: feature request
