Repository NVIDIA/spark-rapids, pull requests merged in 2021-03, with the labels that each got.

#1828 Update cudf dependency to 0.18
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
Labels: build

#1808 Update mortgage tests to support reading multiple dataset formats
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSpark.scala
Labels: test

#1826 Remove benchmarks
  README.md
  docs/benchmarks.md
  docs/get-started/Dockerfile.cuda
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/src/main/python/benchmark.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/tpcds_test.py
  integration_tests/src/main/python/tpch_test.py
  integration_tests/src/main/python/tpcxbb_test.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/CompareResults.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeSpark.scala
  integration_tests/src/test/resources/tpch/customer.tbl/part-00000-5e3bf4cd-c6e9-488b-81f2-00813dd4bfbe-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/lineitem.tbl/part-00000-6de1e1da-3f9b-47ae-a8c6-b4665bea5c5d-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/nation.tbl/part-00000-d9f4400b-9af3-438a-bb6e-a0fd2ab56fd4-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/orders.tbl/part-00000-eac6ea97-a06e-4550-994b-1a1553b26438-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/part.tbl/part-00000-3364eea2-f1b6-49a4-b942-b9c4d0774ded-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/partsupp.tbl/part-00000-458bd63a-12e2-462b-a69a-2a356b8d9f37-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/region.tbl/part-00000-03defe09-3d7c-4a7c-b9df-259eba52db22-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/supplier.tbl/part-00000-317059ee-49a7-4a39-88ab-b1fbd89f0b09-c000.snappy.parquet
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeAdaptiveSparkSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSparkSuite.scala
  tests/README.md
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: benchmark

#1835 Fix merge conflict with branch-0.4
  README.md
  docs/benchmarks.md
  docs/get-started/Dockerfile.cuda
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/src/main/python/benchmark.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/tpcds_test.py
  integration_tests/src/main/python/tpch_test.py
  integration_tests/src/main/python/tpcxbb_test.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/CompareResults.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcds/TpcdsLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSpark.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeBench.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/tpcxbb/TpcxbbLikeSpark.scala
  integration_tests/src/test/resources/tpch/customer.tbl/part-00000-5e3bf4cd-c6e9-488b-81f2-00813dd4bfbe-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/lineitem.tbl/part-00000-6de1e1da-3f9b-47ae-a8c6-b4665bea5c5d-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/nation.tbl/part-00000-d9f4400b-9af3-438a-bb6e-a0fd2ab56fd4-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/orders.tbl/part-00000-eac6ea97-a06e-4550-994b-1a1553b26438-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/part.tbl/part-00000-3364eea2-f1b6-49a4-b942-b9c4d0774ded-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/partsupp.tbl/part-00000-458bd63a-12e2-462b-a69a-2a356b8d9f37-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/region.tbl/part-00000-03defe09-3d7c-4a7c-b9df-259eba52db22-c000.snappy.parquet
  integration_tests/src/test/resources/tpch/supplier.tbl/part-00000-317059ee-49a7-4a39-88ab-b1fbd89f0b09-c000.snappy.parquet
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeAdaptiveSparkSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/tpch/TpchLikeSparkSuite.scala
  tests/README.md
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: build

#1831 Spark 3.0.2 shim no longer a snapshot shim
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/SparkShimServiceProvider.scala
Labels: build

#1838 Make databricks build.sh more convenient for dev
  jenkins/databricks/build.sh
Labels: build

#1704 Create a shim for Spark 3.2.0 development
  api_validation/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  integration_tests/pom.xml
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301db/pom.xml
  shims/spark320/pom.xml
  shims/spark320/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/SparkShimServiceProvider.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/spark320/RapidsShuffleManager.scala
  shims/spark320/src/test/scala/com/nvidia/spark/rapids/shims/spark320/Spark320ShimsSuite.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: build

#1829 Cleanup unused Jenkins files and scripts
  jenkins/Dockerfile.integration.ubuntu16
  jenkins/Dockerfile.ubuntu16
Labels: build

#1832 Spark 3.1.1 shim no longer a snapshot shim
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkShimServiceProvider.scala
Labels: Spark 3.1+, build

#1842 Update to note support for 3.0.2
  docs/FAQ.md
  docs/download.md
Labels: documentation

#1796 Have most of range partitioning run on the GPU
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SamplingUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: bug, performance

#1744 Fix NullPointerException on null partition insert
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/InsertPartition311Suite.scala
Labels: Spark 3.1+, audit_3.1.0

#1848 Fix merge conflict with branch-0.4
  docs/FAQ.md
  docs/download.md
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkShimServiceProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/InsertPartition311Suite.scala
Labels: build

#1849 Update changelog for 0.4
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#1839 Refactor join code to reduce duplicated code
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleHashJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: SQL

#1834 Add shim for Spark 3.0.3
  docs/additional-functionality/rapids-shuffle.md
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark303/pom.xml
  shims/spark303/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/Spark303Shims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/SparkShimServiceProvider.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/spark303/RapidsShuffleManager.scala
  tests/README.md
Labels: build

#1616 Cost-based optimizer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: feature request, performance

#1852 Fix Part Suite Tests
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
Labels: bug, test

#1836 Add shim for Spark 3.1.2
  docs/additional-functionality/rapids-shuffle.md
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark312/pom.xml
  shims/spark312/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/Spark312Shims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkShimServiceProvider.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/spark312/RapidsShuffleManager.scala
  tests/README.md
Labels: build

#1858 fix shuffle manager doc on ucx library path
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#1871 Disable coalesce batch spilling to avoid cudf contiguous_split bug
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: bug

#1869 Fix tests for Spark 3.2.0 shim
  integration_tests/src/main/python/orc_test.py
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: P1, Spark 3.2+, audit_3.2.0, bug

#1874 Update 0.4.0 with contiguous split workaround
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: build

#1841 Add in support for DateAddInterval
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#1855 Expose row count statistics in GpuShuffleExchangeExec
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuShuffleExchangeExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffleExchangeExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: task

#1868 Increase row limit when doing count() for HostColumnarToGpu
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/datasourcev2_read_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: performance

#1830 Enable the tests for collect over window.
  integration_tests/src/main/python/window_function_test.py
Labels: test

#1877 remove docker build in pre-merge [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#1891 Connect UCX endpoints early during app startup
  docs/configs.md
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXConnection.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleHeartbeatManagerTest.scala
Labels: performance, shuffle

#1909 Avoid pinned memory for shuffle host buffers
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
Labels: performance

#1894 Modified Download Page to re-order the items and change the format of download links
  docs/download.md
Labels: documentation

#1908 Remove the Scala version of Mortgage ETL tests from nightly test
  jenkins/spark-tests.sh
Labels: test

#1906 Remove get call on timeZoneId
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: task

#1926 Consolidate RAT settings in parent pom
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  sql-plugin/pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
Labels: build

#1934 Update documentation to use cudf version 0.18.1
  api_validation/README.md
  docs/additional-functionality/cache-serializer.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#1935 Update Alias SQL quoting and float-to-timestamp casting to match Spark 3.2
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/namedExpressions.scala
Labels: SQL

#1927 Change cuDF dependency to 0.18.1
  jenkins/version-def.sh
  pom.xml
Labels: build

#1910 Make hash partitioning match CPU
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
Labels: bug

#1945 Update changelog 0.4 [skip ci]
  CHANGELOG.md
Labels: documentation

#1946 update 0.4.0 with cudf 0.18.1
  CHANGELOG.md
  api_validation/README.md
  docs/additional-functionality/cache-serializer.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  docs/supported_ops.md
  integration_tests/README.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
Labels: build

#1843 Refactor GpuGenerateExec and Explode
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/generate_expr_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
Labels: SQL

#1878 spillable cache for GpuCartesianRDD
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
Labels: SQL

#1937 Fix merge conflict with branch-0.4
  CHANGELOG.md
  api_validation/README.md
  docs/additional-functionality/cache-serializer.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
Labels: build

#1938 Add spark.executor.resource.gpu.amount=1 to YARN and K8s docs
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#1947 Move doc of Pandas UDF to additional-functionality
  docs/additional-functionality/rapids-udfs.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#1889 Decimal DIV changes
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: task

#1957 Update Spark 3.1.2 shim for float upcast behavior
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/Spark312Shims.scala
Labels: build

#1961 change premege GPU_TYPE from secret to global env [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#1960 Replace sonatype staging link with maven central link
  docs/demo/Databricks/generate-init-script.ipynb
Labels: documentation

#1963 Update changelog 0.4 [skip ci]
  CHANGELOG.md
Labels: documentation

#1965 Merge source from branch-0.4 [skip ci]
  CHANGELOG.md
  docs/demo/Databricks/generate-init-script.ipynb
Labels: documentation

#1787 support distributed file path in cloud environment
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
Labels: build

#1930 Relax cudf version check for patch-level versions
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsExecutorPluginSuite.scala
Labels: SQL

#1956 Fix NPE in plugin shutdown
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug

#1955 Fix typo in Arrow optimization config
  integration_tests/src/main/python/datasourcev2_read_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug

#1966 add xml report for codecov
  .github/codecov.yaml
  build/coverage-report
Labels: build

#1967 Update FAQ for Dataset API and format supported versions
  docs/FAQ.md
Labels: documentation

#1951 Branch 0.5 doc remove numpartitions
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/yarn-gpu.md
Labels: documentation

#1971 Update gh-pages for branch-0.4
  docs/FAQ.md
  docs/additional-functionality/README.md
  docs/additional-functionality/cache-serializer.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/udf-to-catalyst-expressions.md
  docs/benchmarks.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/demo/gpu-mortgage_accelerated.ipynb
  docs/dev/README.md
  docs/dev/testing.md
  docs/download.md
  docs/examples.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/img/Databricks/sparkconfig.png
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#1975 Gh pages 0.4 update readme
  CONTRIBUTING.md
  NOTICE
  NOTICE-binary
  README.md
Labels: documentation

#1970 add maven profiles for supported CUDA versions
  pom.xml
Labels: build, task

#1976 Temp fix for parquet write changes
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: bug, cudf_dependency

#1978 Add audit script to list commits from Spark
  scripts/audit-spark-3.2.sh
Labels: task

#1982 Update ORC pushdown filter building to latest Spark logic
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/OrcFilters.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/OrcFiltersBase.scala
Labels: SQL

#1988 broadcast exchange can fail when job group set
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: P1

#1990 Prepare for v0.4.1 release
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark311/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#1994 Merge 0.4 to 0.5 [skip ci]
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  jenkins/databricks/create.py
Labels: build, documentation

#1995 update changelog 0.4.1 [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#1998 Prepare for the rapids v0.4.1 release
  CHANGELOG.md
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  integration_tests/src/main/python/join_test.py
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  scripts/generate-changelog
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark311/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#1983 document building against different CUDA Toolkit versions
  CONTRIBUTING.md
Labels: documentation

#2002 Pass dirs to getBlockData for a wrapped shuffle resolver
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: Spark 3.1+, bug, shuffle

#1919 Add support for Structs for UnionExec
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#1958 Support legacy behavior of parameterless count
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: task

#1991 Fixes creation of invalid DecimalType in GpuDivide.tagExprForGpu
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#2005 Update to new is_before_spark_311 function name
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: build

#2009 Update gh-pages to 0.4.1
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#2007 Fix unknown column name error when filtering ORC file with no names
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#2015 Fix bug where rkey buffer is getting advanced after the first handshake
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
Labels: bug, shuffle

#2000 Use Spark's HybridRowQueue to avoid MemoryConsumer API shim
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/python/rapids/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/RowUtils.scala
Labels: task

#2006 Enable windowed `collect_list` by default
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: SQL

#1999 support casting string to decimal
  docs/configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: feature request

#1981 Fix GpuSize
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/collectionOperations.scala
Labels: task

#2017 Add in murmur3 support for float, double, date and timestamp
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
Labels: bug

#2022 Update order by to not load native libraries when sorting
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: bug

#2016 Refactor logic for parallel testing
  integration_tests/run_pyspark_from_build.sh
Labels: test

#1883 Enable sort for single-level nesting struct columns on GPU
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: SQL

#2033 Bump up pre-merge OS from ubuntu 16 to ubuntu 18 [skip ci]
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
Labels: build

#2037 Fix warnings from use of deprecated cudf methods
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: build

#1814 Struct to string casting functionality
  docs/supported_ops.md
  integration_tests/src/main/python/struct_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/FloatUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: cudf_dependency, feature request
