Repository NVIDIA/spark-rapids, pull requests merged in 2021-02, with the labels that each got.

#1636 RAPIDS accelerated Spark Scala UDF support
  docs/FAQ.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/README.md
  integration_tests/pom.xml
  integration_tests/src/main/python/rapids_udf_test.py
  jenkins/databricks/build.sh
  jenkins/spark-tests.sh
  sql-plugin/src/main/java/com/nvidia/spark/RapidsUDF.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/hiveUDFs.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/ScalaUDFSuite.scala
  udf-examples/README.md
  udf-examples/pom.xml
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWordCount.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/URLDecode.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/URLEncode.java
  udf-examples/src/main/scala/com/nvidia/spark/rapids/udf/scala/URLDecode.scala
  udf-examples/src/main/scala/com/nvidia/spark/rapids/udf/scala/URLEncode.scala
Labels: SQL, feature request

#1617 Enable nightly test checks for Apache Spark
  integration_tests/src/main/python/conftest.py
  jenkins/spark-nightly-build.sh
Labels: feature request

#1565 Add GPU accelerated array_contains operator
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: feature request

#1641 Xfail struct and array order by tests on Dataproc
  integration_tests/README.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/struct_test.py
Labels: bug

#1646 Update links in rapids-udfs.md after moving to subfolder
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#1637 Fail DivModLike on zero divisor in ANSI mode
  integration_tests/src/main/python/arithmetic_ops_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: task

#1649 Move building from source docs to contributing guide
  CONTRIBUTING.md
  README.md
Labels: documentation

#1645 Run Databricks IT with python-xdist parallel, includes test fixes and xfail
  integration_tests/pytest.ini
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/tpch_test.py
  integration_tests/src/main/python/udf_test.py
  jenkins/databricks/build.sh
Labels: test

#1652 Fix typo in arrow optimized config name - spark.rapids.arrowCopyOptimizationEnabled
  integration_tests/src/main/python/datasourcev2_read.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug

#1655 Fix extraneous shuffles added by AQE
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: SQL

#1663 BenchmarkRunner - Include query name in JSON summary filename
  integration_tests/src/main/python/benchmark.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
Labels: bug

#1656 Move UDF to Catalyst Expressions to its own document
  docs/additional-functionality/udf-to-catalyst-expressions.md
  docs/compatibility.md
Labels: documentation

#1639 support GpuScalarSubquery
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/subsuqery_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalarSubquery.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalarSubquerySuite.scala
Labels: SQL, feature request

#1614 add alluxio getting start document
  docs/get-started/getting-started-alluxio.md
Labels: documentation

#1665 Add better automated tests for Arrow columnar copy in HostColumnarToGpu
  integration_tests/src/main/python/datasourcev2_read.py
  integration_tests/src/main/python/datasourcev2_read_test.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/datasourcev2/TestingV2Source.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: test

#1664 Filter nulls for left semi and left anti join to work around cudf
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: SQL

#1661 Enable Parquet test for file containing map struct key
  integration_tests/src/main/python/parquet_test.py
Labels: test

#1669 Add FAQ entries for executor-per-GPU questions
  docs/FAQ.md
Labels: documentation

#1668 Implement way for python integration tests to validate Exec is in GPU plan
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/datasourcev2_read_test.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/spark_session.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastHashJoinSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastNestedLoopJoinSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: test

#1592 Add in support for Decimal divide
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: feature request

#1593 Avoid unnecessary Table instances after contiguous split
  sql-plugin/src/main/format/ShuffleMetadataResponse.fbs
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorFromBuffer.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuCompressedColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuPackedTableColumn.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/WithTableBuffer.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/ColumnMeta.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/LICENSE.md
  sql-plugin/src/main/java/com/nvidia/spark/rapids/format/TableMeta.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CopyCompressionCodec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvcompLZ4CompressionCodec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: performance, shuffle

#1548 Support executing collect_list on GPU with windowing.
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#1671 Allow metrics to be configurable by level
  docs/configs.md
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuShuffledHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffledHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadCSVFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadFileFormatWithMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadOrcFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/NvtxWithMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuCustomShuffleReaderExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: bug

#1678 Fix array/struct checks in Sort and HashAggregate and sorting tests in distributed mode
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/struct_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: bug

#1681 Xfail the collect_list tests for databricks
  integration_tests/src/main/python/window_function_test.py
Labels: test

#1673 support auto-merge for branch 0.5 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1683 update changelog to verify autotmerge 0.5 setup [skip ci]
  CHANGELOG.md
Labels: documentation

#1682 init CI/CD dependencies branch-0.5
  api_validation/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark311/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#1677 When PTDS is enabled, print warning if the allocator is not ARENA
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#1692 Add the integration test resources to the test tarball
  integration_tests/src/assembly/bin.xml
Labels: test

#1691 add validate_execs_in_gpu_plan to pytest.ini
  integration_tests/pytest.ini
Labels: test

#1689 Update docs for plugin 0.5.0-SNAPSHOT and cudf 0.19-SNAPSHOT
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos7
  jenkins/printJarVersion.sh
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/README.md
  udf-examples/Dockerfile
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation

#1694 increase mem and limit parallelism for pre-merge
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build

#1695 support alternate jar paths
  integration_tests/run_pyspark_from_build.sh
Labels: build

#1676 BenchmarkRunner option to generate query plan diagrams in DOT format
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/BenchmarkRunner.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
Labels: benchmark

#1703 Remove xfail for spark 3.1.0 test_broadcast_join_mixed FullOuter
  integration_tests/src/main/python/join_test.py
Labels: test

#1701 remove xfail for orc test_input_meta for spark 3.1.0
  integration_tests/src/main/python/orc_test.py
Labels: test

#1699 Add docs about Spark 3.1 in standalone modes not needing extra class path
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#1685 Fix CustomShuffleReader replacement when decimal types enabled
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: SQL

#1706 cleanup unused is_before_spark_310
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/qa_nightly_sql.py
  integration_tests/src/main/python/tpch_test.py
Labels: test

#1596 Added in Decimal support to ParquetCachedBatchSerializer
  docs/configs.md
  integration_tests/src/main/python/cache_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: task

#1713 Call GpuDeviceManager.shutdown when the executor plugin is shutting down
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug

#1714 Add support for RAPIDS accelerated Java UDFs
  docs/additional-functionality/rapids-udfs.md
  integration_tests/src/main/python/rapids_udf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/URLDecode.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/URLEncode.java
Labels: SQL

#1723 Removed StructTypes support for ParquetCachedBatchSerializer as cudf doesn't support it yet
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
Labels: task

#1728 Skip RAPIDS accelerated Java UDF tests if UDF fails to load
  integration_tests/src/main/python/rapids_udf_test.py
Labels: test

#1734 Disable range partitioning if computation is needed
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#1718 CAST string to temporal type now calls isTimestamp
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#1725 Branch 0.4 FAQ reorg
  docs/FAQ.md
Labels: documentation

#1747 Fix resource leaks in unit tests
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: test

#1740 Disable ORC writes until bug can be fixed
  docs/configs.md
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#1716 Update RapidsShuffleManager documentation for branch 0.4
  docs/get-started/getting-started-on-prem.md
Labels: documentation, shuffle

#1741 Reduce regex use in CAST
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: performance

#1767 Consistent Spark version for test and production
  integration_tests/pom.xml
  pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
Labels: build

#1750 Detect task failures in benchmarks
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/common/BenchUtils.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/common/BenchUtilsSuite.scala
Labels: benchmark

#1760 Update GpuDataSourceScanExec and GpuBroadcastExchangeExec to fix audit issues
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: audit_3.1.0, feature request

#1775 Fix ambiguous ordering for some tests
  integration_tests/src/main/python/sort_test.py
Labels: bug, test

#1742 Fix regression supporting to_date with Spark-3.1
  docs/configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: bug

#1719 Add in out of core sort
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: feature request

#1768 Updating getting started Databricks docs
  docs/demo/gpu-mortgage_accelerated.ipynb
  docs/get-started/getting-started-databricks.md
Labels: documentation

#1788 Spill metrics everywhere
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: task

#1779 Add support of DateType and TimestampType for GetTimestamp expression
  docs/supported_ops.md
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: task

#1781 Better float/double cases for casting tests
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#1766 Branch 0.4 release docs
  docs/additional-functionality/rapids-udfs.md
  docs/benchmarks.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#1798 Add documentation about explain not on GPU when AQE is on
  docs/FAQ.md
Labels: documentation

#1751 Exclude foldable expressions from GPU if constant folding is disabled
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: SQL, documentation

#1807 Fix merge conflict between branch-0.4 and branch-0.5
  docs/FAQ.md
  docs/additional-functionality/rapids-udfs.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-gcp.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: build

#1804 Update UCX documentation for RX_QUEUE_LEN and Docker
  docs/additional-functionality/rapids-shuffle.md
  docs/get-started/getting-started-on-prem.md
  shuffle-plugin/README.md
Labels: documentation

#1809 check if modified files after update_config/supported
  dist/pom.xml
Labels: build, feature request

#1780 Remove SNAPSHOT from test and integration_test READMEs
  integration_tests/README.md
  tests/README.md
Labels: documentation

#1820 [BUG] make modified check pre-merge only
  dist/pom.xml
  jenkins/spark-premerge-build.sh
Labels: bug, build

#1822 Fix conflict 0.4 to 0.5
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  tests/README.md
Labels: build, documentation

#1819 Fix scaladoc warning in GpuCast
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: build
