Repository NVIDIA/spark-rapids, pull requests merged in 2021-09, with the labels that each got.

#3341 ArrayMax and ArrayMin support plus a few other simple ops
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuListUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#3354 Support HashAggregate on struct and nested struct
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: feature request

#3361 Fix databricks 3.1.1 arrow dependency version
  shims/spark311db/pom.xml
Labels: build

#3365 fix databricks builds
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
Labels: task

#3359 UnionExec array and nested array support
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3378 Make Dockerfile.cuda consistent with getting-started-kubernetes.md
  docs/get-started/Dockerfile.cuda
Labels: task

#3389 Bring back setRapidsShuffleManager in the driver side
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: task

#3395 Fix UDF native example build
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: bug, build

#3366 Fix input_file_xxx issue when FileScan is running on CPU
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/InputFileBlockRule.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: bug

#3398 Fix NPE on string repeat when there is no data buffer
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#3387 Fallback to the CPU for IGNORE NULLS on lead and lag
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/OffsetWindowFunctionMeta.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
Labels: audit_3.2.0

#3405 Qualification tool: Filter empty strings from Read Schema
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: bug

#3409 Use devel cuda image for premerge CI
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#3315 Add in reporting of time taken to transition plan to GPU
  docs/FAQ.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: task

#3363 Add AST support for null literals
  integration_tests/src/main/python/ast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: task, cudf_dependency

#3410 Specify number of RDD slices for ID tests
  integration_tests/src/main/python/misc_expr_test.py
Labels: test

#3399 Fix collect_list test so it covers nested types properly
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#3393 Fill with null columns for the names exist only in read schema in ORC reader
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala
Labels: bug

#3392 Support transforming BinaryType between Row and Columnar
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBatchUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuColumnarToRowSuite.scala
Labels: task

#3394 Orc read map
  docs/supported_ops.md
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request, cudf_dependency

#3403 Fix canonicalization regression with Spark 3.2
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: Spark 3.2+

#3412 Restore AST conditional join tests
  integration_tests/src/main/python/join_test.py
Labels: test

#3423 Fix hash_aggregate tests that leaked configs
  integration_tests/src/main/python/ast_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/qa_nightly_select_test.py
Labels: bug, test

#3426 Correct grammar in qualification tool doc
  docs/additional-functionality/qualification-profiling-tools.md
Labels: documentation

#3408 Add leafNodeDefaultParallelism support
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/spark30+all/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/Spark32XShimsUtils.scala
  tests/src/test/scala/org/apache/spark/sql/GpuSparkPlanSuite.scala
Labels: Spark 3.2+

#3303 Update to cudf conditional join change that removes null equality argument
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: build, cudf_dependency

#3421 Revert to CUDA runtime image for build
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#3428 Remove commented-out semanticEquals overrides
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalarSubquery.scala
Labels: audit_3.2.0

#3368 Extend TagForReplaceMode to adapt Databricks runtime
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: task

#3411 Make new build default and combine into dist package
  CONTRIBUTING.md
  aggregator/pom.xml
  api_validation/pom.xml
  build/buildall
  dist/README.md
  dist/com.nvidia.spark.rapids.SparkShimServiceProvider.sparkNonSnapshot
  dist/com.nvidia.spark.rapids.SparkShimServiceProvider.sparkNonSnapshotDB
  dist/com.nvidia.spark.rapids.SparkShimServiceProvider.sparkSnapshot
  dist/com.nvidia.spark.rapids.SparkShimServiceProvider.sparkSnapshotDB
  dist/pom.xml
  dist/unshimmed-base.txt
  dist/unshimmed-extras.txt
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/build.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark301db/pom.xml
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/RapidsShuffleInternalManager.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/spark301db/RapidsShuffleManager.scala
  shims/spark301db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301db/GpuFlatMapGroupsInPandasExec.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/RapidsShuffleInternalManager.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/RapidsShuffleInternalManager.scala
  shims/spark311/pom.xml
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/RapidsShuffleInternalManager.scala
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuWindowInPandasExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/spark311db/RapidsShuffleManager.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark311db/BatchGroupUtils.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark311db/GpuAggregateInPandasExec.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark311db/GpuArrowEvalPythonExec.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark311db/GpuFlatMapGroupsInPandasExec.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark311db/GpuMapInPandasExec.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/GpuGroupUDFArrowPythonRunner.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/RapidsShuffleInternalManager.scala
  shims/spark312/pom.xml
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/301+-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301+-nondb/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301db/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  tests/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#3422 Stop double closing SerializeBatchDeserializeHostBuffer host buffers when running with Spark 3.2
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
Labels: bug, Spark 3.2+

#3425 Throw an error by default if CREATE TABLE AS SELECT overwrites data
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: audit_3.2.0

#3320 Add AST support for logical AND and logical OR
  docs/supported_ops.md
  integration_tests/src/main/python/ast_test.py
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: cudf_dependency

#3414 Add in support for transform_keys
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMapUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: feature request

#3441 update deploy script for Databricks
  jenkins/databricks/deploy.sh
Labels: build

#3443 Remove 301emr shim
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  shims/spark301emr/pom.xml
  shims/spark301emr/src/main/resources/META-INF/services/com.nvidia.spark.rapids.SparkShimServiceProvider
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuBroadcastExchangeExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuBroadcastHashJoinExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuBroadcastNestedLoopJoinExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuOrcScan.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuParquetScan.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuShuffleExchangeExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuShuffledHashJoinExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuSortMergeJoinMeta.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/GpuWindowInPandasExec.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/RapidsShuffleInternalManager.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/Spark301EMRShims.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/SparkBaseShims.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/shims/spark301emr/SparkShimServiceProvider.scala
  shims/spark301emr/src/main/scala/com/nvidia/spark/rapids/spark301emr/RapidsShuffleManager.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/BatchGroupUtils.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/GpuAggregateInPandasExec.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/GpuArrowEvalPythonExec.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/GpuFlatMapGroupsInPandasExec.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/GpuMapInPandasExec.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301emr/GpuWindowInPandasExecBase.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/shims/spark301emr/GpuSchemaUtils.scala
  shims/spark301emr/src/main/scala/org/apache/spark/sql/rapids/shims/spark301emr/ShuffleManagerShim.scala
Labels: build

#3451 Fix typo in spark-tests.sh
  jenkins/spark-tests.sh
Labels: build

#3444 Add in tests for unaligned parquet pages
  integration_tests/src/main/python/parquet_test.py
Labels: test

#3446 Format aggregator pom and commonize some configuration
  aggregator/pom.xml
Labels: build

#3445 Update nightly build to pull Databricks jars
  dist/pom.xml
  jenkins/spark-nightly-build.sh
Labels: build

#3453 Fix spark-tests script for classifier
  jenkins/spark-tests.sh
Labels: build

#3433 Batch scalastyle checks across all modules upfront
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  shims/spark301/pom.xml
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastExchangeExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuRunningWindowExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuShuffleExchangeExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/RapidsShuffleInternalManager.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark301db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301db/GpuArrowEvalPythonExec.scala
  shims/spark301db/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301db/GpuWindowInPandasExecBase.scala
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/GpuRunningWindowExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/GpuGroupUDFArrowPythonRunner.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/GpuShuffleExchangeExec.scala
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shims/spark320/src/test/scala/com/nvidia/spark/rapids/shims/spark320/Spark320ShimsSuite.scala
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/311db/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#3455 Decrease pre_merge_ci parallelism to 4 and reordering time-consuming tests
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/subquery_test.py
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-premerge-build.sh
Labels: test

#3436 Qualification tool: Update expected result for test
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: bug

#3452 Enable AQE/DPP test for Spark 3.2
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: test, Spark 3.2+

#3465 Fix name of 301+-nondb directory to stop at Spark 3.2.0
  pom.xml
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/org/apache/spark/rapids/shims/v2/api/python/ShimBasePythonRunner.scala
Labels: build

#3466 Databricks build fixes for missing shouldFailDivOverflow and removal of needed imports
  shims/spark301db/pom.xml
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark311db/pom.xml
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  udf-compiler/pom.xml
Labels: build

#3464 Add test for empty relation propigation
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#3457 Update the children unpacking pattern for GpuIf.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: Spark 3.2+

#3469 Update tools jar link to 21.08.1
  docs/additional-functionality/qualification-profiling-tools.md
Labels: documentation, tools

#3459 Use Shims v2 for ShuffledBatchRDD
  pom.xml
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301/src/main/scala/org/apache/spark/sql/rapids/shims/spark301/ShuffleManagerShim.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark301db/src/main/scala/org/apache/spark/sql/rapids/shims/spark301db/ShuffleManagerShim.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/SparkBaseShims.scala
  shims/spark302/src/main/scala/org/apache/spark/sql/rapids/shims/spark302/ShuffleManagerShim.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/SparkBaseShims.scala
  shims/spark303/src/main/scala/org/apache/spark/sql/rapids/shims/spark303/ShuffleManagerShim.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/SparkBaseShims.scala
  shims/spark304/src/main/scala/org/apache/spark/sql/rapids/shims/spark304/ShuffleManagerShim.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/ShuffleManagerShim.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/org/apache/spark/sql/rapids/shims/spark311cdh/ShuffleManagerShim.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/ShuffleManagerShim.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark312/src/main/scala/org/apache/spark/sql/rapids/shims/spark312/ShuffleManagerShim.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/ShuffleManagerShim.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301db/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/301until310-nondb/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/shims/v2/ShuffleManagerShim.scala
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/320/scala/org/apache/spark/rapids/shims/v2/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ShuffleManagerShimBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala
Labels: bug

#3467 Update docs to better describe support for floating point aggregation and NaNs
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: documentation

#3377 Fix AnsiCastOpSuite failures with Spark 3.2
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: audit_3.2.0

#3480 Temporarily disable failing cast string to date tests
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: test

#3471 Fix canonicalization of GpuScalarSubquery
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalarSubquery.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalarSubquerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: bug

#3473 Create non-shim specific version of ParquetCachedBatchSerializer
  dist/README.md
  dist/pom.xml
  dist/unshimmed-spark311.txt
  docs/additional-functionality/cache-serializer.md
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuInMemoryTableScanExec.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/ParquetCachedBatchSerializer.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/org/apache/spark/sql/rapids/shims/spark311cdh/GpuInMemoryTableScanExec.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/ParquetCachedBatchSerializer.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/GpuInMemoryTableScanExec.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/ParquetCachedBatchSerializer.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark312/src/main/scala/org/apache/spark/sql/rapids/shims/spark312/GpuInMemoryTableScanExec.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/ParquetCachedBatchSerializer.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/GpuInMemoryTableScanExec.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/shims/v2/GpuInMemoryTableScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: feature request

#3447 Add CUDA async memory resource as an option
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request, performance, shuffle, cudf_dependency

#3477 Update supported docs to clarify casting floating point to string
  docs/supported_ops.md
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation

#3431 Reinstate test_sortmerge_join_struct_mixed_key_with_null_filter
  integration_tests/src/main/python/join_test.py
Labels: test, cudf_dependency

#3417 Adds pre/post steps for merge and update aggregate
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: task

#3489 Fix 311 databricks shim for AnsiCastOpSuite failures
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
Labels: bug

#3491 Shim GpuKryoRegistrator
  dist/unshimmed-base.txt
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/SparkBaseShims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/SparkBaseShims.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKryoRegistrator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: bug

#3460 Add DayTimeIntervalType/YearMonthIntervalType support
  shims/spark320/src/test/scala/com/nvidia/spark/rapids/shims/spark320/Spark320ShimsSuite.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: Spark 3.2+

#3474 Build fixes and IDE instructions
  CONTRIBUTING.md
  build/buildall
  pom.xml
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark313/pom.xml
  sql-plugin/src/main/311until320-apache/scala/org/apache/spark/rapids/shims/v2/sql/execution/datasources/parquet/rapids/ShimVectorizedColumnReader.scala
Labels: documentation, build

#3479 Test with Spark 3.2.1-SNAPSHOT
  pom.xml
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/SparkShimServiceProvider.scala
  shims/spark320/src/test/scala/com/nvidia/spark/rapids/shims/spark320/Spark320ShimsSuite.scala
Labels: build

#3498 Update the scala repl loader to avoid issues with broadcast.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: bug

#3418 Qualification tool: Add filtering based on configuration parameters
  docs/additional-functionality/qualification-profiling-tools.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/FilterAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#3499 Fix Spark 3.2.0 test_div_by_zero_ansi failures
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#3497 Re-enable spark.rapids.shims-provider-override
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug

#3487 Add databricks build tests to pre-merge CI [skip ci]
  CONTRIBUTING.md
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#3500 Fix GpuSum type to match resultType
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: bug, Spark 3.2+

#3503 Have average support nulls for 3.2.0
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/SparkBaseShims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/SparkBaseShims.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#3505 Remove doc references to cudf JIT
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#3454 Catch UDF compiler exceptions and fallback to CPU
  udf-compiler/src/main/scala/com/nvidia/spark/udf/GpuScalaUDF.scala
Labels: bug

#3493 Initialze RAPIDS Shuffle Manager at driver/executor startup
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: shuffle

#3513 Allow spark320 tests to run with 320 or 321
  shims/spark320/src/test/scala/com/nvidia/spark/rapids/shims/spark320/Spark320ShimsSuite.scala
Labels: test, Spark 3.2+

#3517 Update empty CTAS testing to avoid Hive if possible
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#3501 Add limitations for Databricks doc
  docs/FAQ.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#3508 Auto abort dup pre-merge builds [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#3524 Update hashing to normalize -0.0 on 3.2+
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/HashUtils.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/HashUtils.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnCastUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
Labels: bug, Spark 3.2+

#3439 Stop parsing special dates for Spark 3.2+
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/VersionUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalarSubquerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: Spark 3.2+

#3527 Ignore CBO tests that fail against Spark 3.2.0
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: test

#3528 Update NOTICE copyrights to 2021
  NOTICE
  NOTICE-binary
Labels: documentation

#3529 Support UnsafeArrayData in scalars
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: bug

#3507 TimeAdd supports DayTimeIntervalType
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301until320-all/scala/org/apache/spark/sql/rapids.shims.v2/datetimeExpressions.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/320/scala/org/apache/spark/sql/rapids/shims/v2/Spark32XShimsUtils.scala
  sql-plugin/src/main/320/scala/org/apache/spark/sql/rapids/shims/v2/datetimeExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: Spark 3.2+

#3521 Qualification tool: Report nested complex types in Potential Problems and improve write csv identification.
  docs/additional-functionality/qualification-profiling-tools.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualAppInfo.scala
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/decimal_part_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_type_expectation.csv
Labels: tools

#3536 Enable auto-merge from branch 21.10 to 21.12 [skip ci]
  .github/workflows/auto-merge.yml
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#3533 Define a SPARK_SHIM_VER to pick up specific rapids-4-spark-integration-tests jars
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/test.sh
Labels: build

#3537 GpuAdd supports ANSI mode.
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LogOperatorUnitTestSuite.scala
Labels: Spark 3.2+

#3551 Fix window sum overflow for 3.2.0+
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/gpuWindows.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/gpuWindows.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: bug

#3545 Dynamic class file deduplication across shims in dist jar build
  build/buildall
  dist/pom.xml
  dist/scripts/binary-dedupe.sh
Labels: Spark 3.2+

#3556 Fix databricks test.sh script for passing spark shim version
  jenkins/databricks/test.sh
Labels: build

#3504 Fix reserialization of broadcasted tables
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SerializationSuite.scala
Labels: bug

#3557 Add IDEA profile switch workarounds
  CONTRIBUTING.md
Labels: documentation

#3561 Follow on to ANSI Add
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: task

#3531 Fall back to the CPU for date/time parsing we cannot support yet
  docs/configs.md
  integration_tests/src/main/python/cast_test.py
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/YearParseUtil.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/YearParseUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: bug

#3565 Auto-dedupe ASM-relocated shim dependencies
  aggregator/pom.xml
  dist/scripts/binary-dedupe.sh
  dist/unshimmed-base.txt
Labels: build

#3568 Enable 3.2.0 unit test in premerge and nightly
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
Labels: test, build

#3578 Deploy all of the classifier versions of the jars [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#3574 Add in ANSI date time fallback
  integration_tests/src/main/python/date_time_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: bug

#3570 ANSI Support for Abs, UnaryMinus, and Subtract
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/data_gen.py
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/SparkBaseShims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/SparkBaseShims.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/SparkBaseShims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/SparkBaseShims.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/SparkBaseShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/SparkBaseShims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/SparkBaseShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/SparkBaseShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/SparkBaseShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: bug

#3587 Revert shared class list modifications in PR#3545
  dist/README.md
  dist/pom.xml
  dist/unshimmed-common-from-spark301.txt
  dist/unshimmed-from-each-spark3xx.txt
Labels: build

#3544 Add test for nested grouping sets, rollup, cube
  integration_tests/src/main/python/grouping_sets_test.py
Labels: Spark 3.2+

#3594 Fix nightly integration test script for specfic artifacts
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: bug, test

#3588 Disable test_non_empty_ctas test
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#3590 Unshim ExclusiveModeGpuDiscoveryPlugin
  dist/unshimmed-common-from-spark301.txt
  sql-plugin/src/main/scala/com/nvidia/spark/ExclusiveModeGpuDiscoveryPlugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/InternalExclusiveModeGpuDiscoveryPlugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: bug

#3566 Enable String Array Max and Min
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: task

#3607 com.nvidia.spark.rapids.ColumnarRdd not exposed to user for XGBoost
  dist/unshimmed-common-from-spark301.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarRdd.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: build

#3438 Parquet read unsigned int: uint8, uin16, uint32
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnCastUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  tests/src/test/resources/unsigned-int.parquet
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
Labels: Spark 3.2+

#3602 Dedupe proxy rapids shuffle manager byte code
  dist/README.md
  shims/README.md
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/RapidsShuffleInternalManager.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/RapidsShuffleInternalManager.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/RapidsShuffleInternalManager.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/RapidsShuffleInternalManager.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/RapidsShuffleInternalManager.scala
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/RapidsShuffleInternalManager.scala
  shims/spark311cdh/src/main/scala/org/apache/spark/sql/rapids/shims/spark311cdh/RapidsShuffleInternalManager.scala
  shims/spark311db/src/main/scala/org/apache/spark/sql/rapids/shims/spark311db/RapidsShuffleInternalManager.scala
  shims/spark312/src/main/scala/org/apache/spark/sql/rapids/shims/spark312/RapidsShuffleInternalManager.scala
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
  shims/spark320/src/main/scala/org/apache/spark/sql/rapids/shims/spark320/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug

#3615 Ignore order for the test_no_fallback_when_ansi_enabled
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#3626 Add in support for casting decimal to other number types
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/cast_test.py
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
Labels: bug

#3618 Update changelog script to strip ambiguous annotation [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#3619 Added support for Array of Structs [databricks]
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/data_gen.py
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
Labels: feature request

#3628 Fix 313 ShuffleManager build
  build/buildall
  shims/spark313/src/main/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
Labels: build

#3632 Revert disabling of ctas test
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#3636 Change nightly build to not deploy dist for each classifier version [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#3630 Fix CDH Build
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/SparkBaseShims.scala
Labels: bug

#3612 Add support for nested types as non-key columns on joins
  docs/supported_ops.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#3617 Update Version to 21.12.0-SNAPSHOT [databricks]
  aggregator/pom.xml
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
  jenkins/version-def.sh
  pom.xml
  shims/README.md
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark311db/pom.xml
  shims/spark312/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation, build

#3631 Change premerge to build all Spark versions
  jenkins/spark-premerge-build.sh
Labels: build

#3649 Add ignore_order to other fallback tests for the aggregate
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug

#3650 Fix dist copy dependencies
  dist/pom.xml
Labels: build

#3645 Verify unshimmed classes are bitwise-identical
  dist/scripts/binary-dedupe.sh
Labels: build

#3643 Properly override Shims for int96Rebase [databricks]
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark311db/src/main/scala/com/nvidia/spark/rapids/shims/spark311db/Spark311dbShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/Spark312Shims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: bug, Spark 3.2+

#3663 Add back the tests-spark310+
  pom.xml
  tests-spark310+/pom.xml
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: test, build

#3671 Fix tests-spark310+ dependency
  tests-spark310+/pom.xml
Labels: bug, build

#3666 Recompute Parquet block metadata when estimating footer from multiple file input
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
Labels: bug

#3301 Approx Percentile
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuApproximatePercentile.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
Labels: feature request, cudf_dependency

#3683 Change deploy scripts for new build system
  jenkins/databricks/deploy.sh
  jenkins/deploy.sh
  pom.xml
Labels: build

#3674 Move file TestingV2Source.Scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/datasourcev2/parquet/TestingV2Source.scala
Labels: build

#3646 Debug utility method to dump a table or columnar batch to Parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DumpUtils.scala
Labels: task

#3687 Improve dedupe script
  dist/pom.xml
  dist/scripts/binary-dedupe.sh
Labels: bug, build

#3695 Remove duplicated data types for collect_list tests
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#3373 Support `stddev` and `variance` aggregations families [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request, SQL, P1

#3691 Fix issues with AQE and DPP enabled on Spark 3.2 [databricks]
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  sql-plugin/src/main/301+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/301+-nondb/scala/com/nvidia/spark/rapids/shims/v2/ShimBroadcastExchangeLike.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/ShimBroadcastExchangeLike.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/ShimBroadcastExchangeLike.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311db/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/SparkBaseShims.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala
Labels: bug, Spark 3.2+
