Repository NVIDIA/spark-rapids, pull requests merged in 2021-04, with the labels that each got.

#2049 Remove incompatable int overflow checking
  docs/compatibility.md
  docs/configs.md
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: performance

#1954 Fix CBO bug where incompatible plans were produced with AQE on
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: bug

#2044 Use partition for GPU hash partitioning
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioning.scala
Labels: feature request

#1893 Plug-in support for get_json_object
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2061 Run the pands udf using cudf on Databricks
  jenkins/databricks/clusterutils.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
Labels: build

#1812 allow spilled buffers to be unspilled
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: feature request, performance, shuffle

#2046 support casting Decimal to String
  docs/configs.md
  docs/supported_ops.md
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuExpressionTestSuite.scala
Labels: feature request

#2075 Remove debug println from CBO test
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: test

#2059 Add the flag 'TEST_TYPE' to avoid integration tests silently skipping some test cases
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: build

#2025 Update the doc for pandas udf on databricks
  docs/get-started/getting-started-databricks.md
Labels: documentation

#2064 Optimize unnecessary columnar->row->columnar transitions with AQE
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: performance

#2080 Improve error message after failed RMM shutdown
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug

#1932 Create a getting started on K8s page
  docs/get-started/getting-started-kubernetes.md
Labels: documentation

#2088 Upgrade ScalaTest plugin to respect JAVA_HOME
  pom.xml
Labels: build, test

#2084 Enable ORC write by default
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#2050 stream shuffle buffers from GDS to UCX
  sql-plugin/src/main/scala/ai/rapids/cudf/CudaUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleServerSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: performance

#2035 Accelerate data transfer for map Pandas UDF plan
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
Labels: feature request, performance

#2094 Changed name of parquet files for Mortgage ETL Integration test
  integration_tests/src/test/resources/parquet_acq/part-00000-acquisition.snappy.parquet
  integration_tests/src/test/resources/parquet_perf/part-00000-performance.snappy.parquet
Labels: build

#2100 [BUG] add wget for fetching conda [skip ci]
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: bug, build

#2095 fix refcount when materializing device buffer from GDS
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
Labels: bug, performance, shuffle

#2105 Cleanup prior Spark sessions in tests consistently
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
Labels: test

#2099 Remove verbose log prints to make the build/test log clean
  jenkins/databricks/build.sh
  jenkins/databricks/deploy.sh
  jenkins/deploy.sh
Labels: build

#2097 fix the bound row project empty issue in row frame
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
Labels: bug

#2106 Fix some buffer leaks
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: bug

#2114 Modified the Download page for 0.4.1 and updated doc to point to K8s guide
  docs/download.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#1717 Decimal32 support
  integration_tests/src/main/python/parquet_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuInMemoryTableScanExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/java/org/apache/spark/sql/catalyst/CudfUnsafeRow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DecimalUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DecimalBinaryOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: feature request

#2119 Add more comprehensive documentation on supported date formats
  docs/compatibility.md
Labels: documentation

#2120 Materialize Stream before serialization
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBoundAttribute.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: bug

#2124 init branch-0.6 [skip ci]
  CONTRIBUTING.md
  api_validation/pom.xml
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark312/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/Dockerfile
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build, documentation

#2125 enable auto-merge from 0.5 to 0.6 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#2135 Disable Spark 3.2 shim by default
  shims/aggregator/pom.xml
  shims/pom.xml
Labels: build

#2132 Log plugin and cudf versions on startup
  docs/FAQ.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: feature request

#2139 support truncate cuda version for image build [skip ci]
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#2116 Add dynamic Spark configuration for Databricks
  jenkins/databricks/params.py
  jenkins/databricks/run-tests.py
  jenkins/databricks/test.sh
Labels: build

#2128 Add in Partition type check support
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request

#2021 Add in support for murmur3 hashing of structs
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2144 Allow array and struct types to pass thru when doing join
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/join_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/Spark301dbShims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: P1, feature request

#2142 Restore CUDA classifier handling to Jenkins scripts
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
Labels: build

#2153 Change version to 0.4.2-SNAPSHOT [skip ci]
  api_validation/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark311/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#2155 Update docs for rapids v0.4.2 release [skip ci]
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  scripts/generate-changelog
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#2156 Update changelog for v0.4.2 release [skip ci]
  CHANGELOG.md
Labels: build, documentation

#2157 fix merge conflict for 0.4.2 [skip ci]
  CHANGELOG.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  scripts/generate-changelog
Labels: documentation

#2159 Merge branch-0.4 to main [skip ci]
  CHANGELOG.md
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  scripts/generate-changelog
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark311/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build, documentation

#2072 Disable CSV parsing by default and update tests to better show what is left
  docs/compatibility.md
  docs/configs.md
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/test/resources/date.csv
  integration_tests/src/test/resources/empty.csv
  integration_tests/src/test/resources/empty_int_values.csv
  integration_tests/src/test/resources/ints_with_whitespace.csv
  integration_tests/src/test/resources/just_comments.csv
  integration_tests/src/test/resources/nan_and_inf.csv
  integration_tests/src/test/resources/no-comments.csv
  integration_tests/src/test/resources/simple_boolean_values.csv
  integration_tests/src/test/resources/simple_float_values.csv
  integration_tests/src/test/resources/simple_int_values.csv
  integration_tests/src/test/resources/trucks-blank-names.csv
  integration_tests/src/test/resources/trucks-comments.csv
  integration_tests/src/test/resources/trucks-different.csv
  integration_tests/src/test/resources/trucks-empty-values.csv
  integration_tests/src/test/resources/trucks-extra-columns.csv
  integration_tests/src/test/resources/trucks-missing-quotes.csv
  integration_tests/src/test/resources/trucks-more-comments.csv
  integration_tests/src/test/resources/trucks-null.csv
  integration_tests/src/test/resources/trucks-windows.csv
  integration_tests/src/test/resources/trucks.csv
  integration_tests/src/test/resources/trucks.tsv
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CsvScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalarSubquerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SortExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: bug

#2149 Auto generate the supported types for the file formats
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: task

#2130 Fix divide-by-zero in GpuAverage with ansi mode
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: bug

#2169 Work around bug in Spark for integration test
  integration_tests/src/main/python/repart_test.py
Labels: bug

#2151 add corresponding close call for HostMemoryOutputStream
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: task

#2083 add nightly cache tests
  docs/additional-functionality/cache-serializer.md
  jenkins/spark-tests.sh
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/ParquetCachedBatchSerializer.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/ParquetCachedBatchSerializer.scala
Labels: test

#2129 Fall back to CPU when parsing two-digit years
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: bug

#2055 Support PivotFirst
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#2168 Simplify GpuExpressions w/ withResourceIfAllowed
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
Labels: task

#2194 merge from 0.5 to 0.6 [skip ci]
  api_validation/README.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-kubernetes.md
  tests-spark310+/README.md
Labels: documentation

#2197 fix merge conflict from 0.5 [skip ci]
  docs/download.md
Labels: documentation

#2089 Update PandasUDF doc
  docs/additional-functionality/rapids-udfs.md
  docs/img/concurrentPythonWorker.PNG
Labels: documentation

#2199 fix merge conflict for udf doc from 0.5 [skip ci]
  docs/additional-functionality/rapids-udfs.md
  docs/img/concurrentPythonWorker.PNG
Labels: documentation

#2185 Init scripts to install cuda11 runtime [skip ci]
  jenkins/databricks/clusterutils.py
  jenkins/databricks/create.py
  jenkins/databricks/init_cuda11_runtime.sh
Labels: build

#2172 Remove easy unused symbols
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/datasourcev2/TestingV2Source.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastNestedLoopJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastNestedLoopJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuInMemoryTableScanExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVectorBase.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVectorCore.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AutoCloseColumnBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleReceivedBufferCatalog.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBatchUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ImplicitsTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/MetaUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/WindowedBlockIteratorSuite.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/LambdaReflection.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Plugin.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/URLEncode.java
Labels: task

#2086 Updating documentation for data format support
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#2190 JNI fixes for StringWordCount native UDF example
  udf-examples/src/main/cpp/src/StringWordCountJni.cpp
Labels: task

#2191 Use CPM to fetch libcudf dependency for native UDF example build
  udf-examples/Dockerfile
  udf-examples/README.md
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build

#2206 Fix shim301db build
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastNestedLoopJoinExec.scala
Labels: build

#2208 Revert "add nightly cache tests (#2083)"
  docs/additional-functionality/cache-serializer.md
  jenkins/spark-tests.sh
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/ParquetCachedBatchSerializer.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/ParquetCachedBatchSerializer.scala
Labels: bug, build

#2207 fix batch size default values in the tuning guide
  docs/tuning-guide.md
Labels: bug, documentation

#2178 Accelerate data transfer for `FlatMapGroupsInPandas`
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonExecBase.scala
Labels: feature request, performance

#2092 Remove restrictions in struct sort preventing calls to libcudf bounds
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: cudf_dependency

#2218 Fix incorrect RegExpReplace children handling on Spark 3.1+
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
Labels: task

#2209 Fixed a few issues with out of core sort
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
Labels: bug

#2222 Remove groupId already specified in parent pom
  dist/pom.xml
  integration_tests/pom.xml
  shims/aggregator/pom.xml
  shims/pom.xml
  shims/spark300/pom.xml
  shims/spark300emr/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark301emr/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark311/pom.xml
  shims/spark312/pom.xml
  shims/spark320/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests-spark310+/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
Labels: build

#2223 Adds subquery aggregate tests from SPARK-31620
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#2215 Support explode outer
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/generate_expr_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#2227 ParquetCachedBatchSerializer broadcast AllConfs instead of SQLConf to fix distributed mode
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: P1, bug

#2188 Support GPU broadcast exchange reuse to feed CPU BHJ when AQE is enabled
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastExchangeExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala
Labels: P1, bug

#2093 Initial implementation of row count estimates in cost-based optimizer
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: performance

#2226 Add cosine similarity native UDF example
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/rapids_udf_test.py
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
  udf-examples/src/main/cpp/benchmarks/CMakeLists.txt
  udf-examples/src/main/cpp/benchmarks/cosine_similarity/cosine_similarity_benchmark.cpp
  udf-examples/src/main/cpp/benchmarks/fixture/benchmark_fixture.hpp
  udf-examples/src/main/cpp/benchmarks/synchronization/synchronization.cpp
  udf-examples/src/main/cpp/benchmarks/synchronization/synchronization.hpp
  udf-examples/src/main/cpp/src/CosineSimilarityJni.cpp
  udf-examples/src/main/cpp/src/cosine_similarity.cu
  udf-examples/src/main/cpp/src/cosine_similarity.hpp
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWordCount.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/CosineSimilarity.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/NativeUDFExamplesLoader.java
Labels: feature request

#2245 Fix pivot bug for decimalType
  docs/supported_ops.md
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#2204 Run nightly tests for ParquetCachedBatchSerializer
  jenkins/spark-tests.sh
Labels: bug

#2251 Fix issue when out of core sorting nested data types
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: P1, bug

#2249 Update UDF native example libcudf dependency to 0.20
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: build

#2242 Add shuffle doc section on the periodicGC configuration
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#2240 Get the correct 'PIPESTATUS' in bash [skip ci]
  jenkins/databricks/run-build.py
  jenkins/databricks/run-tests.py
Labels: build

#2237 update cudf version to 0.19.1
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build, documentation

#2259 Fix merge conflict from 0.5 to 0.6 [skip ci]
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  jenkins/printJarVersion.sh
Labels: documentation

#2261 Make CBO row count test more robust
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
Labels: build

#2235 Fix distributed cache to read requested schema
  integration_tests/src/main/python/cache_test.py
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/ParquetCachedBatchSerializer.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/Spark310ParquetWriterSuite.scala
Labels: bug

#2247 Allow specifying a superclass for non-GPU execs
  integration_tests/src/main/python/csv_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PlanUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: test

#2254 updated gcp docs with custom dataproc image instructions
  docs/get-started/getting-started-gcp.md
Labels: documentation

#2264 Add spark312 and spark320 versions of cache serializer
  docs/additional-functionality/cache-serializer.md
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/ParquetCachedBatchSerializer.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/ParquetCachedBatchSerializer.scala
Labels: bug

#2101 abstract multi-file clouder reader and apply to parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: performance

#2269 Collect GPU_OP_TIME and FETCH_TIME for GpuColumnarToRowExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
Labels: feature request

#2281 Remove download section for unreleased 0.4.2
  docs/download.md
Labels: documentation

#2285 Require single batch for full outer join streaming
  docs/configs.md
  integration_tests/src/main/python/join_test.py
  shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/GpuBroadcastHashJoinExec.scala
  shims/spark301db/src/main/scala/com/nvidia/spark/rapids/shims/spark301db/GpuBroadcastHashJoinExec.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: P1, bug

#2291 update blossom-ci action repo addr [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2289 Update docs to warn against 450.80.02 driver with 10.x toolkit
  docs/download.md
Labels: documentation

#2293 update cudf version to 0.19.2
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/databricks/init_cudf_udf.sh
  jenkins/printJarVersion.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build, documentation

#2297 fix merge conflict from 0.5 to 0.6 [skip ci]
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
Labels: documentation

#2287 Make optimizer pluggable
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: benchmark

#2288 Add cosine similarity native UDF example to RAPIDS UDF docs
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#2298 Update changelog for v0.5.0 release [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#2283 Update the documentation for behavior of reading early dates in LEGACY mode
  docs/compatibility.md
Labels: documentation

#2301 Update doc to reflect nanosleep problem with 460.32.03
  docs/download.md
Labels: documentation

#2239 Do not cache the batches in Map and Group Map Panda UDF nodes.
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
Labels: task

#2304 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#2131 UCX: add endpoint by sockaddr connection + peer error handling.
  shuffle-plugin/pom.xml
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXTransaction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: shuffle, task

#2308 Fixed indentation
  shims/spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuInMemoryTableScanExec.scala
Labels: task

#2282 Support for date_format
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request
