Repository NVIDIA/spark-rapids, pull requests merged in 2022-04, with the labels that each got.

#5069 Update for the public release [skip ci]
  integration_tests/pom.xml
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-nightly-build.sh
Labels: build

#5110 Appending my id (mattahrens) to the blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#5118 On task failure catch some CUDA exceptions and kill executor [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug

#5127 GpuCast.hasSideEffects now checks to see if the child expression has side-effects
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: bug

#5047 Change Cast.toString as "cast" instead of "ansi_cast" under ANSI mode
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: audit_3.3.0

#5107 Fix GpuFileFormatDataWriter failing to stat file after commit
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/BasicColumnarWriteStatsTracker.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ColumnarWriteStatsTracker.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: bug

#5122 Disable GPU accelerated row-column transpose for Pascal GPUs:
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
Labels: cudf_dependency

#5139 Make mvn-verify check name more descriptive [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: build, task

#5144 Adapt to storage-partitioned join additions in SPARK-37377 [databricks]
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/ShimDataSourceRDD.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/execution/datasources/rapids/DataSourceStrategyUtils.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExecMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/dataSourceUtil.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: build

#5103 Init 22.04 changelog [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#5143 Fix merge conflict with branch-22.04
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
Labels: build

#5141 Upgrade to UCX 1.12.1 for 22.06
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  shuffle-plugin/pom.xml
Labels: shuffle

#5132 Add `count` support for all types
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#5146 Support env var INTEGRATION_TEST_VERSION to override shim version
  integration_tests/run_pyspark_from_build.sh
Labels: test

#4997 Update docs for the 22.04 release[skip ci]
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started.md
  docs/index.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#5165 Update Databricks 10.4 for changes to the QueryStageExec and ClusteredDistribution [databricks]
  jenkins/databricks/build.sh
  sql-plugin/src/main/311until330-nondb/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/shims/Spark320PlusNonDBShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/GpuHashPartitioning.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
Labels: build

#5160 Fix approximate percentile reduction UnsupportedOperationException
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuApproximatePercentile.scala
Labels: bug

#5168 Fix auto merge conflict 5166 [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
  jenkins/databricks/build.sh
  sql-plugin/src/main/311until330-nondb/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/shims/Spark320PlusNonDBShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/GpuHashPartitioning.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/GpuRangePartitioning.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuApproximatePercentile.scala
Labels: build

#5169 Terminate test earlier if pytest ENV issue [skip ci]
  jenkins/spark-tests.sh
Labels: build

#5167 Update cudfjni version to released 22.04.0 [databricks]
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, build

#5020 Support arithmetic operators on ANSI interval types
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/ast_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/TypeSigUtil.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/TypeSigUtil.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalArithmeticSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: audit_3.3.0

#4992 Support Collect-like Reduction Aggregations
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#5185 Fix test failure with Spark 3.3 by looking for less specific error message
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: audit_3.3.0

#5184 Fix CPU fallback for Map lookup
  docs/supported_ops.md
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: bug

#5201 Fix merge conflict from branch-22.04
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: build

#5205 Update 22.04 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#5202 Profiling tool: Remove gettingResultTime from stages & jobs aggregation
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetrics2_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetrics_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_jobandstagemetricsmulti_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsagg2_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsagg_expectation.csv
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetricsaggmulti_expectation.csv
Labels: bug, tools

#5218 XFAIL tests that are failing due to issue 5211
  integration_tests/src/main/python/csv_test.py
Labels: bug

#5239 Fix tools depending on the common jar
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ThreadFactoryBuilder.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
Labels: build

#5232 Fix issue in GpuArrayExists where a parent view outlived the child
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
Labels: bug

#5157 Update the log warning of UDF compiler
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/Plugin.scala
Labels: bug

#5171 Fix the bug COALESCING reading does not work for v2 parquet/orc datasource
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuReaderSuites.scala
  tests/src/test/scala/org/apache/spark/sql/FileUtils.scala
Labels: bug

#5251 Update 22.04 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#5105 Support multiplication on ANSI interval types
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalMultiplySuite.scala
Labels: audit_3.3.0

#5253 Merge branch 22.04 to main [skip ci]
  CHANGELOG.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ThreadFactoryBuilder.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
Labels: build

#5243 Throw again after logging that RMM could not intialize
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug

#5247 Fix test failure caused by change in Spark 3.3 exception
  integration_tests/src/main/python/logic_test.py
Labels: test

#5155 Support casting between day-time interval and string
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/GpuIntervalUtilsTest.scala
Labels: audit_3.3.0

#5001 Add fuzzing test for JSON reader
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/pytest.ini
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/json_fuzz_test.py
  integration_tests/src/main/python/marks.py
Labels: test

#5230 Update csv float tests to reflect changes in precision in cuDF
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/test/resources/simple_float_values.csv
  integration_tests/src/test/resources/small_float_values.csv
Labels: task

#5268 [BUG] When ASYNC is enabled GDS needs to handle cudaMalloced bounce buffers
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
Labels: bug

#5249 Use a bundled spark-rapids-jni dependency instead of external cudf dependency
  api_validation/README.md
  api_validation/pom.xml
  build/dependency-info.sh
  dist/maven-antrun/build-parallel-worlds.xml
  dist/pom.xml
  dist/scripts/binary-dedupe.sh
  dist/unshimmed-common-from-spark311.txt
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  integration_tests/README.md
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/build.sh
  jenkins/printJarVersion.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-tests.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#5236 Update gh-pages branch for 22.04.0 release[skip ci]
  CONTRIBUTING.md
  README.md
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/README.md
  docs/dev/compute_sanitizer.md
  docs/dev/idea-code-style-settings.md
  docs/dev/microk8s.md
  docs/dev/shims.md
  docs/download.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#5280 [BUG] Fix incorrect plugin nightly deployment and release [skip ci]
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-tests.sh
Labels: bug, build

#5284 Enable support for escaping the right square bracket
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5279 Add test case for ANSI pmod and ANSI Remainder
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#5134 Support division on ANSI interval types
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalDivisionSuite.scala
Labels: audit_3.3.0

#5287 Fix nightly scripts to deploy w/ classifier correctly [skip ci]
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
Labels: bug, build

#5288 Temporarily xfail tests to restore premerge builds
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
Labels: test

#5265 Remove unused generic types
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
Labels: bug

#5270 Include dependency of common jar in tools jar
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ThreadFactoryBuilder.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
Labels: tools

#5276 fix markdown check issue[skip ci]
  .github/workflows/markdown-links-check.yml
  .github/workflows/markdown-links-check/markdown-links-check-config.json
Labels: documentation

#5291 fix dead links in shims.md [skip ci]
  docs/dev/shims.md
Labels: documentation

#5296 Fix spark330 build due to removal of isElementAt parameter from mapKeyNotExistError
  sql-plugin/src/main/311until330-nondb/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: build

#5277 Support multiple datatypes in `TypeSig.withPsNote()`
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: task

#5290 Add documentation about reporting security issues [skip ci]
  SECURITY.md
  docs/examples.md
  docs/security.md
Labels: documentation

#5300 Fix DIST_JAR PATH in coverage-report [skip ci]
  build/coverage-report
Labels: bug, build

#5266 Update Outdated GCP getting started guide[skip ci]
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#5298 Qualification tool: Operator mapping from plugin to CSV file
  dist/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExecs.csv
  tools/src/main/resources/supportedExprs.csv
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeCheckerSuite.scala
Labels: feature request

#5307 Remove compatibility guide reference to issue #4060
  docs/compatibility.md
Labels: documentation

#5297 GpuStringSplit now honors the`spark.rapids.sql.regexp.enabled` configuration option
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#5274 Perform explicit UnsafeRow projection in ColumnarToRow transition
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/pytest.ini
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/iceberg_test.py
  integration_tests/src/main/python/marks.py
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
Labels: bug

#5289 Re-enable dollar ($) line anchor in regular expressions in find mode
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5301 Support existence join type for broadcast nested loop join
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ExistenceJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: feature request

#5315 Simplify conditional catalyst expressions generated by udf-compiler
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: feature request

#5319 Re-enable support for `\Z` in regular expressions on the GPU
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5316 Support ANSI mode for `ToUnixTimestamp, UnixTimestamp, GetTimestamp, DateAddInterval`
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#5317 Support arrays_zip
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5326 Update GCP doc and scripts [skip ci]
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/get-started/getting-started-gcp.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#5360 Revert "skip failing tests for Spark 3.3.0 (#5313)"
  integration_tests/src/main/python/map_test.py
Labels: test

#5359 Qualification tool base plan parsing infrastructure
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FilterExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ProjectExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WholeStageExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualificationApp.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeCheckerSuite.scala
Labels: tools

#5293 Support array_repeat
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5399 Update New Issue template to recommend a Discussion or Question [skip ci]
  .github/ISSUE_TEMPLATE/submit-question.md
Labels: task

#5348 Qualification tool: Skip GPU event logs
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/spark-events-profiling/dataset_eventlog
  tools/src/test/resources/spark-events-qualification/dataset_eventlog
  tools/src/test/resources/spark-events-qualification/gpu_eventlog
  tools/src/test/resources/spark-events-qualification/udf_dataset_eventlog
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheckSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools
