Repository NVIDIA/spark-rapids, pull requests merged in 2022-02, with the labels that each got.

#4672 Revert "Disable 311cdh build due to missing dependency (#4659)"
  build/buildall
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#4637 Improve support for reading CSV and JSON floating-point values
  docs/compatibility.md
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/floats.json
  integration_tests/src/test/resources/floats_edge_cases.json
  integration_tests/src/test/resources/floats_invalid.csv
  integration_tests/src/test/resources/floats_invalid.json
  integration_tests/src/test/resources/nan_and_inf.csv
  integration_tests/src/test/resources/nan_and_inf.json
  integration_tests/src/test/resources/nan_and_inf_edge_cases.json
  integration_tests/src/test/resources/simple_float_values.csv
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: task

#4673 Allow GpuWindowExec to partition on structs
  docs/supported_ops.md
  integration_tests/src/main/python/time_window_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: task

#4677 Make Collect, first and last as deterministic aggregate functions for Spark-3.3
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/Spark30Xuntil33XShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: task, audit_3.3.0

#4683 Fix documentation link, clarify documentation [skip ci]
  README.md
  integration_tests/README.md
Labels: documentation

#4681 Reimplement check for non-regexp strings using RegexParser
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
Labels: task

#4572 Add download page for 22.02 [skip ci]
  docs/download.md
Labels: documentation

#4690 Fix map_test ANSI failure in Spark 3.3.0
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: bug

#4639 Update changelog for 22.02 and archive info of some older releases [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_0.1_to_0.5.md
  scripts/generate-changelog
Labels: documentation

#4701 [BUG] Decrease nighlty tests upper limitation to 7 [skip ci]
  jenkins/spark-tests.sh
Labels: bug, build

#4700 Update cudfjni version to released 22.02.0 [databricks]
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  jenkins/version-def.sh
  pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#4706 Update 22.02 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#4707 Fix auto merge conflict 4705 [skip ci]
  CHANGELOG.md
Labels: build

#4669 Prevent deadlock between RapidsBufferStore and RapidsBufferBase on close
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
Labels: bug

#4686 Fall back to CPU for queries referencing hidden metadata columns
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
Labels: audit_3.3.0

#4408 Use the ORC version that corresponds to the Spark version [databricks]
  NOTICE-binary
  aggregator/pom.xml
  common/pom.xml
  common/src/main/scala/com/nvidia/spark/rapids/CheckUtils.scala
  common/src/main/scala/com/nvidia/spark/rapids/ThreadFactoryBuilder.scala
  common/src/test/scala/com/nvidia/spark/rapids/ThreadFactoryBuilderTest.scala
  jenkins/databricks/build.sh
  pom.xml
  shuffle-plugin/pom.xml
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/OrcShims301until320Base.scala
  sql-plugin/src/main/301until320-noncdh/scala/com/nvidia/spark/rapids/shims/v2/OrcShims.scala
  sql-plugin/src/main/311cdh/scala/com/nvidia/spark/rapids/shims/v2/OrcShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/OrcShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/OrcFiltersWrapper.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/OrcFilters.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/OrcFiltersBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  udf-examples/pom.xml
Labels: audit_3.3.0

#4611 Support BitLength and OctetLength
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: audit_3.3.0

#4716 `GpuStringSplit` should return an array on not-null elements
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: audit_3.3.0

#4697 Add preliminary test and test framework changes for ExistanceJoin
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: task

#4588 Optimize semaphore acquisition in GpuShuffledHashJoinExec
  sql-plugin/src/main/scala/ai/rapids/cudf/HostConcatResultUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
Labels: performance

#4692 Add FAQ entry to discuss executor task concurrency configuration [skip ci]
  docs/FAQ.md
Labels: documentation

#4688 Optimize DECIMAL128 sum aggregations [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: performance, cudf_dependency

#4709 Update centos 8 dockerfile to handle EOL issue [skip ci]
  jenkins/Dockerfile-blossom.integration.centos
Labels: build

#4732 Fix failing serializer tests on Spark 3.3.0
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
Labels: bug

#4731 Trim join tests to improve runtime of tests
  integration_tests/src/main/python/join_test.py
Labels: test

#4698 Add tests for few json options
  docs/compatibility.md
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/floats_leading_zeros.json
  integration_tests/src/test/resources/unquotedChars.json
Labels: task

#4738 Change resume-from to aggregator in buildall [skip ci]
  build/buildall
Labels: build

#4717 update gh-pages branch docs for v22.02 release[skip ci]
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/udf-to-catalyst-expressions.md
  docs/archives/CHANGELOG_0.1_to_0.5.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#4735 Re-enables partial regex support for octal digits on the GPU
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#4694 Add clarifications and details to integration-tests README [skip ci]
  integration_tests/README.md
Labels: documentation

#4751 Fix broken hyperlinks in documentation [skip ci]
  docs/additional-functionality/rapids-udfs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/download.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-workload-qualification.md
  docs/tuning-guide.md
Labels: documentation

#4755 Fix databricks doc for limitations.[skip ci]
  docs/get-started/getting-started-databricks.md
Labels: documentation

#4758 Fix merge conflict with branch-22.02 [skip ci]
  docs/additional-functionality/rapids-udfs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-workload-qualification.md
  docs/tuning-guide.md
Labels: documentation, build

#4754 Close SpillableBatch to avoid leaks
  integration_tests/run_pyspark_from_build.sh
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
Labels: bug

#4757 Update qualification tool to remove DECIMAL 128 as potential problem
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/test/resources/ProfilingExpectations/rapids_duration_and_cpu_expectation.csv
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/decimal_part_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
  tools/src/test/resources/spark-events-qualification/decimal_part_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#4750 Updated doc for decimal support
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation

#4767 Update 22.02 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#4771 revert cudf api links from legacy to stable[skip ci]
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#4773 Update 22.02 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#4769 Merge remote-tracking branch 'origin/branch-22.02' into main [skip ci]
  CHANGELOG.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-workload-qualification.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/test/resources/ProfilingExpectations/rapids_duration_and_cpu_expectation.csv
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/decimal_part_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
  tools/src/test/resources/spark-events-qualification/decimal_part_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: build

#4714 Add regular expression support to string_split
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#4781 Add Spark properties table to profiling tool output
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationSummaryInfo.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#4778 Decrease chance of random collisions in test temporary paths
  integration_tests/src/main/python/conftest.py
Labels: test

#4776 Improve aggregation performance of average on DECIMAL128 columns [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: performance

#4742 Add ignoreCorruptFiles feature for Parquet reader [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
Labels: bug

#4799 Fix failure to generate worker_id when xdist is not present
  integration_tests/src/main/python/conftest.py
Labels: test

#4794 Decimal-128 support for mod and pmod
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#4775 Update gh-pages branch for rapids 22.02.0 release[skip ci]
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/udf-to-catalyst-expressions.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#4797 Do not check for metadata during schema comparison
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
Labels: audit_3.3.0

#4804 Profiling tool can miss datasources when they are GPU reads
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/resources/spark-events-profiling/eventlog-gpu-dsv1.zstd
  tools/src/test/resources/spark-events-profiling/eventlog-gpu-dsv2.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#4805 Avoid output cast by using unsigned type output for GpuExtractChunk32 [databricks]
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataTypes.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: performance

#4812 Default integration test configs to allow negative decimal scale [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/explain_mode_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/limit_test.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/project_lit_alias_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sample_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/struct_test.py
  integration_tests/src/main/python/time_window_test.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#4715 Patterns such (3?)+ should now fall back to CPU
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#4823 Reduce redundancy of decimal testing [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/limit_test.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/project_lit_alias_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/row_conversion_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/struct_test.py
  integration_tests/src/main/python/subquery_test.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#4829 Make bloopInstall version configurable in buildall
  build/buildall
Labels: build, task

#4760 Short circuit AND/OR in ANSI mode
  integration_tests/src/main/python/logic_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
Labels: bug

#4827 Make InternalExclusiveModeGpuDiscoveryPlugin and ExplainPlanImpl as protected class.
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/InternalExclusiveModeGpuDiscoveryPlugin.scala
Labels: bug

#4844 Update spark313 dep to released one
  build/buildall
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  sql-plugin/src/main/313/scala/com/nvidia/spark/rapids/shims/spark313/SparkShimServiceProvider.scala
  sql-plugin/src/main/321/scala/com/nvidia/spark/rapids/shims/spark321/SparkShimServiceProvider.scala
Labels: documentation, feature request, build

#4619 Move the udf-examples module to the external repository spark-rapids-examples [databricks]
  docs/additional-functionality/rapids-udfs.md
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/pom.xml
  integration_tests/pytest.ini
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/rapids_udf_test.py
  integration_tests/src/main/python/row-based_udf_test.py
  integration_tests/src/test/java/com/nvidia/spark/rapids/tests/udf/hive/EmptyHiveGenericUDF.java
  integration_tests/src/test/java/com/nvidia/spark/rapids/tests/udf/hive/EmptyHiveSimpleUDF.java
  jenkins/databricks/build.sh
  jenkins/spark-tests.sh
  pom.xml
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/ScalaUDFSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/udf/scala/URLDecode.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/udf/scala/URLEncode.scala
  udf-examples/Dockerfile
  udf-examples/README.md
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
  udf-examples/src/main/cpp/benchmarks/CMakeLists.txt
  udf-examples/src/main/cpp/benchmarks/cosine_similarity/cosine_similarity_benchmark.cpp
  udf-examples/src/main/cpp/benchmarks/fixture/benchmark_fixture.hpp
  udf-examples/src/main/cpp/benchmarks/synchronization/synchronization.cpp
  udf-examples/src/main/cpp/benchmarks/synchronization/synchronization.hpp
  udf-examples/src/main/cpp/src/CosineSimilarityJni.cpp
  udf-examples/src/main/cpp/src/StringWordCountJni.cpp
  udf-examples/src/main/cpp/src/cosine_similarity.cu
  udf-examples/src/main/cpp/src/cosine_similarity.hpp
  udf-examples/src/main/cpp/src/string_word_count.cu
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/DecimalFraction.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/EmptyHiveSimpleUDF.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWordCount.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/URLDecode.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/hive/URLEncode.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/CosineSimilarity.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/DecimalFraction.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/NativeUDFExamplesLoader.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/URLDecode.java
  udf-examples/src/main/java/com/nvidia/spark/rapids/udf/java/URLEncode.java
Labels: task

#4822 Push decimal workarounds to cuDF
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DecimalUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: task

#4839 Optionally return null if element not exists map/array
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShimsBase.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShimsBase.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: feature request

#4838 Trim cache tests to improve integration test time [databricks]
  integration_tests/src/main/python/cache_test.py
Labels: test

#4819 Throw exception if casting from double to datetime
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/AnsiCheckUtil.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/AnsiCheckUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/FloatUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: audit_3.3.0

#4835 Trim parquet_write_test to reduce integration test runtime
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#4848 Profile tool: fix printing of task failed reason
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileOutputWriter.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/resources/ProfilingExpectations/tasks_failure_eventlog_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/HealthCheckSuite.scala
Labels: tools

#4851 Add worker ID to temporary table names in tests
  integration_tests/src/main/python/conftest.py
Labels: test

#4850 Also check cuda runtime version when using the ASYNC allocator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: improve

#4874 Fix spark-tests syntax issue [skip ci]
  jenkins/spark-tests.sh
Labels: bug, build
