Repository NVIDIA/spark-rapids, pull requests merged in 2022-12, with the labels that each got.

#7202 Avoid sort in v1 write for static cloumns[databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
Labels: audit_3.4.0

#7174 Fix dependencies in jenkins-test script to support DB11.3 [databricks]
  docs/additional-functionality/iceberg-support.md
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test, build

#7203 [Doc]add a Contact Us page at the top-level menu[skip ci]
  docs/contact-us.md
Labels: documentation

#7209 Change RegExpExtract to use isNull checks instead of contains_re
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: performance

#6903 Support projectV2 for changelog tooling [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation, build

#7166 Sync up spark2 explain code
  docs/get-started/getting-started-workload-qualification.md
  scripts/rundiffspark2.sh
  scripts/spark2diffs/CastExprMeta.diff
  scripts/spark2diffs/DecimalArithmeticOverrides.diff
  scripts/spark2diffs/GetMapValueMeta.diff
  scripts/spark2diffs/GpuHiveOverrides.diff
  scripts/spark2diffs/GpuOverrides.diff
  scripts/spark2diffs/GpuParquetFileFormat.diff
  scripts/spark2diffs/GpuRegExpUtils.diff
  scripts/spark2diffs/GpuStringSplitMeta.diff
  scripts/spark2diffs/GpuTypeShims.diff
  scripts/spark2diffs/HiveProviderImpl.diff
  scripts/spark2diffs/RapidsConf.diff
  scripts/spark2diffs/RegexParser.diff
  scripts/spark2diffs/aggregate.diff
  scripts/spark2diffs/toRapidsStringOrNull.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCastMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexComplexityEstimator.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/GetMapValueMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/gpuWindows.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: tools

#7207 Change the hive text file parser to not use CSV input format [databricks]
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: task

#7084 [Doc]Update databricks doc for 22.12[skip ci]
  docs/FAQ.md
  docs/get-started/getting-started-databricks.md
  docs/img/Databricks/sparkconfig.png
Labels: documentation

#7235 Create tmp path to make python path explicit [skip ci]
  jenkins/spark-tests.sh
Labels: build

#7080 [Doc] Document Alluxio does not sync metadata from S3 by default [skip ci]
  docs/get-started/getting-started-alluxio.md
Labels: documentation

#7155 Add unit tests for alluxio utils
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioConfigReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioFS.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioConfigReaderSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioUtilsSuite.scala
Labels: test

#7248 Fix AlluxioUtilsSuite build on Databricks [databricks]
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioUtilsSuite.scala
Labels: build

#7172 Add a document for how to view Alluxio metrics on UI [skip ci]
  .github/workflows/markdown-links-check/markdown-links-check-config.json
  docs/get-started/getting-started-alluxio.md
  docs/img/Databricks/a-metric-graph.png
  docs/img/Databricks/grafana.png
  docs/img/Databricks/list-metrics-result.png
  docs/img/Databricks/list-metrics.png
  docs/img/Databricks/prometheus-datasource.png
  docs/img/Databricks/save-prometheus.png
Labels: documentation

#7262 Moving generated files to standalone tools dir
  dist/pom.xml
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedDataSource.csv
  tools/generated_files/supportedExecs.csv
  tools/generated_files/supportedExprs.csv
Labels: tools

#7273 Fix AlluxioUtilsSuite build on Databricks for 22.12 [databricks]
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioUtilsSuite.scala
Labels: build

#7221 Fix date parsing in Hive Delimited Text reader
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/test/resources/hive-delim-text/date-err/date.err.hive.txt
  integration_tests/src/test/resources/hive-delim-text/date/date.hive.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
Labels: bug

#7270 Update 22.12 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#7265 Fix Hive Delimited Text timestamp parsing
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/test/resources/hive-delim-text/timestamp-err/ts.err.hive.txt
  integration_tests/src/test/resources/hive-delim-text/timestamp/ts.hive.txt
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: bug

#7245 Fix boolean, int, and float parsing. Improve decimal parsing for hive
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/test/resources/hive-delim-text/extended-float-values/ext_float_values.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-boolean-values/bools.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-float-values/simple_float_values.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-int-values/simple_int_values.hive.txt
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: bug

#7291 Improve IntelliJ IDEA doc and usability [databricks]
  CONTRIBUTING.md
  pom.xml
Labels: build

#7285 [FEA] Support `reverse` for strings
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request, cudf_dependency

#7306 Cherry pick #7293 to 22.12 [skip ci]
  jenkins/databricks/run_it.sh
Labels: build

#7305 Fix CPU fallback for custom timestamp formats in Hive text tables
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: bug

#7288 Add support for SaveIntoDataSource for Delta Lake 2.x
  NOTICE
  NOTICE-binary
  dist/unshimmed-from-each-spark3xx.txt
  docs/FAQ.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/iceberg-support.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/delta_lake_write_test.py
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/GpuDeltaDataSource.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/package-shims.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuCheckDeltaInvariant.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuDeltaLog.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuWriteIntoDelta.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuCheckDeltaInvariant.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuDeltaLog.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuOptimisticTransaction.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuWriteIntoDelta.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/GpuDeltaDataSource.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/package-shims.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuDeltaIdentityColumnStatsTracker.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuDeltaTaskStatisticsTracker.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuStatisticsCollection.scala
  sql-plugin/src/main/delta-lake-common/scala/org/apache/spark/sql/rapids/delta/GpuIdentityColumn.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuExecutedCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SaveIntoDataSourceCommandMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/UnshimmedTrampolineUtil.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedDataSource.csv
  tools/src/main/resources/supportedExecs.csv
  udf-compiler/pom.xml
Labels: feature request

#7315 Fix merge conflict with branch-22.12
  NOTICE
  NOTICE-binary
  dist/unshimmed-from-each-spark3xx.txt
  docs/FAQ.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/iceberg-support.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/delta_lake_write_test.py
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/GpuDeltaDataSource.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/package-shims.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuCheckDeltaInvariant.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuDeltaLog.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuWriteIntoDelta.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuCheckDeltaInvariant.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuDeltaLog.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuOptimisticTransaction.scala
  sql-plugin/src/main/321db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuWriteIntoDelta.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/GpuDeltaDataSource.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/delta/shims/package-shims.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuDeltaIdentityColumnStatsTracker.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuDeltaTaskStatisticsTracker.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/GpuStatisticsCollection.scala
  sql-plugin/src/main/delta-lake-common/scala/org/apache/spark/sql/rapids/delta/GpuIdentityColumn.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuExecutedCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SaveIntoDataSourceCommandMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/UnshimmedTrampolineUtil.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedDataSource.csv
  tools/generated_files/supportedExecs.csv
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedDataSource.csv
  tools/src/main/resources/supportedExecs.csv
  udf-compiler/pom.xml
Labels: build

#7312 Fix documentation bug
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#7330 xfail all delta-write fallback cases [skip ci]
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#7335 Fix auto merge conflict 7334[skip ci]
  docs/FAQ.md
  docs/archive.md
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#7316 Update jni version 22.12.0 [databricks]
  pom.xml
Labels: build

#7337 Update 22.12 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#7338 Fix auto merge conflict 7336 [skip ci]
  CHANGELOG.md
Labels: build

#7358 Update Delta version to 1.1.0 [databricks]
  pom.xml
Labels: build

#7340 Fix nested-unsigned test issues.
  tests/src/test/resources/nested-unsigned-malformed.parquet
  tests/src/test/resources/nested-unsigned.parquet
  tests/src/test/scala/com/nvidia/spark/rapids/GpuExpressionTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: bug, build

#7298 Improve performance of small file parquet reads from blob stores
  docs/configs.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: performance

#7366 Support Databricks 11.3 [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#7299 Qualification tool: Update parsing of write data format
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/DataWritingCommandExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeCheckerSuite.scala
Labels: bug

#7375 Fix CPU fallback for GpuHiveTableScanExec
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: bug

#7379 Fixes bug where dynamic partition overwrite mode didn't work for ORC
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
Labels: bug

#7385 Fix Databricks version comparison in pytests [databricks]
  integration_tests/src/main/python/spark_session.py
Labels: test

#7386 Spark 3.1.4 snapshot fix setting of reproduceEmptyStringBug
  sql-plugin/src/main/314/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
Labels: bug

#7372 Fix for incorrect nested-unsigned test
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
Labels: bug, build, cudf_dependency

#7365 Move PythonMapInArrowExec to shim for shared 330+ functionality (db11.3) [databricks]
  sql-plugin/src/main/330+-nondb/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/PythonMapInArrowExecShims.scala
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
Labels: task

#7380 [FEA] Support `reverse` for arrays
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request, cudf_dependency

#7388 [databricks] Fix `test_array_element_at_zero_index_fail` and `test_div_overflow_exception_when_ansi` DB 11.3 integration test failures
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/array_test.py
Labels: task

#7377 Update RapidsUDF interface to support UDFs with no input parameters
  docs/additional-functionality/rapids-udfs.md
  sql-plugin/src/main/java/com/nvidia/spark/RapidsUDF.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  tests/src/test/scala/com/nvidia/spark/rapids/KnownNotNullSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalaUDFSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/udf/scala/AlwaysTrueUDF.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/udf/scala/URLDecode.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/udf/scala/URLEncode.scala
Labels: bug

#7371 Avoid shutting down RMM until all allocations have cleared
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug

#7381 Filter out some new timestamp-related Delta Lake tags when comparing logs
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#7390 Aggregate Databricks 11.3 shim in the nightly dist jar
  dist/pom.xml
  jenkins/spark-nightly-build.sh
  jenkins/version-def.sh
Labels: build

#7384 Fix implementation of createReadRDDForDirectories to match DataSource…
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
Labels: bug

#7395 Enable Delta Lake write acceleration by default
  docs/additional-functionality/delta-lake-support.md
  docs/configs.md
  integration_tests/src/main/python/delta_lake_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#7405 Fix multithreaded combine code initial size calculation
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#7362 Fix multiplication and division test failures in 330db and 340 shim [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until340-non330db/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/311until340-non330db/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/311until340-non330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/340+-and-330db/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/340+-and-330db/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/340+-and-330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  tools/generated_files/supportedExprs.csv
Labels: bug

#7410 Remove 314 from dist build list
  dist/pom.xml
Labels: build

#6761 Switch string to float casting to use new kernel
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: feature request

#7422 Skip test_dynamic_partition_write_round_trip in 321cdh
  integration_tests/src/main/python/orc_write_test.py
Labels: bug, test

#7408 Fallback to CPU for unrecognized ShuffleOrigin [databricks]
  integration_tests/src/main/python/aqe_test.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/dpp_test.py
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/ShuffleOriginUtil.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: bug

#7424 xfail Hive text tests failing on CDH
  integration_tests/src/main/python/hive_delimited_text_test.py
Labels: test

#7427 Install-file log4j-core on Databricks 11.3 [databricks]
  jenkins/databricks/build.sh
  sql-plugin/pom.xml
Labels: build

#7416 [databricks] Reorganize and shim ScanExecMeta overrides and fix interval file IO
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/BatchScanExecMeta.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/ScanExecShims.scala
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/shims/Spark321PlusDBShims.scala
  sql-plugin/src/main/330+-nondb/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/ScanExecShims.scala
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
Labels: bug

#7435 Update IntelliJ IDEA doc [skip ci]
  CONTRIBUTING.md
Labels: task

#7440 Xfail largest decimals window aggregation [databricks]
  integration_tests/src/main/python/window_function_test.py
Labels: test
