Repository NVIDIA/spark-rapids, pull requests merged in 2022-05, with the labels that each got.

#5408 [DOC] Add rebase mode notes for databricks doc [skip ci]
  docs/get-started/getting-started-databricks.md
Labels: documentation

#5349 Enable some repetitions for `\A` and `\Z`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5414 Add 320+-noncdh to Databricks to fix 321db build [databricks]
  pom.xml
Labels: build

#5410 Update docs for removal of 311cdh
  CONTRIBUTING.md
  docs/additional-functionality/rapids-shuffle.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: documentation

#5306 Support coalescing reading for avro
  docs/configs.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/avro_test.py
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroDataFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroFileWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuReadAvroFileFormat.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/GpuReaderTypeSuites.scala
Labels: performance

#5418 Add GpuEqualToNoNans and update GpuPivotFirst to use to handle PivotFirst with NaN support enabled on GPU
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
Labels: feature request

#5419 Append my id to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#5427 Workaround to fix cuda repo key rotation in ubuntu images [skip ci]
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/get-started/Dockerfile.cuda
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#5426 Qualification tool: Parsing Execs to get the ExecInfo #2
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/CartesianProductExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/GenerateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/GlobalLimitExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/LocalLimitExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortExecParser.scala
  tools/src/test/resources/spark-events-qualification/global_local_limit_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#5424 Exclude all unicode line terminator characters from matching dot
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5433 [DOC] Removed mention of 30x from shims.md [skip ci]
  docs/dev/shims.md
Labels: documentation

#5432 Test case insensitive reading for Parquet and CSV
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/parquet_test.py
Labels: test

#5428 Make the sync marker uniform for the Avro coalescing reader
  integration_tests/src/main/python/avro_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: bug

#5425 Handle readBatch changes for Spark 3.3.0
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/311until330-nondb/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/CurrentBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
Labels: audit_3.3.0

#5431 [DOC] Update the ubuntu repo key [skip ci]
  docs/get-started/getting-started-on-prem.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#5455 Moved ShimCurrentBatchIterator so it's visible to db312 and db321 [databricks]
  sql-plugin/src/main/311until330-all/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
Labels: bug

#5454 QualificationTool. Add speedup information to AppSummaryInfo
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/db_sim_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/directory_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/jdbc_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_type_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv1_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/spark2_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#5310 Use C++ to parse and filter parquet footers.
  build/buildall
  docs/configs.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroDataFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostMemoryStreams.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#5466 [Doc] Change the picture of the query plan to text format. [skip ci]
  docs/get-started/getting-started-on-prem.md
  docs/img/ease-of-use.png
  docs/index.md
Labels: documentation

#5442 Add support for regular expressions containing hexadecimal digits greater than `0x7f`
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5434 Check schema compatibility when building parquet readers
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#5468 Qualification tool: Add support for join, pandas, aggregate execs
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/AggregateInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ArrowEvalPythonExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastNestedLoopJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FlatMapGroupsInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/HashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/MapInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ObjectHashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ShuffledHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortMergeJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowInPandasExecParser.scala
  tools/src/test/resources/spark-events-qualification/pandas_execs_eventlog.zstd
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#5443 Add support for regular expressions containing octal digits greater than `\200`
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5459 Add test cases for casting string to date in ANSI mode
  integration_tests/src/main/python/cast_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: test

#5465 Fix query planning issue when Iceberg is used with DPP and AQE
  integration_tests/src/main/python/iceberg_test.py
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
Labels: bug

#5471 Add implicit `safeFree` for `RapidsBuffer`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/implicits.scala
Labels: bug

#5436 Support `map_filter` operator
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5486 Fix regression in AnsiCastOpSuite with Spark 3.3.0
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
Labels: test

#5498 Enable 330 unit tests for nightly
  jenkins/spark-nightly-build.sh
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#5494 Fix databrick Shim to support Ansi mode when casting from string to date [databricks]
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
Labels: bug

#5490 Qualification tool: Update speedup factor for few operators
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/AggregateInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ArrowEvalPythonExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BatchScanExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastExchangeExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastNestedLoopJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/CartesianProductExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/CoalesceExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/CollectLimitExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/CustomShuffleReaderExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ExpandExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FileSourceScanExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FilterExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FlatMapGroupsInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/GenerateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/GlobalLimitExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/HashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/InMemoryTableScanExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/LocalLimitExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/MapInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ObjectHashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ProjectExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/RangeExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SampleExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ShuffleExchangeExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ShuffledHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortMergeJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SubqueryBroadcastExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/TakeOrderedAndProjectExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/UnionExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowInPandasExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeCheckerSuite.scala
Labels: tools

#5477 Add support for `\h`, `\H`, `\v`, `\V`, and `\R` character classes
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: feature request

#5499 [DOC]update doc for emr6.6[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#5470 Qualification tool support UI code generation
  LICENSE
  NOTICE
  NOTICE-binary
  aggregator/pom.xml
  pom.xml
  tools/.gitignore
  tools/pom.xml
  tools/prepare-ui-libraries.xml
  tools/src/main/resources/ui/css/rapids-dashboard.css
  tools/src/main/resources/ui/html/index.html
  tools/src/main/resources/ui/html/raw.html
  tools/src/main/resources/ui/js/qual-report.js
  tools/src/main/resources/ui/js/raw-report.js
  tools/src/main/resources/ui/js/ui-config.js
  tools/src/main/resources/ui/js/uiutils.js
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ui/QualificationReportGenerator.scala
Labels: tools

#5491 Enables `$`, `\z`, and `\Z` in `REGEXP_REPLACE` on the GPU
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5520 [DOC] Remove Spark from our naming of Tools [skip ci]
  README.md
  docs/download.md
  docs/get-started/getting-started-workload-qualification.md
  docs/spark-qualification-tool.md
  tools/README.md
Labels: documentation, tools

#5506 Fix ClassCastException in regular expression transpiler
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: bug

#5527 Fix bug with character class immediately following a string anchor
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5489 Fallback to the CPU if Parquet encryption keys are set [databricks]
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: bug

#5523 Enable forcePositionEvolution for 321cdh
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/OrcShims321CDHBase.scala
Labels: bug

#5534 MVN_OPT to last, as it is empty in most cases [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/databricks/build.sh
  jenkins/databricks/params.py
  jenkins/databricks/run-build.py
Labels: build

#5546 Set hasSideEffects correctly for GpuCreateMap
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeCreator.scala
Labels: bug

#5538 Add tests for string to timestamp functions in ANSI mode [databricks]
  integration_tests/src/main/python/date_time_test.py
Labels: test

#5421 Support multi-threaded reading for avro
  docs/configs.md
  integration_tests/src/main/python/avro_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroDataFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuReaderTypeSuites.scala
Labels: performance

#5539 Fix IntervalSuite cases failure
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalSuite.scala
Labels: bug

#5483 Don't distinguish between types of `ArithmeticException` for Spark 3.2.x
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: bug

#5555 [DOC]cherry pick emr660 version updates[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#5558 Fix target file for update from extra-resources in dist module
  dist/pom.xml
Labels: bug, build, P1

#5571 Update array_min and array_max to use new cudf operations
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: performance

#5528 Enable build and test with JDK11
  CONTRIBUTING.md
  dist/maven-antrun/build-parallel-worlds.xml
  pom.xml
  spark2-sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: build

#5560 Minor: Clean up the tests of `concat_list`
  integration_tests/src/main/python/collection_ops_test.py
Labels: test

#5579 Update test_cast_neg_to_decimal_err to work with Databricks 10.4 where exception is different [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test, P1

#5584 Enable automerge from branch-22.06 to 22.08 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#5583 Disable spark snapshot shims build for pre-merge
  jenkins/spark-premerge-build.sh
Labels: build

#5505 Support spark.sql.mapKeyDedupPolicy=LAST_WIN for TransformKeys
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMapUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
Labels: feature request

#5540 Support RaiseError [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/misc_expr_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/misc.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5531 Filter rows with null keys when coalescing due to reaching cuDF row limits [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
Labels: reliability

#5599 Move ShimServiceProvider file re-init/truncate
  dist/maven-antrun/build-parallel-worlds.xml
Labels: build

#5588 Update Databricks build scripts [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/databricks/build.sh
  jenkins/databricks/params.py
  jenkins/databricks/run-build.py
Labels: build

#5601 Update test_div_overflow_exception_when_ansi test for Spark-3.3 [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: bug

#5598 Qualification tool: Update RunningQualificationApp tests
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#5541 Regexp: Transpile `\d`, `\w` to Java's definitions
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: bug

#5526 Fix whitespace `\s` and `\S` tests
  integration_tests/src/main/python/string_test.py
Labels: test

#5612 Qualification tool: update SQL Df value used and look at jobs in SQL
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WholeStageExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/db_sim_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/directory_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/jdbc_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_type_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv1_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/spark2_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#5614 Move HostConcatResultUtil out of unshimmed classes
  jenkins/spark-premerge-build.sh
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/cudf_utils/HostConcatResultUtil.scala
Labels: bug, P1

#5533 Support `GpuMapConcat`
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5625 [DOC]update links for 2206 release[skip ci]
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-udfs.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#5532 Support hex digits in character classes and escaped characters in character class ranges
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5441 Enable optional float confs and update docs mentioning them
  docs/compatibility.md
  docs/configs.md
  docs/get-started/getting-started-workload-qualification.md
  docs/spark-profiling-tool.md
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, feature request

#5645 Add support for octal digits in character classes
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5644 Qualification tool: Enable UDF reporting in potential problems
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#5658 Fallback to CPU when `&&` found in character class
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5600 Qualification tool UI cosmetics and CSV output changes
  tools/src/main/resources/ui/css/rapids-dashboard.css
  tools/src/main/resources/ui/html/index.html
  tools/src/main/resources/ui/html/raw.html
  tools/src/main/resources/ui/js/qual-report.js
  tools/src/main/resources/ui/js/raw-report.js
  tools/src/main/resources/ui/js/ui-config.js
  tools/src/main/resources/ui/js/uiutils.js
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
  tools/src/test/resources/QualificationExpectations/db_sim_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/directory_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/jdbc_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/nested_type_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_missing_sql_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv1_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv2_expectation.csv
  tools/src/test/resources/QualificationExpectations/spark2_expectation.csv
  tools/src/test/resources/QualificationExpectations/truncated_1_end_expectation.csv
  tools/src/test/resources/QualificationExpectations/write_format_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#5514 ANSI mode: allow casting between numeric type and timestamp type [databricks]
  docs/compatibility.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/AnsiUtil.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/AnsiCheckUtil.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/AnsiUtil.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/TimestampSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: audit_3.3.0

#5647 Init version 22.08.0-SNAPSHOT [databricks]
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  common/pom.xml
  dist/pom.xml
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#5472 Add shims for Spark 3.4.0
  build/buildall
  dist/pom.xml
  integration_tests/src/main/python/limit_test.py
  integration_tests/src/main/python/spark_session.py
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/311until330-all/scala/org/apache/spark/sql/rapids/shims/SparkUpgradeExceptionShims.scala
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/GlobalLimitShims.scala
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/ParquetStringPredShims.scala
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/ParquetTimestampNTZShims.scala
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/ShimFilePartitionReaderFactory.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/SparkUpgradeExceptionShims.scala
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/GlobalLimitShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ParquetStringPredShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ParquetTimestampNTZShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/ShimFilePartitionReaderFactory.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/spark340/SparkShimServiceProvider.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/spark340/RapidsShuffleManager.scala
  sql-plugin/src/main/340/scala/org/apache/spark/sql/rapids/shims/spark340/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CostBasedOptimizer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadCSVFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadOrcFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuReadAvroFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  sql-plugin/src/test/340/scala/com/nvidia/spark/rapids/shims/spark340/Spark340ShimsSuite.scala
  tests/pom.xml
  tests/src/test/330+/scala/com/nvidia/spark/rapids/CsvScanForIntervalSuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/GpuIntervalUtilsTest.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/IntervalArithmeticSuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/IntervalCastSuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/IntervalDivisionSuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/IntervalMultiplySuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/IntervalSuite.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/SampleSuite.scala
Labels: build

#5603 Skip unshim and dedup of external spark-rapids-jni and jucx [databricks]
  aggregator/pom.xml
  dist/pom.xml
  dist/unshimmed-common-from-spark311.txt
  pom.xml
  shuffle-plugin/pom.xml
Labels: build

#5627 Install locales and generate en_US.UTF-8
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#5668 Add user as CI owner [skip ci]
  .github/CODEOWNERS
Labels: build

#5677 Qualification tool Enable UI by default
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
Labels: tools

#5542 Support arrays of arrays and structs for concat on arrays
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#5664 Fix edge case where one side of regexp choice ends in duplicate string anchors
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5689 Disable 340 for premerge and nightly
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#5675 Update the error messages for the failing arithmetic tests.
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#5693 Temporarily allow 3.3.1 for 3.3.0 shims.
  pom.xml
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/spark330/SparkShimServiceProvider.scala
  sql-plugin/src/test/330/scala/com/nvidia/spark/rapids/shims/spark330/Spark330ShimsSuite.scala
Labels: build

#5676 Fix ORC reading over different schemas
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#5700 Fix auto merge conflict 5699
  pom.xml
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/spark330/SparkShimServiceProvider.scala
  sql-plugin/src/test/330/scala/com/nvidia/spark/rapids/shims/spark330/Spark330ShimsSuite.scala
Labels: build
