Repository NVIDIA/spark-rapids, pull requests merged in 2022-09, with the labels that each got.

#6468 Use non-capture groups in LIKE regexp pattern
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: performance

#6472 Check more places for Parquet encryption configs
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: bug

#6475 Change GpuKryoRegistrator to load the classes we want to register with the ShimLoader
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKryoRegistrator.scala
Labels: bug

#6066 Add support for arrays in hashaggregate [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#6451 Normalize nans in GpuSortArray
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#6482 Fix leak in interval divide
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala
Labels: bug

#6479 Remove KnownFloatingPointNormalized from allow_non_gpu
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
Labels: test

#6483 Fix DOP calculation for xdist
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-premerge-build.sh
Labels: test

#6492 Fix intermittent failure on test_cast_float_to_timestamp_side_effect
  integration_tests/src/main/python/cast_test.py
Labels: test

#6484 Fixes excessive ShuffleBlockId object creation due to missing map index bounds [databricks]
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/rapids/shims/ShuffledBatchRDDUtil.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/ShuffledBatchRDDUtil.scala
Labels: bug

#6486 Remove the `hasNans` config from `GpuCollectSet`
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: task

#6499 Fix non-deterministic overflows in test_hash_grpby_sum_full_decimal
  docs/compatibility.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: documentation, test

#6476 Add GPU acceleration for OptimizedCreateHiveTableAsSelect
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/datasourcev2_write_test.py
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/PlanShims.scala
  sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/CharVarcharUtilsShims.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/PlanShims.scala
  sql-plugin/src/main/320until330-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/CharVarcharUtilsShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOptimizedCreateHiveTableAsSelectCommand.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
Labels: feature request

#6491 [DOC] Change recommend setting of spark.locality.wait to 3s [skip ci]
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/yarn-gpu.md
  docs/tuning-guide.md
Labels: documentation

#6498 Allow filtering blocks to be done multithreaded in the Parquet coalescing reader
  docs/configs.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExecMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: feature request

#6319 Support float/double castings for ORC reading [databricks]
  docs/configs.md
  integration_tests/src/main/python/orc_cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#6510 Revert "Added in very specific support for from_json to a Map<String,String> (#6211)"
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: SQL

#6466 Use tiered projections for hash aggregates
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBoundAttribute.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalenExpressions.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressionsSuite.scala
Labels: feature request, performance

#6527 Use ShimLoader to access PlanShims
  dist/unshimmed-from-each-spark3xx.txt
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/PlanShimsImpl.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/PlanShimsImpl.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PlanShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: bug

#6525 Fix typo in file name
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
Labels: improve

#6505 Include avro test by using '--packages' option [skip ci]
  jenkins/spark-tests.sh
Labels: test

#6421 Fix notebook and getting started examples [skip ci]
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/get-started/getting-started-gcp.md
Labels: documentation, improve

#6436 Switch to gpu string to integer casts
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: performance

#6461 Enabling AQE on [databricks]
  integration_tests/src/main/python/aqe_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/311+-db/scala/com/nvidia/spark/rapids/shims/ShimLeafExecNode.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/ShimLeafExecNode.scala
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/rapids/shims/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/rapids/shims/GpuShuffleExchangeExec.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInMemoryTableScanExec.scala
Labels: task

#6473 Fix parquet write when the input column is nested type containing timestamp
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/HashUtils.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnCastUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: bug, P2, task

#6429 Fix up `buffer time` for multi-file readers
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: task

#6547 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#6541 Add another alluxio path replacement algorithm
  docs/configs.md
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/shims/Spark320PlusNonDBShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: feature request

#6548 Fixes for recent cuDF regexp changes
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#6522 Nightly spark-tests script to follow PYSP_TEST pattern [skip ci]
  integration_tests/run_pyspark_from_build.sh
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/spark-tests.sh
Labels: test, build

#6549 Update SnakeYaml version for bug fixes
  tools/pom.xml
Labels: bug

#6555 Document a safe unshimming algorithm [skip ci]
  docs/dev/shims.md
Labels: documentation

#6542 [Doc]Doc update for databricks single node cluster[skip ci]
  docs/get-started/getting-started-databricks.md
Labels: documentation

#6512 Remove the `hasNans` config and update the doc
  docs/compatibility.md
  docs/configs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/get-started/getting-started-gcp.md
  docs/spark-profiling-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/mortgage_test.py
  integration_tests/src/main/python/qa_nightly_select_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tools/src/main/resources/supportedExprs.csv
Labels: documentation, test

#6563 Add missing closing ``` for a code block [skip ci]
  docs/dev/shims.md
Labels: documentation

#6566 Fix map gen for `orc_write_test.py`
  integration_tests/src/main/python/orc_write_test.py
Labels: bug, test, P1

#6557 Mitigate non-test failure and remove 21.xx premerge support [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: test, build

#6550 Allow percent_rank to not need an entire group in memory [databricks]
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: bug, SQL, P1, reliability

#6504 [DOC] Add notes for cgroup permission reverted[skip ci]
  docs/get-started/yarn-gpu.md
Labels: documentation

#6562 Handle EmptyRelation in GpuSubqueryBroadcastExec
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
Labels: bug

#6553 Update handling for projectList based WindowExecs to handle window function of window function [databricks]
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: bug

#6575 Fix maxPartitionBytes bounds checking in AutoTuner
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
Labels: bug, tools

#6534 Add GpuColumnVectorUtils to access GpuColumnVector
  dist/unshimmed-common-from-spark311.txt
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnVectorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRDDConverterSuite.scala
Labels: bug

#6564 Fix the check of empty batches for partitioning[databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: bug

#6579 Disable UCX smoke test temporarily [databricks]
  jenkins/spark-premerge-build.sh
Labels: bug, test, shuffle

#6577 Work around multiprocess issues with updating Ivy cache
  jenkins/spark-tests.sh
Labels: build

#6576 Bump snakeyaml version to 1.32
  tools/pom.xml
Labels: tools

#6511 Multi-threaded shuffle reader for RapidsShuffleManager [databricks]
  docs/additional-functionality/rapids-shuffle.md
  docs/configs.md
  jenkins/spark-premerge-build.sh
  sql-plugin/src/main/311-nondb/scala/org/apache/spark/sql/rapids/shims/spark311/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedReader.scala
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedWriter.scala
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala
  sql-plugin/src/main/312-nondb/scala/org/apache/spark/sql/rapids/shims/spark312/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/312db/scala/org/apache/spark/sql/rapids/shims/spark312db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/313/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/314/scala/org/apache/spark/sql/rapids/shims/spark314/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedWriter.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala
  sql-plugin/src/main/320/scala/org/apache/spark/sql/rapids/shims/spark320/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/320until330-all/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedReader.scala
  sql-plugin/src/main/321/scala/org/apache/spark/sql/rapids/shims/spark321/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/321cdh/scala/org/apache/spark/sql/rapids/shims/spark321cdh/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/spark321db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/322/scala/org/apache/spark/sql/rapids/shims/spark322/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/330/scala/org/apache/spark/sql/rapids/shims/spark330/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedReader.scala
  sql-plugin/src/main/331/scala/org/apache/spark/sql/rapids/shims/spark331/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
  tests/src/test/320+-noncdh-nondb/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedReaderSuite.scala
  tests/src/test/320+-noncdh-nondb/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedWriterSuite.scala
Labels: performance, shuffle

#6586 Adds link to spark supporting shuffle classes and fix copyright
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala
Labels: documentation, shuffle

#6573 Update UCX to 1.13.1 in CI and sets UCX_TLS=^posix
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-premerge-build.sh
Labels: bug

#6587 Delta Lake and AQE on Databricks 10.4 workaround [databricks]
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#6437 Use dist/pom file as source of truth for spark versions
  .github/workflows/mvn-verify-check.yml
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#6589 Update doc to indicate ORC and Parquet zstd read support [skip ci]
  docs/compatibility.md
Labels: documentation

#6590 Parallelize tests using spark packages feature [databricks]
  integration_tests/src/main/python/spark_init_internal.py
  jenkins/spark-tests.sh
Labels: test, build

#6412 Qualification tool: Print unsupported Execs and expressions
  docs/spark-qualification-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FilterExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/HashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ObjectHashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ProjectExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WholeStageExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualificationApp.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6574 Add shim layer for Cloudera CDS 3.3
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/330+-noncdh/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/ShimSupportsRuntimeFiltering.java
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/spark330cdh/SparkShimServiceProvider.scala
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/spark330cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/330cdh/scala/org/apache/spark/sql/rapids/shims/spark330cdh/RapidsShuffleInternalManager.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: feature request, task

#6432 [Doc]Add archived release page[skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#6599 Add in support for casting binary to string
  docs/supported_ops.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request, SQL

#6602 Fix version-def script to correctly set list of shims
  jenkins/version-def.sh
Labels: bug, build

#6569 Add dynamic partition concurrent writer to avoid full sort [databricks]
  docs/configs.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
Labels: performance

#6609 Enable automerge from 22.10 to 22.12 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#6506 Add alluxio reliability doc
  docs/get-started/getting-started-alluxio.md
Labels: documentation

#6584 Fix spark2-sql-plugin
  scripts/rundiffspark2.sh
  scripts/spark2diffs/FromUTCTimestampExprMeta.diff
  scripts/spark2diffs/GpuBatchUtils.diff
  scripts/spark2diffs/GpuDecimalDivide.diff
  scripts/spark2diffs/GpuHashJoin.diff
  scripts/spark2diffs/GpuHiveOverrides.diff
  scripts/spark2diffs/GpuOptimizedCreateHiveTableAsSelectCommand.diff
  scripts/spark2diffs/GpuOrcScanBase.diff
  scripts/spark2diffs/GpuOverrides.diff
  scripts/spark2diffs/GpuParquetFileFormat.diff
  scripts/spark2diffs/GpuRLikeMeta.diff
  scripts/spark2diffs/GpuReadOrcFileFormat.diff
  scripts/spark2diffs/GpuRegExpExtractMeta.diff
  scripts/spark2diffs/GpuRegExpReplaceMeta.diff
  scripts/spark2diffs/GpuRegExpUtils.diff
  scripts/spark2diffs/GpuSpecifiedWindowFrameMetaBase.diff
  scripts/spark2diffs/GpuWindowExpressionMetaBase.diff
  scripts/spark2diffs/HiveProviderImpl.diff
  scripts/spark2diffs/RapidsConf.diff
  scripts/spark2diffs/RapidsMeta.diff
  scripts/spark2diffs/RegexParser.diff
  scripts/spark2diffs/TypeChecks.diff
  scripts/spark2diffs/UnixTimeExprMeta.diff
  scripts/spark2diffs/aggregate.diff
  scripts/spark2diffs/average.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOptimizedCreateHiveTableAsSelectCommand.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadOrcFileFormat.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexComplexityEstimator.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimGpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/gpuWindows.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressionsMeta.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringMeta.scala
Labels: task

#6607 Enable tests that were missed when binary support was extended
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: test, task

#6610 Disable 22.10 snapshot builds
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: test, build

#6612 Tolerate event log folder existence when to create it to avoid raisin…
  integration_tests/src/main/python/spark_init_internal.py
Labels: test

#6617 Fix a Delta Lake Deletes issue[databricks]
  sql-plugin/src/main/311+-db/scala/org/apache/spark/sql/rapids/shims/GpuFileScanRDD.scala
Labels: bug, P1

#6627 Move spark331 back to list of snapshot shims
  dist/pom.xml
Labels: build

#6613 Update project version to 22.12.0-SNAPSHOT [databricks]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  common/pom.xml
  dist/pom.xml
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#6630 Allow AutoTuner to accept remore path for WorkerInfo
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
Labels: tools

#6606 Print nvidia-smi output when a task fails due to a cuda fatal exception.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: feature request, reliability

#6642 Qualification tool application time calculation can count stages twice if in separate sql queries
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: bug, tools

#6649 Update CUDF_VER to 22.12 for CI [databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
Labels: test, build

#6638 Qualification tool: Print cluster usage tags to csv and log file
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualificationApp.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6641 Fix case where number of shuffle writer threads is set to 0
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#6640 Avoid failing test on cleanup when filesystem has issues
  tests/src/test/320+-noncdh-nondb/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedWriterSuite.scala
Labels: bug, test

#6643 Workflow to add new issues to Github global project [skip ci]
  .github/workflows/add-to-project.yml
Labels: task

#6662 update spark2 code
  scripts/spark2diffs/RapidsConf.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#6657 Add Qualification tool support for running application - per sql output
  docs/spark-qualification-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/ToolTextFileWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateDot.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualificationApp.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationEventProcessor.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/RunningQualificationEventProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6666 Fix resource leaks in regexp_extract_all
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug
