Repository NVIDIA/spark-rapids, pull requests merged in 2022-07, with the labels that each got.

#5940 Qualification tool UI. fix Read-Schema column broken [skip ci]
  tools/src/main/resources/ui/js/uiutils.js
Labels: tools

#5913 Update gcp cluster init option [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#5878 Fix misleading documentation for `approx_percentile` and some other functions
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedExprs.csv
Labels: bug, documentation

#5954 Add IT dockerfile for rockylinux8 [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
Labels: build

#5951 Fix issue with Profiling tool taking a long time due to finding stage ids that maps to sql nodes
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WholeStageExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/EventProcessorBase.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetrics_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/ToolTestUtils.scala
Labels: tools

#5932 Add string split support for limit = 0 and limit =1
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: feature request

#5950 Fix GpuShuffleCoalesce op time metric doesn't include concat batch time
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
Labels: task

#5935 Enable reading double values on GPU when reading CSV and JSON
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#5952 Qualification tool: Parse expressions in ProjectExec
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ProjectExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#5871 Improve regular expression error messages
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#5971 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#5915 Make the error message of changing decimal type the same as Spark's [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/320until330-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: task

#5955 Fix fake memory leaks in some test cases [databricks]
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: task

#5974 Remove scaladoc warning
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: documentation

#5976 Enable null in regex character classes
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5972 [DOC] add app-details to qualification tools doc [skip ci]
  docs/img/Tools/qualification-tool-app-view-01.png
  docs/img/Tools/qualification-tool-app-view-02.png
  docs/img/Tools/qualification-tool-app-view-03.png
  docs/img/Tools/qualification-tool-recommendation-header-01.png
  docs/img/Tools/qualification-tool-recommendation-indexview.png
  docs/spark-qualification-tool.md
Labels: documentation, tools

#5982 Use the new native parquet footer API instead of the old one
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: task, tech debt

#5960 Set up the framework of type casting for ORC reading
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/OrcShims311until320Base.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/OrcReadingShims.scala
  sql-plugin/src/main/320+-noncdh/scala/com/nvidia/spark/rapids/shims/OrcShims320untilAllBase.scala
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/OrcShims321CDHBase.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/OrcReadingShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala
Labels: task

#5995 Fix a minor potential issue when rebatching for GpuArrowEvalPythonExec
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: bug

#5968 Add support for regexp_extract_all on GPU
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5997 support testing parquet encryption
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: build

#6008 Rename test modes in spark-tests.sh [skip ci]
  jenkins/spark-tests.sh
Labels: test

#5903 Avoid requiring single batch when using out-of-core sort
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommand.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
Labels: task

#6009 Fix issue where spark-tests was producing an unintended error code
  jenkins/spark-tests.sh
Labels: test

#5776 Enable regular expression support based on whether UTF-8 is in the current locale
  docs/compatibility.md
  integration_tests/pytest.ini
  integration_tests/src/main/python/regexp_no_unicode_test.py
  integration_tests/src/main/python/regexp_test.py
  integration_tests/src/main/python/string_test.py
  jenkins/spark-premerge-build.sh
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ConditionalsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5994 Skip Parquet encryption read tests if Parquet version is less than 1.12 [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: bug

#6010 Update docs to better explain limitations of Dataset support
  docs/FAQ.md
Labels: documentation

#6025 Skip Iceberg tests on Databricks [databricks]
  integration_tests/src/main/python/conftest.py
Labels: test

#6020 Unify test modes in databricks test script [databricks]
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
Labels: test

#5988 [FEA] Add a progress bar in Qualification tool when it is running
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ui/ConsoleProgressBar.scala
Labels: tools

#6030 Cleans up some of the redundant code in proxy/internal RAPIDS Shuffle Managers [databricks]
  dist/unshimmed-common-from-spark311.txt
  sql-plugin/src/main/311-nondb/scala/org/apache/spark/sql/rapids/shims/spark311/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/312-nondb/scala/org/apache/spark/sql/rapids/shims/spark312/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/312db/scala/org/apache/spark/sql/rapids/shims/spark312db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/313/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/314/scala/org/apache/spark/sql/rapids/shims/spark314/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/320/scala/org/apache/spark/sql/rapids/shims/spark320/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/321/scala/org/apache/spark/sql/rapids/shims/spark321/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/321cdh/scala/org/apache/spark/sql/rapids/shims/spark321cdh/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/spark321db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/322/scala/org/apache/spark/sql/rapids/shims/spark322/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/330/scala/org/apache/spark/sql/rapids/shims/spark330/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/331/scala/org/apache/spark/sql/rapids/shims/spark331/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/340/scala/org/apache/spark/sql/rapids/shims/spark340/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: shuffle, task

#6033 Refactor: Fix PCBS does not fully follow the pattern for public classes
  sql-plugin/src/main/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: task

#6031 Update spark322shim dependency to released lib
  CONTRIBUTING.md
  build/buildall
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  jenkins/spark-premerge-build.sh
  pom.xml
  sql-plugin/src/main/322/scala/com/nvidia/spark/rapids/shims/spark322/SparkShimServiceProvider.scala
Labels: build

#6000 Support nth_value, first and last in window context
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5970 Address feedback in "Improve regular expression error messages" PR
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: task

#6041 Improve check for UTF-8 in integration tests by testing from the JVM
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/qa_nightly_select_test.py
  integration_tests/src/main/python/qa_nightly_sql.py
  integration_tests/src/main/python/regexp_no_unicode_test.py
  integration_tests/src/main/python/regexp_test.py
  integration_tests/src/main/python/spark_session.py
Labels: bug, test

#6042 Qualification tool: Parse expressions in Aggregates and Sort execs.
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/HashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ObjectHashAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortAggregateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#6049 Fix test hang caused by parquet hadoop test jar log4j file
  integration_tests/run_pyspark_from_build.sh
Labels: test

#6078 Temporarily disable Parquet unsigned int test in ParquetScanSuite
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
Labels: test

#6058 Disable zstd orc tests in cdh
  integration_tests/src/main/python/orc_test.py
Labels: bug, test

#6082 Enable auto-merge from branch-22.08 to branch-22.10 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#6004 Check the existence of alluxio path
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
Labels: task

#5925 Add Alluxio auto mount feature
  docs/configs.md
  docs/get-started/getting-started-alluxio.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#5941 GPU accelerate Apache Iceberg reads
  NOTICE
  NOTICE-binary
  dist/unshimmed-from-each-spark3xx.txt
  docs/additional-functionality/iceberg-support.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/iceberg_test.py
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/311until320-all/java/com/nvidia/spark/rapids/shims/ShimSupportsRuntimeFiltering.java
  sql-plugin/src/main/320+/java/com/nvidia/spark/rapids/shims/ShimSupportsRuntimeFiltering.java
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/IcebergProvider.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/IcebergProviderImpl.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/data/GpuDeleteFilter.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ApplyNameMapping.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquet.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetConversions.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetDictionaryRowGroupFilter.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetIO.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetMetricsRowGroupFilter.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetSchemaUtil.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetTypeVisitor.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/ParquetUtil.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/TypeWithSchemaVisitor.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/Spark3Util.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkConfParser.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkFilters.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkReadConf.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkReadOptions.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkSQLProperties.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkSchemaUtil.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/SparkUtil.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/TypeToSparkType.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/BaseDataReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuBatchDataReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuIcebergReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkBatchQueryScan.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/SparkBatch.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/Stats.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionedFileUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AvroProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request

#6048 Port whole parsePartitions method from Spark3.3 to Gpu side
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/320until330-all/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/util/rapids/DateFormatter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
Labels: bug

#6090 Add missing is_spark_321cdh import in orc_test
  integration_tests/src/main/python/orc_test.py
Labels: test

#6057 Tag `GpuWindow` child expressions for GPU execution
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: bug

#6097 [databricks] Fix 3.3 shim to include castTo handling AnyTimestampType and minor spacing
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
Labels: bug

#6098 Support Apache Iceberg 0.14.0
  docs/additional-functionality/iceberg-support.md
  integration_tests/src/main/python/iceberg_test.py
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
  pom.xml
Labels: feature request

#6107 Disable snapshot shims build in 22.08
  integration_tests/src/main/python/map_test.py
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: test, build

#6104 Revert to only supporting Apache Iceberg 0.13.x
  docs/additional-functionality/iceberg-support.md
  jenkins/databricks/test.sh
  jenkins/spark-tests.sh
  pom.xml
Labels: feature request

#6092 Qualification tool output recommendations on a per sql query basis
  docs/spark-qualification-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileUtils.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationMain.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/RunningQualificationApp.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
  tools/src/test/resources/QualificationExpectations/nds_q86_fail_test_expectation_persql.csv
  tools/src/test/resources/QualificationExpectations/nds_q86_test_expectation_persql.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation_persql.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#5998 Enable Strings as a supported type for GpuColumnarToRow transitions
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/CudfUnsafeRow.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/JCudfUtil.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JCudfUtilSuite.scala
Labels: feature request, performance

#6040 Enable anchors in regexp string split
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#6106 Qualification tool: Parse expressions in WindowExec
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/WindowExecParser.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#6120 Qualification Tool add test for SQL Description escaping commas for csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: test

#6007 Add doc for parsing expressions in qualification tool [skip ci]
  docs/spark-qualification-tool.md
  tools/src/main/resources/ui/html/index.html
  tools/src/main/resources/ui/html/raw.html
  tools/src/main/resources/ui/html/sql-recommendation.html
  tools/src/main/resources/ui/js/app-report.js
Labels: documentation, tools

#6129 Init 22.10.0-SNAPSHOT [databricks]
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  common/pom.xml
  dist/pom.xml
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
Labels: build

#6133 [DOC]update getting started guide doc for aws-emr670 release[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#6147 Revert "Temporarily disable Parquet unsigned int test in ParquetScanS…
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
Labels: test

#6141 Fixes threaded shuffle writer test mocks for spark 3.3.0+ [databricks]
  tests/src/test/320+-noncdh-nondb/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedWriterSuite.scala
Labels: bug, test, shuffle

#6140 Update profile names in unit tests docs [skip ci]
  docs/dev/testing.md
  integration_tests/README.md
  tests/README.md
Labels: documentation

#6027 Re-enable "transpile complex regex 2" scala test
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test
