Repository NVIDIA/spark-rapids, pull requests merged in 2022-03, with the labels that each got.

#4878 Set conda/mamba default to Python version to 3.8 [skip ci]
  jenkins/databricks/init_cudf_udf.sh
Labels: build

#4890 Integration-test tests jar for hive UDF tests
  integration_tests/pom.xml
  jenkins/databricks/deploy.sh
  jenkins/spark-tests.sh
Labels: bug, build

#4881 Fix compilation error caused by ClusteredDistribution parameters
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuRangePartitioning.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuHashPartitioning.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuRangePartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: build

#4891 update getting started doc because aws-emr 6.5.0 released[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#4901 fix a broken link in CONTRIBUTING.md[skip ci]
  CONTRIBUTING.md
Labels: documentation

#4888 Clean up leak detection code
  dev/host_memory_leaks/README.md
  dev/host_memory_leaks/leak_detect.cpp
Labels: task

#4854 Avoid regexp_cost with stringSplit on the GPU using transpilation
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: performance

#4869 Support for hexadecimal digits in regular expressions on the GPU
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4885 Enable fuzz testing for Regular Expression repetitions and move remaining edge cases to CPU
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4875 Support running `GetArrayStructFields` on GPU[databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: feature request

#4858 Support non-literal index for `GpuElementAt` and `GpuGetArrayItem`[databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ArrayIndexUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/BoolUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: feature request

#4882 Disable write/read Parquet when Parquet field IDs are used
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetFieldIdShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/ParquetFieldIdShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
Labels: audit_3.3.0

#4871 Minor changes to print revision differences when building shims
  dist/scripts/check-shims-revisions.sh
Labels: build

#4904 Relocate Hive UDF Classes
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/java/com/nvidia/spark/rapids/tests/udf/hive/EmptyHiveGenericUDF.java
  integration_tests/src/main/java/com/nvidia/spark/rapids/tests/udf/hive/EmptyHiveSimpleUDF.java
  jenkins/databricks/deploy.sh
  jenkins/spark-tests.sh
Labels: build

#4872 Speed up copying decimal column from parquet buffer to GPU buffer
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnarCopyHelper.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: performance

#4859 Aggregate (Min/Max/Count) push down for ORC
  integration_tests/src/main/python/orc_test.py
  pom.xml
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsOrcScanMeta.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsParquetScanMeta.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301until320Shims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/RapidsCsvScanMeta.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsOrcScanMeta.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsParquetScanMeta.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/RapidsOrcScanMeta.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/RapidsParquetScanMeta.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
Labels: audit_3.3.0

#4825 Initial support for reading decimal types from JSON and CSV
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/decimals.csv
  integration_tests/src/test/resources/decimals.json
  integration_tests/src/test/resources/nan_and_inf.json
  integration_tests/src/test/resources/nan_and_inf_edge_cases.json
  integration_tests/src/test/resources/nan_and_inf_invalid.json
  integration_tests/src/test/resources/nan_and_inf_strings.json
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request

#4880 Bump hadoop-client dependency to 3.1.4
  tools/pom.xml
Labels: build

#4856 Enable shim tests in sql-plugin module
  pom.xml
Labels: bug

#4810 Support ANSI intervals to/from Parquet
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuTypeShims.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/rapids/shims/v2/datetimeExpressions.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: audit_3.3.0

#4899 Fixed Decimal 128 bug in ParquetCachedBatchSerializer
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
Labels: bug

#4796 Implement ExistenceJoin Iterator using an auxiliary left semijoin
  docs/configs.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: task

#4919 Case-insensitive PR title check [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4917 Default some configs to protect against cluster settings in integration tests
  integration_tests/src/main/python/spark_session.py
Labels: test

#4921 Add DatabricksShimVersion to unshimmed class list [databricks]
  dist/unshimmed-common-from-spark301.txt
Labels: bug

#4861 Add Apache Spark 3.1.4-SNAPSHOT Shims
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/314/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/314/scala/com/nvidia/spark/rapids/shims/spark314/SparkShimServiceProvider.scala
  sql-plugin/src/main/314/scala/com/nvidia/spark/rapids/spark314/RapidsShuffleManager.scala
  sql-plugin/src/main/314/scala/org/apache/spark/sql/rapids/shims/spark314/RapidsShuffleInternalManager.scala
Labels: feature request

#4930 Add in support for sorting arrays with structs in sort_array
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#4923 Support GpuScalarSubquery on nested types
  docs/supported_ops.md
  integration_tests/src/main/python/subquery_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: performance

#4942 Fix window rank integration tests on [databricks]
  integration_tests/src/main/python/window_function_test.py
Labels: test

#4934 Replace MetadataAttribute with FileSourceMetadataAttribute to follow the update in Spark for 3.3.0+
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
Labels: audit_3.3.0

#4926 Support `DayTimeIntervalType` in `ParquetCachedBatchSerializer`[databricks]
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: audit_3.3.0

#4941 Use new list reduction API to improve performance
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: performance

#4952 Have a fixed GPU memory size for integration tests [databricks]
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: test

#4946 Support predictors on ANSI day time interval type
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: audit_3.3.0

#4965 Documentation: add example python api call for ExplainPlan.explainPotentialGpuPlan [skip ci]
  docs/get-started/getting-started-workload-qualification.md
Labels: documentation

#4927 Support reading ANSI day time interval type from CSV source
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  tests/pom.xml
  tests/src/test/330/scala/com/nvidia/spark/rapids/CsvScanForIntervalSuite.scala
  tests/src/test/resources/day-time-interval-to-be-fix.csv
  tests/src/test/resources/day-time-interval.csv
Labels: audit_3.3.0

#4977 Add missing 314 to buildall script
  build/buildall
Labels: build

#4907 Add markdown check action
  .github/workflows/markdown-links-check.yml
  .github/workflows/markdown-links-check/markdown-links-check-config.json
Labels: documentation, build

#4944 Support for non-string key-types for `GetMapValue` and `element_at()`
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: feature request

#4933 Set OrcConf.INCLUDE_COLUMNS for ORC reading
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
Labels: audit_3.2.0

#4958 Add independent mvn verify check [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: build

#4990 Remove 30X permerge support for version 22.04 and above [skip ci]
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4994 Add databricks 10.4 build in pre-merge [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4955 Add UDT support to ParquetCachedBatchSerializer (CPU)
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/PCBSSchemaHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#4973 Implement support for ArrayExists expression
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
Labels: feature request

#4981 Update doc for CSV reading interval
  docs/compatibility.md
Labels: documentation

#4995 Include 321db shim in distribution build [skip ci]
  dist/pom.xml
  jenkins/spark-nightly-build.sh
Labels: build

#4999 Enable automerge from branch-22.04 to branch-22.06 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#4998 Added the id back for struct children to make them unique [databricks]
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/PCBSSchemaHelper.scala
Labels: bug

#4971 Fall back to the CPU for non-zero scale on Ceil or Floor functions [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until330-all/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: bug, audit_3.3.0

#5004 Add ClouderaShimVersion to unshimmed files
  dist/unshimmed-common-from-spark311.txt
Labels: bug

#5009 Remove references of `shims` folder in docs [skip ci]
  CONTRIBUTING.md
  docs/dev/shims.md
Labels: documentation

#4956 Add avro reader support [databricks]
  dist/pom.xml
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/avro_test.py
  jenkins/databricks/build.sh
  jenkins/spark-premerge-build.sh
  sql-plugin/pom.xml
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/sql/rapids/shims/AvroUtils.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/sql/rapids/shims/AvroUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroDataReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuReadAvroFileFormat.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request

#5007 Remove schema utils, case class copying, file partition, and legacy statistical aggregate shims [databricks]
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/shims/GpuSchemaUtils.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: task

#5010 Unshim GpuSumDefaults [databricks]
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/rapids/aggregate/GpuSum.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: task

#5012 Unshim GpuOrcScan and GpuParquetScan [databricks]
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/GpuOrcScan.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/GpuParquetScan.scala
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/RapidsOrcScanMeta.scala
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/RapidsParquetScanMeta.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/RapidsOrcScanMeta.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/RapidsParquetScanMeta.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RapidsOrcScanMeta.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RapidsParquetScanMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadOrcFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: task

#5013 Unshim GpuRowBasedScalaUDF [databricks]
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/GpuRowBasedScalaUDF.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
Labels: task

#5026 Update RoCE doc URL [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#5022 Unshim many Pandas execs [databricks]
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: task

#5033 Removed limit from the test
  integration_tests/src/main/python/cache_test.py
Labels: test

#5040 Fix missing imports for 321db shim [databricks]
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/catalyst/csv/GpuCsvUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
Labels: build

#4993 PCBS and Parquet support ANSI year month interval type [databricks]
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/330/scala/com/nvidia/spark/rapids/IntervalSuite.scala
Labels: audit_3.2.0, audit_3.3.0

#5042 Implement hasSideEffects for GpuSequence
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: bug

#4972 Add support for ORC forced positional evolution
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/OrcShims311until320Base.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
Labels: audit_3.2.0

#5059 Fix merge from 22.04 to 22.06
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/OrcShims311until320Base.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: build

#5030 Fix regression from 21.12 where udfs defined in repl no longer worked
  udf-compiler/src/main/scala/com/nvidia/spark/udf/LambdaReflection.scala
Labels: bug

#5046 Init 22.06.0-SNAPSHOT [databricks]
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  common/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
Labels: build

#5066 Add getOrcSchemaString for OrcShims [databricks]
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/OrcShims311until320Base.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/OrcShims320untilAllBase.scala
  sql-plugin/src/main/320until330-all/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: bug

#5077 Change Scala style continuation indentation to be 2 spaces to match guide [skip ci]
  docs/dev/idea-code-style-settings.xml
Labels: task

#5073 Add in nvtx ranges for parquet filterBlocks
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: performance

#4961 Support approx_percentile in reduction context
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuApproximatePercentile.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
Labels: cudf_dependency

#5083 Remove EMRShimVersion
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/VersionUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: tech debt

#5067 Premerge databricks CI autotrigger [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#5094 Fix profiling tool reading collectionAccumulator
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools
