Repository NVIDIA/spark-rapids, pull requests merged in 2022-08, with the labels that each got.

#6055 Add tests for .count() in the file readers
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
Labels: test

#6136 Fix Alluxio inferring partitions for BooleanType with Hive
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
Labels: bug

#6071 Update `test_add_overflow_with_ansi_enabled` and `test_subtraction_overflow_with_ansi_enabled` to check the exception type for Integral case.
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#6103 Fix crash when casting decimals to long
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
Labels: bug

#6162 Remove hard-coded versions from buildall [skip ci]
  build/buildall
Labels: build

#6166 Update the configs used to choose the Python runner for flat-map Pandas UDF [databricks]
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuFlatMapGroupsInPandasExec.scala
Labels: bug

#6181 Fix the qualification tool per sql number output rows option
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualOutputWriter.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6159 Workaround for Databricks using AQE even when disabled
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/AQEUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PlanUtils.scala
Labels: bug

#5946 GpuGlobalLimitExec and GpuCollectLimitExec support offset
  integration_tests/src/main/python/limit_test.py
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/GlobalLimitShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
Labels: task

#6189 Qualification UI change floating precision [skip ci]
  tools/src/main/resources/ui/js/uiutils.js
Labels: tools

#6156 Fix Bloop project generation in buildall [skip ci]
  .gitignore
  CONTRIBUTING.md
  build/buildall
Labels: documentation, build

#5958 Add set based operations for arrays: `array_intersect`, `array_union`, `array_except`, and `arrays_overlap` for running on GPU
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request, SQL, cudf_dependency

#6152 Improve coverage in mvn verify check github workflow
  .github/workflows/mvn-verify-check.yml
  pom.xml
Labels: build, task

#6013 Add fixed issues to regex fuzzer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#6210 Fix merge conflict with branch-22.08
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/test/resources/test_orc_varchar.orc
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: build

#6132 [DOC]update outofdate mortgage notebooks and update docs for xgboost161 jar[skip ci]
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/GCP/Mortgage-ETL-CPU.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.zpln
  docs/demo/gpu-mortgage_accelerated.ipynb
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#6218 Disable overflow tableInsert tests for 331+
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
Labels: test

#6223 Temporary fix for test_array_intersect failures on Spark 3.3.0 [databricks]
  integration_tests/src/main/python/array_test.py
Labels: test

#6211 Added in very specific support for from_json to a Map<String,String>
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request, SQL, cudf_dependency

#6194 Make dist jar compression opt-out optional
  CONTRIBUTING.md
  build/buildall
  dist/pom.xml
  pom.xml
Labels: build

#6227 Configurable task failures in integration tests
  integration_tests/run_pyspark_from_build.sh
Labels: test, task

#6216 [Doc] Update 22.08 documentation
  docs/FAQ.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/img/spark3cluster.png
  docs/spark-profiling-tool.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#6225 Fix count() in avro failed when reader_types is coalescing
  integration_tests/src/main/python/avro_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: bug

#6110 Iceberg Parquet supports multi-threaded reading.
  integration_tests/src/main/python/iceberg_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquet.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuIcebergReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/SparkBatch.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInputFileBlock.scala
Labels: feature request

#6235 Fix merge conflict with branch-22.08
  docs/FAQ.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/img/spark3cluster.png
  docs/spark-profiling-tool.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: build

#6222 Init 22.08 changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_21.06_to_21.12.md
  scripts/generate-changelog
Labels: documentation

#6161 Added binary read support for Parquet [Databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  tools/src/main/resources/supportedDataSource.csv
  tools/src/main/resources/supportedExecs.csv
Labels: feature request

#6215 Update Spark2 Explain API code for 22.08
  scripts/rundiffspark2.sh
  scripts/spark2diffs/GpuBaseWindowExecMeta.diff
  scripts/spark2diffs/GpuCSVScan.diff
  scripts/spark2diffs/GpuHiveOverrides.diff
  scripts/spark2diffs/GpuJsonScan.diff
  scripts/spark2diffs/GpuOrcFileFormat.diff
  scripts/spark2diffs/GpuOrcScanBase.diff
  scripts/spark2diffs/GpuOverrides.diff
  scripts/spark2diffs/GpuParquetFileFormat.diff
  scripts/spark2diffs/GpuParquetScanBase.diff
  scripts/spark2diffs/GpuRegExpExtractMeta.diff
  scripts/spark2diffs/GpuRegExpReplaceMeta.diff
  scripts/spark2diffs/GpuRegExpUtils.diff
  scripts/spark2diffs/GpuStringSplitMeta.diff
  scripts/spark2diffs/GpuToTimestamp.diff
  scripts/spark2diffs/HiveProviderImpl.diff
  scripts/spark2diffs/ParquetFieldIdShims.diff
  scripts/spark2diffs/RapidsConf.diff
  scripts/spark2diffs/RapidsMeta.diff
  scripts/spark2diffs/RegexParser.diff
  scripts/spark2diffs/TypeChecks.diff
  scripts/spark2diffs/UnixTimeExprMeta.diff
  scripts/spark2diffs/aggregate.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregateMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/ParquetFieldIdShims.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressionsMeta.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringMeta.scala
Labels: tools

#6079 Add support for nested types to `collect_set(...)` on the GPU [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#6237 Preserve underscore in executorEnv in integration tests
  integration_tests/src/main/python/spark_init_internal.py
Labels: test

#6248 Fix some issues with reading binary from parquet
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
  tools/src/main/resources/supportedExecs.csv
  tools/src/main/resources/supportedExprs.csv
Labels: bug, SQL, P1

#6203 Add config option to log all query transformations
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#6250 Fix bug where AQE does not respect `entirePlanWillNotWork`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: bug

#5989 Add `NaN` handling in `GpuMax`
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tools/src/main/resources/supportedExprs.csv
Labels: task

#6292 Fix parquet binary reads to do the transformation in the plugin [databricks]
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
Labels: bug, feature request, SQL, P1, task

#6297 Fix merge conflict with branch-22.08
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
Labels: build

#6062 Nested struct binary comparison operator support
  docs/supported_ops.md
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedExprs.csv
Labels: task

#6305 Increase robustness of MVN commands in pre-merge scripts [databricks]
  jenkins/databricks/build.sh
  jenkins/spark-premerge-build.sh
Labels: build

#6006 Estimate and validate regular expression complexities
  docs/configs.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexComplexityEstimator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: task

#6318 [BugFix]Change the RapidsDiskBlockManager in ShuffleBufferCatalog to guarantee the shuffle files can be cleaned successfully
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSinglePartitioningSuite.scala
Labels: bug, shuffle

#6314 Increase robustness of mvn commands in nightly scripts
  build/buildall
  jenkins/databricks/deploy.sh
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-tests.sh
Labels: build

#6256 [Bug] Add Expr OverflowInTableInsert to fix AnsiCastOpSuite
  pom.xml
  sql-plugin/src/main/331+/scala/com/nvidia/spark/rapids/shims/Spark331PlusShims.scala
  sql-plugin/src/main/331+/scala/org/apache/spark/sql/rapids/GpuCheckOverflowInTableInsert.scala
  sql-plugin/src/main/331/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#6316 Add Nan handling for `GpuArrayMax`
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#6311 Re-implement cast timestamp to string and add more tests
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug

#6044 [BUG] Fix IT discrepancy which depending on TEST_PARALLEL
  integration_tests/run_pyspark_from_build.sh
Labels: test

#6333 Make run_pyspark to report fail and error as default [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: test

#5646 Use Spark's `Utils.getContextOrSparkClassLoader` to load Shims [databricks]
  CONTRIBUTING.md
  dist/unshimmed-common-from-spark311.txt
  jenkins/databricks/test.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/UnshimmedTrampolineUtil.scala
Labels: build, task

#5981 Run Delta Lake tests with Spark 3.2.x
  integration_tests/src/main/python/delta_lake_test.py
  jenkins/spark-tests.sh
Labels: test

#6307 Add more infomation in FileSourceScanExec log when timezone is not UTC
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: task

#6234 [Doc] Add 22.08 docs' links [skip ci]
  docs/download.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#6335 Add missing subnet option to dataproc cluster example [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#6286 Change `TimestampGen` unit in integration test from millisecond to microsecond
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test, P1, improve

#6342 Avoid passing duplicate conf to spark_init_internal [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: bug, test

#6348 Update plugin jni version to released 22.08.0 [databricks]
  pom.xml
Labels: build

#6354 Update 22.08 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#6356 Fix auto merge conflict 6353 [skip ci]
  CHANGELOG.md
Labels: build

#6338 Adding AutoTuner to Profiling Tool
  tools/pom.xml
  tools/scripts/discoveryScript.sh
  tools/scripts/getWorkerInfo.sh
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AnalysisSuite.scala
Labels: tools

#6367 Revert "Enable Strings as a supported type for GpuColumnarToRow transitions"
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/CudfUnsafeRow.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/JCudfUtil.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JCudfUtilSuite.scala
Labels: task

#6271 Add format `SSS` for `date_format` function
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request, SQL, P1

#6365 Honor delta_lake marker for pytest [databricks]
  integration_tests/README.md
  integration_tests/pytest.ini
  integration_tests/src/main/python/conftest.py
Labels: bug, test

#6350 Allow writing Binary data in Parquet
  docs/supported_ops.md
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala
  tools/src/main/resources/supportedExecs.csv
Labels: SQL, task

#6306 Struct null aware equality comparator <=> support
  docs/supported_ops.md
  integration_tests/src/main/python/cmp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedExprs.csv
Labels: task

#6361 Binary type support in Iceberg read
  docs/supported_ops.md
  integration_tests/src/main/python/iceberg_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: task

#6371 Fix datetime name collision in cast_test
  integration_tests/src/main/python/cast_test.py
Labels: test

#6376 Update 22.08 changelog to latest
  CHANGELOG.md
Labels: documentation

#6349 Add `Nan` handling in `GpuArrayMin`
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#6378 Merge Branch 22.08 to main [skip ci]
  CHANGELOG.md
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/CudfUnsafeRow.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/JCudfUtil.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JCudfUtilSuite.scala
Labels: build

#6374 Remove anthony-chang [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#6393 Add zip&unzip in pre-merge dockerfile [databricks]
  integration_tests/run_pyspark_from_build.sh
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/test.sh
Labels: test

#6387 Use new custom kernel for large decimal multiply
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: SQL, task

#6358 Support _ in spark conf of integration tests
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/main/python/spark_session.py
  jenkins/spark-tests.sh
Labels: bug, test

#6379 Rebalance time of parallel stages for pre-merge CI
  .github/workflows/mvn-verify-check.yml
  integration_tests/src/main/python/explain_test.py
  integration_tests/src/main/python/join_test.py
  jenkins/spark-premerge-build.sh
Labels: test

#6407 Remove empty unreferenced file unshimmed-spark311.txt
  dist/unshimmed-spark311.txt
Labels: build, task

#6409 Fix test_dpp_from_swizzled_hash_keys on CDH
  integration_tests/src/main/python/dpp_test.py
Labels: test

#6396 Make the variable "BASE_SPARK_VERSION" consistent [databricks]
  jenkins/databricks/run-tests.py
  jenkins/databricks/test.sh
Labels: build

#6398 Fix DecimalGen to generate full range and fix failing test cases
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/expand_exec_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tools/src/main/resources/supportedExprs.csv
Labels: bug

#6410 Fix handling of older array encodings in Parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
Labels: bug

#6418 Fix tests for DateTimeInterval that were overflowing on CPU
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: bug, test

#6405 Support more timestamp format when casting string to timestamp
  docs/compatibility.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: feature request, SQL, P1, task, cudf_dependency

#6290 Add `GpuMapConcat` support for nested type keys.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CollectionOpSuite.scala
Labels: task

#6370 Support simple pass-through for `FromUTCTimestamp`
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request, SQL, P1

#6273 Support bool/int8/int16/int32/int64 castings for ORC reading.
  integration_tests/src/main/python/orc_cast_test.py
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: task

#6441 Skip decimal gens that overflow on Spark 3.3.0+
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#6448 Revert patch that caused failing test on databricks 321 [databricks]
  integration_tests/src/main/python/orc_cast_test.py
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#6414 Add support for full 128-bit decimal divide
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  tools/src/main/resources/supportedExprs.csv
Labels: SQL, task

#6449 Remove caching of needles in GpuInSet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuInSet.scala
Labels: bug

#6251 Add `Nan` handling in the `GpuMin`
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tools/src/main/resources/supportedExprs.csv
Labels: task

#6439 Fix leaks in GpuShuffledHashJoinExecSuite
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
Labels: bug, test

#6457 Reading delta log Table Checkpoint files should fallback the entire plan
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: task

#6458 Change some Alluxio log messages to be debug
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
Labels: task

#6450 Add new github ID to blossom-ci allow list [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#6422 Iceberg supports coalescing reading for Parquet
  integration_tests/src/main/python/iceberg_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/IcebergProvider.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/IcebergProviderImpl.scala
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkBatchQueryScan.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/SparkBatch.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: performance

#6454 Support bool/int8/16/32/64 castings for ORC reading [databricks]
  integration_tests/src/main/python/orc_cast_test.py
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/OrcCastingShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: task

#6462 Increase stability of pytest run with PVC storage
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: bug, test

#6434 Install reduced pom for dist module
  dist/pom.xml
Labels: bug, build
