Repository NVIDIA/spark-rapids, pull requests merged in 2022-10, with the labels that each got.

#6583 Update the `GpuSingleDirectoryDataWriter` and `GpuDynamicDirectorySingleDataWriter` to split ColumnarBatch when writing to match the `maxRecordsPerFile`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: bug

#6604 Make broadcast tables spillable
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SerializationSuite.scala
Labels: task

#6667 Retain all heap dumps per JVM lifecycle
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug

#6675 Adding error handling to print help out when at end of command
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/QualificationArgs.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6631 Fixes split estimation in explode/explode_outer [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuGenerateSuite.scala
Labels: cudf_dependency, reliability

#6679 Revert "Add support for arrays in hashaggregate [databricks] (#6066)"
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  tools/src/main/resources/supportedExprs.csv
Labels: bug

#6616 String to decimal casting custom kernel
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
Labels: feature request, performance

#6652 Revise AutoTuner to match the BootStrap tool
  tools/scripts/discoveryScript.sh
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AutoTunerSuite.scala
Labels: tools

#6690 Update spark2 code for Revert "Add support for arrays in hashaggregate"
  scripts/spark2diffs/GpuOverrides.diff
  scripts/spark2diffs/aggregate.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: tools

#6670 [Doc]Add 22.10 download page[skip ci]
  docs/FAQ.md
  docs/archive.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
Labels: documentation

#6691 Fix validity checks for large decimal window bounds
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: bug

#6704 Removing --help tools tests that trigger System.exit()
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6697 Fix AutoTuner yaml error handling and discovery script rounding
  tools/scripts/discoveryScript.sh
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AutoTunerSuite.scala
Labels: tools

#6701 Add AutoTuner documentation [skip ci]
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
Labels: documentation, P1, tools

#6644 Simplify how we transpile negated character classes and add more tests
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#6721 Fix a couple of markdown links that are now permanently moved [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#6719 Document that we test on JDK8 and JDK11, other versions are untested [skip ci]
  CONTRIBUTING.md
Labels: documentation

#6695 [Doc] Adding Dataproc quick start steps to use new user tools package [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#6724 Qualification tool: Read SQL function names for parsing expressions
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: bug, tools

#6728 Disable maven-compiler-plugin
  pom.xml
Labels: build

#6729 Fix NullPointerException in iceberg schema parsing code when selecting single column
  integration_tests/src/main/python/iceberg_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
Labels: bug, P1

#6717 Qualification tool: Parse expressions in Expand, Generate and TakeOrderedAndProject Execs
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ExpandExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/GenerateExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/TakeOrderedAndProjectExecParser.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#6742 Rework for adding event log info for profiler output
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationSummaryInfo.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#6681 Fixes for more efficient bound checks for GpuCast [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: performance

#6750 Enabling decimal 38,2 casting
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCastMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug, P1

#6743 Add spark-rapids pulls to GitHub project [skip ci]
  .github/workflows/add-to-project.yml
Labels: task

#6756 Temporarily xfail failing test_iceberg_parquet_read_round_trip test
  integration_tests/src/main/python/iceberg_test.py
Labels: test

#6703 Docker container for ease of deployment to Databricks [skip ci]
  docker/databricks/00-custom-spark-driver-defaults.conf
  docker/databricks/Dockerfile
  docker/databricks/README.md
  docker/databricks/build.sh
  docker/databricks/ganglia/ganglia.conf
  docker/databricks/ganglia/gconf/conf.d/modpython.conf
  docker/databricks/ganglia/gconf/databricks-gmond.conf
  docker/databricks/ganglia/gconf/gmetad.conf
  docker/databricks/ganglia/gconf/gmond.conf
  docker/databricks/ganglia/start_spark_slave.sh
  docker/databricks/init.sh
  docker/databricks/requirements_10.4ML.txt
  docker/databricks/scripts/monit
  docker/databricks/webterminal/setup_ttyd_daemon.sh
  docker/databricks/webterminal/start_ttyd_daemon.sh
  docker/databricks/webterminal/stop_ttyd_daemon.sh
  docker/databricks/webterminal/webTerminalBashrc
Labels: feature request

#6730 Fix an unchecked conversion warning
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
Labels: task

#6726 Provision hive scratch dir before test execution
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug

#6765 [DOC] Add gcp dataproc gpu limit [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#6760 Clean run directory before running tests in run_pyspark_from_build
  integration_tests/run_pyspark_from_build.sh
Labels: test

#6767 Avoid any issues with scalar values returned by evalColumnar [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
Labels: bug

#6772 [Doc]remove group on array in 22.10, target in 22.12[skip ci]
  docs/download.md
Labels: documentation

#6754 [Doc] update getting started guide for emr 6.8.0 release[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#6770 Revert "Docker container for ease of deployment to Databricks [skip ci]"
  docker/databricks/00-custom-spark-driver-defaults.conf
  docker/databricks/Dockerfile
  docker/databricks/README.md
  docker/databricks/build.sh
  docker/databricks/ganglia/ganglia.conf
  docker/databricks/ganglia/gconf/conf.d/modpython.conf
  docker/databricks/ganglia/gconf/databricks-gmond.conf
  docker/databricks/ganglia/gconf/gmetad.conf
  docker/databricks/ganglia/gconf/gmond.conf
  docker/databricks/ganglia/start_spark_slave.sh
  docker/databricks/init.sh
  docker/databricks/requirements_10.4ML.txt
  docker/databricks/scripts/monit
  docker/databricks/webterminal/setup_ttyd_daemon.sh
  docker/databricks/webterminal/start_ttyd_daemon.sh
  docker/databricks/webterminal/stop_ttyd_daemon.sh
  docker/databricks/webterminal/webTerminalBashrc
Labels: task

#6734 Init 22.10 changelog [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#6763 Fix a class casting error in concurrent writer when enabling AQE [databricks]
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: bug

#6783 Revert "Temporarily xfail failing test_iceberg_parquet_read_round_trip test"
  integration_tests/src/main/python/iceberg_test.py
Labels: test

#6751 Support columnar processing for FlatMapCoGroupInPandas[databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/311+-db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
  sql-plugin/src/main/311+-db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/311+-nondb/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/320+/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/python/rapids/GpuPandasUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapCoGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExecs.csv
Labels: task

#6755 [doc] Add diagnostic tool section to GCP Dataproc getting started page [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#6799 Update JNI version to released 22.10.0 [databricks]
  pom.xml
Labels: build

#6803 Updated 22.10 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#6809 Relocate Scala files placed in the java/ directory
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnCastUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProviderImpl.scala
Labels: build

#6821 [Doc]update download links for branch-22.10 release in main branch[skip ci]
  docs/download.md
Labels: documentation

#6766 Adding timestamp functions into potential problems for qual tool
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppBase.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/QualificationSuite.scala
Labels: tools

#6815 Update castPartValue function to fix ClassCastException
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
Labels: audit

#6810 Dump stack traces for tasks with the semaphore held when OOM goes unhandled
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
Labels: reliability

#6819 Move the `RapidsShuffleThreadedReader` from 330~340 shims to 330+ shims
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedReader.scala
Labels: audit_3.4.0

#6826 Place hive scratch files under pytest $RUN_DIR
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, test

#6852 Fix deprecated Github actions API [skip ci]
  .github/workflows/add-to-project.yml
  .github/workflows/auto-merge.yml
  .github/workflows/blossom-ci.yml
  .github/workflows/mvn-verify-check.yml
  .github/workflows/signoff-check.yml
Labels: bug, build

#6847 Fix integration builds failing with current directory not found
  integration_tests/run_pyspark_from_build.sh
Labels: build

#6855 Add the `FileIndexOptions` shims for Spark340
  pom.xml
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/FileIndexOptionsShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/FileIndexOptionsShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
Labels: audit_3.4.0

#6859 Reduce memory usage in aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: reliability

#6849 Cuda.deviceSynchronize as a last resort if we cannot spill enough
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandlerSuite.scala
Labels: cudf_dependency, reliability

#6861 Add check for is_spark_330cdh and update orc test to skip zstd for cdh
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/spark_session.py
Labels: bug

#6796 Qualification tool: Parse expressions in Join execs
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/BroadcastNestedLoopJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/ShuffledHashJoinExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SortMergeJoinExecParser.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/ToolUtils.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#6813 Move `_databricks_internal` check to shim layer [databricks]
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/DeltaLakeUtils.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/DeltaLakeUtils.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/DeltaLakeUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: task

#6860 Adjust to cudf removal of checks in scatter and repeat
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ExistenceJoin.scala
Labels: build, cudf_dependency

#6857 Fix bug that can not switch Alluxio auto-mount option on the fly
  docs/configs.md
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug

#6873 Add in support for zorder operators on databricks [databricks]
  integration_tests/src/main/python/delta_zorder_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/zorder/GpuHilbertLongIndex.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/zorder/ZOrderRules.scala
Labels: SQL

#6877 Plugin fixes after cuDF removed INT8 for binary columns in parquet writer
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: bug

#6866 Use a unique run directory for each run when testing in run_pyspark_from_build
  integration_tests/run_pyspark_from_build.sh
Labels: test, build

#6876 Fix Spark 3.4 build issues
  pom.xml
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtilsFor330plus.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/SparkUpgradeExceptionShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/FileIndexOptionsShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/GlobalLimitShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ParquetStringPredShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ParquetTimestampNTZShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/ShimFilePartitionReaderFactory.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ParquetCVShims.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/SparkUpgradeExceptionShims.scala
Labels: build, Spark 3.4+

#6827 Follow on from recent regexp fixes to reject patterns that cuDF no longer rejects
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#6891 Remove invalid members from allow list [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#6889 Create target folder before attempting to add unique RUN_DIR [databricks]
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/run-tests.py
Labels: build

#6892 Fix the Spark340 build error related to `mapKeyNotExistError`
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtilsFor330plus.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
Labels: build

#6858 [Doc]Update gh-pages branch for 22.10.0 release[skip ci]
  docs/FAQ.md
  docs/additional-functionality/iceberg-support.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/get-started/yarn-gpu.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#6893 Add different codepoint for unicode 13.0
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
Labels: test

#6757 Add startupOnly tag to configs
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#6907 [Doc]a hot fix for download links versions[skip ci]
  docs/download.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#6833 Flatten simple 4+ nesting of withResource
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: task

#6913 [BUG] GpuPartitioning should close CVs before releasing semaphore
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioningBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRoundRobinPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSinglePartitioning.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
Labels: bug, reliability

#6910 [FEA] Support string Instr function
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#6899 Add ApplicationSummaryInfo wrapper to allow mock tests
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Analysis.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationSummaryInfo.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/AutoTuner.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AutoTunerSuite.scala
Labels: tools

#6905 Fix Spark 340 build error related to `checkForNumericExpr`
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/TypeUtilsShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/TypeUtilsShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: build

#6920 Support Spark 3.3.1
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  jenkins/spark-premerge-build.sh
  pom.xml
  sql-plugin/src/main/331/scala/com/nvidia/spark/rapids/shims/spark331/SparkShimServiceProvider.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: build

#6919 Enable DPP and DPP+AQE on [databricks]
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/shims/GpuSubqueryBroadcastMeta.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/shims/ReuseGpuBroadcastExchangeAndSubquery.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/rapids/execution/shims/GpuSubqueryBroadcastMeta.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/rapids/execution/shims/ReuseGpuBroadcastExchangeAndSubquery.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: feature request

#6918 Added shim for Spark 3.3.2
  dist/pom.xml
  pom.xml
  sql-plugin/src/main/332/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/332/scala/com/nvidia/spark/rapids/shims/spark332/SparkShimServiceProvider.scala
  sql-plugin/src/main/332/scala/com/nvidia/spark/rapids/spark332/RapidsShuffleManager.scala
  sql-plugin/src/main/332/scala/org/apache/spark/sql/rapids/shims/spark332/RapidsShuffleInternalManager.scala
Labels: build

#6824 Use alluxio Java API to mount instead of cmd [databricks]
  docs/configs.md
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioCfgUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: task

#6936 Fixing exception when appStartInfo isn't available due to incomplete event log
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/AppFilterSuite.scala
Labels: tools

#6925 Only warn when hive scratch creation fails
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, task

#6938 Spark-3.4 - Fix build errors in DataSourceStrategy and SparkDateTimeException
  sql-plugin/src/main/320until340-all/scala/org/apache/spark/sql/execution/datasources/rapids/DataSourceStrategyUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/AnsiUtil.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/rapids/ShimTrampolineUtil.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/rapids/ShimTrampolineUtil.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/execution/datasources/rapids/DataSourceStrategyUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
Labels: build, Spark 3.4+

#6944 Update to a valid cuda docker image for k8s run [skip ci]
  docs/get-started/Dockerfile.cuda
Labels: documentation

#6953 Remove unsupported format when converting dates/timestamps to strings [skip ci]
  docs/compatibility.md
Labels: documentation

#6948 Pass through escaped punctuation in Regular Expression Transpiler
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#6956 Throw SparkDateTimeException for invalid cast in Spark3.3+ versions
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/AnsiUtil.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/rapids/ShimTrampolineUtil.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/rapids/ShimTrampolineUtil.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
Labels: bug

#6943 Mechanism to reduce redundancy in Maven profiles for shims [databricks]
  CONTRIBUTING.md
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/ShimSupportsRuntimeFiltering.java
  tests/pom.xml
Labels: build, task
