Repository NVIDIA/spark-rapids, pull requests merged in 2022-06, with the labels that each got.

#5708 Fix shim-related bugs [databricks]
  dist/unshimmed-common-from-spark311.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug, build, task

#5710 Fix auto merge conflict 5709
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: build

#5687 Minor: Clean up GpuConcat
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#5604 ORC encrypted write should fallback to CPU [databricks]
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: task

#5715 Update GPU ORC statistics write support
  docs/compatibility.md
  integration_tests/src/main/python/orc_test.py
Labels: test

#5713 Fix GpuCast losing the timezoneId during canonialization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: bug

#5681 Branch 22.06 nvcomp notice binary [skip ci]
  NOTICE-binary
Labels: documentation

#5725 Fix auto merge conflict 5724
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: build

#5283 Add documentation for MIG on Dataproc [skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#5701 Update docs for qualification tool to reflect recommendations and UI [skip ci]
  docs/img/Tools/qualification-tool-recommendation-header-01.png
  docs/spark-qualification-tool.md
  tools/src/main/resources/ui/html/index.html
  tools/src/main/resources/ui/html/raw.html
Labels: documentation, tools

#5641 [Doc]Update 22.06 documentation[skip ci]
  docs/FAQ.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.zpln
  docs/dev/nvtx_profiling.md
  docs/download.md
  docs/examples.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/tuning-guide.md
Labels: documentation

#5610 Fall back to CPU for unsupported regular expression edge cases with end of line/string anchors and newlines
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#5479 Add support for word boundaries `\b` and `\B`
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5731 Throw SparkDateTimeException for InvalidInput while casting in ANSI mode [databricks]
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/AnsiUtil.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/rapids/ShimTrampolineUtil.scala
Labels: bug

#5450 Handle `?`, `*`, `{0,}` and `{0,n}` based repetitions in regexp_replace on the GPU
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5753 [DOC] Update regexp compatibility for 22.06 [skip ci]
  docs/compatibility.md
Labels: documentation

#5737 Remove the ORC encryption tests [databricks]
  integration_tests/src/main/python/orc_write_test.py
Labels: bug

#5716 Disable Avro support when spark-avro classes not loadable by Shim classloader [databricks]
  docs/FAQ.md
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
Labels: bug

#5746 Init 22.06 changelog [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#5760 Enable avrotest in nightly tests [skip ci]
  jenkins/spark-tests.sh
Labels: test

#5762 Fix auto merge conflict 5759
  docs/FAQ.md
  docs/compatibility.md
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
Labels: build

#5764 Add test for encrypted ORC write [databricks]
  tests/pom.xml
  tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: test

#5692 Add support for POSIX predefined character classes
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5768 Support MMyyyy date/timestamp format
  docs/compatibility.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#5774 Fix merge conflict with branch-22.06
  tests/pom.xml
  tests/src/test/320+/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: build

#5690 Update the error checking of `test_cast_neg_to_decimal_err`
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/spark_session.py
Labels: bug

#5761 Throw an exception when attempting to read columnar encrypted Parquet files on the GPU [databricks]
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/spark_session.py
  pom.xml
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/320+-noncdh/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#5790 Fix auto merge conflict 5789
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/spark_session.py
  pom.xml
  sql-plugin/src/main/311until320-all/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/320+-noncdh/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/GpuParquetCrypto.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: build

#5740 Handle regexp_replace inconsistency with empty strings and zero-repetition patterns [databricks]
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/311-nondb/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/312-nondb/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/313/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/314/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/321/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/322/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: audit_3.3.0

#5798 Fall back to CPU for RoundCeil and RoundFloor expressions
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until330-all/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark33XShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: bug

#5800 Fix auto merge conflict 5799
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until330-all/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsFloorCeilUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: build

#5350 Halt Spark executor when encountering unrecoverable CUDA errors
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: feature request

#5780 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#5749 Add shims for `AnsiCast` [databricks]
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/320/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/320until340-all/scala/com/nvidia/spark/rapids/shims/Spark320until340Shims.scala
  sql-plugin/src/main/321/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/321cdh/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/322/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/330/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ParquetCVShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/340/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ParquetCVShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/330+/scala/com/nvidia/spark/rapids/TimestampSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: audit_3.4.0

#5802 Update spark-rapids-jni.version to release 22.06.0 [databricks]
  pom.xml
Labels: build

#5696 Support Parquet field IDs [databricks]
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/ParquetFieldIdShims.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/ParquetFieldIdShims.scala
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SchemaUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetFieldIdSuite.scala
Labels: audit_3.3.0

#5767 Fix the time zone check issue
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: bug

#5795 Update FAQ to include local jar deployment via extraClassPath [skip ci]
  docs/FAQ.md
Labels: documentation

#5816 Update 22.06.0 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#5821 Merge remote-tracking branch 'origin/branch-22.06' into main [skip ci]
  CHANGELOG.md
  docs/FAQ.md
Labels: documentation, build

#5809 Disable Spark 3.4.0 premerge for 22.08 and enable for 22.10
  build/buildall
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#5805 [Issue 5726] Removing duplicate BINARY keyword
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#5822 Configure log4j version 2.x for test cases
  integration_tests/src/test/resources/log4j2.properties
  sql-plugin/src/test/resources/log4j2.properties
  tests/src/test/resources/log4j2.properties
  tools/src/test/resources/log4j2.properties
  udf-compiler/src/test/resources/log4j2.properties
Labels: test

#5829 Add regexp support for Alert, and Escape control characters
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#5845 Update Parquet binaryAsString integration to use a static parquet file
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/test/resources/binary_as_string.parquet
Labels: test

#5840 [DOC] Updated RapidsConf to reflect the default value of `spark.rapids.sql.improvedFloatOps.enabled` [skip ci]
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#5848 Update spark330shim to use released lib
  build/buildall
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/spark330/SparkShimServiceProvider.scala
  sql-plugin/src/test/330/scala/com/nvidia/spark/rapids/shims/spark330/Spark330ShimsSuite.scala
Labels: documentation, build

#5851 Update 22.06 changelog to include new commits [skip ci]
  CHANGELOG.md
Labels: documentation

#5852 Merge remote tracking branch-22.06 to main [skip ci]
  CHANGELOG.md
  build/buildall
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  docs/configs.md
  pom.xml
  sql-plugin/src/main/330/scala/com/nvidia/spark/rapids/shims/spark330/SparkShimServiceProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/test/330/scala/com/nvidia/spark/rapids/shims/spark330/Spark330ShimsSuite.scala
Labels: documentation, build

#5857 Remove user sperlingxx[skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#5860 [Doc]Add Spark3.3 support in doc[skip ci]
  docs/FAQ.md
  docs/dev/shims.md
  docs/download.md
Labels: documentation

#5861 [Doc]Add Spark3.3 support in doc for 22.06 branch[skip ci]
  docs/FAQ.md
  docs/dev/shims.md
  docs/download.md
Labels: documentation

#5865 Merge remote tracking branch-22.06 to main [skip ci]
  CHANGELOG.md
  docs/FAQ.md
  docs/dev/shims.md
  docs/download.md
Labels: build

#5856 Update unit test doc
  tests/README.md
Labels: documentation

#5695 Verify DPP over LIKE ANY/ALL expression
  integration_tests/src/main/python/dpp_test.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#5873 Correct the value of spark.rapids.sql.explain
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
Labels: test

#5868 Profiling tool add wholestagecodegen to execs mapping, sql to stage info and job end time
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationSummaryInfo.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CollectInformation.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/Profiler.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/ApplicationInfo.scala
  tools/src/test/resources/ProfilingExpectations/rapids_join_eventlog_sqlmetrics_expectation.csv
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#5783 `assertMinValueOverflow` should throw same type of exception as Spark
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/320until330-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: task

#5835 Update gh-pages branch for 22.06.0 release[skip ci]
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/additional-functionality/udf-to-catalyst-expressions.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/demo/GCP/Mortgage-ETL-GPU.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.zpln
  docs/dev/idea-code-style-settings.xml
  docs/dev/nvtx_profiling.md
  docs/dev/shims.md
  docs/download.md
  docs/examples.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/get-started/gpu_dataproc_packages_ubuntu_sample.sh
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/img/Tools/qualification-tool-recommendation-header-01.png
  docs/img/ease-of-use.png
  docs/security.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
  index.md
Labels: documentation

#5877 Add Apache Spark 3.3.1-SNAPSHOT Shims
  build/buildall
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  sql-plugin/src/main/330until340/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ParquetCVShims.scala
  sql-plugin/src/main/331/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/331/scala/com/nvidia/spark/rapids/shims/spark331/SparkShimServiceProvider.scala
  sql-plugin/src/main/331/scala/com/nvidia/spark/rapids/spark331/RapidsShuffleManager.scala
  sql-plugin/src/main/331/scala/org/apache/spark/sql/rapids/shims/spark331/RapidsShuffleInternalManager.scala
  sql-plugin/src/test/331/scala/com/nvidia/spark/rapids/shims/spark331/Spark331ShimsSuite.scala
Labels: feature request, build, spark 3.3+

#5880 Qualification tool: Parse expressions in FilterExec
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/FilterExecParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeChecker.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/qualification/PluginTypeCheckerSuite.scala
Labels: tools

#5894 [Doc]fix a typo with double "("[skip ci]
  docs/get-started/getting-started-gcp.md
Labels: documentation

#5723 Dynamically load hive and avro using reflection to avoid potential class not found exception [databricks]
  dist/unshimmed-from-each-spark3xx.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AvroProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AvroProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
Labels: bug

#5819 Modify the default value of spark.rapids.sql.explain as NOT_ON_GPU
  docs/FAQ.md
  docs/configs.md
  docs/get-started/getting-started.md
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#5869 Qualification: fix sorting and add unit-tests script
  tools/.gitignore
  tools/src/main/resources/ui/html/application.html
  tools/src/main/resources/ui/html/index.html
  tools/src/main/resources/ui/html/raw.html
  tools/src/main/resources/ui/js/app-report.js
  tools/src/main/resources/ui/js/qual-report.js
  tools/src/main/resources/ui/js/raw-report.js
  tools/src/main/resources/ui/js/uiutils.js
  tools/src/main/scala/com/nvidia/spark/rapids/tool/qualification/Qualification.scala
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/dev/generate-qualification-test-results.sh
Labels: tools

#5900 Optimize some common if/else cases
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
Labels: performance

#5898 Enable testing parquet with zstd for spark releases 3.2.0 and later
  integration_tests/src/main/python/parquet_test.py
Labels: test

#5686 Add `GpuMapConcat` support for nested-type values
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/data_gen.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CollectionOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: feature request

#5916 Revert "Enable testing zstd for spark releases 3.2.0 and later (#5898)"
  integration_tests/src/main/python/parquet_test.py
Labels: task

#5917 Improve sort removal heuristic for sort aggregate
  docs/configs.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: performance

#5930 Make first/last test for sorted deterministic
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug

#5926 Collect databricks test report [databricks]
  jenkins/databricks/run-tests.py
Labels: build

#5918 Filter profiling tool based on start time.
  docs/spark-profiling-tool.md
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileArgs.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ProfileMain.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/AppFilterImpl.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/AppFilterSuite.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/ApplicationInfoSuite.scala
Labels: tools

#5883 Add support for `element_at` and `GetMapValue`
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMapUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#5936 [BUG] Fix databricks test report location [databricks]
  jenkins/databricks/run-tests.py
Labels: bug, test
