Repository NVIDIA/spark-rapids, pull requests merged in 2022-11, with the labels that each got.

#6924 Shim for shaded protobuf orc-core
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/OrcProtoWriterShim.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/OrcProtoWriterShim.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: task

#6962 Stop using deprecated JDK API javax.xml.bind
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/literals.scala
Labels: task

#6801 Enable the config `MaxRecordsPerFile` on the `GpuDynamicDirectoryConcurrentWriter`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: bug

#6901 Add JDK11 to mvn-verify-check
  .github/workflows/mvn-verify-check.yml
  dist/pom.xml
  jenkins/version-def.sh
Labels: build

#6931 mergeSort late batch materialization and free already merged batches eagerly
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: reliability

#6974 Add doc for `mapInArrow` [skip ci]
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#6937 Removed PromotePrecision for Spark 3.4 [databricks]
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: build, audit_3.4.0

#7000 Spark-3.4: Update DecimalArithmeticOverrides to object
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
Labels: build, Spark 3.4+

#6976 Update the docs of `write` and `writebatch` of `ColumnOutputWriter`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
Labels: documentation

#6996 Fix HostToGpuCoalesceIterator sometimes closing input batches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AutoCloseColumnBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: bug

#6950 Throw when onAllocFailure is invoked with invalid arguments
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandlerSuite.scala
Labels: bug

#7011 Fix buffertime for multi-threaded reader
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#7006 Revert "Fix a minor potential issue when rebatching for GpuArrowEvalP…
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
Labels: bug

#6806 Fix read old data from alluxio regardless of S3 changes when using CONVERT_TIME replacement algorithm
  sql-plugin/src/main/311until320-all/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
Labels: bug

#7004 Alluxio pathsToReplace should has higher priority
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: bug

#6362 [FEA] Add support for using nvcomp ZSTD compression
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: feature request

#7015 Fix the test failure of `avg literals bools fail` on Spark 3.4.0
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
Labels: audit_3.4.0

#6977 Close the `batch` in the `writeBatch` function of `GpuDynamicPartitionDataSingleWriter`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
Labels: bug

#6999 Enable snapshot builds as optional PR checks
  .github/workflows/mvn-verify-check.yml
  dist/pom.xml
  jenkins/version-def.sh
Labels: build, Spark 3.4+

#7016 Parse out positive and negative lookahead explicitly to fallback to GPU
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexComplexityEstimator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#6914 Add in tests to verify corner cases in parquet
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: test

#7002 ParquetCachedBatchSerializer: Close the hostBatch in ColumnBatchToCachedBatchIterator when the iterator has exhausted
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
Labels: test

#7031 Add skip test options [skip ci]
  jenkins/spark-nightly-build.sh
Labels: test, build

#7022 Fallback to CPU when reading Delta delta_log parquet checkpoint files
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#7027 Include unit tests and integration tests in mvn-verify-check
  .github/workflows/mvn-verify-check.yml
Labels: build

#6960 Use cudf like operator in GpuLike operator
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: performance

#7052 Enable automerge 22.12 to 23.02 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#7049 add parenthesis around delta_log check to short circuit
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#7048 Enable tiered projections for GpuProjectExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: performance

#7045 Fix parquet test for nztimestamp on spark 3.4.0
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: bug, test, audit_3.4.0

#7025 Spark-3.4 - Fix cast unit tests
  sql-plugin/src/main/311until340-all/scala/com/nvidia/spark/rapids/shims/CastingConfigShim.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/CastingConfigShim.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
Labels: test, Spark 3.4+

#7063 Init version 23.02.0 [databricks]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  common/pom.xml
  dist/pom.xml
  docs/FAQ.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-udfs.md
  docs/configs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/dev/shims.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
Labels: build

#7067 Update the tests in `array_test.py` to adapt the removal of `strictIndexOperator` in Spark 3.4
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#7051 Support non literal position and length for substring
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#7102 Skip test_hash_groupby_collect_partial_replace_with_distinct_fallback for #7092 [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug, build

#7107 Skip test_hash_groupby_collect_with_single_distinct [skip ci]
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug, test

#7097 Use Databricks instance Spark version as default
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
Labels: build

#7074 Update JNI and cudf-py version to 23.02 [databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
Labels: build

#7088 Fix ConditionalExpr parser in Qualification tool
  tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala
  tools/src/test/scala/com/nvidia/spark/rapids/tool/planparser/SqlPlanParserSuite.scala
Labels: tools

#7077 Add shims for Spark 3.2.3
  dist/pom.xml
  pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/323/scala/com/nvidia/spark/rapids/shims/RegExpShim.scala
  sql-plugin/src/main/323/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/323/scala/com/nvidia/spark/rapids/shims/spark323/SparkShimServiceProvider.scala
  sql-plugin/src/main/323/scala/com/nvidia/spark/rapids/spark323/RapidsShuffleManager.scala
  sql-plugin/src/main/323/scala/org/apache/spark/sql/rapids/shims/spark323/RapidsShuffleInternalManager.scala
  sql-plugin/src/test/323/scala/com/nvidia/spark/rapids/shims/spark323/Spark323ShimsSuite.scala
Labels: feature request

#7013 Hive delimited textfile read support [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/test/resources/hive-delim-text/Acquisition_2007Q3/Acquisition_2007Q3.hive.txt
  integration_tests/src/test/resources/hive-delim-text/Performance_2007Q3/Performance_2007Q3.hive.txt
  integration_tests/src/test/resources/hive-delim-text/carriage-return-err/carriage.return.err.hive.txt
  integration_tests/src/test/resources/hive-delim-text/carriage-return/carriage.return.hive.txt
  integration_tests/src/test/resources/hive-delim-text/comments/comments.hive.txt
  integration_tests/src/test/resources/hive-delim-text/date-err/date.err.hive.txt
  integration_tests/src/test/resources/hive-delim-text/date/date.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-boolean-values/bools.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-float-values/simple_float_values.hive.txt
  integration_tests/src/test/resources/hive-delim-text/simple-int-values/simple_int_values.hive.txt
  integration_tests/src/test/resources/hive-delim-text/timestamp-err/ts.err.hive.txt
  integration_tests/src/test/resources/hive-delim-text/timestamp/ts.hive.txt
  integration_tests/src/test/resources/hive-delim-text/trucks-1/trucks.hive.txt
  integration_tests/src/test/resources/hive-delim-text/trucks-err/trucks.err.hive.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HiveProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExecs.csv
Labels: feature request

#7120 Build noSnapshots without cdh shims on arm CPU [skip ci]
  jenkins/version-def.sh
Labels: build

#6934 Add support for chunked parquet reading [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquet.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuBatchDataReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExecMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataProducer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: reliability

#7125 Add missing cleanup of shuffle data when using multi-threaded shuffle
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#7103 Add support to DB 11.3 ML LTS in databricks build script [databricks]
  jenkins/databricks/build.sh
Labels: spark 3.3+, Spark 3.4+

#7135 Revert "Suffix artifactId with amd64/arm64 for the dist jars [skip ci]] (#7070)(#7120)"
  api_validation/pom.xml
  build/buildall
  dist/pom.xml
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/version-def.sh
  pom.xml
  scripts/prioritize-commits.sh
Labels: build

#7145 Remove inaccurate warnings about fallbacks when using multithreaded shuffle
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle, P2

#7141 Get PROJECT_VERSION from version-def.sh [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: bug, build

#7142 Restore hash aggregate tests after cub segmented sort fix [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test, cudf_dependency

#7153 Add `SchemaUtilsShims`
  sql-plugin/src/main/311until340-all/scala/org/apache/spark/sql/rapids/shims/SchemaUtilsShims.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/SchemaUtilsShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala
Labels: Spark 3.4+

#7113 Use an improved API for appending binary to host vector
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
Labels: performance

#7099 Update AQE tests to support Spark 3.4
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: Spark 3.4+

#7136 Skip the unit test `sorted_partitioned_write` on Spark 340.
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: test

#7171 Add tests for 331 and 332
  tests/pom.xml
Labels: test

#7115 Support `array_remove` operator
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/src/main/resources/operatorsScore.csv
  tools/src/main/resources/supportedExprs.csv
Labels: feature request

#7126 Fix support for binary encoded decimal for parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: bug

#7180 multithreaded RapidsShuffleManager change when we release memory
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#7169 Remove snapshot shims build in premerge script
  jenkins/spark-premerge-build.sh
Labels: build

#7164 Search for `CudaFatalException` in causes of `failureReason` in function `onTaskFailed`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: reliability

#7165 Try/catch cudf file scan exceptions and re-throw with file metadata in message
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCSVScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: reliability

#7189 specify shim versions to build [skip ci]
  jenkins/version-def.sh
Labels: build

#7188 Remove "SNAPSHOT" for 323 shim
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  sql-plugin/src/main/323/scala/com/nvidia/spark/rapids/shims/spark323/SparkShimServiceProvider.scala
  tests/pom.xml
Labels: documentation, build

#7176 Copying common ThreadFactoryBuilder to tools to remove dependency
  tools/pom.xml
  tools/src/main/scala/com/nvidia/spark/rapids/ThreadFactoryBuilder.scala
  tools/src/test/scala/com/nvidia/spark/rapids/ThreadFactoryBuilderTest.scala
Labels: tools

#7075 Fix the failure of `test_array_element_at_zero_index_fail` on Spark3.4 [databricks]
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/311until320-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/320until330-nondb/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/321db/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtilsFor330plus.scala
  sql-plugin/src/main/330until340/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala
Labels: Spark 3.4+

#7170 Fix the `limit_test` failures on Spark 3.4
  integration_tests/src/main/python/limit_test.py
Labels: Spark 3.4+

#7195 Fix non-deterministic query in test_aqe_join_reused_exchange_inequality_condition [databricks]
  integration_tests/src/main/python/aqe_test.py
Labels: test

#7194 Skip tests that fail due to recent cuDF changes related to end of string/line anchors
  integration_tests/src/main/python/regexp_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#7167 Handle two changes related to `FileFormatWriter` since Spark 340
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala
  sql-plugin/src/main/340/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuV1WriteUtils.scala
Labels: Spark 3.4+

#7156 Add scripts to run integration test on Databricks by leveraging Jenkins parallelism [skip ci]
  jenkins/databricks/run_it.sh
  jenkins/databricks/setup.sh
Labels: build

#7199 Fixes unregisterShuffle bugs in the driver and a missed match for the GpuResolver
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#7034 Read directly from S3 instead of reading from Alluxio caches if files are large and disk is slow [databricks]
  docs/configs.md
  docs/get-started/getting-started-alluxio.md
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/321db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: performance
