Repository NVIDIA/spark-rapids, pull requests merged in 2022-01, with the labels that each got.

#4417 Fix an Intellij debug issue [databricks]
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: task

#4447 Fix 330 build error and add 322 shims layer [databricks]
  build/buildall
  dist/pom.xml
  docs/additional-functionality/rapids-shuffle.md
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
  pom.xml
  shims/pom.xml
  shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/spark301/Spark301Shims.scala
  shims/spark302/src/main/scala/com/nvidia/spark/rapids/shims/spark302/Spark302Shims.scala
  shims/spark303/src/main/scala/com/nvidia/spark/rapids/shims/spark303/Spark303Shims.scala
  shims/spark304/src/main/scala/com/nvidia/spark/rapids/shims/spark304/Spark304Shims.scala
  shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/spark311/Spark311Shims.scala
  shims/spark311cdh/src/main/scala/com/nvidia/spark/rapids/shims/spark311cdh/Spark311CDHShims.scala
  shims/spark312/src/main/scala/com/nvidia/spark/rapids/shims/spark312/Spark312Shims.scala
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/shims/spark312db/Spark312dbShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  shims/spark321/src/main/scala/com/nvidia/spark/rapids/shims/spark321/Spark321Shims.scala
  shims/spark322/pom.xml
  shims/spark322/src/main/scala/com/nvidia/spark/rapids/shims/spark322/Spark322Shims.scala
  shims/spark322/src/main/scala/com/nvidia/spark/rapids/shims/spark322/SparkShimServiceProvider.scala
  shims/spark322/src/main/scala/com/nvidia/spark/rapids/spark322/RapidsShuffleManager.scala
  shims/spark322/src/main/scala/org/apache/spark/sql/rapids/shims/spark322/RapidsShuffleInternalManager.scala
  shims/spark322/src/test/scala/com/nvidia/spark/rapids/shims/spark322/Spark322ShimsSuite.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuHashPartitioning.scala
  sql-plugin/src/main/311+-all/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/ParquetMaterializer.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/RebaseShims.scala
  sql-plugin/src/main/320until322/scala/com/nvidia/spark/rapids/shims/v2/Spark320until322Shims.scala
  sql-plugin/src/main/320until322/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/v2/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/322+/scala/com/nvidia/spark/rapids/shims/v2/Spark322PlusShims.scala
  sql-plugin/src/main/322+/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/v2/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuHashPartitioning.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioningBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: build

#4437 Change logInfo to logWarning
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/BasicColumnarWriteStatsTracker.scala
Labels: audit_3.3.0

#4449 Add recursive type checking and fallback tests for casting array with unsupported element types to string
  docs/supported_ops.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: bug

#4452 Limit parallelism of nightly tests [skip ci]
  jenkins/spark-tests.sh
Labels: test

#4430 update pca example link in ml-integration.md[skip ci]
  docs/additional-functionality/ml-integration.md
Labels: documentation

#4428 Exhaustively iterate ColumnarToRow iterator to avoid leaks
  tests/src/test/scala/com/nvidia/spark/rapids/GpuColumnarToRowSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRDDConverterSuite.scala
Labels: test

#4155 Add partial support for line begin and end anchors in regexp_replace
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#4436 Print error log to stderr output
  dist/scripts/check-shims-revisions.sh
Labels: build

#4435 Disable add profile src execution by default to make the build log clean
  aggregator/pom.xml
  pom.xml
  sql-plugin/pom.xml
Labels: build

#4451 Some metrics improvements and timeline reporting
  docs/spark-profiling-tool.md
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/ClassWarehouse.scala
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/GenerateTimeline.scala
  tools/src/main/scala/org/apache/spark/sql/rapids/tool/profiling/EventsProcessor.scala
Labels: task, tools

#4362 Decimal128 support for Parquet
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  tests/src/test/resources/test_unsigned64.parquet
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala
  tools/src/main/resources/supportedDataSource.csv
Labels: feature request

#4172 Support String to Decimal 128 [databricks]
  docs/configs.md
  integration_tests/src/main/python/cast_test.py
  shims/spark322/src/main/scala/com/nvidia/spark/rapids/shims/spark322/Spark322Shims.scala
  shims/spark330/src/main/scala/com/nvidia/spark/rapids/shims/spark330/Spark330Shims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShimsBase.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShimsBase.scala
  sql-plugin/src/main/320until322/scala/com/nvidia/spark/rapids/shims/v2/Spark320until322Shims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: feature request

#4416 Unshim join execs [databricks]
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuJoinUtils.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuJoinUtils.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301until320Shims.scala
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuHashPartitioning.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/GpuJoinUtils.scala
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/311until330-all/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320until322/scala/com/nvidia/spark/rapids/shims/v2/Spark320until322Shims.scala
  sql-plugin/src/main/322+/scala/com/nvidia/spark/rapids/shims/v2/Spark322PlusShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/GpuHashPartitioning.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastHashJoinSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BroadcastNestedLoopJoinSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
Labels: build

#4456 Fix build issues: 1 clean non-exists target dirs; 2 remove duplicated plugin
  pom.xml
  sql-plugin/pom.xml
Labels: build

#4383 Fix correctness issue with CASE WHEN with expressions that have side-effects
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ConditionalsSuite.scala
Labels: bug

#4460 Abstract the text based PartitionReader
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
Labels: task

#4376 Add sequence support [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: feature request

#4440 Enable GPU broadcast exchange reuse for DPP when AQE enabled [databricks]
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToCpuExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
Labels: performance

#4472 Modify docs for 22.02 to address issue-4319[skip ci]
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
Labels: documentation

#4464 Throw SparkArrayIndexOutOfBoundsException for Spark 3.3.0+
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/RapidsErrorUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
Labels: bug

#4479 Change signoff check image to slim-buster [skip ci]
  .github/workflows/signoff-check/Dockerfile
Labels: build

#4462 Rename DECIMAL_128_FULL and rework usage of TypeSig.gpuNumeric
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShimsBase.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/301until320-all/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/301until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark301until320Shims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShimsBase.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/TypeSigUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
Labels: task

#4471 Disable orc write by default because of https://issues.apache.org/jira/browse/ORC-1075
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: task

#4400 Enable approx percentile tests [databricks]
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug

#4494 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#4459 Use merge sort for struct types in non-key columns
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: task

#4491 Skip the test for spark versions 3.1.1, 3.1.2 and 3.2.0 only [databricks]
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/spark_session.py
  shims/spark312db/src/main/scala/com/nvidia/spark/rapids/shims/spark312db/Spark312dbShims.scala
  shims/spark313/src/main/scala/com/nvidia/spark/rapids/shims/spark313/Spark313Shims.scala
  shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/spark320/Spark320Shims.scala
  shims/spark322/src/main/scala/com/nvidia/spark/rapids/shims/spark322/Spark322Shims.scala
  shims/spark330/src/main/scala/com/nvidia/spark/rapids/shims/spark330/Spark330Shims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShimsBase.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: task

#4424 Improve support for regular expression string anchors `\A`, `\Z`, and `\z`
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#4476 Don't acquire the semaphore for empty input while scanning
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScanBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: performance

#4489 Add arrays of decimal128 to join tests
  integration_tests/src/main/python/join_test.py
Labels: task

#4461 [Audit] Add bucketed scan info in query plan of data source v1 [databricks]
  integration_tests/src/main/python/explain_test.py
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
  sql-plugin/src/main/320until322/scala/com/nvidia/spark/rapids/shims/v2/Spark320until322Shims.scala
  sql-plugin/src/main/322+/scala/com/nvidia/spark/rapids/shims/v2/Spark322PlusShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: audit_3.3.0

#4490 Remove warning about RMM default allocator
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#4420 Fix up incorrect results of rounding past the max digits of data type [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: bug

#4495 Enable approx_percentile by default
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
Labels: task

#4492 Fall back to CPU for regular expressions containing hex digits
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#4484 Update GpuFileFormatWriter to stay in sync with recent Spark changes, but still not support writing Hive bucketed table on GPU.
  integration_tests/src/main/python/datasourcev2_write_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: audit_3.3.0

#4510 Update copyright in NOTICE [skip ci]
  NOTICE
Labels: documentation

#4482 Simplified the construction of zero scalar in GpuUnaryMinus
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: task

#3762 Call the right method to convert table from row major <=> col major [databricks]
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/UnsafeRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
Labels: task

#4523 Add more integration tests for decimal 128
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/sort_test.py
Labels: test

#4502 Removed the redundant test for element_at and fixed the failing one [databricks]
  integration_tests/src/main/python/array_test.py
Labels: test

#4525 Properly close data writer in GpuFileFormatWriter
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
Labels: bug

#4527 Fall back to CPU for regular expressions containing \D or \W
  docs/compatibility.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4512 remove hadoop version requirement[skip ci]
  docs/download.md
Labels: documentation

#4497 Make better use of pinned memory pool
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillPriorities.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: performance, shuffle, improve

#4322 Add an explain only mode to the plugin
  docs/configs.md
  docs/get-started/getting-started-workload-qualification.md
  integration_tests/src/main/python/explain_mode_test.py
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: feature request

#4534 Temporarily disable integration test - test_hash_reduction_pivot_without_nans
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#4434 Support max on single-level struct in aggregation context
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request

#4540 Remove user kuhushukla
  .github/workflows/blossom-ci.yml
Labels: build

#4543 Enable auto-merge from branch-22.02 to branch-22.04 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#4545 Fix CVE-2021-22569
  pom.xml
Labels: bug

#4549 Fix typos in integration tests README [skip ci]
  integration_tests/README.md
Labels: documentation

#4530 Fix correctness issues in regexp and add `\r` and `\n` to fuzz tests
  docs/compatibility.md
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ConditionalsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4553 Reenable test_hash_reduction_pivot_without_nans
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#4552 Fix resource leak in GpuCaseWhen
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
Labels: bug

#4562 Fix signoff check [skip ci]
  .github/workflows/signoff-check/Dockerfile
Labels: build

#4563 Change signoff check image to slim-buster (#4479)
  .github/workflows/signoff-check/Dockerfile
Labels: build

#4554 Update gh-pages UDF doc to correct links for 21.12 version[skip ci]
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#4566 remove scala-library from combined tools jar
  tools/pom.xml
Labels: build

#4477 Use libcudf mixed joins for conditional hash joins [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance, cudf_dependency

#4570 A few quick fixes to try to reduce max memory usage in the tests
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#4520 GpuSequence refactor[databricks]
  integration_tests/src/main/python/collection_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/BoolUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: bug

#4577 Revert "Fix CVE-2021-22569 (#4545)"
  pom.xml
Labels: build

#4569 Fix infinite loop with Profiling tool compare mode and app with no sql ids
  tools/src/main/scala/com/nvidia/spark/rapids/tool/profiling/CompareApplications.scala
Labels: tools

#4556 regexp_replace with back-references should fall back to CPU
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/311+-nondb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: bug

#4485 Add json reader support
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/get_json_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/301until330-all/scala/com/nvidia/spark/rapids/shims/v2/Spark30Xuntil33XShims.scala
  sql-plugin/src/main/301until330-all/scala/org/apache/spark/sql/catalyst/json/rapids/shims/v2/Spark30Xuntil33XFileOptionsShims.scala
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
  sql-plugin/src/main/330+/scala/org/apache/spark/sql/catalyst/json/rapids/shims/v2/Spark33XFileOptionsShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  tools/src/main/resources/supportedDataSource.csv
  tools/src/test/resources/QualificationExpectations/qual_test_simple_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv1_expectation.csv
  tools/src/test/resources/QualificationExpectations/read_dsv2_expectation.csv
Labels: feature request

#4589 Increase premerge databricks IDLE_TIMEOUT to 4 hours [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4585 Spark2 module upmerge, deploy script, and updates for Jenkins
  jenkins/deploy.sh
  scripts/rundiffspark2.sh
  scripts/spark2diffs/GpuHashJoin.diff
  scripts/spark2diffs/GpuSortMergeJoinMeta.diff
  scripts/spark2diffs/aggregate.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/v2/GpuBroadcastHashJoinExecMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/v2/GpuShuffledHashJoinExecMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/v2/GpuSortMergeJoinMeta.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: build

#4594 Resolve case-folding issue [skip ci]
  scripts/spark2diffs/GpuhashJoin.diff
Labels: bug

#4501 Switch and/or to use new cudf binops to improve performance
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
Labels: performance

#4575 Correct and update links in UDF doc[skip ci]
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#4573 Correct version from 21.12 to 22.02[skip ci]
  docs/additional-functionality/ml-integration.md
  docs/demo/Databricks/generate-init-script-cuda11.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#4583 Avoid unapply on PromotePrecision [databricks]
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: build

#4560 Make shims.v2.ParquetCachedBatchSerializer as protected
  sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
  tests-spark310+/src/test/scala/com/nvidia/spark/rapids/shims/v2/Spark310ParquetWriterSuite.scala
Labels: bug

#4504 Implement AST-based regular expression fuzz tests
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#4535 Revert "Disable orc write by default because of https://issues.apache.org/jira/browse/ORC-1075 (#4471)"
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: bug, cudf_dependency

#4470 Add in HashPartitioning support for decimal 128 [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: task

#4592 Adds SQL function HYPOT using the GPU
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
Labels: feature request

#4597 Update plugin version to 22.04.0-SNAPSHOT
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shims/README.md
  shims/pom.xml
  shims/spark301/pom.xml
  shims/spark301db/pom.xml
  shims/spark302/pom.xml
  shims/spark303/pom.xml
  shims/spark304/pom.xml
  shims/spark311/pom.xml
  shims/spark311cdh/pom.xml
  shims/spark312/pom.xml
  shims/spark312db/pom.xml
  shims/spark313/pom.xml
  shims/spark320/pom.xml
  shims/spark321/pom.xml
  shims/spark322/pom.xml
  shims/spark330/pom.xml
  shuffle-plugin/pom.xml
  spark2-sql-plugin/pom.xml
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests-spark310+/pom.xml
  tests/pom.xml
  tools/pom.xml
  udf-compiler/pom.xml
  udf-examples/pom.xml
  udf-examples/src/main/cpp/CMakeLists.txt
Labels: documentation, build

#4622 Fallback to CPU when encoding is not supported for JSON reader
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
Labels: task

#4624 Enable integration test results report on Jenkins [skip ci]
  integration_tests/run_pyspark_from_build.sh
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#4618 [DB31x] Pick the correct Python runner for flatmap-group Pandas UDF[databricks]
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/31xdb/scala/org/apache/spark/sql/rapids/execution/python/shims/v2/GpuFlatMapGroupsInPandasExec.scala
Labels: bug

#4531 Use libcudf mixed joins for conditional hash semi and anti joins
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance, cudf_dependency

#4633 Suppress newTaskTempFile method warnings for Spark 3.3.0 build
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
Labels: build

#4630 Fix the incomplete capture of SubqueryBroadcast
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/301db/scala/com/nvidia/spark/rapids/shims/v2/Spark30XdbShims.scala
  sql-plugin/src/main/301until310-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark30XShims.scala
  sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala
  sql-plugin/src/main/31xdb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XdbShims.scala
  sql-plugin/src/main/320+/scala/com/nvidia/spark/rapids/shims/v2/Spark320PlusShims.scala
Labels: bug

#4606 Set default RMM pool to ASYNC for cuda 11.2+
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation, performance, shuffle, ease of use

#4643 Add profile release301 when mvn help:evaluate
  jenkins/spark-nightly-build.sh
Labels: build

#4652 Remove non-deterministic test order in nightly [skip ci]
  jenkins/spark-tests.sh
Labels: build

#4659 Disable 311cdh build by default because of a missing dependency
  build/buildall
  dist/pom.xml
  jenkins/spark-premerge-build.sh
  jenkins/version-def.sh
Labels: build

#4623 Enable aggregate push down for parquet
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/v2/Spark33XShims.scala
Labels: audit_3.3.0

#4657 Upmerge spark2 directory to the latest 22.02 changes
  scripts/rundiffspark2.sh
  scripts/spark2diffs/FileSourceScanExec.diff
  scripts/spark2diffs/GpuFileSourceScanExec.diff
  scripts/spark2diffs/GpuJsonScan.diff
  scripts/spark2diffs/GpuOrcFileFormat.diff
  scripts/spark2diffs/GpuOverrides.diff
  scripts/spark2diffs/GpuReadJsonFileFormat.diff
  scripts/spark2diffs/GpuRegExpReplaceMeta.diff
  scripts/spark2diffs/RapidsConf.diff
  scripts/spark2diffs/TypeChecks.diff
  scripts/spark2diffs/aggregate.diff
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregateMeta.scala
  spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/shims/v2/GpuRegExpReplaceMeta.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
  spark2-sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: feature request

#4648 Append new authorized user to blossom-ci safelist
  .github/workflows/blossom-ci.yml
Labels: build

#4662 Update the deploy script [skip ci]
  jenkins/deploy.sh
Labels: build
