Repository NVIDIA/spark-rapids, pull requests merged in 2023-12, with the labels that each got.

#9831 Skip fastparquet timestamp tests when plugin cannot read/write timestamps
  integration_tests/src/main/python/fastparquet_compatibility_test.py
Labels: test

#9852 Avoid generating duplicate nan keys with MapGen(FloatGen)
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/map_test.py
Labels: test

#9906 Fix test_initcap to use the intended limited character set
  integration_tests/src/main/python/string_test.py
Labels: test

#9928 Test `inset` with `NaN` only for Spark from 3.1.3
  docs/compatibility.md
  integration_tests/src/main/python/cmp_test.py
Labels: documentation, test

#9904 Params for build and test CI scripts on Databricks
  jenkins/databricks/build.sh
  jenkins/databricks/common_vars.sh
  jenkins/databricks/params.py
  jenkins/databricks/run-build.py
  jenkins/databricks/run-tests.py
Labels: build

#9937 Refactor to use CLASSIFIER instead of CUDA_CLASSIFIER [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/version-def.sh
Labels: test

#9947 Fix merge conflict with branch-23.12
  docs/compatibility.md
  integration_tests/src/main/python/cmp_test.py
Labels: build

#9946 Fix test_multi_tier_ast to ignore ordering of output rows
  integration_tests/src/main/python/ast_test.py
Labels: test

#9940 Fix 'year 0 is out of range' by setting a fix seed
  integration_tests/src/main/python/json_test.py
Labels: test

#9942 Fix a potential data corruption for Pandas UDF
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
Labels: bug

#9950 Avoid generating NaNs as partition values in test_part_write_round_trip
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#9960 Fix LongGen accidentally using special cases when none are desired
  integration_tests/src/main/python/data_gen.py
Labels: test

#9961 Avoid using floating point for partition values in Delta Lake tests
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9949 Override the seed for `test_map_scalars_supported_key_types ` for version of Spark before 3.4.0 [Databricks]
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#9957 Update cases for cast between integral and (date/time)
  integration_tests/src/main/python/cast_test.py
Labels: test

#9929 Add host memory retries for GeneratedInternalRowToCudfRowIterator
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
Labels: reliability

#9978 Avoid using floating point values as partition values in tests
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#9972 Fix year 0 is out of range in test_from_json_struct_timestamp
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/json_test.py
Labels: test

#9970 Avoid leading and trailing zeros in test_timestamp_seconds_rounding_necessary
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
Labels: test

#10003 Fix merge conflict with branch-23.12
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
Labels: build

#10000 Optimize from_unixtime
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: performance

#10002 Use Spark 3.3.3 instead of 3.3.2 for Scala 2.13 premerge builds
  pom.xml
  scala2.13/pom.xml
Labels: build

#9827 Enable ORC timestamp and decimal predicate push down tests
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcFilterSuite.scala
Labels: test

#10007 Fix Java OOM in non-UTC case with lots of xfail (#9944)
  integration_tests/src/main/python/asserts.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ShimmedExecutionPlanCaptureCallbackImpl.scala
Labels: test

#10009 Using fix seed to unblock 23.12 release; Move the blocked issues to 24.02
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/schema_evolution_test.py
Labels: test

#9760 Support split broadcast join condition into ast and non-ast [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AstUtil.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
Labels: feature request

#9954 Update private and JNI version to released 23.12.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#10014 Add documentation for how to run tests with a fixed datagen seed [skip ci]
  integration_tests/README.md
Labels: documentation

#10019 Fix auto merge conflict 10010 [skip ci]
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: build

#9943 [DOC] Update docs for 23.12.0 release [skip ci]
  CONTRIBUTING.md
  docs/archive.md
  docs/dev/testing.md
  docs/download.md
Labels: documentation

#9935 Init 23.12 changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.08.md
Labels: documentation

#10011 Add cpu oom retry split handling to InternalRowToColumnarBatchIterator
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: feature request, reliability

#9481 Use parse_url kernel for PROTOCOL parsing
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/url_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#10016 Fix infinite loop in test_str_to_map_expr_random_delimiters
  integration_tests/src/main/python/map_test.py
Labels: test

#10033 Remove GpuToTimestampImproved and spark.rapids.sql.improvedTimeOps.enabled
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: tech debt

#9902 Some refactor for the Python UDF code[databricks]
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInBatchExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonRunnerCommon.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuBasePythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuMapInBatchExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuPythonArrowShims.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuBasePythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuPythonArrowShims.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
Labels: tech debt

#9816 Support unix_timestamp and to_unix_timestamp with non-UTC timezones (non-DST)
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#9973 Batching support for row-based bounded window functions
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchedBoundedWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request, reliability

#9845 Use parse_url kernel for HOST parsing
  docs/supported_ops.md
  integration_tests/src/main/python/url_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
Labels: feature request

#9470 Use float to string kernel
  docs/compatibility.md
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTextFileFormat.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuExpressionTestSuite.scala
Labels: feature request

#9721 Support date_format via Gpu for non-UTC time zone [databricks]
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: task

#10049 Fix out of range error from pySpark in test_timestamp_millis and other two integration test cases
  integration_tests/src/main/python/date_time_test.py
Labels: test

#10053 Remove invalid user from CODEOWNER file [skip ci]
  .github/CODEOWNERS
Labels: build

#10052 Set seed=0 for some integration test cases
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/orc_cast_test.py
Labels: test

#10013 Extended configuration of OOM injection mode
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: test

#10060 Fix failed cases for non-utc time zone
  integration_tests/README.md
  integration_tests/src/main/python/array_test.py
Labels: bug

#10070 Fix 332db build failure [databricks]
  tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala
Labels: build

#10065 Improve host memory spill interfaces
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: bug, reliability

#9996 Test full timestamp output range in PySpark [databricks]
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#10066 [DOC] updates gh-pages files for 23.12 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/README.md
  docs/dev/data-sources.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
  index.md
Labels: documentation

#10057 Add support for StringConcatFactory.makeConcatWithConstants (#9555)
  udf-compiler/src/main/scala-2.13/com/nvidia/spark/udf/Instruction.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/LambdaReflection.scala
Labels: bug, Scala 2.13

#9999 Add some odd time zones for timezone transition tests
  integration_tests/pytest.ini
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/parquet_pyarrow_test.py
  integration_tests/src/main/python/parquet_test.py
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/test-timezones.sh
Labels: test

#10090 Replace GPU-unsupported `\z` with an alternative RLIKE expression
  integration_tests/src/main/python/conditionals_test.py
Labels: bug, test

#10085 Update tests that originally restricted the Spark timestamp range
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#10092 Implement Math.round using floor on GPU
  integration_tests/src/main/python/orc_cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#10096 Shim MockTaskContext to fix Spark 3.5.1 build
  tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala
  tests/src/test/spark311/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContextBase.scala
  tests/src/test/spark351/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContextBase.scala
Labels: test, build

#10078 Add perf test for non-UTC operators
  tests/src/test/scala/com/nvidia/spark/rapids/timezone/TimeZonePerfSuite.scala
  tests/src/test/scala/org/apache/spark/sql/FileUtils.scala
  tests/src/test/scala/org/apache/spark/sql/timezone/TimeZonePerfUtils.scala
Labels: performance, test

#10061 Use parse_url kernel for QUERY parsing
  integration_tests/src/main/python/url_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
Labels: feature request

#9925 Use threads, cache Scala compiler in GH mvn workflow
  .github/workflows/mvn-verify-check.yml
  pom.xml
  scala2.13/pom.xml
Labels: build

#10112 Remove datagen seed override for test_conditional_with_side_effects_cast
  integration_tests/src/main/python/conditionals_test.py
Labels: bug, test

#10121 [DOC] update download page for db hot fix [skip ci]
  docs/download.md
Labels: documentation

#10122 Init changelog for v23.12.1 [skip ci]
  CHANGELOG.md
Labels: documentation

#10123 Change version to v23.12.1 [skip ci]
  docs/dev/shims.md
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: documentation

#10124 Update changelog for v23.12.1 [skip ci]
  CHANGELOG.md
Labels: documentation

#10093 Fix test_unsupported_fallback_regexp_replace
  integration_tests/src/main/python/regexp_test.py
Labels: test

#10097 [DOC] Update docs for 23.12.1 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#10054 Support Ascii function for ascii and latin-1 [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/GpuAscii.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/shims/GpuAscii.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request
