Repository NVIDIA/spark-rapids, pull requests merged in 2023-03, with the labels that each got.

#7830 Fix buffer and Filter time with Parquet multithreaded combine reader
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#7841 Hardcode scan projects [skip ci]
  .github/workflows/blossom-ci.yml
Labels: bug, build

#7842 Try fix broken blackduck scan [skip ci]
  .github/workflows/blossom-ci.yml
Labels: bug, build

#7824 Use withRetryNoSplit in BasicWindowCalc
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregateRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RmmSparkRetrySuiteBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
Labels: reliability

#7840 Execute mvn initialize before parallel build [skip ci]
  build/buildall
Labels: build

#7822 Add in support for OOM retry
  docs/configs.md
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
Labels: reliability

#7839 Add reduced pom to dist jar in the packaging phase [databricks]
  dist/maven-antrun/build-parallel-worlds.xml
  dist/pom.xml
  dist/unshimmed-common-from-spark311.txt
Labels: build

#7848 Initialize only sql-plugin to prevent missing submodule artifacts in buildall [skip ci]
  build/buildall
Labels: build

#7856 Update references to reduced dependencies pom [skip ci]
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
Labels: build

#7854 Optimize `regexp_extract*` by transpiling capture groups to non-capturing groups so that only the required capturing group is manifested
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: performance

#7860 Enable manual copy-and-paste code detection [skip ci]
  docs/dev/shimplify.md
  pom.xml
Labels: documentation, build

#7878 Fixing host memory calculation to properly be 5GiB
  integration_tests/run_pyspark_from_build.sh
Labels: test

#7794 Implement sub partitioning for large/skewed hash joins
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSubPartitionSuite.scala
Labels: task

#7863 [Doc] Address document issues [skip ci]
  docs/FAQ.md
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-gcp.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#7835 Update to pull the rapids spark extra plugin jar
  aggregator/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: build

#7862 Reduce shimming of GpuFlatMapGroupsInPandasExec [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunnerShims.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunnerShims.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuFlatMapGroupsInPandasExec.scala
Labels: task

#7885 Add Join Reordering Integration Test
  integration_tests/src/main/python/join_test.py
Labels: test

#7896 Update regular expression parser to handle escape character sequences
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
Labels: bug

#7887 Fix DPP/DFP cases when join keys are rewritten when there are multiple integral columns [databricks]
  integration_tests/src/main/python/delta_zorder_test.py
  integration_tests/src/main/python/dpp_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
Labels: bug

#7909 Interpolate buildver into secondaryCacheDir
  pom.xml
Labels: bug, build

#7906 ColumnarToRowIterator should release the semaphore if parent is empty
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
Labels: bug

#7916 Add clarification for Delta Lake optimized write fallback due to sorting [skip ci]
  docs/additional-functionality/delta-lake-support.md
Labels: documentation

#7905 [Doc] Fix some documentation issue based on VPR feedback on 23.04 branch (new PR) [skip CI]
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-workload-qualification.md
  docs/index.md
  docs/spark-qualification-tool.md
Labels: documentation

#7895 Some refactor of shuffled hash join
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
Labels: task

#7928 Adjust assert for SparkShims: no longer a per-shim file [skip ci]
  build/shimplify.py
Labels: bug, build

#7926 Fixes issue where UCX compressed tables would be decompressed multiple times
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
Labels: bug

#7877 Upgrade to UCX 1.14.0
  NOTICE-binary
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
Labels: shuffle

#7918 [Doc] Hotfix gh-pages branch for compatibility page format issue [skip ci]
  docs/compatibility.md
Labels: documentation

#7889 Support auto-compaction for Delta tables on [databricks]
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaSQLConf.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDoAutoCompaction.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransaction.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDoAutoCompaction.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransaction.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  docs/additional-functionality/delta-lake-support.md
  integration_tests/src/main/python/delta_lake_auto_compact_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: feature request, P0

#7930 Add OOM Retry handling for join gather next
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
Labels: feature request, P0, reliability

#7945 Enable automerge from 2304 to 2306 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#7951 Fix PMD docs URL [skip ci]
  docs/dev/shimplify.md
Labels: documentation

#7849 Fix CPU broadcast exchanges being left unreplaced due to AQE and reuse [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ReusedExchangeFixupSuite.scala
Labels: performance

#7948 Init plugin version 23.06.0-SNAPSHOT
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#7958 Add CheckpointRestore trait and withRestoreOnRetry
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: feature request, reliability

#7970 [DOCS] Updating qual tool docs from latest in tools repo
  docs/spark-qualification-tool.md
Labels: documentation, tools

#7925 Inject RetryOOM in CI where retry iterator is used
  integration_tests/conftest.py
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: reliability

#7936 Stop showing internal details of ternary expressions in SparkPlan.toString
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
Labels: task
