Repository NVIDIA/spark-rapids, pull requests merged in 2023-09, with the labels that each got.

#9128 Test parquet predicate pushdown for basic types and fields having dots in names [databricks]
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcFilterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
Labels: test, reliability

#9157 XFAIL parquet `lz4_raw` tests for Spark 3.5.0 or later
  integration_tests/src/main/python/parquet_testing_test.py
Labels: test, Spark 3.5+

#9188 Fix flaky tests in FileCacheIntegrationSuite
  tests/src/test/scala/org/apache/spark/sql/rapids/filecache/FileCacheIntegrationSuite.scala
Labels: test

#9134 Fix shuffle fallback due to AQE on AWS EMR [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/GpuShuffleMeta.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuShuffleMeta.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/GpuShuffleMeta.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/execution/GpuShuffleMeta.scala
Labels: performance

#9190 Prevent returning internal compiler expressions when compiling UDFs
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CatalystExpressionBuilder.scala
Labels: bug

#9170 Add in new HostAlloc API
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: reliability

#9195 Deploy sql-plugin-api artifact in DBR CI pipelines [skip ci]
  jenkins/databricks/deploy.sh
Labels: bug, test, build

#9183 Add test to verify UDT fallback for parquet
  tests/src/test/resources/udt.orc
  tests/src/test/scala/com/nvidia/spark/rapids/OrcQuerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetQuerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/TestingUDT.scala
  tests/src/test/spark330/scala/com/nvidia/spark/rapids/ParquetUDTSuite.scala
Labels: test

#9189 Expose host store spill
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: reliability

#9150 add error section in report and the rest queries
  datagen/src/main/scala/com/nvidia/rapids/tests/scaletest/TableGenerator.scala
  integration_tests/ScaleTest.md
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/QuerySpecs.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/ScaleTest.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/TaskFailureListener.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/TestReport.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/Utils.scala
Labels: test, data gen, scale test

#9192 Throw overflow exception when interval seconds are outside of range [0, 59] [databricks]
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtilsBase.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
Labels: Spark 3.5+

#9132 Support `spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY`
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: feature request, SQL, task, reliability

#9181 [DOC] address document issues [skip ci]
  .github/workflows/markdown-links-check/markdown-links-check-config.json
  docs/FAQ.md
  docs/img/Databricks/initscript.png
Labels: documentation

#9209 Fix tests for datetime rebase in Databricks [databricks]
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#9222 Deploy classified aggregator for Databricks [skip ci]
  jenkins/databricks/deploy.sh
Labels: bug

#9200 Fix a few minor things with scale test
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/QuerySpecs.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/ScaleTest.scala
Labels: scale test

#9225 Add in a HostAlloc API for high priority and add in spilling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: reliability

#8404 Add in support for FIXED_LEN_BYTE_ARRAY as binary
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/ParquetSchemaClipShims.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: Spark 3.4+

#9231 Use conda libmamba solver to resolve intermittent libarchive issue [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: bug, build

#9234 Enable Spark 350 builds
  pom.xml
Labels: build, Spark 3.5+

#9211 Allow skipping host spill for a direct device->disk spill
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractHostByteBufferIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostByteBufferIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: reliability

#9053 [DOC] update the turning guide document issues [skip ci]
  docs/get-started/best-practices.md
  docs/tuning-guide.md
Labels: documentation

#9240 Fix flaky ORC filecache test
  tests/src/test/scala/org/apache/spark/sql/rapids/filecache/FileCacheIntegrationSuite.scala
Labels: test

#9239 Handle escaping the dangling right ] and right } in the regexp transpiler
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionParserSuite.scala
Labels: performance

#9251 Enable a couple of retry asserts in internal row to cudf row iterator suite
  tests/src/test/scala/com/nvidia/spark/rapids/GeneratedInternalRowToCudfRowIteratorRetrySuite.scala
Labels: test

#9252 Add Spark 3.5.0 to list of supported Spark versions [skip ci]
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
Labels: documentation, task, Spark 3.5+

#9228 Add in unbounded to unbounded optimization for min/max
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: task

#9254 [Doc]update the emr getting started doc for emr-6130 release[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/name-and-applications.png
Labels: documentation

#9256 Test Parquet double column stat without NaN [databricks]
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScaleTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetScaleTestUtils.scala
Labels: test

#9262 Add Delta Lake support for Spark 3.4.1 and Delta Lake tests on Spark 3.4.x
  aggregator/pom.xml
  jenkins/spark-tests.sh
  pom.xml
Labels: feature request, test

#9266 Specify correct dependency versions for 350 build
  pom.xml
Labels: build, task, Spark 3.5+

#9267 Roll our own BufferedIterator so we can close cleanly
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CloseableBufferedIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ScalableTaskCompletion.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ScalableTaskCompletionSuite.scala
Labels: bug

#9270 Remove GDS spilling
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/gds-spilling.md
  pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferSendState.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandlerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
Labels: task

#9273 Add arm64 profile to build arm artifacts
  api_validation/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#9253 Enforce Scala method syntax over deprecated procedure syntax
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/GpuOptimisticTransaction.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/GpuOptimisticTransaction.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/GpuOptimisticTransaction.scala
  delta-lake/delta-24x/src/main/scala/org/apache/spark/sql/delta/rapids/delta24x/GpuOptimisticTransaction.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransaction.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransaction.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransaction.scala
  pom.xml
  scalastyle-config.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRunnableCommandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SamplingUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/PythonMapInArrowExecShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBatchUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
  tests/src/test/spark321/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala
Labels: task

#9257 Have host spill use the new HostAlloc API
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RmmSparkRetrySuiteBase.scala
Labels: reliability

#9264 Fix leak in test and double free in corner case
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GeneratedInternalRowToCudfRowIteratorRetrySuite.scala
Labels: test

#9294 Fix test_delta_read_column_mapping test failures on Spark 3.2.x and 3.3.x
  integration_tests/src/main/python/delta_lake_test.py
Labels: test

#9292 Init project version 23.12.0-SNAPSHOT
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  datagen/README.md
  datagen/ScaleTest.md
  datagen/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/ScaleTest.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shim-deps/cloudera/pom.xml
  shim-deps/databricks/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#9297 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#9229 Support negative preceding/following for ROW-based window functions
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request, cudf_dependency

#9286 [FEA][AUDIT][SPARK-44641] Incorrect result in certain scenarios when SPJ is not triggered
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/KeyGroupedPartitioningShim.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/KeyGroupedPartitioningShim.scala
Labels: bug, Spark 3.5+

#9313 Sort results of collect_list test before comparing since it is not guaranteed
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#9159 Update tests and documentation for `spark.sql.timestampType` when reading CSV/JSON
  docs/compatibility.md
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/json_test.py
Labels: documentation, test, Spark 3.5+

#9146 Improve some CSV integration tests [databricks]
  integration_tests/src/main/python/csv_test.py
Labels: test, task

#9287 Allow checkpoint and restore on non-deterministic expressions in GpuFilter and GpuProject
  dist/unshimmed-common-from-spark311.txt
  sql-plugin/src/main/java/com/nvidia/spark/Retryable.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuRandomExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/util/random/rapids/XORShiftRandom.scala
  tests/src/test/scala/com/nvidia/spark/rapids/NonDeterministicRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: reliability

#9308 Initiate arm64 CI support [skip ci]
  CONTRIBUTING.md
  jenkins/Dockerfile-blossom.multi
Labels: documentation, build

#9314 Fix RMM crash in FileCacheIntegrationSuite with ARENA memory allocator
  tests/src/test/scala/org/apache/spark/sql/rapids/filecache/FileCacheIntegrationSuite.scala
Labels: test

#9321 [DOC] Fix some incorrect config links in doc [skip ci]
  docs/FAQ.md
  docs/compatibility.md
  docs/get-started/getting-started-databricks.md
  docs/tuning-guide.md
Labels: documentation

#9221 Add GPU version of ToPrettyString [databricks]
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/GpuToPrettyString.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBatchUtilsSuite.scala
  tests/src/test/spark350/scala/com/nvidia/spark/rapids/ToPrettyStringSuite.scala
Labels: Spark 3.5+

#9318 Update authorized user in blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#9335 Temporarily skip failing tests test_csv_infer_schema_timestamp_ntz*
  integration_tests/src/main/python/csv_test.py
Labels: test

#9281 Support `format_number`
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#9329 Add kuhushukla to blossom ci yml
  .github/workflows/blossom-ci.yml
Labels: task

#9328 Building different Cuda versions section profile does not take effect [skip ci]
  CONTRIBUTING.md
Labels: documentation, build

#9330 Add Hao to blossom-ci whitelist
  .github/workflows/blossom-ci.yml
Labels: task
