Repository NVIDIA/spark-rapids, pull requests merged in 2023-01, with the labels that each got.

#7447 Xfail the test of pruning partition column for json read
  integration_tests/src/main/python/prune_partition_column_test.py
Labels: test

#7445 Support pruning partition columns for avro file scan
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AvroProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
Labels: bug

#7413 [Doc]update getting started doc for EMR and databricks[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
Labels: documentation

#7346 [Doc]revert the changes in FAQ for deltalake table support[skip ci]
  docs/FAQ.md
Labels: documentation

#7439 Suppress unknown RunnableCommand warnings by default
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: task

#7438 Add documentation for runnable command enable configs
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#7442 Fix parsing of Delta Lake logs containing multi-line JSON records
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#7420 Ubuntu build&test images default as 20.04
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#7417 Make cudf-udf tests runnable on Databricks 11.3 [databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
Labels: test, task

#7444 Explicitly check if the platform is supported
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: bug, good first issue

#7418 Fix for AQE+DPP issue on AWS EMR [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala
  tests/src/test/320+-noncdh-nondb/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
Labels: bug

#7431 Remove release script of spark-rapids/tools [skip ci]
  jenkins/deploy.sh
Labels: build

#7456 Sort Delta log objects when comparing and avoid caching all logs
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#7464 Enable integration tests against Databricks 11.3 in premerge [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#7474 xfail array zip tests
  integration_tests/src/main/python/array_test.py
Labels: test

#7460 More cases support partition column pruning
  integration_tests/src/main/python/prune_partition_column_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuFileScanPrunePartitionSuite.scala
Labels: performance

#7484 Fix arrays_zip to not rely on broken segmented gather
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: bug

#7475 Inject GpuCast for decimal AddSub when operands' precision/scale differ on 340, 330db [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until340-non330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/340+-and-330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: bug

#7497 Inserting multiple times to HashedPriorityQueue should not corrupt the heap
  sql-plugin/src/main/java/com/nvidia/spark/rapids/HashedPriorityQueue.java
  tests/src/test/java/com/nvidia/spark/rapids/TestHashedPriorityQueue.java
Labels: bug

#7489 Remove the MIT license from tools jar[skip ci]
  LICENSE
  NOTICE
  NOTICE-binary
Labels: documentation

#7434 Support `json_tuple`
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_tuple_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#7494 Implement a simplified version of `from_json`
  docs/compatibility.md
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, task, cudf_dependency

#7269 Add hadoop-def.sh to support multiple spark release tarballs
  jenkins/hadoop-def.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: build

#7509 Fix json_test.py imports
  integration_tests/src/main/python/json_test.py
Labels: test

#7414 batched full hash join
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: feature request, reliability

#7506 Add RapidsDeltaWrite node to fix undesired transitions with AQE
  docs/additional-functionality/delta-lake-support.md
  integration_tests/src/main/python/delta_lake_write_test.py
  sql-plugin/src/main/320+-nondb/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/320+-nondb/scala/org/apache/spark/sql/delta/rapids/shims/GpuOptimisticTransaction.scala
  sql-plugin/src/main/321+-db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuDeltaInvariantCheckerExec.scala
  sql-plugin/src/main/321+-db/scala/com/databricks/sql/transaction/tahoe/rapids/shims/GpuOptimisticTransactionBase.scala
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/delta/shims/DeltaProviderImpl.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/DeltaProviderImplBase.scala
  sql-plugin/src/main/delta-lake-common/scala/com/nvidia/spark/rapids/delta/RapidsDeltaWrite.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
Labels: task

#7504 Align CI test scripts with new init scripts for Databricks [skip ci]
  jenkins/databricks/run_it.sh
  jenkins/databricks/setup.sh
Labels: test

#7515 Fix leak in GpuHiveTableScanExec
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
Labels: bug

#7507 Fallback to CPU for unrecognized Distributions [databricks]
  sql-plugin/src/main/311until330-nondb/scala/com/nvidia/spark/rapids/shims/DistributionUtil.scala
  sql-plugin/src/main/312db/scala/com/nvidia/spark/rapids/shims/DistributionUtil.scala
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/shims/DistributionUtil.scala
  sql-plugin/src/main/330+-nondb/scala/com/nvidia/spark/rapids/shims/DistributionUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DistributionSuite.scala
Labels: task

#7522 Update docs and add Rapids shuffle manager for Databricks-11.3 [databricks]
  docs/FAQ.md
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/spark330db/RapidsShuffleManager.scala
  sql-plugin/src/main/330db/scala/org/apache/spark/sql/rapids/shims/spark330db/RapidsShuffleInternalManager.scala
Labels: bug, documentation

#7536 Fix datetime out-of-range error in pytest when timezone is not UTC
  integration_tests/src/main/python/data_gen.py
Labels: bug, test

#7539 Enable automerge from 23.02 to 23.04 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#7527 Allow concurrentGpuTasks to be set per job
  docs/configs.md
  docs/dev/README.md
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#7512 Adds RapidsBufferHandle as an indirection layer to RapidsBufferId
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleReceivedBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRDDConverterSuite.scala
Labels: performance, reliability

#7499 README.md for auditing purposes [skip ci]
  scripts/README.md
Labels: documentation

#7549 Remove unused Maven property shim.module.name
  CONTRIBUTING.md
  pom.xml
Labels: build

#7538 Fix Spark 340 build error due to change in KeyGroupedPartitioning
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala
  sql-plugin/src/main/330until340/scala/com/nvidia/spark/rapids/shims/KeyGroupedPartitioningShim.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/KeyGroupedPartitioningShim.scala
Labels: build, audit

#7541 Init version 23.04.0-SNAPSHOT [databricks]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#7513 Remove usage to `ColumnView.repeatStringsSizes`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: task, cudf_dependency, tech debt

#7555 Fix case where tracking batch is never updated in batched full join
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: bug, P0, reliability

#7532 Update Databricks docs to add a limitation against DB 11.3 [skip ci]
  docs/get-started/getting-started-databricks.md
Labels: documentation

#7567 Fix a small leak in generate
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
Labels: bug

#7554 Add mixed decimal testing for binary arithmetic ops
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#7589 Fix get started link in gh-pages
  index.md
Labels: documentation

#7584 Write test for multithreaded combine wrong buffer size bug
  integration_tests/src/main/python/parquet_test.py
Labels: test

#7578 Fix double close on exception in GpuCoalesceBatches
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: bug

#7596 Fix deprecation warnings
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#7211 Fix regressions related to cuDF changes in handline of end-of-line/string anchors
  docs/compatibility.md
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#7608 Skip/xfail some regexp tests
  integration_tests/src/main/python/regexp_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#7600 Centralize source-related properties in parent pom for consistent usage in submodules
  dist/pom.xml
  pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
Labels: bug

#7604 Fix memory leak in GpuIntervalUtilsTest
  tests/src/test/330+/scala/com/nvidia/spark/rapids/GpuIntervalUtilsTest.scala
Labels: test

#7618 Update JNI to 23.04.0-SNAPSHOT and update new delta-stub ver to 23.04
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-stub/pom.xml
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
Labels: test, build

#7590 Fix `json_tuple` cudf error and java array out-of-bound issue
  integration_tests/src/main/python/json_tuple_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
Labels: bug

#7571 Refact deploy script to support gpg and nvsec signature [skip ci]
  jenkins/deploy.sh
Labels: build

#7598 Disable decimal `pmod` due to #7553
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExprs.csv
Labels: task

#7626 Revert "Skip/xfail some regexp tests (#7608)"
  integration_tests/src/main/python/regexp_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#7621 Document GNU sed for macOS auto-copyrighter users [skip ci]
  CONTRIBUTING.md
Labels: documentation
