Repository NVIDIA/spark-rapids, pull requests merged in 2023-04, with the labels that each got.

#7986 Provides a config to expose Alluxio master URL to support K8s Env
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioConfigReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#7902 Add oom retry handling for createGatherer in gpu hash joins
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: feature request, improve, reliability

#8010 Specify that UCX should be 1.12.1 only [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation, shuffle

#8007 Fix leak where RapidsShuffleIterator for a completed task was kept alive
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
Labels: bug, shuffle

#8013 [Doc] Adding user tools info into EMR getting started guide [skip ci]
  docs/get-started/getting-started-aws-emr.md
Labels: documentation

#8006 Handle caused-by retry exceptions in withRestoreOnRetry
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: bug, reliability

#7828 Fallback to arena allocator if RMM failed to initialize with async allocator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: reliability

#8031 Fix regexp_replace integration test that should fallback when unicode is disabled
  integration_tests/src/main/python/regexp_no_unicode_test.py
Labels: test

#8034 Fix the check for dedicated per-shim files [skip ci]
  build/shimplify.py
Labels: task

#8040 Fix device vector leak in RmmRetryIterator.splitSpillableInHalfByRows
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: bug, P0, reliability

#8049 [DOC] Adding user tool info to main qualification docs page [skip ci]
  docs/spark-qualification-tool.md
Labels: documentation

#8051 MINOR: Improve assertion error in assert_py4j_exception
  integration_tests/src/main/python/asserts.py
Labels: test

#7996 Sub-partitioning supports repartitioning the input data multiple times
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSubPartitionSuite.scala
Labels: reliability

#8047 Enable line/string anchors in choice
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#8069 Fix loading extra jar [databricks]
  api_validation/src/main/scala/com/nvidia/spark/rapids/api/ApiValidation.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/DeltaIOProvider.scala
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/DeltaRuntimeShim.scala
  dist/unshimmed-common-from-spark311.txt
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKryoRegistrator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PlanUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimReflectionUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProviderImpl.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/zorder/ZOrderRules.scala
Labels: bug

#8077 Temporarily skip `test_parquet_read_nano_as_longs_31x` on dataproc
  integration_tests/src/main/python/parquet_test.py
Labels: test

#8087 Add an FAQ entry on encryption support [skip ci]
  docs/FAQ.md
Labels: documentation

#8075 Update some integration tests so that they are compatible with Spark 3.4.0
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/datasourcev2_write_test.py
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test, Spark 3.4+

#8101 Improve OOM exception messages
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: reliability

#8100 Update/improve EMR getting started documentation [skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/EMR_notebook_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2b.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_3.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_4.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/img/AWS-EMR/bootstrap-action.png
  docs/img/AWS-EMR/cluster-configuration.png
  docs/img/AWS-EMR/name-and-applications.png
  docs/img/AWS-EMR/networking.png
  docs/img/AWS-EMR/notebook-workspace-creation.png
  docs/img/AWS-EMR/ssh-key-pair.png
Labels: documentation

#8103 Add license of spark-rapids private in NOTICE-binary[skip ci]
  NOTICE-binary
Labels: documentation

#8060 Support repetitions in regexp choice expressions
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#8110 Update ML integration page docs page [skip ci]
  docs/additional-functionality/ml-integration.md
Labels: documentation

#8098 Fix loading of ORC files with missing column names
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
Labels: bug

#8127 Avoid SQL result check of Delta Lake full delete on Databricks [databricks]
  docs/additional-functionality/delta-lake-support.md
  integration_tests/src/main/python/delta_lake_delete_test.py
Labels: documentation, test

#8093 Add cuda12 build support [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#7939 [Doc]update download docs for 2304 version[skip ci]
  docs/FAQ.md
  docs/archive.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/img/Databricks/sparkconfig.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#8135 Fix Orc writer test failure with Spark 3.4
  tests/src/test/spark321/scala/com/nvidia/spark/rapids/OrcEncryptionSuite.scala
Labels: test, Spark 3.4+

#8109 Bump up JNI and private version to released 23.04.0
  aggregator/pom.xml
  pom.xml
Labels: build

#8092 Init changelog for 23.04 [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: documentation

#8139 Fix auto merge conflict 8138 [skip ci]
  CHANGELOG.md
  scripts/generate-changelog
Labels: build

#8096 Add OOM retry handling for existence joins
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ExistenceJoin.scala
Labels: reliability

#8136 Add GPU support for KnownNullable expression (Spark 3.4.0)
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/GpuKnownNullable.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala
Labels: Spark 3.4+

#8035 [FEA] support StringTranslate function
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#8142 Enable ParquetWriterSuite test 'sorted partitioned write' on Spark 3.4.0
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
Labels: test, Spark 3.4+

#8058 Add retry to BatchByKeyIterator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Arm.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKeyBatchingIterator.scala
Labels: reliability

#8146 Set version of slf4j for Spark 3.4.0
  pom.xml
Labels: Spark 3.4+

#8145 Fix nz timestamp unit tests
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: Spark 3.4+

#8128 Fix CastOpSuite failures with Spark 3.4
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/CastCheckShims.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/CastCheckShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CastCheckShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: Spark 3.4+

#8150 xfail test_substring_column
  integration_tests/src/main/python/string_test.py
Labels: test

#8154 Use repo1.maven.org/maven2 instead of default apache central url
  pom.xml
Labels: build

#8152 Fix Spark-3.4 test failure in AdaptiveQueryExecSuite
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: test, Spark 3.4+

#8143 Add handling for SplitAndRetryOOM in nextCbFromGatherer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
Labels: reliability

#8169 Fix AnsiCastShim for 330db [databricks]
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/AnsiCastShim.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/AnsiCastShim.scala
Labels: build

#8175 Restore test_substring_column
  integration_tests/src/main/python/string_test.py
Labels: test

#7227 Fix PCBS integration tests for Spark-3.4
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
Labels: bug, Spark 3.4+

#8172 Fix ORC decimal read when precision/scale changes
  integration_tests/src/main/python/orc_cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#8180 Follow-up for ORC Decimal read failure (#8172)
  integration_tests/src/main/python/orc_cast_test.py
Labels: test

#8159 Verify CPU fallback class when creating HIVE table [Databricks]
  integration_tests/src/main/python/hive_write_test.py
Labels: Spark 3.4+

#8177 Fix 340 shim of GpuCreateDataSourceTableAsSelectCommand and shim GpuDataSource for 3.4.0 [databricks]
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuDataSourceBase.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/GpuDataSource.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala
Labels: Spark 3.4+

#8165 [Doc] Update gh-pages branch for 23.04.0 release [skip ci]
  docs/FAQ.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/shimplify.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/img/AWS-EMR/EMR_notebook_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_2b.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_3.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_4.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/img/AWS-EMR/bootstrap-action.png
  docs/img/AWS-EMR/cluster-configuration.png
  docs/img/AWS-EMR/name-and-applications.png
  docs/img/AWS-EMR/networking.png
  docs/img/AWS-EMR/notebook-workspace-creation.png
  docs/img/AWS-EMR/ssh-key-pair.png
  docs/img/Databricks/sparkconfig.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/tuning-guide.md
Labels: documentation

#8183 Disable asserts for non-empty nulls
  integration_tests/run_pyspark_from_build.sh
  pom.xml
Labels: bug

#8167 Add oom retry handling to GpuGenerateExec.doGenerate path
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
Labels: feature request, reliability

#8182 Support STRING order-by columns for RANGE window functions
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
Labels: feature request, SQL, P0

#8193 Increase databricks cluster autotermination to 6.5 hours [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#8195 Bump mockito to 3.12.4
  pom.xml
Labels: test
