Repository NVIDIA/spark-rapids, pull requests merged in 2023-11, with the labels that each got.

#9439 Support stack function
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/generate_expr_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#9454 Support encryption and compression in disk store
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsSerializerManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsDiskBlockManager.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
Labels: feature request

#9594 Revert "Ignore failing Parquet filter test to unblock CI (#9519)"
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
Labels: test

#9586 Merge metrics and file format fixes to Delta 2.4 support
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/GpuDelta24xParquetFileFormat.scala
  delta-lake/delta-24x/src/main/scala/org/apache/spark/sql/delta/rapids/delta24x/GpuMergeIntoCommand.scala
Labels: bug

#9591 Enable implicit JDK profile activation [databricks]
  .github/workflows/mvn-verify-check.yml
  CONTRIBUTING.md
  aggregator/pom.xml
  datagen/README.md
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  jdk-profiles/pom.xml
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/delta-lake/delta-20x/pom.xml
  scala2.13/delta-lake/delta-21x/pom.xml
  scala2.13/delta-lake/delta-22x/pom.xml
  scala2.13/delta-lake/delta-24x/pom.xml
  scala2.13/delta-lake/delta-spark321db/pom.xml
  scala2.13/delta-lake/delta-spark330db/pom.xml
  scala2.13/delta-lake/delta-spark332db/pom.xml
  scala2.13/delta-lake/delta-stub/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/jdk-profiles/pom.xml
  scala2.13/pom.xml
  scala2.13/shim-deps/pom.xml
  shim-deps/pom.xml
Labels: build, Scala 2.13

#9544 Support batching for `RANGE` running window aggregations. Including on [databricks]
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: reliability

#9610 Propagate local properties to broadcast execs
  integration_tests/src/main/python/generate_expr_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/ShimBaseSubqueryExec.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/ShimBaseSubqueryExec.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/BroadcastLocalPropertySuite.scala
Labels: audit_3.5.0

#9607 Integration tests: Install specific fastparquet version. [databricks]
  integration_tests/requirements.txt
  integration_tests/src/assembly/bin.xml
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/setup.sh
Labels: test

#9626 Fix ENV typo in pre-merge github actions [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: bug, test

#9618 Remove unused dataTypes argument from HostShuffleCoalesceIterator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala
Labels: tech debt

#9611 Move simple classes after refactoring to sql-plugin-api
  dist/unshimmed-common-from-spark311.txt
  sql-plugin-api/src/main/java/com/nvidia/spark/RapidsUDF.java
  sql-plugin-api/src/main/java/com/nvidia/spark/Retryable.java
  sql-plugin-api/src/main/scala/com/nvidia/spark/ExclusiveModeGpuDiscoveryPlugin.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/SQLPlugin.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/udf/Plugin.scala
Labels: tech debt

#9617 Support rebase checking for nested dates and timestamps
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: task

#9608 Fix nullability issues for some decimal operations[databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCanonicalize.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: bug

#9624 Add jenkins-level retry for pre-merge build in databricks runtimes [databricks]
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#9423 Re-enable `from_json` / `JsonToStructs`
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request

#9641 Revert "Support rebase checking for nested dates and timestamps (#9617)" [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: task

#9623 Running window optimization for `LAST()`
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
Labels: reliability

#9615 Bloop updates - require JDK11 in buildall + docs, build bloop for all targets.
  CONTRIBUTING.md
  build/buildall
  pom.xml
  scala2.13/pom.xml
Labels: bug, build

#9655 Document problem with handling of invalid characters in CSV reader
  docs/compatibility.md
Labels: documentation

#9609 Add valid retry solution to mvn-verify [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: test, build

#9663 Making User Guide info in bold and adding it as top right link in github.io [skip ci]
  docs/_config.yml
  docs/index.md
Labels: documentation

#9635 Support split non-AST-able join condition for BroadcastNestedLoopJoin
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AstUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AstUtilSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: feature request

#9678 Add flow control for multithreaded shuffle writer
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedWriter.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/RapidsShuffleThreadedWriter.scala
  tests/src/test/spark321/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedWriterSuite.scala
Labels: bug, P0, reliability

#9693 Enable automerge from 23.12 to 24.02 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#9695 Revert "Support split non-AST-able join condition for BroadcastNested… [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AstUtil.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AstUtilSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
Labels: bug, test, build

#9658 Support `spark.sql.parquet.int96RebaseModeInWrite=LEGACY` [databricks]
  integration_tests/src/main/python/delta_lake_write_test.py
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: task

#9509 Fine-grained spill metrics
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
Labels: task, reliability

#9686 Removed Maven Profiles From `tests/pom.xml`
  scala2.13/tests/pom.xml
  tests/pom.xml
Labels: test

#9612 Escape quotes and newlines when converting strings to json format in to_json
  docs/compatibility.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: task

#9649 Support `spark.sql.parquet.datetimeRebaseModeInRead=LEGACY` and `spark.sql.parquet.int96RebaseModeInRead=LEGACY` [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: feature request

#9441 Add a random seed specific to datagen cases
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/ast_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/expand_exec_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#9726 Fix leak in BatchWithPartitionData
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/BatchWithPartitionData.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BatchWithPartitionDataSuite.scala
Labels: bug

#9732 Temporarily force `datagen_seed=0` for `test_re_replace_all` to unblock CI
  integration_tests/src/main/python/regexp_test.py
Labels: build

#9660 Fully support date/time legacy rebase for nested input [databricks]
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala
Labels: task

#9741 Set seed=0 for the delta lake part roundtrip tests [databricks]
  integration_tests/pytest.ini
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9745 Avoid generating null filter values in test_delta_dfp_reuse_broadcast_exchange [databricks]
  integration_tests/src/main/python/delta_zorder_test.py
Labels: test

#9748 Fix Delta Lake part_write_round_trip_unmanaged tests with floating point [databricks]
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9698 Speed up build: unnecessary invalidation in the incremental recompile mode [databricks]
  .github/workflows/mvn-verify-check.yml
  CONTRIBUTING.md
  aggregator/pom.xml
  build/buildall
  dist/pom.xml
  dist/scripts/binary-dedupe.sh
  integration_tests/src/assembly/bin.xml
  jenkins/databricks/build.sh
  jenkins/spark-premerge-build.sh
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/pom.xml
  scala2.13/sql-plugin/pom.xml
  sql-plugin/pom.xml
  tests/README.md
Labels: build

#9736 Fix `TimestampGen` to generate value not too close to the minimum allowed timestamp [databricks]
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#9652 Add time zone config to set non-UTC [databricks]
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/spark_session.py
Labels: test

#9758 Remove forced seed from Delta Lake part_write_round_trip_unmanaged tests [databricks]
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9761 Fix bug in tagging of JsonToStructs
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#9770 [BUG] Fix the doc for Maven and Scala 2.13 test example [skip ci]
  tests/README.md
Labels: bug, documentation

#9785 Force datagen_seed for 9781 and 9784 [skip ci]
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/string_test.py
Labels: test, P1

#9673 Fix the broadcast joins issues caused by InputFileBlockRule[databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/InputFileBlockRule.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: bug

#9666 Add support for parsing strings as dates in `from_json` [databricks]
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
Labels: feature request

#9769 Use withGpuSparkSession to customize SparkConf
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: bug, test

#9818 Specify nullable=False when generating filter values in dpp tests
  integration_tests/src/main/python/dpp_test.py
Labels: bug, test

#9720 Support timestamp in `from_json` [databricks]
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
Labels: feature request

#9812 Update JNI and private dep version to 24.02.0-SNAPSHOT [databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#9826 Set seed to 0 for test_hash_reduction_sum
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#9821 Update timestamp gens to avoid "year 0 is out of range" errors
  integration_tests/src/main/python/delta_lake_write_test.py
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#9786 Check paths for existence to prevent ignorable error messages during build
  aggregator/pom.xml
  dist/pom.xml
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/pom.xml
  scala2.13/sql-plugin/pom.xml
  sql-plugin/pom.xml
Labels: bug, build

#9835 Avoid pre-Gregorian dates in schema_evolution_test
  integration_tests/src/main/python/schema_evolution_test.py
Labels: test

#9809 Re-enable AST string integration cases
  integration_tests/src/main/python/ast_test.py
Labels: bug

#9848 Force datagen_seed for test_ceil_scale_zero and test_decimal_round
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#9773 xfail all the impacted cases when using non-UTC time zone [databricks]
  integration_tests/src/main/python/aqe_test.py
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/ast_test.py
  integration_tests/src/main/python/cache_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/cmp_test.py
  integration_tests/src/main/python/collection_ops_test.py
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/csv_test.py
  integration_tests/src/main/python/datasourcev2_read_test.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/expand_exec_test.py
  integration_tests/src/main/python/explain_test.py
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/hashing_test.py
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/limit_test.py
  integration_tests/src/main/python/map_test.py
  integration_tests/src/main/python/mortgage_test.py
  integration_tests/src/main/python/orc_cast_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_testing_test.py
  integration_tests/src/main/python/parquet_write_test.py
  integration_tests/src/main/python/qa_nightly_select_test.py
  integration_tests/src/main/python/repart_test.py
  integration_tests/src/main/python/row-based_udf_test.py
  integration_tests/src/main/python/row_conversion_test.py
  integration_tests/src/main/python/sample_test.py
  integration_tests/src/main/python/schema_evolution_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/struct_test.py
  integration_tests/src/main/python/subquery_test.py
  integration_tests/src/main/python/time_window_test.py
  integration_tests/src/main/python/udf_test.py
  integration_tests/src/main/python/window_function_test.py
  jenkins/spark-premerge-build.sh
Labels: test

#9840 Avoid using NaNs as Delta Lake partition values
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9864 Add compatibility documentation with respect to decimal overflow detection [skip ci]
  docs/compatibility.md
Labels: documentation

#9865 Fix problems with nulls in sequence tests
  integration_tests/src/main/python/collection_ops_test.py
Labels: test

#9654 Detect multiple jars on the classpath when init plugin [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: reliability

#9810 Support from_utc_timestamp on the GPU for non-UTC timezones (non-DST)
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/TimeZoneDB.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/timezone/TimeZoneSuite.scala
Labels: feature request

#9885 Preparation for non-UTC nightly CI [skip ci]
  jenkins/spark-tests.sh
Labels: test

#9871 Fix test_cast_string_date_valid_format generating year 0
  integration_tests/src/main/python/cast_test.py
Labels: test

#9656 Update for new retry state machine JNI APIs
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCX.scala
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/BatchWithPartitionData.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsShuffleHeartbeatManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TaskRegistryTracker.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/BufferReceiveState.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/BatchWithPartitionDataSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GeneratedInternalRowToCudfRowIteratorRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSortRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RmmSparkRetrySuiteBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowToColumnarIteratorRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClientSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIteratorSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriterSuite.scala
Labels: reliability

#9600 Add date and timestamp support to to_json [databricks]
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuStructsToJson.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/catalyst/json/GpuJsonUtils.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request

#9879 Fix resource leak in to_json
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: bug

#9874 Fix zero-scale floor and ceil tests
  integration_tests/src/main/python/arithmetic_ops_test.py
Labels: test

#9833 Fix a hang for Pandas UDFs on DB 13.3[databricks]
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/PythonUDFShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuPythonArrowShims.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/Spark341PlusDBShims.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuPythonArrowShims.scala
Labels: bug

#9888 Update nightly build and deploy script for arm artifacts [skip ci]
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
Labels: build

#9889 Fix test_cast_string_ts_valid_format test
  integration_tests/src/main/python/cast_test.py
Labels: bug, test
