Repository NVIDIA/spark-rapids, pull requests merged in 2023-08, with the labels that each got.

#8872 Terminate CI if fail to clone submodule [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#7233 [FEA] Support `order by` on single-level array
  docs/supported_ops.md
  integration_tests/src/main/python/sort_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request, cudf_dependency

#8917 Databricks shim version for integration test [databricks]
  jenkins/databricks/common_vars.sh
  jenkins/databricks/test.sh
Labels: test

#8931 Clone submodule using git command instead of checkoutSCM plugin
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#8927 Skipping test_map_scalars_supported_key_types because of distributed …
  integration_tests/src/main/python/map_test.py
Labels: bug, test

#8918 Output unified diff when GPU output deviates
  integration_tests/src/main/python/asserts.py
Labels: test

#8915 Move LegacyBehaviorPolicy references to shim layer [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/util/rapids/DateFormatter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/ParquetRecordMaterializer.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/LegacyBehaviorPolicyShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/spark321/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala
Labels: audit_3.5.0

#8924 Deprecate and delegate GpuCV.debug to cudf TableDebug
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: test

#8824 Drop the in-range check at INT96 output path [databricks]
  docs/compatibility.md
  integration_tests/src/main/python/delta_lake_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
Labels: cudf_dependency, reliability

#8744 Add test for selecting a single complex field array and its parent struct array [databricks]
  integration_tests/src/main/python/prune_partition_column_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
Labels: test

#8946 [Spark 3.5.0] Shim access to StructType.fromAttributes
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapCoGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/DataTypeUtilsShim.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
Labels: Spark 3.5+

#8957 Fix building dockerfile.cuda hanging at tzdata installation [skip ci]
  docs/get-started/Dockerfile.cuda
Labels: bug, build

#8892 Experimental support for BloomFilterAggregate expression in a reduction context [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuBloomFilterAggregate.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/spark330/scala/com/nvidia/spark/rapids/BloomFilterAggregateQuerySuite.scala
Labels: performance

#8909 Match Spark's NaN handling in collect_set
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
Labels: feature request

#8947 Add ArrowUtilsShims in preparation for Spark 3.5.0
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapCoGroupsInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInBatchExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunnerShims.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/ArrowUtilsShim.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunnerShims.scala
Labels: Spark 3.5+

#8940 Add test case for ORC statistics test
  integration_tests/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/orc/OrcSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/orc/TestBase.scala
  integration_tests/src/test/spark311/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
  integration_tests/src/test/spark320/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
Labels: test

#8920 Add test case to test orc dictionary encoding with lots of rows for nested types [databricks]
  tests/src/test/scala/com/nvidia/spark/rapids/OrcQuerySuite.scala
Labels: test

#8983 Revert OrcSuite to fix deployment build [databricks]
  integration_tests/pom.xml
  integration_tests/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/orc/OrcSuite.scala
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/orc/TestBase.scala
  integration_tests/src/test/spark311/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
  integration_tests/src/test/spark320/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
Labels: build

#8960 [Doc] address profiling tool formatted issue [skip ci]
  docs/spark-profiling-tool.md
Labels: documentation

#8990 Remove doc references to 312db [skip ci]
  CONTRIBUTING.md
  docs/dev/shimplify.md
Labels: documentation

#8971 Fix test_map_scalars_supported_key_types
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/map_test.py
Labels: test, reliability

#8948 [Doc]update download docs for 2308 version[skip ci]
  CONTRIBUTING.md
  docs/FAQ.md
  docs/additional-functionality/rapids-shuffle.md
  docs/archive.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#8987 Fix host memory buffer leaks in SerializationSuite
  tests/src/test/scala/com/nvidia/spark/rapids/SerializationSuite.scala
Labels: test

#8988 Move big data generator to a separate module
  datagen/README.md
  datagen/pom.xml
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  datagen/src/main/spark311/scala/org/apache/spark/sql/tests/datagen/DataGenExprBase.scala
  datagen/src/main/spark320/scala/org/apache/spark/sql/tests/datagen/datagen/DataGenExprBase.scala
  pom.xml
Labels: test

#8972 [Doc]Add best practice doc[skip ci]
  docs/get-started/best-practices.md
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-workload-qualification.md
  docs/tuning-guide.md
Labels: documentation

#8977 Create an anonymous subclass of AdaptiveSparkPlanHelper in ExecutionPlanCaptureCallback.scala [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
Labels: bug

#8949 Update JNI and private version to released 23.08.0 [databricks]
  pom.xml
Labels: build

#8970 Add ability to debug dump input data only on errors
  integration_tests/src/main/python/avro_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquet.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuBatchDataReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DumpUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: feature request

#8995 Add test case for ORC statistics test [databricks]
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/OrcSuite.scala
  tests/src/test/spark311/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
  tests/src/test/spark320/scala/com/nvidia/spark/rapids/shims/OrcStatisticShim.scala
Labels: test

#9001 [Doc]update the emr getting started doc for emr-6120 release[skip ci]
  docs/get-started/getting-started-aws-emr.md
  docs/img/AWS-EMR/name-and-applications.png
Labels: documentation

#9006 Revert test changes to fix binary dedup error [databricks]
  integration_tests/src/main/python/prune_partition_column_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
Labels: build

#9014 Updating link to download jar [skip ci]
  docs/get-started/getting-started-kubernetes.md
Labels: bug, documentation

#9016 Fix issue where murmur3 tried to work on array of structs
  docs/supported_ops.md
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#9013 Create a two-shim jar by default on Databricks [databricks]
  jenkins/databricks/build.sh
Labels: test, build

#8975 Init 23.08 changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#9024 Do not trigger snapshot spark version test in pre-release maven-verify checks [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: bug, test

#9023 Allow WindowLocalExec to run on CPU for a map test.
  integration_tests/src/main/python/map_test.py
Labels: bug, test

#9029 Update 23.08 changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#9009 Add in a layer of indirection for task completion callbacks [databricks]
  delta-lake/common/src/main/scala/com/nvidia/spark/rapids/delta/GpuRapidsProcessDeltaMergeJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/CurrentBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AutoCloseColumnBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/CloseableBufferedIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuKeyBatchingIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PartitionReaderIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ScalableTaskCompletion.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/python/PythonWorkerSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/shims/GpuFileScanRDD.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuBloomFilterMightContain.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/GpuDataSourceRDD.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSemaphoreSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriterSuite.scala
Labels: reliability

#9035 Handle null values when merging Bloom filters
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuBloomFilterAggregate.scala
Labels: bug

#9042 Bump up project version to 23.08.1-SNAPSHOT
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/DATA_GEN.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#9045 Fix auto merge conflict 9043 [skip ci]
  CONTRIBUTING.md
  docs/get-started/getting-started-databricks.md
Labels: documentation, build

#9036 Fix meta class cast exception when generator not supported
  integration_tests/src/main/python/generate_expr_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
Labels: bug

#9040 Fix issues from 23.08 merge in join_test
  integration_tests/src/main/python/join_test.py
Labels: test, build

#9044 [DOC] update release version from v2308.0 to 2308.1 [skip ci]
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#9048 Update 23.08 changelog 23/08/15 [skip ci]
  CHANGELOG.md
Labels: documentation

#9050 Merge branch 'branch-23.08' into main [skip ci]
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/DATA_GEN.md
  integration_tests/README.md
  integration_tests/pom.xml
  integration_tests/src/main/python/generate_expr_test.py
  integration_tests/src/main/python/join_test.py
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuBloomFilterAggregate.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#9051 Use number of threads on executor instead of driver to set core count
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: task

#8934 Implement SumUnboundedToUnboundedFixer
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: reliability

#9061 Fix import order
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/parquet/ShimCurrentBatchIterator.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TestUtils.scala
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CFG.scala
Labels: task

#9072 Revert "Implement SumUnboundedToUnboundedFixer (#8934)"
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: bug

#9067 Add array support for round robin partition; Refactor pluginSupportedOrderableSig [databricks]
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuShuffleExchangeExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/zorder/ZOrderRules.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala
Labels: bug

#9018 Add test for selecting a single complex field array and its parent struct array [databricks]
  dist/unshimmed-common-from-spark311.txt
  integration_tests/src/main/python/prune_partition_column_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AdaptiveSparkPlanHelperImpl.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
Labels: test

#9073 Stop using invalid escape sequences
  integration_tests/src/main/python/get_json_test.py
  integration_tests/src/main/python/regexp_test.py
Labels: test

#9066 Add retry support to RowToColumnarIterator
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowToColumnarIteratorRetrySuite.scala
Labels: reliability

#9070 Spillable host buffer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: reliability

#9054 Initial entry point to data generation for scale test
  datagen/README.md
  datagen/ScaleTest.md
  datagen/pom.xml
  datagen/src/main/scala/com/nvidia/rapids/tests/scaletest/ScaleTestDataGen.scala
  datagen/src/main/scala/com/nvidia/rapids/tests/scaletest/TableGenerator.scala
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
Labels: data gen

#9068 Test ORC predicate pushdown (PPD) with timestamps decimals booleans
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcPushDownSuite.scala
Labels: test

#9038 [DOC] updates gh-pages files for 23.08 release [skip ci]
  docs/FAQ.md
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/filecache.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/archive.md
  docs/configs.md
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/dev/shimplify.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/best-practices.md
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/img/AWS-EMR/name-and-applications.png
  docs/spark-profiling-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#9093 Update ParquetFormatScanSuite to not call CUDF directly
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFormatScanSuite.scala
Labels: test

#9095 Support released spark 3.3.3
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  sql-plugin/src/main/spark333/scala/com/nvidia/spark/rapids/shims/spark333/SparkShimServiceProvider.scala
Labels: build

#8961 Save Databricks init scripts in the workspace [databricks]
  docs/additional-functionality/rapids-shuffle.md
  docs/img/Databricks/initscript_ucx.png
  jenkins/Jenkinsfile-blossom.premerge-databricks
  jenkins/databricks/clusterutils.py
  jenkins/databricks/create.py
  jenkins/databricks/init_cuda11_runtime.sh
  jenkins/databricks/init_cudf_udf.sh
Labels: documentation, build

#9085 Retry with smaller split on `CudfColumnSizeOverflowException`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: bug

#9109 [DOC] adding java 11 to download docs [skip ci]
  docs/download.md
Labels: documentation

#8925 Add GpuConv operator for the `conv` 10<->16 expression
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: task

#9100 Support broadcast nested loop existence joins with no condition
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHelper.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/TestTrampolineUtil.scala
Labels: bug

#9117 Temply disable spark 350 shim build in nightly [skip ci]
  pom.xml
Labels: bug, build

#9091 GPU support for DynamicPruningExpression and InSubqueryExec
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDynamicPruningExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/InSubqueryShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuInSubqueryExec.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/InSubqueryShims.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/GpuInSubqueryExecSuite.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: performance

#9098 Add SpillableHostColumnarBatch
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBuffer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/SerializedHostTableUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: task, reliability

#9115 [DOC] updates documentation related to java compatibility [skip ci]
  docs/download.md
Labels: documentation

#9124 Import `scala.collection` intead of `collection`
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
Labels: Spark 3.5+

#9133 Add 350 tag to InSubqueryShims
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/GpuInSubqueryExec.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/InSubqueryShims.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/GpuInSubqueryExecSuite.scala
Labels: build

#9140 Bump Jython to 2.7.3
  pom.xml
Labels: build

#8476 Use retry with split in GpuCachedDoublePassWindowIterator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: reliability

#9143 [DOC] update spark.rapids.sql.concurrentGpuTasks default value in tuning guide [skip ci]
  docs/tuning-guide.md
Labels: documentation

#9089 Add application to run Scale Test
  datagen/ScaleTest.md
  integration_tests/README.md
  integration_tests/ScaleTest.md
  integration_tests/pom.xml
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/IdleSessionListener.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/QuerySpecs.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/ScaleTest.scala
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/scaletest/TestReport.scala
Labels: test, data gen, scale test

#9102 Add retry support to GpuOutOfCoreSortIterator.mergeSortEnoughToOutput
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarToRowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: reliability

#9158 Add json4s dependencies for Databricks integration_tests build [databricks]
  integration_tests/pom.xml
  jenkins/databricks/install_deps.py
Labels: build
