Repository NVIDIA/spark-rapids, pull requests merged in 2023-10, with the labels that each got.

#9352 Refine rules for skipping `test_csv_infer_schema_timestamp_ntz_*` tests
  integration_tests/src/main/python/csv_test.py
Labels: test

#9365 Update DataWriteCommandExec docs to reflect ORC support for nested types
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExecs.csv
Labels: documentation

#9362 [DOC] Removing User Guide pages that will be source of truth on docs.nvidia…
  README.md
  docs/FAQ.md
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/filecache.md
  docs/additional-functionality/iceberg-support.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/download.md
  docs/examples.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/best-practices.md
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-azure-synapse-analytics.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/get-started/yarn-gpu.md
  docs/index.md
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
  integration_tests/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
Labels: documentation

#9238 Simplified handling of GPU core dumps
  docs/dev/gpu-core-dumps.md
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/GpuCoreDumpMsg.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoreDumpHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoreDumpHandlerSuite.scala
Labels: task

#9382 Bump up project version to 23.08.2 [databricks]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#9385 Merge branch-23.08 to main for v23.08.2 release [skip ci]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#9351 Put back in full decimal support for format_number
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#9388 Add developer documentation about working with data sources [skip ci]
  docs/dev/README.md
  docs/dev/data-sources.md
Labels: documentation, task

#9381 Change the executor core calculation to take into account the cluster manager
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: bug

#9401 Remove using mamba before they fix the incompatibility issue [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: bug, build

#9392 Only run test_json_ts_formats_round_trip_ntz tests with PySpark >= 3.4.1
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/spark_session.py
Labels: test, build

#9407 [Doc]Update docs for 23.08.2 version[skip ci]
  CONTRIBUTING.md
  docs/archive.md
  docs/download.md
Labels: documentation

#9409 [DOC]Updates ghpages for 23.08.2 release[skip ci]
  docs/archive.md
  docs/configs.md
  docs/dev/shims.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-on-prem.md
Labels: documentation

#9415 [BUG] fix docker modified check in premerge [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: bug, build

#9424 Refactor aggregate functions [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/GpuApproximatePercentile.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/BloomFilterShims.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/aggregate/GpuBloomFilterAggregate.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/PythonUDFShim.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregateRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressionsSuite.scala
Labels: SQL, improve, tech debt

#9420 Update private and jni dep version to released 23.10.0
  pom.xml
Labels: build

#9380 Fix parsing of Parquet legacy list-of-struct format
  integration_tests/src/main/python/parquet_testing_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: cudf_dependency

#9445 Only run test_csv_infer_schema_timestamp_ntz tests with PySpark >= 3.4.1
  integration_tests/src/main/python/csv_test.py
Labels: test

#9421 Init changelog of 23.10 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.06.md
Labels: documentation

#9453 Update codeowner and blossom-ci ACL [skip ci]
  .github/CODEOWNERS
  .github/workflows/blossom-ci.yml
Labels: build

#9434 Add retry support to `HostToGpuCoalesceIterator.concatAllAndPutOnGPU`
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HostColumnToGpuRetrySuite.scala
Labels: reliability

#9427 [DOC] Update docs for 23.10.0 release [skip ci]
  CONTRIBUTING.md
  docs/archive.md
  docs/dev/testing.md
  docs/download.md
Labels: documentation

#9425 Add support for AtomicCreateTableAsSelect with Delta Lake [databricks]
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeltaCatalogBase.scala
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeltaLog.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DatabricksDeltaProvider.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DeleteCommandMeta.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/MergeIntoCommandMeta.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/UpdateCommandMeta.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/DeltaIOProvider.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/RapidsDeltaUtils.scala
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/DeltaRuntimeShim.scala
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/GpuDeltaCatalogBase.scala
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/GpuDeltaLog.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/DeleteCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/Delta20xProvider.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/MergeIntoCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/UpdateCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/Delta20xRuntimeShim.scala
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/GpuDeltaCatalog.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/DeleteCommandMeta.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/Delta21xProvider.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/MergeIntoCommandMeta.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/UpdateCommandMeta.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/Delta21xRuntimeShim.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/GpuDeltaCatalog.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/DeleteCommandMeta.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/Delta22xProvider.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/MergeIntoCommandMeta.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/UpdateCommandMeta.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/Delta22xRuntimeShim.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/GpuDeltaCatalog.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/DeleteCommandMeta.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/Delta24xProvider.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/GpuDeltaCatalog.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/MergeIntoCommandMeta.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/UpdateCommandMeta.scala
  delta-lake/delta-24x/src/main/scala/org/apache/spark/sql/delta/rapids/delta24x/Delta24xRuntimeShim.scala
  delta-lake/delta-24x/src/main/scala/org/apache/spark/sql/delta/rapids/delta24x/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeltaCatalog.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeltaCatalog.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeltaCatalog.scala
  integration_tests/src/main/python/delta_lake_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AtomicCreateTableAsSelectExecMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/ShimTrampolineUtil.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
Labels: feature request

#9459 Fix 332cdh build [skip ci]
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicCreateTableAsSelectExec.scala
Labels: build

#9460 Update links in old release notes to new doc locations [skip ci]
  docs/archive.md
Labels: documentation

#9479 Merge branch-23.10 to main [skip ci]
  CONTRIBUTING.md
  docs/archive.md
  docs/dev/testing.md
  docs/download.md
Labels: documentation

#9476 Refactor common Delta Lake test code [databricks]
  integration_tests/src/main/python/delta_lake_auto_compact_test.py
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_merge_test.py
  integration_tests/src/main/python/delta_lake_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/delta_lake_utils.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#9443 Add AtomicReplaceTableAsSelectExec support for Delta Lake [databricks]
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DatabricksDeltaProvider.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/DeltaIOProvider.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/Delta20xProvider.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/Delta21xProvider.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/Delta22xProvider.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/Delta24xProvider.scala
  integration_tests/src/main/python/delta_lake_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/v2WriteCommandMetas.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicReplaceTableAsSelectExec.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicReplaceTableAsSelectExec.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicReplaceTableAsSelectExec.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicReplaceTableAsSelectExec.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/execution/datasources/v2/rapids/GpuAtomicReplaceTableAsSelectExec.scala
Labels: feature request

#9296 Implement `percentile` aggregation
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/GpuPercentile.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, cudf_dependency

#9500 Fix Spark 3.5.0 shell classloader issue with the plugin
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: bug

#9419 Add retry to RoundRobin Partitioner and Range Partitioner
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRangePartitioner.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRoundRobinPartitioning.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ShufflePartitionerRetrySuite.scala
Labels: reliability

#9366 Add tests to check compatibility with `fastparquet`
  integration_tests/README.md
  integration_tests/requirements.txt
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/setup.sh
Labels: test

#9478 Support AppendDataExecV1 for Delta Lake tables [databricks]
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DatabricksDeltaProvider.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/DeltaIOProvider.scala
  integration_tests/src/main/python/delta_lake_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/v2WriteCommandMetas.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/v1FallbackWriters.scala
Labels: feature request

#9519 Ignore failing Parquet filter test to unblock CI
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
Labels: test, build

#9522 Update 23.10 changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#9524 Merge branch-23.10 to main [skip ci]
  CHANGELOG.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: build

#9504 Add a spark-shell smoke test to premerge and nightly [databricks]
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: test

#9289 Add tests to check compatibility with pyarrow [databricks]
  integration_tests/README.md
  integration_tests/conftest.py
  integration_tests/pytest.ini
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/parquet_pyarrow_test.py
  integration_tests/src/main/python/pyarrow_utils.py
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: test

#9506 Move ProxyShuffleInternalManagerBase to api [databricks]
  datagen/pom.xml
  dist/unshimmed-common-from-spark311.txt
  integration_tests/pom.xml
  shim-deps/databricks/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimReflectionUtils.scala
  sql-plugin-api/src/main/scala/org/apache/spark/sql/rapids/ProxyRapidsShuffleInternalManagerBase.scala
  sql-plugin-api/src/main/scala/org/apache/spark/sql/rapids/execution/UnshimmedTrampolineUtil.scala
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ExplainPlan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PlanShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoaderTemp.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProvider.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExternalSource.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ShimmedExecutionPlanCaptureCallbackImpl.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: tech debt

#9525 Follow-up to dbdeps consolidation [databricks]
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  pom.xml
Labels: build, tech debt

#9444 Remove redundant pass-through shuffle manager classes [databricks]
  dist/unshimmed-from-each-spark3xx.txt
  docs/dev/shims.md
  pom.xml
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin-api/src/main/scala/org/apache/spark/sql/rapids/ProxyRapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/ExecutionPlanCaptureCallback.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/spark311/RapidsShuffleManager.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/spark311/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark312/scala/com/nvidia/spark/rapids/spark312/RapidsShuffleManager.scala
  sql-plugin/src/main/spark312/scala/org/apache/spark/sql/rapids/shims/spark312/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark313/scala/com/nvidia/spark/rapids/spark313/RapidsShuffleManager.scala
  sql-plugin/src/main/spark313/scala/org/apache/spark/sql/rapids/shims/spark313/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/spark320/RapidsShuffleManager.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/spark320/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark321/scala/com/nvidia/spark/rapids/spark321/RapidsShuffleManager.scala
  sql-plugin/src/main/spark321/scala/org/apache/spark/sql/rapids/shims/spark321/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark321cdh/scala/com/nvidia/spark/rapids/spark321cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark321cdh/scala/org/apache/spark/sql/rapids/shims/spark321cdh/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/spark321db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/shims/spark321db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark322/scala/com/nvidia/spark/rapids/spark322/RapidsShuffleManager.scala
  sql-plugin/src/main/spark322/scala/org/apache/spark/sql/rapids/shims/spark322/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark323/scala/com/nvidia/spark/rapids/spark323/RapidsShuffleManager.scala
  sql-plugin/src/main/spark323/scala/org/apache/spark/sql/rapids/shims/spark323/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark324/scala/com/nvidia/spark/rapids/spark324/RapidsShuffleManager.scala
  sql-plugin/src/main/spark324/scala/org/apache/spark/sql/rapids/shims/spark324/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/spark330/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/spark330/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark330cdh/scala/com/nvidia/spark/rapids/spark330cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330cdh/scala/org/apache/spark/sql/rapids/shims/spark330cdh/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/spark330db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/shims/spark330db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark331/scala/com/nvidia/spark/rapids/spark331/RapidsShuffleManager.scala
  sql-plugin/src/main/spark331/scala/org/apache/spark/sql/rapids/shims/spark331/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark332/scala/com/nvidia/spark/rapids/spark332/RapidsShuffleManager.scala
  sql-plugin/src/main/spark332/scala/org/apache/spark/sql/rapids/shims/spark332/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark332cdh/scala/com/nvidia/spark/rapids/spark332cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark332cdh/scala/org/apache/spark/sql/rapids/shims/spark332cdh/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/spark332db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/spark332db/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark333/scala/com/nvidia/spark/rapids/spark333/RapidsShuffleManager.scala
  sql-plugin/src/main/spark333/scala/org/apache/spark/sql/rapids/shims/spark333/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/spark340/RapidsShuffleManager.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/shims/spark340/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark341/scala/com/nvidia/spark/rapids/spark341/RapidsShuffleManager.scala
  sql-plugin/src/main/spark341/scala/org/apache/spark/sql/rapids/shims/spark341/RapidsShuffleInternalManager.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/spark350/RapidsShuffleManager.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/spark350/RapidsShuffleInternalManager.scala
Labels: tech debt

#9534 Add pyarrow tests for Databricks runtime [databricks]
  jenkins/databricks/test.sh
Labels: test

#9539 Add delta-24x to delta-lake/README.md [skip ci]
  delta-lake/README.md
Labels: documentation

#9468 Add SplitAndRetry to GpuRunningWindowIterator
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
Labels: reliability

#9418 Fix STRUCT comparison between Pandas and Spark dataframes in fastparquet tests
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  integration_tests/src/main/python/fastparquet_utils.py
Labels: test

#9548 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#9527 Support Split And Retry for GpuProjectAstExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
Labels: reliability

#9551 Enable malformed Parquet failure test
  integration_tests/src/main/python/parquet_testing_test.py
Labels: test

#9558 Support integration test against scala2.13 spark binaries[skip ci]
  jenkins/spark-tests.sh
Labels: build

#9554 Fix fastparquet installation for [databricks]
  jenkins/databricks/setup.sh
Labels: test, build

#9489 Batching support for ROW-based `FIRST()` window function
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
Labels: improve, reliability

#9557 Support launching Map Pandas UDF on empty partitions
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowPythonRunner.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInBatchExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/ArrowUtilsShim.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/ArrowUtilsShim.scala
Labels: bug

#9487 [DOC] updates gh-pages files for 23.10 release [skip ci]
  docs/FAQ.md
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/filecache.md
  docs/additional-functionality/gds-spilling.md
  docs/additional-functionality/iceberg-support.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/gpu-core-dumps.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/examples.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/best-practices.md
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-alluxio.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-azure-synapse-analytics.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-kubernetes.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/get-started/getting-started.md
  docs/get-started/yarn-gpu.md
  docs/img/AWS-EMR/name-and-applications.png
  docs/img/Databricks/initscript.png
  docs/img/Databricks/initscript_ucx.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
  index.md
Labels: documentation

#9568 Enforce Apache 3.3.0+ for Scala 2.13
  pom.xml
  scala2.13/pom.xml
Labels: build

#9574 Fix broken #endif scala comments [skip ci]
  pom.xml
  scala2.13/pom.xml
Labels: bug, build

#9576 Move Stack classes to wrapper classes to fix non-deterministic build issue
  sql-plugin/src/main/scala-2.12/com/nvidia/spark/rapids/RapidsStack.scala
  sql-plugin/src/main/scala-2.13/com/nvidia/spark/rapids/RapidsStack.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: task

#9562 Delta Lake 2.3.0 support
  aggregator/pom.xml
  delta-lake/README.md
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/DeltaRuntimeShim.scala
  delta-lake/delta-23x/pom.xml
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/DeleteCommandMeta.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/Delta23xProvider.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/GpuDelta23xParquetFileFormat.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/GpuDeltaCatalog.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/MergeIntoCommandMeta.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/delta23x/UpdateCommandMeta.scala
  delta-lake/delta-23x/src/main/scala/com/nvidia/spark/rapids/delta/shims/MetadataShims.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/Delta23xRuntimeShim.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/GpuCreateDeltaTableCommand.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/GpuDeleteCommand.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/GpuMergeIntoCommand.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/GpuOptimisticTransaction.scala
  delta-lake/delta-23x/src/main/scala/org/apache/spark/sql/delta/rapids/delta23x/GpuUpdateCommand.scala
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/delta-lake/delta-23x/pom.xml
  scala2.13/pom.xml
Labels: feature request

#9508 Consolidate deps switching in an intermediate pom [databricks]
  aggregator/pom.xml
  api_validation/pom.xml
  datagen/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/api_validation/pom.xml
  scala2.13/datagen/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/integration_tests/pom.xml
  scala2.13/pom.xml
  scala2.13/shim-deps/databricks/pom.xml
  scala2.13/shim-deps/pom.xml
  scala2.13/shuffle-plugin/pom.xml
  scala2.13/sql-plugin-api/pom.xml
  scala2.13/sql-plugin/pom.xml
  scala2.13/tests/pom.xml
  scala2.13/udf-compiler/pom.xml
  shim-deps/databricks/pom.xml
  shim-deps/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
Labels: bug, build, tech debt

#9583 Fix fastparquet tests to work with HDFS
  integration_tests/src/main/python/fastparquet_compatibility_test.py
Labels: test
