Repository NVIDIA/spark-rapids, pull requests merged in 2023-07, with the labels that each got.

#8608 Matrix stages to dynamically build Databricks shims [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#8645 Fix "PytestUnknownMarkWarning: Unknown pytest.mark.inject_oom" warning
  integration_tests/pytest.ini
  integration_tests/src/main/python/marks.py
Labels: test

#8658 Check if need to run Databricks pre-merge [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: bug, build

#8389 Add filecache support for ORC [databricks]
  docs/additional-functionality/filecache.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchScanExecMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostMemoryStreams.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuOrcDataReader.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/OrcShims311until320Base.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuOrcDataReader.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuOrcDataReaderBase.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/OrcShims320untilAllBase.scala
  sql-plugin/src/main/spark321cdh/scala/com/nvidia/spark/rapids/shims/GpuOrcDataReader.scala
  sql-plugin/src/main/spark321cdh/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  sql-plugin/src/main/spark321cdh/scala/com/nvidia/spark/rapids/shims/OrcShims321CDHBase.scala
  sql-plugin/src/main/spark330cdh/scala/com/nvidia/spark/rapids/shims/OrcShims.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/filecache/FileCacheIntegrationSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/filecache/NoFileCacheIntegrationSuite.scala
Labels: feature request

#8495 Speed up PCBS CPU read path by not recalculating as much
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
Labels: bug, performance

#8650 Support TIMESTAMP_SECONDS, TIMESTAMP_MILLIS and TIMESTAMP_MICROS [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TimeOperatorsSuite.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#8671 Fix use-after-freed bug in `GpuFloatArrayMin`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: bug

#8681 changed container name to adapt to blossom-lib refactor [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#8637 Support Float order-by columns for RANGE window functions [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/gpuWindows.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request

#8682 [DOC] Update CUDA requirements in documentation and Dockerfiles[skip ci]
  docs/download.md
  docs/get-started/Dockerfile.cuda
  docs/get-started/getting-started-gcp.md
  jenkins/Dockerfile-blossom.integration.rocky
Labels: documentation, build

#8687 Handle TIMESTAMP_MILLIS for rebase check
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
Labels: bug

#7465 Add support for arrays in hashaggregate [databricks]
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/repart_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request, cudf_dependency

#8704 Add tests for column names with dots
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#8695 Always create the main artifact along with a shim-classifier artifact [databricks]
  .github/workflows/mvn-verify-check.yml
  CONTRIBUTING.md
  aggregator/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#8707 Update config docs for new filecache configs [skip ci]
  docs/additional-functionality/advanced_configs.md
Labels: documentation

#8673 Fix some potential memory leaks
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesSuite.scala
Labels: bug

#8705 Add schema evolution integration tests for partitioned data
  integration_tests/src/main/python/schema_evolution_test.py
Labels: test

#8711 Factor out modules shared among shim profiles [databricks]
  pom.xml
Labels: build

#8728 Use specific mamba version and install libarchive explictly [skip ci]
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: build

#8706 Add a tool to support generating large amounts of data
  integration_tests/DATA_GEN.md
  integration_tests/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  integration_tests/src/main/spark311/scala/org/apache/spark/sql/tests/datagen/DataGenExprBase.scala
  integration_tests/src/main/spark320/scala/org/apache/spark/sql/tests/datagen/DataGenExprBase.scala
Labels: test

#8737 Fix parquet_write_test.py::test_hive_timestamp_value failure for Databricks [databricks]
  integration_tests/src/main/python/parquet_write_test.py
Labels: bug, test

#8769 Remove iceberg scripts from Databricks test scripts [databricks]
  jenkins/databricks/run_it.sh
  jenkins/databricks/test.sh
Labels: build

#8684 Add 'submodule update --init' when build spark-rapids
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#8772 Test concurrent writer update file metrics [databricks]
  delta-lake/common/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaTaskStatisticsTracker.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/BasicColumnarWriteStatsTracker.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/spark320/scala/com/nvidia/spark/rapids/ConcurrentWriterMetricsSuite.scala
Labels: test

#8777 Install python packages with shared scripts on Databricks [databricks]
  jenkins/databricks/test.sh
Labels: build

#8790 Update ubuntu dockerfiles default to 20.04 and deprecating centos one [skip ci]
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/get-started/Dockerfile.cuda
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/init_cudf_udf.sh
Labels: build

#8791 Auto merge to branch-23.10 from branch-23.08[skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#8796 Init version 23.10.0-SNAPSHOT
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  docs/dev/shims.md
  docs/get-started/getting-started-on-prem.md
  integration_tests/DATA_GEN.md
  integration_tests/README.md
  integration_tests/pom.xml
  jenkins/databricks/create.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  shuffle-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: build

#8801 Fix shuffling an empty Struct() column with UCX
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleClient.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#8805 Bump up dep versions to 23.10.0-SNAPSHOT [databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
Labels: build

#8829 Enable rle_boolean_encoding.parquet test
  integration_tests/src/main/python/parquet_testing_test.py
Labels: test

#8802 Treat unbounded windows as truly non-finite.
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
Labels: bug

#8848 Try mitigate mismatched JDK versions in mvn-verify checks [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: bug, build

#8852 Update test scripts and dockerfiles to match cudf change [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/init_cudf_udf.sh
Labels: test

#8854 Fix auto merge conflict 8853 [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/databricks/init_cudf_udf.sh
Labels: build

#8783 Fix collect_set_on_nested_type tests failed
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#8799 Add tests to cover some odd corner cases with nulls and empty arrays
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#8830 Update documentation to add Databricks 12.2 as a supported platform [skip ci]
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#8869 Specify expected JAVA_HOME and bin for mvn-verify-check [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: bug, build

#8857 Remove the pageable pool
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AddressSpaceAllocator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillPriorities.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AddressSpaceAllocatorSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: reliability

#8871 Adjust parallelism in spark-tests script to reduce memory footprint [skip ci]
  jenkins/spark-tests.sh
Labels: test
