Repository NVIDIA/spark-rapids, pull requests merged in 2023-02, with the labels that each got.

#7609 Fallback to CPU for mod only for DB11.3 [Databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/311until340-non330db/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/340+-and-330db/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#7633 Bump up add-to-project version to 0.4.0 [skip ci]
  .github/workflows/add-to-project.yml
Labels: build

#7628 Disable HiveTextReaders for CDH due to NVIDIA#7423
  sql-plugin/src/main/330cdh/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/330cdh/scala/org/apache/spark/sql/hive/cdh/HiveOverrides.scala
Labels: task

#7632 Update UCX shuffle doc w/ memlock limit config [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#7644 Create a new ColumnarBatch from the broadcast when LazySpillable takes ownership
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: bug

#7638 Update UCX docs to call out Ubuntu 22.04 is not supported yet [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#7620 Support Delta Lake DeleteCommand
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DeleteCommandMeta.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DeltaProviderImpl.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/DeleteCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/Delta20xProvider.scala
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/GpuDeleteCommand.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/DeleteCommandMeta.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/Delta21xProvider.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/GpuDeleteCommand.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/DeleteCommandMeta.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/Delta22xProvider.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/GpuDeleteCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  docs/additional-functionality/delta-lake-support.md
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: feature request

#7576 Support EXECUTOR_BROADCAST on Databricks 11.3 in BroadcastNestedLoopJoin [databricks]
  integration_tests/src/main/python/aqe_test.py
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/311until340-non330db/scala/com/nvidia/spark/rapids/shims/GpuBroadcastJoinMeta.scala
  sql-plugin/src/main/311until340-non330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/GpuBroadcastJoinMeta.scala
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala
  sql-plugin/src/main/330db/scala/org/apache/spark/sql/rapids/execution/GpuShuffleMeta.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/GpuBroadcastJoinMeta.scala
  sql-plugin/src/main/340+/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: feature request

#7653 Add dynamic partitioning test for Parquet writer.
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test, task

#7680 Fix Parquet dynamic partition test for [databricks]
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#7673 Add missing spark shim test suites
  sql-plugin/src/test/311/scala/com/nvidia/spark/rapids/shims/spark311/SparkShimsSuite.scala
  sql-plugin/src/test/312/scala/com/nvidia/spark/rapids/shims/spark312/SparkShimsSuite.scala
  sql-plugin/src/test/313/scala/com/nvidia/spark/rapids/shims/spark313/SparkShimsSuite.scala
  sql-plugin/src/test/320/scala/com/nvidia/spark/rapids/shims/spark320/SparkShimsSuite.scala
  sql-plugin/src/test/321/scala/com/nvidia/spark/rapids/shims/spark321/SparkShimsSuite.scala
  sql-plugin/src/test/321cdh/scala/com/nvidia/spark/rapids/shims/spark321cdh/SparkShimsSuite.scala
  sql-plugin/src/test/322/scala/com/nvidia/spark/rapids/shims/spark322/SparkShimsSuite.scala
  sql-plugin/src/test/323/scala/com/nvidia/spark/rapids/shims/spark323/SparkShimsSuite.scala
  sql-plugin/src/test/330/scala/com/nvidia/spark/rapids/shims/spark330/SparkShimsSuite.scala
  sql-plugin/src/test/330cdh/scala/com/nvidia/spark/rapids/shims/spark330cdh/SparkShimsSuite.scala
  sql-plugin/src/test/331/scala/com/nvidia/spark/rapids/shims/spark331/SparkShimsSuite.scala
  sql-plugin/src/test/332/scala/com/nvidia/spark/rapids/shims/spark332/SparkShimsSuite.scala
  sql-plugin/src/test/340/scala/com/nvidia/spark/rapids/shims/spark340/SparkShimsSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/FQSuiteName.scala
Labels: test

#7652 Support Delta Lake UpdateCommand
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/DeltaProviderImpl.scala
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/UpdateCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/Delta20xProvider.scala
  delta-lake/delta-20x/src/main/scala/com/nvidia/spark/rapids/delta/delta20x/UpdateCommandMeta.scala
  delta-lake/delta-20x/src/main/scala/org/apache/spark/sql/delta/rapids/delta20x/GpuUpdateCommand.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/Delta21xProvider.scala
  delta-lake/delta-21x/src/main/scala/com/nvidia/spark/rapids/delta/delta21x/UpdateCommandMeta.scala
  delta-lake/delta-21x/src/main/scala/org/apache/spark/sql/delta/rapids/delta21x/GpuUpdateCommand.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/Delta22xProvider.scala
  delta-lake/delta-22x/src/main/scala/com/nvidia/spark/rapids/delta/delta22x/UpdateCommandMeta.scala
  delta-lake/delta-22x/src/main/scala/org/apache/spark/sql/delta/rapids/delta22x/GpuUpdateCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  docs/additional-functionality/delta-lake-support.md
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: feature request

#7667 Reenable tests originally bypassed for 3.4 [databricks]
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
Labels: Spark 3.4+

#7687 Fix window tests for Spark-3.4
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
Labels: Spark 3.4+

#7556 Write support for Hive delimited text tables [databricks]
  docs/configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/311until340-all/scala/org/apache/spark/sql/hive/rapids/shims/GpuCreateHiveTableAsSelectCommand.scala
  sql-plugin/src/main/311until340-all/scala/org/apache/spark/sql/hive/rapids/shims/GpuHiveTextFileFormat.scala
  sql-plugin/src/main/311until340-all/scala/org/apache/spark/sql/hive/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/311until340-all/scala/org/apache/spark/sql/hive/rapids/shims/HiveProviderCmdShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/TypeChecks.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTextFileUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  tools/generated_files/supportedDataSource.csv
Labels: feature request

#7697 Disable Dynamic partitioning tests on CDH
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: bug, test

#7572 Enables spillable/unspillable state for RapidsBuffer and allow buffer sharing
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandler.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsDiskStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsGdsStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsHostMemoryStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShuffleReceivedBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  tests/src/test/scala/com/nvidia/spark/rapids/DeviceMemoryEventHandlerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuPartitioningSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsBufferCatalogSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDeviceMemoryStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsDiskStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsGdsStoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsHostMemoryStoreSuite.scala
Labels: performance, reliability

#7702 Merge 23.02 into 23.04
  integration_tests/src/main/python/hive_delimited_text_test.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: build

#7708 Set Hive write test to ignore order on verification.
  integration_tests/src/main/python/hive_delimited_text_test.py
Labels: bug, test

#7700 Init 23.02 changelog and move 22 changelog to archives [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_22.02_to_22.12.md
  scripts/generate-changelog
Labels: documentation

#7712 Enable Dynamic FIle Pruning on [databricks]
  integration_tests/src/main/python/delta_zorder_test.py
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
Labels: feature request

#7718 GpuParquetScan fails with NullPointerException during combining
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#7721 Fix issue where UCX mode was trying to use catalog from the driver [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug, shuffle

#7728 Fix estimatedNumBatches in case of OOM for Full Outer Join
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: bug, reliability

#7734 Temporarily skip the test_parquet_read_ignore_missing on Databricks
  integration_tests/src/main/python/parquet_test.py
Labels: test

#7737 Workaround for cudf setup in databricks 11.3 runtime [databricks]
  jenkins/databricks/init_cudf_udf.sh
Labels: bug, build

#7735 Update JNI version to released 23.02.0
  pom.xml
Labels: build

#7740 Revert 7737 workaround for cudf setup in databricks 11.3 runtime [skip ci]
  jenkins/databricks/init_cudf_udf.sh
Labels: bug, test

#7716 Clean the code of `GpuMetrics`
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
Labels: bug

#7570 [Doc] 23.02 doc updates [skip ci]
  docs/archive.md
  docs/compatibility.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/img/Databricks/sparkconfig.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
Labels: documentation

#7760 Add notice in gds to install cuda 11.8 [skip ci]
  docs/additional-functionality/gds-spilling.md
Labels: documentation

#7761 [Doc] remove xgboost demo from aws-emr doc due to nccl issue [skip ci]
  docs/get-started/getting-started-aws-emr.md
Labels: documentation

#7763 23.02 changelog update 2/14 [skip ci]
  CHANGELOG.md
Labels: documentation

#7758 Hardcode python 3.8 to be used in databricks runtime for cudf_udf ENV [databricks]
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
  jenkins/databricks/init_cudf_udf.sh
  jenkins/databricks/test.sh
Labels: bug, test

#7747 batched full join tracking batch does not need to be lazy
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: improve, tech debt

#7717 Move Databricks variables into blossom-lib [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#7772 Fix cache test for Spark 3.3.2 [databricks]
  pom.xml
  sql-plugin/src/main/311until332-all/scala/com/nvidia/spark/rapids/shims/ParquetLegacyNanoAsLongShims.scala
  sql-plugin/src/main/332+/scala/com/nvidia/spark/rapids/shims/ParquetLegacyNanoAsLongShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
Labels: bug

#7780 Make AlluxioUtilsSuite pass for 340
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioUtilsSuite.scala
Labels: test

#7769 Fix issue where GpuSemaphore can throw NPE when logDebug is on
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
Labels: bug

#7095 Fix the failure in `map_test.py` on Spark 3.4 [databricks]
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  sql-plugin/src/main/340+/scala/com/nvidia/spark/rapids/shims/Spark340PlusShims.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: Spark 3.4+

#7788 Support released spark 3.3.2
  .github/workflows/mvn-verify-check.yml
  docs/additional-functionality/rapids-shuffle.md
  pom.xml
  sql-plugin/src/main/332/scala/com/nvidia/spark/rapids/shims/spark332/SparkShimServiceProvider.scala
Labels: build

#7730 [FEA] Switch to `regex_program` APIs
  sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/GpuIntervalUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: task

#7786 Fix nested loop joins when there's no build-side columns
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: bug

#7787 Document a workaround to RuntimeException 'boom' [skip ci]
  CONTRIBUTING.md
  build/buildall
  jenkins/databricks/build.sh
Labels: documentation, task

#7798 Do not error out DB IT test script when pytest code 5 [skip ci]
  jenkins/databricks/run_it.sh
Labels: test, build

#7781 [Doc] Update gh-pages branch for 23.02.0 release [skip ci]
  docs/FAQ.md
  docs/additional-functionality/delta-lake-support.md
  docs/additional-functionality/gds-spilling.md
  docs/additional-functionality/ml-integration.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/rapids-udfs.md
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/AWS-EMR/Mortgage-ETL-GPU-EMR.ipynb
  docs/demo/Databricks/Mortgage-ETL-db.ipynb
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/README.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/get-started/getting-started-workload-qualification.md
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_1.png
  docs/img/AWS-EMR/RAPIDS_EMR_GUI_5.png
  docs/img/Databricks/sparkconfig.png
  docs/img/Databricks/sparkconfig_ucx.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#7561 Ant task to automatically convert to a simple shim layout
  CONTRIBUTING.md
  build/shimplify.py
  docs/dev/shimplify.md
  pom.xml
Labels: documentation, task

#7797 Add GPU support for EphemeralSubstring [databricks]
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/321+-db/scala/com/nvidia/spark/rapids/shims/Spark321PlusDBShims.scala
Labels: performance

#7791 Doc changes for new nested JSON reader [skip ci]
  docs/compatibility.md
Labels: documentation

#7815 Fix the hyperlink to shimplify.py [skip ci]
  docs/dev/shimplify.md
Labels: documentation

#7771 Add withRetry and withRetryNoSplit and PoC with hash aggregate
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSemaphoreSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RapidsAggregateRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WithRetrySuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/SpillableColumnarBatchSuite.scala
Labels: reliability

#7810 UnXfail large decimal window range queries [databricks]
  integration_tests/src/main/python/window_function_test.py
Labels: test, Spark 3.4+

#7821 Restore pandas import check in db113 runtime
  integration_tests/src/main/python/udf_cudf_test.py
  integration_tests/src/main/python/udf_test.py
Labels: bug

#7823 [BUG] Enable managed memory only if async allocator is not used
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug, P0, reliability

#7678 Premerge CI to drop support for Databricks-9.1 ML LTS [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  pom.xml
Labels: build
