Repository NVIDIA/spark-rapids, pull requests merged in 2023-06, with the labels that each got.

#8462 Fix compressed Hive text read on [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
Labels: bug, build

#8464 Remove NOP Maven javadoc plugin definition
  .github/workflows/mvn-verify-check.yml
  CONTRIBUTING.md
  build/buildall
  integration_tests/pom.xml
  jenkins/spark-premerge-build.sh
  pom.xml
  scalastyle-config.xml
Labels: build

#8433 Add regression test for regexp_replace hanging with some inputs
  docs/compatibility.md
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRegExpReplaceMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: test

#8467 Add retry support to GpuExpandExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: reliability

#8414 Add support for computing remainder with Decimal128 operands with more precision on Spark 3.4 [databricks]
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/DecimalArithmeticOverrides.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
Labels: Spark 3.4+

#8488 Adds note on multi-threaded shuffle targetting <= 200 partitions and on TCP keep-alive for UCX [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation, shuffle

#8485 Disable `test_read_compressed_hive_text` on CDH.
  integration_tests/src/main/python/hive_delimited_text_test.py
Labels: test

#8481 Removed spark.rapids.sql.castDecimalToString.enabled and enabled GPU decimal to string by default [databricks]
  docs/configs.md
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuExpressionTestSuite.scala
Labels: feature request

#8486 Move task completion listener registration to after variables are initialized
  delta-lake/common/src/main/scala/com/nvidia/spark/rapids/delta/GpuRapidsProcessDeltaMergeJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala
Labels: task

#8426 Pre-merge CI to support Databricks 12.2 [databricks]
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#8427 [Doc] address Spark RAPIDS NVAIE VDR issues [skip ci]
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-gcp.md
  docs/img/AWS-EMR/spark-history-server-UI.png
Labels: documentation

#8494 Fix 23.08 build on Databricks 12.2
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala
Labels: bug

#8515 Fix warning about deprecated parquet config
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: task

#8509 Remove legacy spark version check
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
Labels: test

#8516 Avoid calling Table.merge with BinaryType columns
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/sort_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
Labels: bug

#8441 Memoizing DataGens in integration tests
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/window_function_test.py
Labels: test

#8521 List supported Spark versions when no shim found
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
Labels: feature request

#8338 Moved some configs to an advanced config page
  dist/pom.xml
  docs/additional-functionality/advanced_configs.md
  docs/configs.md
  docs/dev/README.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsPrivateUtil.scala
Labels: documentation

#8529 Init changelog 23.06 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.04.md
  scripts/generate-changelog
Labels: documentation

#8526 Fix `from_json` function failure when input contains empty or null strings
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#8537 Add limitation for the UCX shuffle keep_alive workaround [skip ci]
  docs/additional-functionality/rapids-shuffle.md
Labels: documentation

#8510 [Doc] address getting-started-on-prem document issues [skip ci]
  docs/get-started/getting-started-on-prem.md
  docs/img/join-sql-ui-example.png
Labels: documentation

#8492 [Doc]update download docs for 2306 version[skip ci]
  docs/archive.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-databricks.md
Labels: documentation

#8528 Update deps JNI and private version to 23.06.0
  pom.xml
Labels: build

#8507 Handle caching empty batch
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
Labels: bug, test

#8549 Revert "Handle caching empty batch (#8507)" [databricks]
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
Labels: bug, test

#8503 Remove hard-coded version numbers for dependencies when building on [databricks]
  jenkins/databricks/build.sh
  jenkins/databricks/install_deps.py
Labels: build

#8557 Disable `JsonToStructs` for input schema other than `Map<String, String>`
  docs/supported_ops.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExprs.csv
Labels: bug

#8560 Fix relative path in config doc [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#8562 Update changelog to latest 230612 [skip ci]
  CHANGELOG.md
Labels: documentation

#8570 Update changelog to latest [skip ci]
  CHANGELOG.md
Labels: documentation

#8572 Merge branch-23.06 to main [skip ci]
  CHANGELOG.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#8574 Remove maxTaskFailures=4 for pre-3.1.1 Spark [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: test

#8553 Handle empty batch in ParquetCachedBatchSerializer [databricks]
  integration_tests/src/main/python/cache_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CachedBatchWriterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala
Labels: bug

#8564 Fold `verify-all-modules-with-headSparkVersion` into `verify-all-modules` [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: test, build

#8581 Fix 321db 330db shims build errors caused by DB updates
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuMergeIntoCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  jenkins/databricks/build.sh
Labels: bug, build

#8584 Update 23.06 changelog 6/19 [skip ci]
  CHANGELOG.md
Labels: documentation

#8585 Merge branch-23.06 to main [skip ci]
  CHANGELOG.md
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuMergeIntoCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  jenkins/databricks/build.sh
Labels: build

#8582 Fix databricks shims build errors caused by DB updates
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuMergeIntoCommand.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark321db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuMergeIntoCommand.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark330db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuDeleteCommand.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuMergeIntoCommand.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimizeExecutor.scala
  delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuUpdateCommand.scala
Labels: bug, build

#8589 Revert to the JVM-based Spark version extraction in pytests
  integration_tests/run_pyspark_from_build.sh
Labels: test

#8599 Fix broken links in advanced_configs.md
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: documentation

#8555 Support `flatten` SQL function
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, task, cudf_dependency

#8590 Drop ".dev0" suffix from Spark SNASHOT distro builds
  integration_tests/run_pyspark_from_build.sh
Labels: test

#8566 [Doc] Update gh-pages branch for 23.06.0 release [skip ci]
  docs/FAQ.md
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/filecache.md
  docs/additional-functionality/rapids-shuffle.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.centos_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/demo/Databricks/generate-init-script.ipynb
  docs/dev/README.md
  docs/dev/shimplify.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/get-started/getting-started-OCI.md
  docs/get-started/getting-started-aws-emr.md
  docs/get-started/getting-started-databricks.md
  docs/get-started/getting-started-gcp.md
  docs/get-started/getting-started-on-prem.md
  docs/img/AWS-EMR/spark-history-server-UI.png
  docs/img/Databricks/initscript.png
  docs/img/join-sql-ui-example.png
  docs/spark-profiling-tool.md
  docs/spark-qualification-tool.md
  docs/supported_ops.md
  docs/tuning-guide.md
Labels: documentation

#8578 Add in metric to see how much computation time is lost due to retry
  docs/tuning-guide.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
Labels: reliability

#8613 Try print JVM core dump files if any test failures in CI
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: test

#8639 Add iceberg test for nightly DB12.2 IT pipeline[skip ci]
  jenkins/databricks/run_it.sh
Labels: bug, test

#8638 Support nested structs for `min`/`max` aggregations
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: feature request, SQL, task, cudf_dependency

#8632 Fix GCP examples and getting started guide [skip ci]
  docs/demo/GCP/Mortgage-ETL.ipynb
  docs/demo/GCP/mortgage-xgboost4j-gpu-scala.ipynb
  docs/get-started/getting-started-gcp.md
Labels: documentation

#8628 Enable Delta Write fallback tests on Databricks 12.2 [databricks]
  integration_tests/src/main/python/delta_lake_merge_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#8517 Revert "Disable asserts for non-empty nulls (#8183)" [databricks]
  integration_tests/run_pyspark_from_build.sh
  pom.xml
Labels: bug
