Repository NVIDIA/spark-rapids, pull requests merged in 2024-03, with the labels that each got.

#10465 Add missed shims for scala2.13
  pom.xml
  scala2.13/pom.xml
Labels: build

#10525 Update changelog for v24.02.0 release [skip ci]
  CHANGELOG.md
Labels: documentation

#10521 Fix Spark 3.5.1 build
  aggregator/pom.xml
  scala2.13/aggregator/pom.xml
Labels: build

#10519 Replicate HostColumnVector.ColumnBuilder in plugin to enable host memory oom work
  sql-plugin/src/main/java/com/nvidia/spark/rapids/ColumnarCopyHelper.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/InternalColumnarRddConverter.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/GpuTypeShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
Labels: feature request, reliability

#10512 Move to parsing from_json input preserving quoted strings.
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
Labels: task

#10503 Distinct inner join
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance, cudf_dependency

#10541 Fix Delta log cache size settings during integration tests [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: test

#10546 Update changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#10547 Merge branch 'branch-24.02' into main [skip ci]
  CHANGELOG.md
  integration_tests/run_pyspark_from_build.sh
Labels: build

#10544 Fix merge conflict from branch-24.02
  integration_tests/run_pyspark_from_build.sh
Labels: build

#10549 Update to latest branch-24.02 [skip ci]
  CHANGELOG.md
Labels: build

#10522 Fix missing scala-parser-combinators dependency on Databricks [databricks]
  jenkins/databricks/install_deps.py
  scala2.13/shim-deps/databricks/pom.xml
  shim-deps/databricks/pom.xml
Labels: build

#10555 Update change log [skip ci]
  CHANGELOG.md
Labels: documentation

#10557 Merge branch 'branch-24.02' into main [skip ci]
  CHANGELOG.md
  integration_tests/src/main/python/dpp_test.py
Labels: build

#10552 Fix issues when no value can be extracted from a regular expression
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#10538 Move K8s cloud name into common lib for Jenkins CI
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#10520 Distinct left join
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/JoinGatherer.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance, cudf_dependency

#10564 Enable specifying specific integration test methods via TESTS environment
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
Labels: test

#10562 Fix test_spark_from_json_date_with_format when run in a non-UTC TZ
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/json_test.py
Labels: test

#10550 Enable window-group-limit optimization on [databricks]
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/GpuWindowGroupLimitExec.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/Spark341PlusDBShims.scala
Labels: performance

#10447 [DOC] updates gh-pages files for 24.02.0 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/rapids-udfs.md
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/README.md
  docs/dev/mem_debug.md
  docs/dev/microk8s.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation

#10568 Add configuration to share JNI pinned pool with cuIO
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request, performance, cudf_dependency

#10572 Improve performance of Sort for the common single batch use case
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSortRetrySuite.scala
Labels: performance

#10590 Turn on transition logging in HostAllocSuite
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: test

#10540 Handle minimum GPU architecture supported [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuArchitectureTestSuite.scala
Labels: feature request

#10597 add guardword to hide cloud info
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#10620 Remove unused shared lib in Jenkins files
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#10623 Auto merge PRs to branch-24.06 from branch-24.04 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#10630 Fix removal of internal metadata information in 350 shim
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuCreateDataSourceTableAsSelectCommandShims.scala
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/SchemaMetadataShims.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/SchemaMetadataShims.scala
  tests/src/test/spark350/scala/org/apache/spark/sql/rapids/GpuCreateDataSourceTableAsSelectCommandSuite.scala
Labels: audit_3.5.0, Spark 3.5+
