Repository NVIDIA/spark-rapids, pull requests merged in 2024-07, with the labels that each got.

#11115 Fix match error in RapidsShuffleIterator.scala [scala2.13]
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
Labels: bug

#11099 Spark 4: Handle ANSI mode in sort_test.py
  integration_tests/src/main/python/sort_test.py
Labels: Spark 4.0+

#11117 Update Scala2.13 premerge CI against JDK17
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-premerge-build.sh
Labels: build

#10965 Profiler: Disable collecting async allocation events by default
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/profiler.scala
Labels: tools

#11043 Dataproc serverless test fixes
  integration_tests/README.md
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/join_test.py
Labels: test

#11118 Fix issue with DPP and AQE on reused broadcast exchanges [databricks]
  integration_tests/src/main/python/aqe_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
Labels: bug

#11097 Fix miscellaneous integ tests for Spark 4 [databricks]
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/dpp_test.py
  integration_tests/src/main/python/grouping_sets_test.py
  integration_tests/src/main/python/map_test.py
Labels: test, Spark 4.0+

#11133 Fix `test_window_group_limits_fallback` [databricks]
  integration_tests/src/main/python/window_function_test.py
Labels: test

#11139 Improve MetricsSuite to allow more gc jitter [databricks]
  tests/src/test/scala/com/nvidia/spark/rapids/MetricsSuite.scala
Labels: bug, test

#11138 Update fastparquet to 2024.5.0 for numpy2 compatibility [databricks]
  integration_tests/requirements.txt
  integration_tests/src/main/python/fastparquet_compatibility_test.py
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/databricks/setup.sh
Labels: bug, test, build

#11147 upgrade ucx to 1.17.0
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: feature request

#11151 Fix the test error of the bucketed write for the non-utc case
  integration_tests/src/main/python/hive_parquet_write_test.py
Labels: test

#11102 Fix ANSI mode failures in subquery_test.py [databricks]
  integration_tests/src/main/python/subquery_test.py
Labels: test, Spark 4.0+

#11164 fix the bucketed write error for non-utc cases
  integration_tests/src/main/python/datasourcev2_write_test.py
Labels: test

#11126 Coalesce batches after a logical coalesce operation
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: task

#11165 Fix some GpuBroadcastToRowExec by not dropping columns [databricks]
  integration_tests/src/main/python/aqe_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala
Labels: bug

#10951 Case when performance improvement: reduce the `copy_if_else` [databricks]
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnVectorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
Labels: performance

#11141 Enable some Rapids config in RapidsSQLTestsBaseTrait for Spark UT
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11197 Fix class not found error: com/nvidia/spark/rapids/GpuScalar
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnVectorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala
Labels: bug

#11205 Update docs for 24.06.1 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#11144 Build the Scala2.13 dist jar with JDK17
  jenkins/spark-nightly-build.sh
Labels: build

#11202 Fix read from Delta Lake table with name column mapping and missing Parquet IDs
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormatBase.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala
  integration_tests/src/main/python/delta_lake_test.py
Labels: bug

#11211 Use fixed seed for test_from_json_struct_decimal
  integration_tests/src/main/python/json_test.py
Labels: bug, test

#11217 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#11221 Change cudf version back to 24.06.0-SNAPSHOT [skip ci]
  jenkins/version-def.sh
Labels: build

#11222 Update change log for v24.06.1 release [skip ci]
  CHANGELOG.md
Labels: documentation

#11194 Fix ANSI mode test failures in url_test.py [databricks]
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/url_test.py
Labels: Spark 4.0+

#11163 Support `MapFromArrays` on GPU [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  integration_tests/src/main/python/hive_parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMapUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#11226 Fix auto merge conflict 11212
  CHANGELOG.md
  integration_tests/src/main/python/json_test.py
Labels: documentation, build

#11220 Avoid failing spark bug SPARK-44242 while generate run_dir [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: test

#11230 Skip test where Delta Lake may not be fully compatible with Spark
  integration_tests/src/main/python/delta_lake_test.py
Labels: test

#11200 Multi-get_json_object [databricks]
  delta-lake/common/src/main/databricks/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
  delta-lake/common/src/main/delta-io/scala/org/apache/spark/sql/delta/rapids/GpuOptimisticTransactionBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBoundAttribute.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExecMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregateRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/NonDeterministicRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
Labels: performance

#11231 Cache dependencies for scala 2.13 [skip ci]
  .github/workflows/mvn-verify-check.yml
  .github/workflows/mvn-verify-check/populate-daily-cache.sh
Labels: build

#11238 Update gh-pages for 24.06.1 release [skip ci]
  docs/archive.md
  docs/configs.md
  docs/dev/shims.md
  docs/download.md
Labels: documentation

#11237 Fork jvm for maven-source-plugin
  aggregator/pom.xml
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/pom.xml
Labels: bug

#11236 Remove the unused vars from the version-def CI script
  jenkins/version-def.sh
Labels: build

#11149 Rework on substring index
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: performance

#11241 Auto merge PRs to branch-24.10 from branch-24.08 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#11246 Rework Maven Source Plugin Skip
  .github/workflows/mvn-verify-check.yml
  aggregator/pom.xml
  dist/pom.xml
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/pom.xml
Labels: bug

#11247 Fix `string_test.py` errors on Spark 4.0
  integration_tests/src/main/python/string_test.py
Labels: audit_4.0.0

#11259 CI Docker to support integration tests with Rocky OS + jdk17 [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
Labels: build

#11244 Fix ArrayIndexOutOfBoundsException on join counts with constant join keys
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: bug

#11268 Fix degenerate conditional nested loop join detection [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: bug

#11260 Mitigate intermittent test_buckets and shuffle_smoke_test OOM issue [databricks]
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/test.sh
Labels: bug, test

#11269 Revert "upgrade ucx to 1.17.0"
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: bug

#10917 Adopt changes from JNI for casting from float to decimal
  integration_tests/src/main/python/cast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: bug, SQL, task

#11280 Asynchronously copy table data to the host during shuffle
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPartitioning.scala
Labels: performance
