Repository NVIDIA/spark-rapids, pull requests merged in 2024-12, with the labels that each got.

#11802 Fall back to CPU for non-UTC months_between
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: bug, test

#11819 Add the 'test_type' parameter for Databricks script
  jenkins/Jenkinsfile-blossom.premerge-databricks
  jenkins/databricks/params.py
  jenkins/databricks/run-build.py
  jenkins/databricks/run-tests.py
Labels: build, improve

#11826 Balance the pre-merge CI job's time for the ci_1 and ci_2 tests
  integration_tests/src/main/python/join_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/main/python/window_function_test.py
  pom.xml
  scala2.13/pom.xml
Labels: build, improve

#11763 Orc writes don't fully support Booleans with nulls
  integration_tests/src/main/python/datasourcev2_write_test.py
  integration_tests/src/main/python/hive_parquet_write_test.py
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/orc_test.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/schema_evolution_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcFilterSuite.scala
Labels: bug

#11832 Fix leak in GpuBroadcastNestedLoopJoinExecBase
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
Labels: bug

#11817 Optimize Databricks Jenkins scripts [skip ci]
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#11811 Fix bug: populate cache deps [skip ci]
  .github/workflows/mvn-verify-check/populate-daily-cache.sh
Labels: bug, build

#11823 Fix for `LEAD/LAG` window function test failures.
  integration_tests/src/main/python/window_function_test.py
Labels: test

#11840 Support running Databricks CI_PART2 integration tests with JARs built by CI_PART1 [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build, improve

#11857 Increase the pre-merge CI timeout to 6 hours
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#11805 Enable some integration tests for `from_json`
  integration_tests/src/main/python/json_test.py
Labels: test

#11841 [DOC] update doc for 24.12 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#11867 Generate the CHANGELOG based on the PR's target branch [skip ci]
  scripts/generate-changelog
Labels: bug

#11870 Workaround: Exclude cudf_log.txt in RAT check
  .gitignore
  pom.xml
  scala2.13/pom.xml
Labels: bug, build

#11833 Support `trunc` and `date_trunc` SQL function
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, task

#11849 Update rapids JNI and private dependency to 24.12.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#11851 Update latest changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.08.md
Labels: build

#11874 Remove 350db143 shim's build [skip ci]
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#11876 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: build

#11877 Fix auto merge conflict 11873 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.08.md
Labels: build

#11894 Fix bug: add timeout for cache deps steps [skip ci]
  .github/workflows/mvn-verify-check.yml
Labels: build

#11890 Update operatorsScore,supportedExprs for TruncDate, TruncTimestamp
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
Labels: documentation

#11898 Add missing json reader options for JsonScanRetrySuite
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonReadCommon.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JsonScanRetrySuite.scala
Labels: bug

#11789 Improve the retry support for nondeterministic expressions
  integration_tests/src/main/python/rand_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuRandomExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowEvalPythonExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/NonDeterministicRetrySuite.scala
Labels: bug

#11816 address some comments for 11792
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
Labels: tech debt

#11893 [DOC] updates gh-pages docs for 24.12.0 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/shimplify.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation
