Repository NVIDIA/spark-rapids, pull requests merged in 2024-05, with the labels that each got.

#10756 Fix Authorization Failure While Reading Tables From Unity Catalog [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/ReaderUtils.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/ReaderUtils.scala
Labels: bug

#10644 Add logging to Integration test runs in local and local-cluster mode
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/test/resources/log4j.properties
  integration_tests/src/test/resources/log4j2.properties
  integration_tests/src/test/resources/pytest_log4j.properties
Labels: test

#10766 Fix dead links related to tools documentation [skip ci]
  README.md
Labels: documentation

#10763 Add in the GpuArrayFilter command
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  tools/generated_files/311/operatorsScore.csv
  tools/generated_files/311/supportedExprs.csv
  tools/generated_files/312/operatorsScore.csv
  tools/generated_files/312/supportedExprs.csv
  tools/generated_files/313/operatorsScore.csv
  tools/generated_files/313/supportedExprs.csv
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#10777 Update rapids JNI dependency: private to 24.04.2
  pom.xml
  scala2.13/pom.xml
Labels: build

#10780 [DOC]Update download page for v24.04.1 [skip ci]
  docs/download.md
Labels: documentation

#10743 initial PR for the framework reusing Vanilla Spark's unit tests
  NOTICE
  pom.xml
  scala2.13/pom.xml
  scala2.13/tests/pom.xml
  tests/pom.xml
  tests/src/test/java/com/nvidia/spark/rapids/TestStats.java
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsCastSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsDataFrameAggregateSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsJsonFunctionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsJsonSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsMathFunctionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsRegexpExpressionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsStringExpressionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsStringFunctionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/BackendTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestConstants.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsCommonTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala
Labels: test

#10636 Update actions version [skip ci]
  .github/workflows/add-to-project.yml
  .github/workflows/auto-merge.yml
  .github/workflows/mvn-verify-check.yml
  .github/workflows/signoff-check.yml
Labels: build

#10791 Fix auto merge conflict 10779 [skip ci]
  CHANGELOG.md
  docs/archive.md
  docs/download.md
Labels: build

#10805 Drop Support for CentOS 7
  jenkins/Dockerfile-blossom.integration.centos
  jenkins/Dockerfile-blossom.multi
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#10795 Remove fixed seed for exact `percentile` integration tests
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#10813 Fix the errors for Pandas UDF tests on DB13.3 [databricks]
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuAggregateInPandasExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuFlatMapGroupsInPandasExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupedPythonRunnerFactory.scala
Labels: bug

#10812 Replace ThreadPoolExecutor creation with ThreadUtils API [databricks]
  shuffle-plugin/src/main/scala/com/nvidia/spark/rapids/shuffle/ucx/UCXShuffleTransport.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: task, tech debt

#10715 Rewrite some rlike expression to StartsWith/Contains
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionRewriteSuite.scala
Labels: performance

#10723 Implement chunked ORC reader
  integration_tests/src/main/python/orc_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: feature request, SQL, P1, task

#10811 Fix NPE in GpuParseUrl for null keys.
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
Labels: bug

#10829 Fix `Inheritance Shadowing` to add support for Spark 4.0.0 [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/iceberg/IcebergProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AvroProviderImpl.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuScalaUDF.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/Spark340PlusNonDBShims.scala
Labels: Spark 4.0+

#10828 Added DateTimeUtilsShims [Databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/DateTimeUtilsShims.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/DateTimeUtilsShims.scala
Labels: Spark 4.0+

#10826 Add NVTX ranges to identify Spark stages and tasks
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: tools

#10855 Fix auto merge conflict 10845 [[skip ci]]
  CHANGELOG.md
Labels: build

#10833 Filter out unused json_path tokens
  integration_tests/src/main/python/get_json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
Labels: tech debt

#10873 Auto merge PRs to branch-24.08 from branch-24.06 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#10789 [DOC] updates gh-pages files for 24.04.1 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#10839 Replace anonymous classes for SortOrder and FIlterExec overrides
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/limit.scala
Labels: tech debt

#10872 [DOC] ignore released plugin links to reduce the bother info [skip ci]
  .github/workflows/markdown-links-check/markdown-links-check-config.json
Labels: build

#10868 Disable default cuDF pinned pool
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug, cudf_dependency

#10900 Fix type convert error in format_number scalar input
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: bug

#10870 Add support for self-contained profiling
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RangeConfMatcher.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/profiler.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/RangeConfMatcherSuite.scala
Labels: tools

#10871 Add classloader diagnostics to initShuffleManager error message
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala
Labels: ease of use

#10945 Add Support for Multiple Filtering Keys for Subquery Broadcast [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastMeta.scala
  sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/execution/GpuSubqueryBroadcastMeta.scala
  tests/src/test/spark321/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala
Labels: Spark 4.0+

#10946 Unarchive Spark test jar for spark.read(ability)
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsJsonSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: feature request, test

#10863 [Spark 4.0] Account for `CommandUtils.uncacheTableOrView` signature change.
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/hive/rapids/shims/CommandUtilsShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/hive/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/spark400/scala/org/apache/spark/sql/hive/rapids/shims/CommandUtilsShim.scala
Labels: Spark 4.0+

#10912 GpuInsertIntoHiveTable supports parquet format
  integration_tests/src/main/python/hive_parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveFileFormat.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/hive/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/GpuInsertIntoHiveTable.scala
Labels: feature request

#10949 Change dependency version to 24.08.0-SNAPSHOT
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#10947 Prevent contains-PrefixRange optimization if not preceded by wildcards
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionRewriteSuite.scala
Labels: bug, reliability
