Repository NVIDIA/spark-rapids, pull requests merged in 2024-08, with the labels that each got.

#11285 Remove files under tools/generated_files/spark31* [skip ci]
  tools/generated_files/311/operatorsScore.csv
  tools/generated_files/311/supportedDataSource.csv
  tools/generated_files/311/supportedExecs.csv
  tools/generated_files/311/supportedExprs.csv
  tools/generated_files/312/operatorsScore.csv
  tools/generated_files/312/supportedDataSource.csv
  tools/generated_files/312/supportedExecs.csv
  tools/generated_files/312/supportedExprs.csv
  tools/generated_files/313/operatorsScore.csv
  tools/generated_files/313/supportedDataSource.csv
  tools/generated_files/313/supportedExecs.csv
  tools/generated_files/313/supportedExprs.csv
Labels: tools

#11288 Move easy unshimmed classes to sql-plugin-api
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ColumnarRdd.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/GpuColumnVectorUtils.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/PlanUtils.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala
Labels: tech debt

#11284 Use distinct count to estimate join magnification factor
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance

#11295 Remove redundant classes from the dist jar and unshimmed list
  dist/scripts/binary-dedupe.sh
  dist/unshimmed-common-from-spark320.txt
Labels: bug, build

#11299 Enable get_json_object by default and remove legacy version
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/get_json_test.py
  integration_tests/src/main/python/json_matrix_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: task

#11301 Skip deploying non-critical intermediate artifacts [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#11312 Add jihoonson as an authorized user for blossom-ci [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#11313 Fix auto merge conflict 10845 11310 [skip ci]
  docs/dev/lore.md
Labels: build

#11307 Safely close multiple resources in RapidsBufferCatalog
  sql-plugin/src/main/scala-2.12/com/nvidia/spark/rapids/implicits.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
Labels: bug

#11296 [DOC] update doc for 2408 release [skip CI]
  docs/archive.md
  docs/download.md
Labels: documentation

#11303 Update rapids JNI and private dependency to 24.08.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#11304 Update changelog for v24.08.0 release [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.04.md
Labels: documentation

#11325 Fix auto merge conflict 11317 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.04.md
Labels: build

#11327 Make hive column matches not case-sensitive
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveTableScanExec.scala
Labels: bug

#11283 Fix the mismatching default configs in integration tests
  integration_tests/conftest.py
  integration_tests/pom.xml
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/assembly/bin.xml
  integration_tests/src/main/python/arithmetic_ops_test.py
  integration_tests/src/main/python/ast_test.py
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/conftest.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/hash_aggregate_test.py
  integration_tests/src/main/python/spark_session.py
  integration_tests/src/main/python/string_test.py
  integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/DumpDefaultConfigs.scala
  pom.xml
  scala2.13/integration_tests/pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug

#11335 Fix Delta Lake truncation of min/max string values [databricks]
  delta-lake/common/src/main/scala/com/nvidia/spark/rapids/delta/GpuStatisticsCollection.scala
  integration_tests/src/main/python/delta_lake_utils.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: bug

#11340 Audit script - Check commits from sql-hive directory [skip ci]
  scripts/audit-spark.sh
Labels: task

#11353 Update download doc for v24.08.1 [skip ci]
  docs/download.md
Labels: documentation

#11358 Fix download doc [skip ci]
  CHANGELOG.md
  docs/download.md
Labels: documentation

#11328 Swap build side for outer joins when natural build side is explosive [databricks]
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
Labels: performance

#10604 Add string escaping JSON tests to the test_json_matrix
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/test/resources/escaped_strings.json
Labels: test

#11363 Fix failing test compile for Spark 4.0.0
  tests/src/test/scala/org/apache/spark/sql/rapids/ProjectExprSuite.scala
Labels: test, build

#11365 Set numRows for the ColumnBatch created in GpuBringBackToHost
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBringBackToHost.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBringBackToHostSuite.scala
Labels: bug

#11329 Change reference to `MapUtils` into `JSONUtils`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: tech debt

#11368 Move SparkRapidsBuildInfoEvent to its own file
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/sparkRapidsListeners.scala
Labels: feature request

#11383 Fix nightly snapshots being downloaded in premerge build
  jenkins/spark-premerge-build.sh
Labels: build

#11375 Fix spark400 build in datagen and tests
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  datagen/src/main/spark320/scala/org/apache/spark/sql/tests/datagen/DataGenExprShims.scala
  datagen/src/main/spark400/scala/org/apache/spark/sql/tests/datagen/DataGenExprShims.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ProjectExprSuite.scala
  tests/src/test/scala/org/apache/spark/sql/timezone/TimeZonePerfUtils.scala
Labels: build

#11396 Drop cudf-py python 3.9 support [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: build

#11291 Add distinct join support for right outer joins
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AbstractGpuJoinIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: performance

#11400 [DOC] update notes in download page for the decompressing gzip issue [skip ci]
  CONTRIBUTING.md
  docs/download.md
  integration_tests/README.md
Labels: documentation

#11360 [DOC] updates gh-pages docs for 24.08.0 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/archive.md
  docs/configs.md
  docs/dev/README.md
  docs/dev/lore.md
  docs/dev/shimplify.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation

#11409 Merge branch-24.08 into main [skip ci]
  CONTRIBUTING.md
  docs/download.md
  integration_tests/README.md
Labels: build

#11371 Support MinBy and MaxBy for non-float ordering
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#11395 Fix a Pandas UDF slowness issue
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/BatchGroupUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuArrowReader.scala
Labels: bug

#11411 Fix asymmetric join crash when stream side is empty
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
Labels: bug
