Repository NVIDIA/spark-rapids, pull requests merged in 2024-02, with the labels that each got.

#10348 Remove redundant joinOutputRows metric [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuCartesianProductExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExecBase.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuSubPartitionHashJoin.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastHashJoinExec.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastNestedLoopJoinExec.scala
Labels: task

#10358 Disable Spark UI by default for integration tests [databricks]
  integration_tests/run_pyspark_from_build.sh
Labels: test

#10369 Revert "Support barrier mode for mapInPandas/mapInArrow (#10364)" [databricks]
  integration_tests/src/main/python/udf_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInBatchExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuMapInPandasExec.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/GpuMapInPandasExecMeta.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/PythonMapInArrowExecShims.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/GpuPythonMapInArrowExec.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/GpuPythonMapInArrowExecMeta.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/PythonMapInArrowExecShims.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuMapInPandasExecMeta.scala
  sql-plugin/src/main/spark350/scala/org/apache/spark/sql/rapids/shims/GpuPythonMapInArrowExecMeta.scala
Labels: build

#10356 Update locate_parquet_testing_files function to support hdfs input path for dataproc CI
  integration_tests/src/main/python/parquet_testing_test.py
Labels: test

#10389 Change version and branch to 24.02 in docs [skip ci]
  CONTRIBUTING.md
  docs/dev/testing.md
Labels: documentation

#10394 Fix auto merge conflict 10393 [skip ci]
  docs/dev/testing.md
Labels: documentation

#10158 Add in framework for unbounded to unbounded window agg optimization
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferCatalog.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsBufferStore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuUnboundedToUnboundedAggWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExecMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuGenerateSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/window/GpuUnboundedToUnboundedAggWindowSuite.scala
Labels: reliability

#10399 Update NOTICE-binary
  NOTICE-binary
Labels: documentation

#10403 Cherry-pick: Fix a memory leak in json tuple (#10360)
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
Labels: bug

#10406 Enabled subPage chunking by default
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request, task

#10248 Group-by aggregation based optimization for UNBOUNDED `collect_set` window function
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuUnboundedToUnboundedAggWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExecMeta.scala
  tests/src/test/scala/com/nvidia/spark/rapids/window/GpuUnboundedToUnboundedAggWindowSuite.scala
Labels: performance, reliability

#10414 [DOC] Fix 24.02.0 documentation errors [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/download.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExprs.csv
Labels: documentation

#10247 Improve `GpuExpand` by pre-projecting some columns[databricks]
  integration_tests/src/main/python/expand_exec_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#10415 Avoid comparing Delta logs when writing partitioned tables
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_merge_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: test

#10407 Enable Single Quote Support in getJSONObject API with GetJsonObjectOptions
  integration_tests/src/main/python/get_json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
Labels: bug

#10421 Use withRetry when manifesting spillable batch in GpuShuffledHashJoinExec
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
Labels: reliability

#10396 Remove inactive user from github workflow [skip ci]
  .github/workflows/blossom-ci.yml
Labels: task

#10367 Update rapids JNI and private version to release 24.02.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#10380 Init changelog 24.02 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.10.md
Labels: documentation

#10426 Fix auto merge conflict 10425 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.10.md
  pom.xml
  scala2.13/pom.xml
Labels: documentation

#10439 Reverts NVIDIA/spark-rapids#10232 and fixes the plugin build on Databricks 11.3 [databricks]
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
Labels: bug

#10443 Update change log for v24.02.0 release [skip ci]
  CHANGELOG.md
Labels: documentation

#10445 Merge branch branch-24.02 into main [skip ci]
  CHANGELOG.md
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark341db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
Labels: build

#10438 Integrate perfio.s3 reader [databricks]
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
Labels: performance

#10450 Improve internal row to columnar host memory by using a combined spillable buffer
  sql-plugin/src/main/java/com/nvidia/spark/rapids/InternalRowToColumnarBatchIterator.java
  tests/src/test/scala/com/nvidia/spark/rapids/GeneratedInternalRowToCudfRowIteratorRetrySuite.scala
Labels: improve, reliability

#10459 [DOC] Fix table rendering issue in github.io download UI page on branch-24.02 [skip ci]
  docs/compatibility.md
  docs/download.md
Labels: documentation

#10461 Preserve tags on FileSourceScanExec [databricks]
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/Spark31XShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/BatchScanExecMeta.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/BatchScanExecMeta.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/BatchScanExecMeta.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/BatchScanExecMeta.scala
Labels: bug

#10475 Fix scalar leak in RankFixer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala
Labels: bug

#10501 Fix scalar leak in WindowRetrySuite
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuRunningWindowExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
Labels: test

#10497 Add minValue overflow check in ORC double-to-timestamp cast
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
Labels: bug

#10490 Start working on a more complete json test matrix json
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/boolean_formatted.json
  integration_tests/src/test/resources/decimal_locale_formatted_strings.json
  integration_tests/src/test/resources/float_formatted.json
  integration_tests/src/test/resources/float_formatted_strings.json
  integration_tests/src/test/resources/int_formatted.json
  integration_tests/src/test/resources/int_formatted_strings.json
  integration_tests/src/test/resources/sci_formatted.json
  integration_tests/src/test/resources/sci_formatted_strings.json
  integration_tests/src/test/resources/single_quoted_strings.json
  integration_tests/src/test/resources/withBackslashEscapingAnyCharacter.json
  integration_tests/src/test/resources/withComments.json
  integration_tests/src/test/resources/withNonnumericNumbers.json
  integration_tests/src/test/resources/withNumericLeadingZeros.json
  integration_tests/src/test/resources/withSingleQuotes.json
  integration_tests/src/test/resources/withUnquotedControlChars.json
  integration_tests/src/test/resources/withUnquotedFieldNames.json
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: test, tech debt

#10466 Use parser from spark to normalize json path in GetJsonObject
  docs/compatibility.md
  integration_tests/src/main/python/get_json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug

#10510 Fix scalar leak in SumBinaryFixer
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala
Labels: bug, reliability

#10513 Fix scalar leak in SumBinaryFixer (#10510)
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala
Labels: bug, reliability

#10508 Move 351 shims into noSnapshot buildvers
  pom.xml
  scala2.13/pom.xml
Labels: build

#10500 Support "WindowGroupLimit" optimization on GPU [databricks]
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/GpuWindowGroupLimitExec.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/SparkShims.scala
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExecs.csv
Labels: performance

#10511 Update rapids jni and private dependency version to 24.02.1
  pom.xml
  scala2.13/pom.xml
Labels: build
