Repository NVIDIA/spark-rapids, pull requests merged in 2024-01, with the labels that each got.

#10087 Additional unit tests for GeneratedInternalRowToCudfRowIterator
  tests/src/test/scala/com/nvidia/spark/rapids/GeneratedInternalRowToCudfRowIteratorRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RmmSparkRetrySuiteBase.scala
Labels: test, reliability

#10084 Refactor GpuJsonToStruct to reduce code duplication and manage resources more efficiently
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: tech debt

#10128 [DOC] updates gh-pages files for 23.12.1 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#10139 Add Delta Lake 2.3.0 to list of versions to test for Spark 3.3.x
  jenkins/spark-tests.sh
Labels: test, build

#10138 Update copyright dates in NOTICE files [skip ci]
  NOTICE
  NOTICE-binary
Labels: documentation

#10130 Change unit tests that force ooms to specify the oom type (gpu|cpu)
  tests/src/test/scala/com/nvidia/spark/rapids/BatchWithPartitionDataSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ColumnToRowIteratorRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CsvScanRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuCoalesceBatchesRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuSortRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregateRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HostColumnToGpuRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JsonScanRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/NonDeterministicRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ProjectExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RangeRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowToColumnarIteratorRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ShufflePartitionerRetrySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
Labels: test, reliability

#9887 Reduce time-consuming of pre-merge
  dist/pom.xml
  integration_tests/src/main/python/conditionals_test.py
  integration_tests/src/main/python/sort_test.py
  jenkins/spark-premerge-build.sh
  scala2.13/dist/pom.xml
Labels: build

#10143 Fix `test_window_aggs_for_batched_finite_row_windows_partitioned` fail
  integration_tests/src/main/python/window_function_test.py
Labels: test

#10150 Increase timeouts in HostAllocSuite to avoid timeout failures on slow machines
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: bug, test

#10148 fix test_hash_agg_with_nan_keys floating point sum failure
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: bug, test

#10140 Removed Unnecessary Whitespaces From Spark 3.3.4 Shim [skip ci]
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/rapids/RapidsCachingReader.scala
  tests/src/test/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleTestHelper.scala
Labels: task

#10100 Enable to_date (via gettimestamp and casting timestamp to date) for non-UTC time zones
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/window_function_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/expressions/rapids/Timestamp.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#10153 Disable multi-threaded Maven
  .github/workflows/mvn-verify-check.yml
  jenkins/spark-nightly-build.sh
Labels: build

#10155 Install procps tools for rocky docker images [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
Labels: bug, build

#10146 Refactor the window code so it is not mostly kept in a few very large files [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/BasicWindowCalc.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuBatchedBoundedWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuBatchedWindowIteratorUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuCachedDoublePassWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuRunningWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExecMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExpression.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonUDF.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/PythonUDFShim.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/gpuWindows.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/gpuWindows.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuRunningWindowExecMeta.scala
  sql-plugin/src/main/spark321db/scala/com/nvidia/spark/rapids/shims/GpuWindowInPandasExec.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/PythonUDFShim.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowRetrySuite.scala
Labels: tech debt

#10162 Fix Spark 334 Build
  pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/shims/GpuAscii.scala
Labels: spark 3.3+

#10144 Support to_utc_timestamp [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/timezone/TimeZonePerfSuite.scala
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#9790 Support float case of format_number with format_float kernel
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
Labels: feature request

#10168 Prevent a degenerative join in test_dpp_reuse_broadcast_exchange [databricks]
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/dpp_test.py
Labels: test

#10167 Defined Shims Should Be Declared In POM
  build/shimplify.py
Labels: bug

#10074 Update the legacy mode check: only take effect when reading date/timestamp column
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DataTypeUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/datetimeRebaseUtils.scala
Labels: task

#10176 Fix format_number NaN symbol in high jdk version
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: bug

#10179 Fix build regression against Spark 3.2.x [databricks]
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuJsonToStructsShim.scala
Labels: build

#10131 With a single row GpuExplode tries to split the generator array
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuGenerateSuite.scala
Labels: bug

#10191 Updating the config documentation for filecache configs [skip ci]
  docs/additional-functionality/advanced_configs.md
Labels: documentation

#10156 Update string to float compatibility doc[skip ci]
  docs/compatibility.md
Labels: documentation

#10204 Further prevent degenerative joins in dpp_test [databricks]
  integration_tests/src/main/python/dpp_test.py
Labels: test

#10205 Deterministic ordering in window tests
  integration_tests/src/main/python/window_function_test.py
Labels: test

#10225 Download Maven from apache.org archives [skip ci]
  jenkins/databricks/build.sh
Labels: bug, build

#10232 Fixed 330db Shims to Adopt the PythonRunner Changes [databricks]
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark321db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala
Labels: build

#10230 Fix Databricks 13.3 BroadcastHashJoin using executor side broadcast fed by ColumnarToRow [Databricks]
  integration_tests/src/main/python/aqe_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SparkShims.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/Spark330PlusDBShims.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/Spark341PlusDBShims.scala
Labels: bug

#10220 Disable GetJsonObject by default and add tests for as many issues with it as possible
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/get_json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/supportedExprs.csv
Labels: tech debt

#10201 Deploy release candidates to local maven repo for dependency check[skip ci]
  jenkins/dependency-check.sh
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
Labels: build

#10238 Smoke test with '--package' to fetch the plugin jar
  integration_tests/run_pyspark_from_build.sh
  jenkins/spark-tests.sh
Labels: bug, build

#10178 Mark hash reduction decimal overflow test as a permanent seed override
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#10257 Enable auto-merge from branch-24.02 to branch-24.04 [skip CI]
  .github/workflows/auto-merge.yml
Labels: build

#9993 Enable mixed types as string in GpuJsonScan
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/mixed-primitive-arrays.ndjson
  integration_tests/src/test/resources/mixed-types-in-struct.ndjson
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: feature request

#10208 Added Support for Lazy Quantifier [databricks]
  docs/compatibility.md
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: feature request

#10211 Use parse_url kernel for QUERY literal and column key
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/url_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
  tools/generated_files/supportedExprs.csv
Labels: feature request

#10190 UCX 1.16.0 upgrade
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.multi
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: feature request

#10289 Add gerashegalov to CODEOWNERS [skip ci]
  .github/CODEOWNERS
Labels: tech debt

#10297 Revert "UCX 1.16.0 upgrade (#10190)"
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.multi
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: bug

#10268 Add config to enable mixed types as string in GpuJsonToStruct & GpuJsonScan
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: feature request

#10278 Clean up $M2_CACHE to avoid side-effect of previous dependency:get [skip ci]
  jenkins/dependency-check.sh
Labels: test

#10275 Add tests for window Python udf with array input
  integration_tests/src/main/python/udf_test.py
Labels: test

#10260 Add perf test for time zone operators
  tests/src/test/scala/com/nvidia/spark/rapids/timezone/TimeZonePerfSuite.scala
Labels: performance, test

#10272 Add FullOuter support to GpuShuffledSymmetricHashJoinExec
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSymmetricHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
Labels: performance

#10306 Fix performance regression in from_json
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: bug, performance

#10273 Support reading JSON data with single quotes around attribute names and values
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/dates.json
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: feature request

#10279 Run '--packages' only with default cuda11 jar
  jenkins/spark-tests.sh
Labels: test

#10328 Fix typo in spark-tests.sh [skip ci]
  jenkins/spark-tests.sh
Labels: build

#9991 Start to use explicit memory limits in the parquet chunked reader
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquet.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuBatchDataReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: cudf_dependency, reliability

#10329 update download page for v23.12.2 release [skip ci]
  docs/download.md
Labels: documentation

#10323 Upgrade version to 23.12.2-SNAPSHOT [databricks]
  CONTRIBUTING.md
  README.md
  aggregator/pom.xml
  api_validation/pom.xml
  datagen/README.md
  datagen/ScaleTest.md
  datagen/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-23x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-spark341db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  docs/configs.md
  integration_tests/README.md
  integration_tests/ScaleTest.md
  integration_tests/pom.xml
  jdk-profiles/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/api_validation/pom.xml
  scala2.13/datagen/pom.xml
  scala2.13/delta-lake/delta-20x/pom.xml
  scala2.13/delta-lake/delta-21x/pom.xml
  scala2.13/delta-lake/delta-22x/pom.xml
  scala2.13/delta-lake/delta-23x/pom.xml
  scala2.13/delta-lake/delta-24x/pom.xml
  scala2.13/delta-lake/delta-spark321db/pom.xml
  scala2.13/delta-lake/delta-spark330db/pom.xml
  scala2.13/delta-lake/delta-spark332db/pom.xml
  scala2.13/delta-lake/delta-spark341db/pom.xml
  scala2.13/delta-lake/delta-stub/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/integration_tests/pom.xml
  scala2.13/jdk-profiles/pom.xml
  scala2.13/pom.xml
  scala2.13/shim-deps/cloudera/pom.xml
  scala2.13/shim-deps/databricks/pom.xml
  scala2.13/shim-deps/pom.xml
  scala2.13/shuffle-plugin/pom.xml
  scala2.13/sql-plugin-api/pom.xml
  scala2.13/sql-plugin/pom.xml
  scala2.13/tests/pom.xml
  scala2.13/udf-compiler/pom.xml
  shim-deps/cloudera/pom.xml
  shim-deps/databricks/pom.xml
  shim-deps/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#10340 Copyright to 2024 [skip ci]
  aggregator/pom.xml
  api_validation/pom.xml
  datagen/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-23x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark321db/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-spark341db/pom.xml
  delta-lake/delta-stub/pom.xml
  dist/pom.xml
  integration_tests/pom.xml
  jdk-profiles/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/api_validation/pom.xml
  scala2.13/datagen/pom.xml
  scala2.13/delta-lake/delta-20x/pom.xml
  scala2.13/delta-lake/delta-21x/pom.xml
  scala2.13/delta-lake/delta-22x/pom.xml
  scala2.13/delta-lake/delta-23x/pom.xml
  scala2.13/delta-lake/delta-24x/pom.xml
  scala2.13/delta-lake/delta-spark321db/pom.xml
  scala2.13/delta-lake/delta-spark330db/pom.xml
  scala2.13/delta-lake/delta-spark332db/pom.xml
  scala2.13/delta-lake/delta-spark341db/pom.xml
  scala2.13/delta-lake/delta-stub/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/integration_tests/pom.xml
  scala2.13/jdk-profiles/pom.xml
  scala2.13/pom.xml
  scala2.13/shim-deps/cloudera/pom.xml
  scala2.13/shim-deps/databricks/pom.xml
  scala2.13/shim-deps/pom.xml
  scala2.13/shuffle-plugin/pom.xml
  scala2.13/sql-plugin-api/pom.xml
  scala2.13/sql-plugin/pom.xml
  scala2.13/tests/pom.xml
  scala2.13/udf-compiler/pom.xml
  shim-deps/cloudera/pom.xml
  shim-deps/databricks/pom.xml
  shim-deps/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation, build

#10341 Update changelog for v23.12.2 [skip ci]
  CHANGELOG.md
Labels: documentation

#10321 Bump up dependency version to 24.04.0-SNAPSHOT[databricks]
  jenkins/databricks/init_cudf_udf.sh
  jenkins/version-def.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#10345 Fix auto merge conflict 10339 [skip ci]
  CHANGELOG.md
Labels: documentation
