Repository NVIDIA/spark-rapids, pull requests merged in 2024-11, with the labels that each got.

#11683 [DOC] update download page for 2410 hot fix release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#11282 Reserve allocation should be displayed when erroring due to lack of memory on startup
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
Labels: bug

#11685 Exclude shimplify-generated files from scalastyle
  pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExecutedCommandExec.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/XxHash64Shims.scala
Labels: bug, build

#11652 Fix skipping fixed_length_char ORC tests on [databricks] > 13.3
  integration_tests/src/main/python/orc_test.py
Labels: test

#11670 Fix `misc_expr_test` for [databricks] 14.3
  integration_tests/src/main/python/misc_expr_test.py
Labels: test

#11689 Update the Maven repository to download Spark JAR files [skip ci]
  jenkins/spark-tests.sh
Labels: build

#11695 Fix spark400 build due to LogicalRelation signature changes [databricks]
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/LogicalPlanShims.scala
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/LogicalPlanShims.scala
Labels: build

#11669 Fix `string_test` for [databricks] 14.3
  integration_tests/src/main/python/string_test.py
Labels: test

#11673 Fix Parquet Writer tests on [databricks] 14.3
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#11699 [DOC] updates gh-pages docs for 24.10.1 release [skip ci]
  docs/configs.md
  docs/download.md
Labels: documentation

#11710 Add shim version 344 to LogicalPlanShims.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/LogicalPlanShims.scala
  tools/generated_files/400/supportedExprs.csv
Labels: bug, build

#11697 Make delta-lake shim dependencies parametrizable [databricks]
  aggregator/pom.xml
  build/make-scala-version-build-files.sh
  pom.xml
  scala2.13/aggregator/pom.xml
  scala2.13/pom.xml
Labels: tech debt

#11703 Simplify $ transpiling and fix newline character bug
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
Labels: bug

#11714 Let AWS Databricks automatically choose an Availability Zone
  jenkins/databricks/clusterutils.py
  jenkins/databricks/create.py
Labels: build

#11702 Improve JSON scan and `from_json`
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: test

#11728 Change Databricks 14.3 shim name to spark350db143 [skip ci]
  jenkins/databricks/deploy.sh
Labels: bug, build

#11413 Support multi string contains [databricks]
  integration_tests/src/main/python/conditionals_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: performance

#11731 Add NullIntolerantShim to adapt to Spark 4.0 removing NullIntolerant [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/predicates.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/NullIntolerantShim.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/GpuAscii.scala
  sql-plugin/src/main/spark323/scala/org/apache/spark/sql/rapids/shims/GpuAscii.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/arithmetic.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/NullIntolerantShim.scala
Labels: build

#11719 Skip `from_json` overflow tests for [databricks] 14.3
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/test/resources/int_struct_formatted.json
  integration_tests/src/test/resources/int_struct_formatted_problematic_rows.json
Labels: test

#11727 Widen type promotion for decimals with larger scale in Parquet Read [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#11737 Add in support for months_between
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#11744 Do not package the Databricks 14.3 shim into the dist jar [skip ci]
  build/get_buildvers.py
  pom.xml
  scala2.13/pom.xml
Labels: build

#11721 Add a few more JSON tests for MAP<STRING,STRING>
  integration_tests/src/main/python/json_matrix_test.py
Labels: test

#11746 Remove batch size bytes limits
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#11725 host watermark metric
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostAlloc.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
Labels: task

#11618 Execute `from_json` with struct schema using `JSONUtils.fromJSONToStructs`
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonReadCommon.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: feature request, SQL, performance, P0, task

#11733 Print out the current attempt object when OOM inside a retry block
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCoalesceBatches.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGenerateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
Labels: reliability

#11753 Enable JSON Scan and from_json by default
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  docs/supported_ops.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tools/generated_files/320/supportedDataSource.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedDataSource.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedDataSource.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedDataSource.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedDataSource.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedDataSource.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedDataSource.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedDataSource.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedDataSource.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedDataSource.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedDataSource.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedDataSource.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedDataSource.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedDataSource.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedDataSource.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedDataSource.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/supportedDataSource.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/supportedDataSource.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/supportedDataSource.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedDataSource.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/supportedDataSource.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/supportedDataSource.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/400/supportedDataSource.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/supportedDataSource.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#11730 Add support for asynchronous writing for parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/io/async/AsyncOutputStream.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/io/async/ThrottlingExecutor.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/io/async/TrafficController.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/io/async/AsyncOutputStreamSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/io/async/ThrottlingExecutorSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/io/async/TrafficControllerSuite.scala
Labels: performance

#11756 remove excluded release shim and TODO
  build/get_buildvers.py
  pom.xml
  scala2.13/pom.xml
Labels: bug, build

#11752 Ability to decompress snappy and zstd Parquet files via CPU [databricks]
  integration_tests/src/main/python/parquet_test.py
  jenkins/databricks/install_deps.py
  scala2.13/shim-deps/databricks/pom.xml
  shim-deps/databricks/pom.xml
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostMemoryStreams.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#11785 Update advanced configs introduced by private repo [skip ci]
  docs/additional-functionality/advanced_configs.md
Labels: documentation

#11788 Support running Databricks CI_PART2 integration tests with JARs built by CI_PART1
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
Labels: build

#11792 [BUG] Fix issue 11790
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
Labels: bug
