Repository NVIDIA/spark-rapids, pull requests merged in 2024-09, with the labels that each got.

#11425 Update signoff usage [skip ci]
  .github/workflows/signoff-check.yml
  .github/workflows/signoff-check/Dockerfile
  .github/workflows/signoff-check/action.yml
  .github/workflows/signoff-check/signoff-check
Labels: build

#11421 [DOC] remove the redundant archive link [skip ci]
  docs/archive.md
Labels: documentation

#11331 Add companion metrics for all nsTiming metrics without semaphore
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
Labels: task

#11451 xfail array and map cast to string tests
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/test/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSparkSuite.scala
Labels: test

#11455 Log DBR BuildInfo [databricks]
  jenkins/databricks/build.sh
  jenkins/databricks/install_deps.py
  scala2.13/shim-deps/databricks/pom.xml
  shim-deps/databricks/pom.xml
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/DatabricksShimServiceProvider.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/spark330db/SparkShimServiceProvider.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/spark332db/SparkShimServiceProvider.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/shims/spark341db/SparkShimServiceProvider.scala
Labels: task

#11469 Skip test_hash_groupby_approx_percentile byte and double tests tempor…
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#11466 Replace scala.util.Try with a try statement in the DBR buildinfo [databricks]
  jenkins/databricks/build.sh
  jenkins/databricks/test.sh
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/DatabricksShimServiceProvider.scala
Labels: bug

#11473 Revert "Skip test_hash_groupby_approx_percentile byte and double test…
  integration_tests/src/main/python/hash_aggregate_test.py
Labels: test

#11464 Use improved CUDF JSON validation
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  integration_tests/src/test/resources/bad_whitespace.json
  integration_tests/src/test/resources/float_formatted.json
  integration_tests/src/test/resources/invalid_ridealong_columns.json
  integration_tests/src/test/resources/scan_emtpy_lines.json
  integration_tests/src/test/resources/sci_formatted.json
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTextBasedPartitionReader.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonReadCommon.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JsonScanRetrySuite.scala
Labels: test

#11482 Fix a json test for non utc time zone
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
Labels: test

#11483 Use reusable auto-merge workflow [skip ci]
  .github/workflows/auto-merge.yml
  .github/workflows/auto-merge/Dockerfile
  .github/workflows/auto-merge/action.yml
  .github/workflows/auto-merge/automerge
Labels: build

#11456 Enable tests for all JSON white space normalization
  integration_tests/src/main/python/json_matrix_test.py
Labels: test

#11449 Support yyyyMMdd in GetTimestamp operator for LEGACY mode [databricks]
  docs/compatibility.md
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
Labels: feature request

#11462 Support non-UTC timezone for casting from date type to timestamp type [databricks]
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/date_time_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
Labels: feature request

#11477 Install cuDF-py against python 3.10 on Databricks
  integration_tests/src/main/python/udf_cudf_test.py
  jenkins/databricks/cudf_udf_test.sh
  jenkins/databricks/init_cudf_udf.sh
Labels: build

#11366 Enable parquet suites from Spark UT
  scala2.13/tests/pom.xml
  tests/pom.xml
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetAvroCompatibilitySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetColumnIndexSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetCompressionCodecPrecedenceSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetDeltaByteArrayEncodingSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetDeltaEncodingSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetDeltaLengthByteArrayEncodingSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetFieldIdIOSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetFieldIdSchemaSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetFileFormatSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetInteroperabilitySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetPartitionDiscoverySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetProtobufCompatibilitySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetQuerySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetRebaseDatetimeSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetSchemaPruningSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetSchemaSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetThriftCompatibilitySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetVectorizedSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#10798 Optimzing Expand+Aggregate in sqls with many count distinct
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpandExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExpressions.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
Labels: performance

#11503 Download artifacts via wget [skip ci]
  jenkins/spark-tests.sh
Labels: bug, build

#11507 Replace libmamba-solver with mamba command [skip ci]
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Dockerfile-blossom.integration.ubuntu
Labels: bug, build

#11516 Deploy all submodules for default sparkver in nightly [skip ci]
  jenkins/spark-nightly-build.sh
Labels: bug, build

#11542 Update rapids JNI and private dependency to 24.12.0-SNAPSHOT [skip ci]
  jenkins/databricks/init_cudf_udf.sh
  pom.xml
  scala2.13/pom.xml
Labels: feature request, build
