Repository NVIDIA/spark-rapids, pull requests merged in 2024-06, with the labels that each got.

#10959 Add new ID to blossom-ci allow list [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#10966 Add default value for REF of premerge jenkinsfile to avoid bad overwritten [skip ci]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: bug, build

#10970 Move Support for `RaiseError` to a Shim Excluding Spark 4.0.0 [databricks]
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/RaiseErrorShim.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/shims/misc.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/RaiseErrorShim.scala
Labels: Spark 4.0+

#10958 Fix a hive write test failure
  integration_tests/src/main/python/hive_parquet_write_test.py
  integration_tests/src/main/python/spark_session.py
Labels: bug

#10953 Speed up the integration tests by running them in parallel on the Databricks cluster
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
  jenkins/databricks/test.sh
Labels: build

#10963 Add rapids configs to enable GPU running in Spark UT
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala
Labels: test

#10943 Fix Spark UT issues in RapidsDataFrameAggregateSuite
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsDataFrameAggregateSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/BackendTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#10992 Addressing the Named Parameter change in Spark 4.0.0 [databricks]
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/GpuInSubqueryExecSuite.scala
Labels: Spark 4.0+

#10974 Update rapids JNI and private dependency to 24.06.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#10984 [DOC] Update docs for 24.06.0 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#10981 Update latest changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02.md
Labels: documentation

#10998 Improve log to print more lines in build [skip ci]
  build/buildall
Labels: build

#11036 Update blossom-ci ACL to secure format [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#11035 Fix auto merge conflict 11034 [skip ci]
  CHANGELOG.md
  docs/archive.md
  docs/archives/CHANGELOG_24.02.md
  docs/download.md
Labels: build

#10977 Rewrite multiple literal choice regex to multiple contains in rlike
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionRewriteSuite.scala
Labels: bug, performance

#11002 Add in the ability to fingerprint JSON columns
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
Labels: data gen

#11039 Concat() Exception bug fix
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: bug

#11052 Add spark343 shim for scala2.13 dist jar
  pom.xml
  scala2.13/pom.xml
Labels: bug, build

#11056 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: build

#11058 Merge branch-24.06 into main [skip ci]
  CHANGELOG.md
  pom.xml
  scala2.13/pom.xml
Labels: build

#11060 Add in the ability to fingerprint JSON columns [databricks]
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
  jenkins/databricks/install_deps.py
  scala2.13/shim-deps/databricks/pom.xml
  shim-deps/databricks/pom.xml
Labels: data gen

#10993 `binary-dedupe` changes for Spark 4.0.0 [databricks]
  dist/maven-antrun/build-parallel-worlds.xml
  dist/scripts/binary-dedupe.sh
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
Labels: Spark 4.0+

#11054 fix flaky array_item test failures
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/parquet_write_test.py
Labels: test

#11072 Workaround numpy2 failed fastparquet compatibility tests [databricks]
  integration_tests/src/main/python/fastparquet_compatibility_test.py
Labels: test

#10957 Support bucketing write for GPU
  integration_tests/src/main/python/asserts.py
  integration_tests/src/main/python/orc_write_test.py
  integration_tests/src/main/python/parquet_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuHashPartitioningBase.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/GpuOptimizedCreateHiveTableAsSelectCommandShims.scala
  sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/spark311/GpuBucketingUtils.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/hive/rapids/shims/GpuCreateHiveTableAsSelectCommand.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/hive/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/spark330/GpuBucketingUtils.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/CreateDataSourceTableAsSelectCommandMetaShims.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/GpuInsertIntoHiveTable.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/GpuOptimizedCreateHiveTableAsSelectCommandShims.scala
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriterSuite.scala
Labels: feature request

#11086 upgrade blossom-ci actions version [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#11076 Improve the diagnostics for 'conv' fallback explain
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
Labels: task

#10997 Fix some test issues in Spark UT and keep RapidsTestSettings update-to-date
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsCastSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsJsonExpressionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsJsonFunctionsSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala
Labels: test

#11083 Exclude a case based on JDK version in Spark UT
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/BackendTestSettings.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11049 Fix some cast_tests for Spark 4.0.0 [databricks]
  integration_tests/src/main/python/cast_test.py
Labels: Spark 4.0+

#10950 Add a heuristic to skip second or third agg pass
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#11088 Support regex patterns with brackets when rewriting to PrefixRange pattern in rlike.
  integration_tests/src/main/python/regexp_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionRewriteSuite.scala
Labels: feature request
