Repository NVIDIA/spark-rapids, pull requests merged in 2024-10, with the labels that each got.

#11548 Fix negative rs. shuffle write time
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
Labels: bug

#11519 Spark 4: Fix parquet_test.py [databricks]
  integration_tests/src/main/python/parquet_test.py
Labels: test, Spark 4.0+

#11567 Fix test case unix_timestamp(col, 'yyyyMMdd') failed for Africa/Casablanca timezone and LEGACY mode
  docs/compatibility.md
  integration_tests/src/main/python/date_time_test.py
Labels: test

#11544 Update test case related to LEACY datetime format to unblock nightly CI
  docs/compatibility.md
  integration_tests/src/main/python/date_time_test.py
Labels: test

#11579 Fix merge conflict with branch-24.10
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
Labels: build

#11582 [DOC] update doc for 24.10 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#11577 Update latest changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.06.md
Labels: documentation, build

#11605 Fix auto merge conflict 11604 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.06.md
Labels: build

#11595 Remove an unused config shuffle.spillThreads
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: ease of use, tech debt

#11549 Adopt `JSONUtils.concatenateJsonStrings` for concatenating JSON strings
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonReadCommon.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: performance

#11610 Change DataSource calendar interval error to fix spark400 build [databricks]
  sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala
Labels: build

#11608 Use mvn -f scala2.13/ in the build scripts to build the 2.13 jars
  .github/workflows/mvn-verify-check.yml
  build/buildall
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  scala2.13/README.md
Labels: documentation, build

#11597 `install_deps` changes for Databricks 14.3 [databricks]
  jenkins/databricks/install_deps.py
Labels: task

#11612 Revert "Disable regex tests to unblock CI (#11606)"
  integration_tests/src/main/python/regexp_test.py
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionTranspilerSuite.scala
Labels: test

#11614 Ensure repartition overflow test always overflows
  integration_tests/src/main/python/repart_test.py
Labels: test

#11617 Quick fix for the build script failure of Scala 2.13 jars [skip ci]
  jenkins/spark-nightly-build.sh
Labels: bug, build

#11624 Update the download link [skip ci]
  README.md
Labels: documentation

#11631 Update JSON tests based on a closed/fixed issues
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
Labels: test

#11626 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#11637 Merge branch-24.10 into main [skip ci]
  CHANGELOG.md
  README.md
Labels: documentation

#11591 Spark UT framework: Read Parquet file generated by parquet-thrift Rapids, UT case adjust.
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetThriftCompatibilitySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11640 Disable date/timestamp types by default when parsing JSON
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
Labels: SQL, reliability

#11553 Fix udf-compiler scala2.13 internal return statements
  udf-compiler/src/main/scala/com/nvidia/spark/udf/CFG.scala
  udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
Labels: bug

#11521 Datetime rebasing issue fixed
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetRebaseDatetimeSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11522 UT adjust test SPARK-26677: negated null-safe equality comparison
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetQuerySuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11634 Put DF_UDF plugin code into the main uber jar.
  DF_UDF_README.md
  df_udf/pom.xml
  integration_tests/src/test/scala/com/nvidia/spark/rapids/functionsSuite.scala
  integration_tests/src/test/scala/org/apache/spark/sql/nvidia/SparkTestBase.scala
  pom.xml
  scala2.13/df_udf/pom.xml
  scala2.13/pom.xml
  sql-plugin-api/src/main/scala/com/nvidia/spark/DFUDFPlugin.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/functions.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/DFUDFPluginAPI.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/Functions.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/DFUDFPluginImpl.scala
  sql-plugin/src/main/scala/com/nvidia/spark/FunctionsImpl.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/nvidia/LogicalPlanRules.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/nvidia/dataframe_udfs.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala
  sql-plugin/src/main/spark400/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala
Labels: feature request

#11647 Fix a NPE issue in GpuRand
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuRandomExpressions.scala
Labels: bug

#11665 Generate classes identical up to the shim package name [databricks]
  build/shimplify.py
  docs/dev/shimplify.md
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/RapidsShuffleManager.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/spark320/RapidsShuffleManager.scala
  sql-plugin/src/main/spark321/scala/com/nvidia/spark/rapids/spark321/RapidsShuffleManager.scala
  sql-plugin/src/main/spark321cdh/scala/com/nvidia/spark/rapids/spark321cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark322/scala/com/nvidia/spark/rapids/spark322/RapidsShuffleManager.scala
  sql-plugin/src/main/spark323/scala/com/nvidia/spark/rapids/spark323/RapidsShuffleManager.scala
  sql-plugin/src/main/spark324/scala/com/nvidia/spark/rapids/spark324/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/spark330/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330cdh/scala/com/nvidia/spark/rapids/spark330cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/spark330db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark331/scala/com/nvidia/spark/rapids/spark331/RapidsShuffleManager.scala
  sql-plugin/src/main/spark332cdh/scala/com/nvidia/spark/rapids/spark332cdh/RapidsShuffleManager.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/spark332db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark333/scala/com/nvidia/spark/rapids/spark333/RapidsShuffleManager.scala
  sql-plugin/src/main/spark334/scala/com/nvidia/spark/rapids/spark334/RapidsShuffleManager.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/spark340/RapidsShuffleManager.scala
  sql-plugin/src/main/spark341/scala/com/nvidia/spark/rapids/spark341/RapidsShuffleManager.scala
  sql-plugin/src/main/spark341db/scala/com/nvidia/spark/rapids/spark341db/RapidsShuffleManager.scala
  sql-plugin/src/main/spark342/scala/com/nvidia/spark/rapids/spark342/RapidsShuffleManager.scala
  sql-plugin/src/main/spark343/scala/com/nvidia/spark/rapids/spark343/RapidsShuffleManager.scala
  sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/spark350/RapidsShuffleManager.scala
  sql-plugin/src/main/spark351/scala/com/nvidia/spark/rapids/spark351/RapidsShuffleManager.scala
  sql-plugin/src/main/spark352/scala/com/nvidia/spark/rapids/spark352/RapidsShuffleManager.scala
  sql-plugin/src/main/spark353/scala/com/nvidia/spark/rapids/spark353/RapidsShuffleManager.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/spark400/RapidsShuffleManager.scala
Labels: build, tech debt

#11656 [DOC] update the supported OS in download page [skip ci]
  docs/download.md
Labels: documentation

#11664 Fix `orc_write_test.py` for [databricks] 14.3
  integration_tests/src/main/python/orc_write_test.py
Labels: test

#11596 Add a new NVTX range for task GPU ownership
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: task

#11672 Fix race condition with Parquet filter pushdown modifying shared hadoop Configuration
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#11676 Fix race condition with Parquet filter pushdown modifying shared hadoop Configuration
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
Labels: bug

#11680 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#11682 Fix auto merge conflict 11679 [skip ci]
  CHANGELOG.md
Labels: documentation, build
