Repository NVIDIA/spark-rapids, pull requests merged in 2024-04, with the labels that each got.

#10614 Use random seed for `test_from_json_struct_decimal` [databricks]
  integration_tests/src/main/python/json_test.py
Labels: test

#10617 Host Memory OOM handling for RowToColumnarIterator
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnOverflow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowToColumnarIteratorRetrySuite.scala
Labels: reliability

#10637 Cleanup async state when multi-threaded shuffle readers fail
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/RapidsShuffleInternalManagerBase.scala
  tests/src/test/spark321/scala/org/apache/spark/sql/rapids/RapidsShuffleThreadedReaderSuite.scala
Labels: bug

#10625 Pin to 3.1.0 maven-gpg-plugin in deploy script [skip ci]
  jenkins/deploy.sh
Labels: build

#10657 Revert "Host Memory OOM handling for RowToColumnarIterator (#10617)" [databricks]
  integration_tests/src/main/python/row_conversion_test.py
  sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnBuilder.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/RapidsHostColumnOverflow.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RowToColumnarIteratorRetrySuite.scala
Labels: build

#10652 Substitute murmurHash32 for spark32BitMurmurHash3 [databricks]
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
Labels: task

#10664 Remove build link from the premerge-CI workflow
  jenkins/Jenkinsfile-blossom.premerge
Labels: bug, build

#10662 Audit script - Check commits from shuffle and storage directories [skip ci]
  scripts/audit-spark.sh
Labels: task

#10667 Update rapids private dependency to 24.04.1
  pom.xml
  scala2.13/pom.xml
Labels: build

#10678 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#10654 Add a config to switch back to old impl for getJsonObject
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  docs/supported_ops.md
  integration_tests/src/main/python/get_json_test.py
  integration_tests/src/main/python/json_matrix_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuGetJsonObject.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tools/generated_files/311/supportedExprs.csv
  tools/generated_files/312/supportedExprs.csv
  tools/generated_files/313/supportedExprs.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: bug

#10660 Ensure an executor broadcast is in a single batch [databricks]
  integration_tests/src/main/python/aqe_test.py
  sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/GpuExecutorBroadcastHelper.scala
Labels: bug

#10681 Update rapids JNI dependency to 24.04.0, private to 24.04.1
  pom.xml
  scala2.13/pom.xml
Labels: build

#10683 Update latest changelog [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.12.md
Labels: documentation

#10706 Fix auto merge conflict 10704 [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_23.02_to_23.12.md
Labels: build

#10709 Removing some authorizations for departed users [skip ci]
  .github/workflows/blossom-ci.yml
Labels: bug, build, tech debt

#10707 [DOC] updates gh-pages files for 24.04.0 release [skip ci]
  docs/_config.yml
  docs/_sass/custom/custom.scss
  docs/additional-functionality/advanced_configs.md
  docs/archive.md
  docs/archives/CHANGELOG_0.1_to_0.5.md
  docs/archives/CHANGELOG_21.06_to_21.12.md
  docs/archives/CHANGELOG_22.02_to_22.12.md
  docs/archives/CHANGELOG_23.02_to_23.12.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation

#10292 Upgrade to UCX 1.16.0
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.multi
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: task

#10716 Remove the mixedType config for JSON as it has no downsides any longer
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuJsonScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonReadCommon.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuJsonToStructs.scala
Labels: task

#10635 Use new getJsonObject kernel for json_tuple
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_tuple_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tools/generated_files/311/supportedExprs.csv
  tools/generated_files/312/supportedExprs.csv
  tools/generated_files/313/supportedExprs.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: task

#10728 Let big data gen set nullability recursively
  datagen/src/main/scala/org/apache/spark/sql/tests/datagen/bigDataGen.scala
Labels: data gen

#10755 [DOC] Update README for prioritize-commits script [skip ci]
  scripts/README.md
Labels: documentation

#10754 Substitute whoami for $USER
  build/build-info
Labels: build

#10752 Add SparkRapidsBuildInfoEvent to the event log
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/TrampolineUtil.scala
Labels: feature request
