Repository NVIDIA/spark-rapids, pull requests merged in 2025-08, with the labels that each got.

#13229 Update dependency version JNI, private, hybrid to 25.10.0-SNAPSHOT
  jenkins/databricks/init_cudf_udf.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#13211 Improve the pull request template [skip ci]
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#13243 Define the DB required method named 'ensReqDPMetricTag' in GpuShuffleExechangeExec. [databricks]
  sql-plugin/src/main/spark350db143/scala/org/apache/spark/rapids/shims/GpuShuffleExchangeExec.scala
Labels: bug

#13262 Run test_decimal_precision_over_max for all Spark versions[databricks]
  integration_tests/src/main/python/decimal_precision_over_max_test.py
Labels: test

#13257 Update dependency version JNI, private, hybrid to 25.08.0 [databricks]
  pom.xml
  scala2.13/pom.xml
Labels: build

#13258 Update changelog for the v25.08 release [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_25.02-to-25.04.md
  docs/archives/CHANGELOG_25.02.md
Labels: documentation

#13280 Fix fallback test params for Delta MergeCommand, UpdateCommand, and DeleteCommand
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_merge_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
Labels: test

#13282 Update changelog for the v25.08 release [skip ci]
  CHANGELOG.md
Labels: documentation, build

#13284 Merge branch-25.08 into main
  CHANGELOG.md
  integration_tests/src/main/python/delta_lake_delete_test.py
  integration_tests/src/main/python/delta_lake_merge_test.py
  integration_tests/src/main/python/delta_lake_update_test.py
Labels: build

#13287 Revert "enable shellcheck" [skip ci]
  .github/workflows/shell-check.yml
  build/buildall
  build/coverage-report
  build/make-scala-version-build-files.sh
  dist/scripts/binary-dedupe.sh
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/build.sh
  jenkins/databricks/cudf_udf_test.sh
  jenkins/databricks/init_cudf_udf.sh
  jenkins/dependency-check.sh
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/version-def.sh
  scripts/audit-spark.sh
  scripts/prioritize-commits.sh
Labels: build

#13087 Add Support for map_zip_with
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/map_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/356/operatorsScore.csv
  tools/generated_files/356/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#13220 Add test cases for Collate, CharType and VarcharType
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/string_type_test.py
Labels: test, Spark 4.0+

#13053 Allowlist zlib for Orc writes
  integration_tests/src/main/python/hive_write_test.py
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: feature request

#13322 Fix testing.md to use fixed relative paths [skip ci]
  docs/dev/testing.md
Labels: documentation

#13333 Fix test_delta_optimize_fallback_on_clustered_table test failure with Spark 3.5.6 [databricks]
  integration_tests/src/main/python/delta_lake_optimize_table_test.py
Labels: bug, test

#13338 Suppress deprecation warnings for `ParseURI`
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuParseUrl.scala
Labels: bug

#13344 [DOC] update the wrong links in download doc [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#13356 CUDF Conda package has dropped cuda11 python packages from 25.10 [skip ci]
  jenkins/databricks/init_cudf_udf.sh
Labels: test
