Repository NVIDIA/spark-rapids, pull requests merged in 2025-02, with the labels that each got.

#12054 Update the version of the rapids-hybrid-execution dependency.
  jenkins/hybrid_execution.sh
Labels: build

#12060 Relax decimal metadata checks for mismatched precision/scale [databricks]
  integration_tests/src/main/python/parquet_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: bug

#12064 Run mvn with the project's pom.xml in hybrid_execution.sh
  jenkins/hybrid_execution.sh
Labels: build

#12068 Do not build Spark-4.0.0-SNAPSHOT [skip ci]
  build/get_buildvers.py
  pom.xml
  scala2.13/pom.xml
Labels: build, Spark 4.0+

#12080 Quick fix for hybrid tests without git information.
  jenkins/hybrid_execution.sh
Labels: bug

#12075 Use SHUFFLE_KUDO_SERIALIZER_MEASURE_BUFFER_COPY_ENABLED for [databricks]
  delta-lake/common/src/main/databricks/scala/org/apache/spark/sql/rapids/delta/GpuOptimizeWriteExchangeExec.scala
Labels: bug

#12082 Use 350db143 jars in integration tests on [databricks] 14.3
  integration_tests/run_pyspark_from_build.sh
  jenkins/databricks/common_vars.sh
Labels: bug

#12058 upgrade jucx to 1.18
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: feature request

#12103 Revert "Enable event log for qualification & profiling tools testing …
  jenkins/databricks/test.sh
Labels: bug, test

#12114 Fix HybridParquetScan over select(1)
  integration_tests/src/main/python/hybrid_parquet_test.py
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridExecutionUtils.scala
Labels: bug

#12092 Fix an assertion error in the sized hash join
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
Labels: bug

#12110 Upgrade ucx to 1.18
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: task

#12138 Use SPARK_SHIM_VER in RapidsShuffleManager package [databricks]
  jenkins/databricks/test.sh
Labels: bug, test

#12141 Xfail test_delta_update_fallback_with_deletion_vectors on [databricks]
  integration_tests/src/main/python/delta_lake_update_test.py
Labels: bug, test

#12102 [DOC] update the download page for 2502 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#12129 Update dependency version JNI, private, hybrid to 25.02.0 [skip ci]
  .github/workflows/mvn-verify-check/get-deps-sha1.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#12155 Fix auto merge conflict 12153 [skip ci]
  .github/workflows/mvn-verify-check/get-deps-sha1.sh
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.10.md
Labels: documentation, build

#12157 Add hybrid sha1 to mvn verify cache key [skip ci]
  .github/workflows/mvn-verify-check/get-deps-sha1.sh
Labels: build

#12188 Update dependency version JNI to 25.02.1-SNAPSHOT
  pom.xml
  scala2.13/pom.xml
Labels: build

#12205 Workaround: tmply disable the HostAllocSuite to unblock CI [skip ci]
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: test

#12183 Add GPU support for `spark.sql.catalyst.expressions.Slice`
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12148 Add the pre-split support to GPU project
  integration_tests/src/main/python/project_presplit_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuBatchUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/window/GpuWindowExecMeta.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/ComplexCreatorSizeEstimationTest.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/LiteralSizeEstimationTest.scala
Labels: reliability

#12204 [DOC] address ghpage pr comments [skip ci]
  docs/dev/hybrid-execution.md
  docs/download.md
Labels: documentation

#12185 [DOC] updates gh-pages docs for 25.02.0 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/archive.md
  docs/configs.md
  docs/dev/hybrid-execution.md
  docs/dev/idea-code-style-settings.xml
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation

#12198 Refactor SparkStrategy to fix Spark-4.0 build
  delta-lake/common/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProviderImplBase.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala
Labels: build, Spark 4.0+

#12237 Simplify mvn verify cache key [skip ci]
  .github/workflows/mvn-verify-check.yml
  .github/workflows/mvn-verify-check/get-deps-sha1.sh
Labels: build

#12239 Mirror the Cloudera Maven repository
  jenkins/settings.xml
Labels: build

#12236 make kudo shuffle read retryable and spillable
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuColumnarBatchSerializer.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableKudoTable.scala
Labels: reliability

#12233 Add retry with SpillableHostBuffer to GPU scans
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/SpillableColumnarBatch.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: reliability
