Repository NVIDIA/spark-rapids, pull requests merged in 2025-10, with the labels that each got.

#13558 Avoid throwing ClassNotFoundExceptions when checking isSupportedFormat with Delta Lake versions < 2.0.1
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/DeltaIOProvider.scala
Labels: bug

#13532 Fix read option name for change data feed for Delta [databricks]
  integration_tests/src/main/python/delta_lake_low_shuffle_merge_test.py
  integration_tests/src/main/python/delta_lake_utils.py
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: bug, test

#13572 Upgrade UCX to 1.19-rc1
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: feature request
