Repository NVIDIA/spark-rapids, pull requests merged in 2025-06, with the labels that each got.

#12847 Update spark400 to released version
  pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/spark400/SparkShimServiceProvider.scala
Labels: Spark 4.0+

#12868 Fix double column mapping in delta 3.3 parquet reader
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala
  delta-lake/delta-33x/src/main/scala/com/nvidia/spark/rapids/delta/delta33x/GpuDelta33xParquetFileFormat.scala
Labels: bug

#12831 Support eager I/O prefetch for scan as two-sides of bucket ShuffleSizedHashJoin
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/BucketJoinTwoSidesPrefetch.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusNonDBShims.scala
Labels: performance

#12842 Add the NV license to relevant py files[skip ci]
  python/rapids/daemon_databricks.py
Labels: documentation

#12894 Disable multi thread reader with deletions in iceberg[databricks]
  iceberg/src/main/scala/org/apache/iceberg/spark/source/GpuReaderFactory.scala
Labels: bug

#12680 cpu mem defaults
  docs/additional-functionality/advanced_configs.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/MemoryChecker.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
Labels: feature request

#12892 Fix Column to Expression conversion for Spark 4.0
  sql-plugin/src/main/spark400/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala
Labels: bug, Spark 4.0+

#12869 Revert "Remove Delta Lake 3.3.0 support from the plugin for Spark 3.5.3, 3.5.4 and 3.5.5 (#12853)"
  delta-lake/README.md
  pom.xml
  scala2.13/pom.xml
Labels: task

#12925 [Spark-4.0]: Resolve integration tests in parquet_test
  integration_tests/src/main/python/parquet_test.py
Labels: test, Spark 4.0+

#12846 [DOC] update the download doc for 2506 release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#12935 XFAIL failing tests in `delta_lake_write_test.py` and assert fallback for Delta Lake 3.3.x [databricks]
  delta-lake/delta-33x/src/main/scala/com/nvidia/spark/rapids/delta/delta33x/Delta33xProvider.scala
  integration_tests/src/main/python/delta_lake_write_test.py
Labels: task

#13009 [DOC] update the download doc for 2506 release [skip ci] (#12846)
  docs/archive.md
  docs/download.md
Labels: documentation
