Repository NVIDIA/spark-rapids, pull requests merged in 2025-04, with the labels that each got.

#12397 Set the `spark.rapids.sql.format.parquet.reader.type` to `AUTO` even on Databricks 14.3
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: bug, test

#12426 Use a single listener for all timeout fixture invocations
  integration_tests/src/main/java/org/apache/spark/rapids/tests/TimeoutSparkListener.java
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, test

#12448 Ignore flaky "test task metrics" from ThrottlingExecutorSuite
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/io/async/ThrottlingExecutorSuite.scala
Labels: bug, test

#12459 Unblock CI due to #12452 and #12453
  integration_tests/src/main/python/hyper_log_log_plus_plus_test.py
  integration_tests/src/main/python/parquet_testing_test.py
Labels: bug, test

#12464 Disable HLLPP precision 4 due to cuCollection bug
  docs/compatibility.md
  integration_tests/src/main/python/hyper_log_log_plus_plus_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
Labels: bug, test

#12456 Fix the Pandas UDF test failures on DB14.3[databricks]
  integration_tests/src/main/python/udf_test.py
Labels: bug, test

#12490 Fix bug where rows dropped if partitioned column size is too large
  integration_tests/src/main/python/col_size_exceeding_cudf_limit_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarPartitionReaderWithPartitionValues.scala
Labels: bug

#12416 Enable kudo by default.
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/lore/GpuLoreSuite.scala
Labels: feature request

#12463 Fix the flaky ThrottlingExecutor task metrics test
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/io/async/ThrottlingExecutorSuite.scala
Labels: test

#12306 Accelerate ArrayDistinct
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/ArrayUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12473 Update dependency version JNI, private, hybrid to 25.04.0
  pom.xml
  scala2.13/pom.xml
Labels: build

#12494 Update changelog for v25.04.0 release [skip ci]
  CHANGELOG.md
  docs/archives/CHANGELOG_24.02-to-24.12.md
  scripts/generate-changelog
Labels: build

#12513 Update CICD defaults to ubuntu 22.04
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/Jenkinsfile-blossom.premerge
Labels: build

#12455 Crash pytest worker if the Pyspark child JVM is unusable
  integration_tests/src/main/java/org/apache/spark/rapids/tests/TimeoutSparkListener.java
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, test

#12370 HybridScan: Add a specific SQL Hint
  integration_tests/src/main/python/hybrid_parquet_test.py
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuPostHocResolutionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridExecutionUtils.scala
Labels: feature request

#12525 Explicitly disable LTO in shuffle example dockerfiles [skip ci]
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
Labels: build

#12535 Fix bug when join side is outer side
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: bug

#12543 Update changelog for the v25.04 release [skip ci]
  CHANGELOG.md
Labels: documentation

#12545 Merge branch-25.04 into main [skip ci]
  CHANGELOG.md
  integration_tests/src/main/python/join_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala
Labels: build

#12437 Fully support Conv expression [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/string_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/ConvShim.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/errors/ConvUtils.scala
  sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/ConvShim.scala
  sql-plugin/src/main/spark340/scala/org/apache/spark/sql/errors/ConvUtils.scala
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12559 Update Databricks CICD default Ubuntu Docker image to 22.04 [databricks]
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/Jenkinsfile-blossom.premerge-databricks
Labels: build

#12565 fix broken nvtx_ranges link [skip ci]
  docs/dev/nvtx_profiling.md
Labels: documentation

#12568 A quick fix for the rmm import issue [databricks]
  python/rapids/worker.py
Labels: test

#12560 [DOC] updates gh-pages docs for 25.04.0 release [skip ci]
  docs/additional-functionality/advanced_configs.md
  docs/additional-functionality/rapids-udfs.md
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  docs/archive.md
  docs/compatibility.md
  docs/configs.md
  docs/dev/hybrid-execution.md
  docs/dev/lore.md
  docs/dev/mem_debug.md
  docs/dev/shims.md
  docs/dev/testing.md
  docs/download.md
  docs/supported_ops.md
Labels: documentation

#12414 HybridScan: Fix supported expressions list in filter pushdown
  integration_tests/src/main/python/hybrid_parquet_test.py
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridExecutionUtils.scala
Labels: bug, test

#12394 Add a way to override the PLUGIN_JARS [databricks]
  integration_tests/README.md
  integration_tests/run_pyspark_from_build.sh
Labels: test

#12569 Fix overflow for `stddev` and `variance` SQL functions
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
Labels: bug

#12588 Fix the Python pip installation failure using 'get-pip.py' [databricks]
  jenkins/databricks/setup.sh
Labels: bug

#12595 [Cherry-pic] Fix the Python pip installation failure using 'get-pip.py' [skip ci]
  jenkins/databricks/setup.sh
Labels: build
