Repository NVIDIA/spark-rapids, pull requests merged in 2025-05, with the labels that each got.

#12572 Add sha1
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hashing_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/HashFunctions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12433 Run unit tests with both ANSI modes enabled and disabled containing HashAggregates for Spark 4.0
  scala2.13/tests/pom.xml
  tests/pom.xml
  tests/src/test/scala/com/nvidia/spark/rapids/DecimalBinaryOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ExpandExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuBringBackToHostSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/UnaryOperatorsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/lore/GpuLoreSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcFilterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
Labels: test, Spark 4.0+

#12502 Add Support For Timezone Rules
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/data_gen.py
  integration_tests/src/main/python/date_time_test.py
  integration_tests/src/main/python/timezones.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala
  tests/src/test/scala/com/nvidia/spark/rapids/timezone/TimeZonePerfSuite.scala
Labels: feature request

#12627 Always use boolean columnar to columnar conversion
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HostColumnarToGpu.scala
Labels: bug

#12618 Restrict the pyarrow version to 19.0.1 in requirements.txt [databricks]
  integration_tests/requirements.txt
  jenkins/databricks/setup.sh
Labels: test

#12634 Allow NonGPU for MonthsBetween Tests
  integration_tests/src/main/python/date_time_test.py
Labels: bug

#12558 by default enable skip agg
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuAggregateExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: performance

#12602 Update UCX default ver to 1.18.1 to support ubuntu24.04
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.rocky_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
  pom.xml
  scala2.13/pom.xml
Labels: build

#12636 [Spark-4.0] ParseDateDateTimeSuite- Skip some of the unit tests when ansi is enabled
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
Labels: test, Spark 4.0+

#12670 Add deepwiki badge [skip ci]
  README.md
Labels: documentation

#12667 Allow 0 for some footer fields [Databricks]
  integration_tests/src/main/python/parquet_test.py
  integration_tests/src/test/resources/empty_arrow.parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetScan.scala
Labels: bug

#12374 Use metrics about memory usage to adjust the number of concurrent tasks
  docs/additional-functionality/advanced_configs.md
  docs/configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/PrioritySemaphore.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuTaskMetrics.scala
  tests/src/test/scala/com/nvidia/spark/rapids/PrioritySemaphoreSuite.scala
Labels: ease of use

#12622 Fix the failing delta log query test test_delta_read_with_deletion_vectors_enabled [databricks]
  integration_tests/src/main/python/delta_lake_test.py
Labels: test

#12705 [DO NOT REVIEW] fix spill framework bug causing gpu oom
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
Labels: bug

#12721 Fix auto merge conflict 12710 [skip ci]
  iceberg-common/pom.xml
  iceberg/pom.xml
  iceberg/src/main/java/com/nvidia/spark/rapids/iceberg/parquet/GpuParquetReader.java
  iceberg/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  iceberg/src/main/scala/com/nvidia/spark/rapids/iceberg/parquet/converter/FromIcebergShaded.scala
  integration_tests/src/main/python/delta_lake_test.py
  pom.xml
  scala2.13/iceberg-common/pom.xml
  scala2.13/iceberg/pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
Labels: build

#12693 Disable Databricks 11.3 shim build [databricks]
  delta-lake/README.md
  jenkins/Jenkinsfile-blossom.premerge-databricks
  jenkins/databricks/common_vars.sh
  jenkins/databricks/setup.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#12607 Support bitwise aggregate functions (`bit_and`, `bit_or` and `bit_xor`) in groupby and reduction
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/hash_aggregate_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/aggregate/aggregateFunctions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, P0, cudf_dependency

#12731 Update SHIM_M2DIR for all shims build if DEV_MODE is enabled [skip ci]
  jenkins/spark-nightly-build.sh
Labels: build

#12606 Support `bit_count` SQL function
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/bitwise.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request, SQL, P0, cudf_dependency

#12688 Propagate errors to JVM while initializing GPU memory in python worker
  integration_tests/pytest.ini
  python/rapids/daemon.py
  python/rapids/daemon_databricks.py
  python/rapids/worker.py
Labels: bug

#12761 Use cuda12 as default, drop cuda11 support [databricks]
  CONTRIBUTING.md
  build/buildall
  delta-lake/delta-33x/pom.xml
  docs/configs.md
  integration_tests/README.md
  jenkins/Dockerfile-blossom.integration.rocky
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
  jenkins/version-def.sh
  pom.xml
  scala2.13/delta-lake/delta-33x/pom.xml
  scala2.13/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: test, build

#12684 Spark-4.0: Fix/Skip non-ansi unit test failures
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/OperatorsUtilShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/Spark320PlusShims.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/OperatorsUtilShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetWriterSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/TimeOperatorsSuite.scala
Labels: test, Spark 4.0+

#12760 Accelerate premerge CI with non-PVC workspace
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build

#12776 Enable pr desc check [skip ci]
  .github/workflows/pr-description-check.yml
Labels: build

#12777 Fix auto merge conflict 12774 [skip ci]
  .github/workflows/pr-description-check.yml
  jenkins/Jenkinsfile-blossom.premerge
  jenkins/spark-premerge-build.sh
Labels: build

#12798 Update dockerfile to use HTTPS service for ubuntu repos [skip ci]
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma
  docs/additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
  jenkins/Dockerfile-blossom.integration.ubuntu
  jenkins/Dockerfile-blossom.ubuntu
Labels: build

#12809 Temporarily disable test case test_delta_scan_read [databricks]
  integration_tests/src/main/python/delta_lake_test.py
Labels: test

#12817 Fix the dead links issue for Pandas UDFs doc[skip ci]
  docs/additional-functionality/rapids-udfs.md
Labels: documentation

#12812 Replace stale use_cdf parameter reference in test_delta_scan_read pytest [databricks]
  integration_tests/src/main/python/delta_lake_test.py
Labels: bug

#12598 Fully support casting string with timezone to timestamp [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/compatibility.md
  integration_tests/src/main/python/cast_test.py
  integration_tests/src/main/python/explain_test.py
  integration_tests/src/main/python/spark_session.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala
Labels: feature request
