Repository NVIDIA/spark-rapids, pull requests merged in 2025-03, with the labels that each got.

#12214 Change JsonTuple Implemenation to MultiGetJSONObject
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuJsonTuple.scala
Labels: task

#12253 Accelerate nightly build [skip ci]
  jenkins/Dockerfile-blossom.ubuntu
  jenkins/spark-nightly-build.sh
Labels: build

#12252 Update dependency version private to 25.02.1-SNAPSHOT
  pom.xml
  scala2.13/pom.xml
Labels: build

#12241 Add validation for `start` and `length` parameters for `slice`
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/collectionOperations.scala
Labels: task

#12270 Add AST expression support for `IsNull` and `IsNotNull`
  docs/supported_ops.md
  integration_tests/src/main/python/ast_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/nullExpressions.scala
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12280 Disable hybrid cases for spark35X [skip ci]
  jenkins/version-def.sh
Labels: test

#12221 Add support for `ORC` stripe cudf size configs
  integration_tests/src/main/python/orc_write_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala
Labels: task

#12282 [DOC] update the download page for 2502.1 hot release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#12289 Update dependency version JNI, private to 25.02.1
  pom.xml
  scala2.13/pom.xml
Labels: build

#12294 Update changelog for the v25.02 release [skip ci]
  CHANGELOG.md
Labels: documentation

#12262 Enable GPU acceleration for Hive delimited text write
  docs/additional-functionality/advanced_configs.md
  integration_tests/src/main/python/hive_delimited_text_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#11743 Add test for ORC write with two stripes
  integration_tests/src/main/python/orc_write_test.py
Labels: test

#12302 [DOC] updates gh-pages docs for 25.02.1 hot release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#12249 Fix bloop project generation on [databricks]
  jenkins/databricks/build.sh
  pom.xml
  scala2.13/pom.xml
Labels: bug

#12318 Fix integration tests compilation due to missing function in TrampolineUtil
  integration_tests/src/test/scala/org/apache/spark/sql/nvidia/SparkTestBase.scala
  integration_tests/src/test/spark320/scala/org/apache/spark/sql/rapids/shims/TrampolineUtilShim.scala
  integration_tests/src/test/spark400/scala/org/apache/spark/sql/rapids/shims/TrampolineUtilShim.scala
Labels: bug

#12328 Fix empty broadcast conversion
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala
Labels: bug

#12248 Reenable JsonTuple
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/json_matrix_test.py
  integration_tests/src/main/python/json_tuple_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsJsonConfTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsSQLTestsBaseTrait.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestsTrait.scala
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/supportedExprs.csv
Labels: task

#12313 Fix Spark-4.0 build errors for tests module.
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/TrampolineConnectShims.scala
  sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/spark400/SparkShimServiceProvider.scala
  sql-plugin/src/main/spark400/scala/org/apache/spark/sql/rapids/shims/TrampolineConnectShims.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AdaptiveQueryExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/AnsiCastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ApproximatePercentileSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CastOpSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ConditionalsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ExpandExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FilterExprSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/FuzzerUtils.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashAggregatesSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/HashSortOptimizeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/JoinsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/LimitExecSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/OrcQuerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/OrcScanSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParquetQuerySuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/ParseDateTimeSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/RegularExpressionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/SparkQueryCompareTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/StringFunctionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/WindowFunctionSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/tests/CacheTestSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/unit/DecimalUnitTest.scala
  tests/src/test/scala/org/apache/spark/sql/GpuSparkPlanSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/OrcFilterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/ProjectExprSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/TestTrampolineUtil.scala
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/GpuInSubqueryExecSuite.scala
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExecs.csv
  tools/generated_files/400/supportedExprs.csv
Labels: build, Spark 4.0+

#12317 Always respect the new conf for RMM allocation mode
  docs/additional-functionality/advanced_configs.md
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/python/PythonConfEntries.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonHelper.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuDeviceManagerSuite.scala
  tests/src/test/scala/org/apache/spark/sql/rapids/execution/python/GpuPythonHelperSuite.scala
Labels: bug

#12308 Add support for `org.apache.spark.sql.catalyst.expressions.ArrayPosition` [databricks]
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/array_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/complexTypeExtractors.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/355/operatorsScore.csv
  tools/generated_files/355/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#12325 Add option to dump kudo tables for debugging
  integration_tests/src/main/python/kudo_dump_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffleCoalesceExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExecSuite.scala
Labels: tools, reliability

#12356 Add 350db143 as supported by spark320 SparkSessionUtils [databricks]
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/SparkSessionUtils.scala
Labels: bug

#12363 Added Databricks 14.3 Specific Error Messages [databricks]
  integration_tests/src/main/python/array_test.py
Labels: test

#12362 HybridScan: a hotfix over previous changes on HybridExecutionUtils.useHybridScan
  integration_tests/src/main/python/hybrid_parquet_test.py
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridExecutionUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridFileSourceScanExec.scala
Labels: bug

#12375 Updating link to RapidsUDF.java
  docs/additional-functionality/rapids-udfs.md
Labels: bug, documentation

#12338 print spillable summary on bookkeep
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
Labels: task, reliability

#12352 Refine split-retry logs to expose the real reason
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RmmRapidsRetryIterator.scala
Labels: bug

#12380 add doc for ai.rapids.memory.bookkeep
  docs/dev/mem_debug.md
Labels: documentation

#12346 Implement Job-level timeout for pytests to avoid forever hangs [databricks]
  integration_tests/pytest.ini
  integration_tests/src/main/java/org/apache/spark/rapids/tests/TimeoutSparkListener.java
  integration_tests/src/main/python/spark_init_internal.py
  integration_tests/src/main/python/udf_test.py
Labels: test

#12224 add test case for issue 12158
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/HostAllocSuite.scala
Labels: test

#12372 Allow BigSizedJoinIterator#buildPartitioner to produce more subparittions
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuShuffledSizedHashJoinExec.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuSortMergeJoinMeta.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
Labels: feature request

#12404 Remove special timeout for udf_test
  integration_tests/src/main/python/udf_test.py
Labels: test

#12419 WAR: hardcode fsspec==2025.3.0 [skip ci]
  integration_tests/requirements.txt
  jenkins/databricks/setup.sh
Labels: test

#12415 Use 1hr as the default Spark action timeout
  integration_tests/src/main/python/spark_init_internal.py
Labels: bug, test
