Repository NVIDIA/spark-rapids, pull requests merged in 2025-01, with the labels that each got.

#11910 fix bug: enable if_modified_files check for all shims in github actions [skip ci]
  dist/pom.xml
  scala2.13/dist/pom.xml
  scala2.13/tools/pom.xml
  tools/pom.xml
Labels: bug, build

#11915 Deploy the sources and Javadoc JARs in the nightly CICD [skip ci]
  jenkins/deploy.sh
  jenkins/spark-nightly-build.sh
Labels: build

#11938 Update codeowners file to use team [skip ci]
  .github/CODEOWNERS
Labels: build

#11920 Remove Alluxio support [databricks]
  delta-lake/common/src/main/databricks/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormatBase.scala
  delta-lake/common/src/main/delta-io/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala
  delta-lake/delta-24x/src/main/scala/com/nvidia/spark/rapids/delta/delta24x/GpuDelta24xParquetFileFormat.scala
  delta-lake/delta-spark341db/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala
  delta-lake/delta-spark350db143/src/main/scala/com/nvidia/spark/rapids/delta/GpuDeltaParquetFileFormat.scala
  docs/additional-functionality/advanced_configs.md
  pom.xml
  scala2.13/pom.xml
  scala2.13/sql-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuMultiFileBatchReader.java
  sql-plugin/src/main/java/com/nvidia/spark/rapids/iceberg/spark/source/GpuSparkScan.java
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioCfgUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioConfigReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioFS.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/AlluxioUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadCSVFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadFileFormatWithMetrics.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadOrcFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuReadParquetFileFormat.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/catalyst/json/rapids/GpuReadJsonFileFormat.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuReadAvroFileFormat.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/FileIndexOptionsShims.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/spark320/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/spark330/scala/org/apache/spark/sql/types/shims/PartitionValueCastShims.scala
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/FileSourceScanExecMeta.scala
  sql-plugin/src/main/spark332db/scala/com/nvidia/spark/rapids/shims/FileIndexOptionsShims.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioConfigReaderSuite.scala
  sql-plugin/src/test/scala/com/nvidia/spark/rapids/AlluxioUtilsSuite.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
  tests/src/test/spark321/scala/com/nvidia/spark/rapids/DynamicPruningSuite.scala
Labels: task

#11939 [DOC] update release note to add spark 353 support [skip ci]
  docs/download.md
Labels: documentation

#11941 [DOC] update release note to add spark version support [skip ci]
  docs/download.md
Labels: documentation

#11944 Update download page for 24.12.1 hot fix release [skip ci]
  docs/archive.md
  docs/download.md
Labels: documentation

#11943 Update rapids JNI dependency to 24.12.1
  pom.xml
  scala2.13/pom.xml
Labels: build

#11950 Update latest changelog [skip ci]
  CHANGELOG.md
Labels: documentation

#11952 Fix auto merge conflict 11948 [skip ci]
  CHANGELOG.md
  aggregator/pom.xml
  api_validation/pom.xml
  datagen/pom.xml
  delta-lake/delta-20x/pom.xml
  delta-lake/delta-21x/pom.xml
  delta-lake/delta-22x/pom.xml
  delta-lake/delta-23x/pom.xml
  delta-lake/delta-24x/pom.xml
  delta-lake/delta-spark330db/pom.xml
  delta-lake/delta-spark332db/pom.xml
  delta-lake/delta-spark341db/pom.xml
  delta-lake/delta-spark350db143/pom.xml
  delta-lake/delta-stub/pom.xml
  integration_tests/pom.xml
  jdk-profiles/pom.xml
  jenkins/databricks/create.py
  jenkins/version-def.sh
  scala2.13/aggregator/pom.xml
  scala2.13/api_validation/pom.xml
  scala2.13/datagen/pom.xml
  scala2.13/delta-lake/delta-20x/pom.xml
  scala2.13/delta-lake/delta-21x/pom.xml
  scala2.13/delta-lake/delta-22x/pom.xml
  scala2.13/delta-lake/delta-23x/pom.xml
  scala2.13/delta-lake/delta-24x/pom.xml
  scala2.13/delta-lake/delta-spark330db/pom.xml
  scala2.13/delta-lake/delta-spark332db/pom.xml
  scala2.13/delta-lake/delta-spark341db/pom.xml
  scala2.13/delta-lake/delta-spark350db143/pom.xml
  scala2.13/delta-lake/delta-stub/pom.xml
  scala2.13/integration_tests/pom.xml
  scala2.13/jdk-profiles/pom.xml
  scala2.13/shim-deps/cloudera/pom.xml
  scala2.13/shim-deps/databricks/pom.xml
  scala2.13/shim-deps/pom.xml
  scala2.13/shuffle-plugin/pom.xml
  scala2.13/sql-plugin-api/pom.xml
  scala2.13/tests/pom.xml
  scala2.13/udf-compiler/pom.xml
  shim-deps/cloudera/pom.xml
  shim-deps/databricks/pom.xml
  shim-deps/pom.xml
  shuffle-plugin/pom.xml
  sql-plugin-api/pom.xml
  sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  tests/pom.xml
  udf-compiler/pom.xml
Labels: documentation

#11959 Remove inactive user from github workflow[skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#11958 Update to use vulnerability-scan runner [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#11960 Remove jlowe as committer since he retired
  .github/workflows/blossom-ci.yml
  pom.xml
  scala2.13/pom.xml
Labels: build

#11911 Avoid concatentating multiple host buffers when reading Parquet
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/DumpUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala
  tests/src/test/scala/com/nvidia/spark/rapids/GpuMultiFileReaderSuite.scala
Labels: cudf_dependency

#11720 Introduce hybrid (CPU) scan for Parquet read [databricks]
  docs/dev/hybrid-execution.md
  integration_tests/run_pyspark_from_build.sh
  integration_tests/src/main/python/hybrid_parquet_test.py
  integration_tests/src/main/python/marks.py
  integration_tests/src/main/python/spark_session.py
  scala2.13/sql-plugin/pom.xml
  sql-plugin/pom.xml
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/HybridExecutionUtils.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/CoalesceConvertIterator.scala
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridFileSourceScanExec.scala
  sql-plugin/src/main/scala/org/apache/spark/rapids/hybrid/HybridParquetScanRDD.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/HybridFileSourceScanExecMeta.scala
  sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/ScanExecShims.scala
  sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/ScanExecShims.scala
Labels: performance

#11972 Update MockTaskContext to support new functions added in Spark-4.0 [databricks]
  docs/dev/shims.md
  tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala
Labels: bug, Spark 4.0+

#11969 Support `raise_error()` on [databricks] 14.3, Spark 4.
  integration_tests/src/main/python/misc_expr_test.py
  sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/RaiseErrorShim.scala
  sql-plugin/src/main/spark350db143/scala/org/apache/spark/sql/rapids/shims/misc.scala
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
Labels: feature request

#11973 Minor change: Make Hybrid version a separate config like priviate repo
  pom.xml
  scala2.13/pom.xml
  scala2.13/sql-plugin/pom.xml
  sql-plugin/pom.xml
Labels: build

#11978 Try to fix Scala 2.13 nightly failure: can not find version-def.sh
  jenkins/hybrid_execution.sh
  jenkins/spark-premerge-build.sh
  jenkins/spark-tests.sh
Labels: build

#11982 Use common add-to-project action [skip ci]
  .github/workflows/add-to-project.yml
Labels: build

#11967 Add support for `org.apache.spark.sql.catalyst.expressions.Bin`
  docs/additional-functionality/advanced_configs.md
  docs/supported_ops.md
  integration_tests/src/main/python/arithmetic_ops_test.py
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala
  sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala
  tools/generated_files/320/operatorsScore.csv
  tools/generated_files/320/supportedExprs.csv
  tools/generated_files/321/operatorsScore.csv
  tools/generated_files/321/supportedExprs.csv
  tools/generated_files/321cdh/operatorsScore.csv
  tools/generated_files/321cdh/supportedExprs.csv
  tools/generated_files/322/operatorsScore.csv
  tools/generated_files/322/supportedExprs.csv
  tools/generated_files/323/operatorsScore.csv
  tools/generated_files/323/supportedExprs.csv
  tools/generated_files/324/operatorsScore.csv
  tools/generated_files/324/supportedExprs.csv
  tools/generated_files/330/operatorsScore.csv
  tools/generated_files/330/supportedExprs.csv
  tools/generated_files/330cdh/operatorsScore.csv
  tools/generated_files/330cdh/supportedExprs.csv
  tools/generated_files/331/operatorsScore.csv
  tools/generated_files/331/supportedExprs.csv
  tools/generated_files/332/operatorsScore.csv
  tools/generated_files/332/supportedExprs.csv
  tools/generated_files/332cdh/operatorsScore.csv
  tools/generated_files/332cdh/supportedExprs.csv
  tools/generated_files/333/operatorsScore.csv
  tools/generated_files/333/supportedExprs.csv
  tools/generated_files/334/operatorsScore.csv
  tools/generated_files/334/supportedExprs.csv
  tools/generated_files/340/operatorsScore.csv
  tools/generated_files/340/supportedExprs.csv
  tools/generated_files/341/operatorsScore.csv
  tools/generated_files/341/supportedExprs.csv
  tools/generated_files/342/operatorsScore.csv
  tools/generated_files/342/supportedExprs.csv
  tools/generated_files/343/operatorsScore.csv
  tools/generated_files/343/supportedExprs.csv
  tools/generated_files/344/operatorsScore.csv
  tools/generated_files/344/supportedExprs.csv
  tools/generated_files/350/operatorsScore.csv
  tools/generated_files/350/supportedExprs.csv
  tools/generated_files/351/operatorsScore.csv
  tools/generated_files/351/supportedExprs.csv
  tools/generated_files/352/operatorsScore.csv
  tools/generated_files/352/supportedExprs.csv
  tools/generated_files/353/operatorsScore.csv
  tools/generated_files/353/supportedExprs.csv
  tools/generated_files/354/operatorsScore.csv
  tools/generated_files/354/supportedExprs.csv
  tools/generated_files/400/operatorsScore.csv
  tools/generated_files/400/supportedExprs.csv
  tools/generated_files/operatorsScore.csv
  tools/generated_files/supportedExprs.csv
Labels: feature request

#11956 Enable tests in RapidsParquetSchemaPruningSuite
  tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
Labels: test

#11977 Use bounce buffer pools in the Spill Framework
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
  sql-plugin/src/main/scala/com/nvidia/spark/rapids/spill/SpillFramework.scala
Labels: task

#11997 Configure 14.3 support at runtime [databricks]
  jenkins/databricks/test.sh
  sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/DatabricksShimServiceProvider.scala
  sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/spark350db143/SparkShimServiceProvider.scala
Labels: feature request

#12045 [DOC] updates gh-pages docs for 24.12.1 release [skip ci]
  docs/archive.md
  docs/configs.md
  docs/dev/shims.md
  docs/download.md
Labels: documentation

#12050 Fixed `FileSourceScanExec` and `BatchScanExec` inadvertently falling to the CPU in non-utc orc tests
  integration_tests/src/main/python/orc_cast_test.py
  integration_tests/src/main/python/orc_test.py
Labels: bug

#12044 Set CI=true for complete failure reason in summary
  integration_tests/run_pyspark_from_build.sh
Labels: test

#12030 Update dependency version JNI, private, hybrid to 25.04.0-SNAPSHOT
  jenkins/databricks/init_cudf_udf.sh
  pom.xml
  scala2.13/pom.xml
Labels: build

#11970 Explicitly set Delta table props to accommodate for different defaults [databricks]
  integration_tests/src/main/python/delta_lake_utils.py
Labels: test
